### ISSUE TITLE
[iOS] Share.shareSingle shares a base 64 file as text for mail

### ISSUE THREAD

**Issue by padupuy** [react-native-community/react-native-share#103]
Hello @EstebanFuentealba,

I use the latest version of your library `1.0.19` with RN `0.40.0`.
I try to share a PDF file encoded in base64 only by mail. 

Here is my code

```
import {Platform} from 'react-native';
import Share from 'react-native-share';
const RNFS = require('react-native-fs');

const ENCODING = 'base64';
const PDF_MIME_TYPE = 'application/pdf';

export function sendPDFFileByMail(file) {
    let path = null;
    let getBase64File = null;

    if (Platform.OS === 'ios') {
        path = `${RNFS.MainBundlePath}/${file}`;
        getBase64File = getBase64FileIOS;
    }
    else {
        path = `pdf/${file}`;
        getBase64File = getBase64FileAndroid;
    }

    getBase64File(path)
        .then(content => {
            // console.log('content', content);
            shareByMail(content);
        })
        .catch(error =>console.log('error', error));
}

function getBase64FileIOS(path) {
    return RNFS.readFile(path, ENCODING);
}

function getBase64FileAndroid(path) {
    return RNFS.readFileAssets(path, ENCODING);
}

function shareByMail(base64File) {
    base64File = `data:${PDF_MIME_TYPE};${ENCODING},${base64File}`;

    const shareOptions = {
        title: 'Title',
        message: 'Body',
        url: base64File,
        subject: 'Subject',
        type: PDF_MIME_TYPE,
        social: 'email'
    };

    Share.shareSingle(shareOptions);
}

```

This code works really well on Android but unfortunately not on iOS, the base 64 file is shared as text.

![screenshot_20170131-145405](https://cloud.githubusercontent.com/assets/715255/22467832/7562fc12-e7c6-11e6-8b59-355cb440b425.jpg)

![thumb_img_0043_1024](https://cloud.githubusercontent.com/assets/715255/22467567/787b4d74-e7c5-11e6-8e1c-fed8723c8f61.jpg)

If I use `Share.open` instead of `Share.shareSingle`, the attachment looks good.

![thumb_img_0044_1024](https://cloud.githubusercontent.com/assets/715255/22467568/787b952c-e7c5-11e6-8ef1-b4ce590d4e6a.jpg)

One more question, how I could specify the name of the attachment

**Comment by twvdb** [comment]
Also trying to figure out how to specify the name of the attachment

**Comment by mbenjamin618** [comment]
+1

**Comment by packruler** [comment]
Has anyone figured out how to set the attachment file name using Base64?

**Comment by fernandofranca** [comment]
Use `react-native-fs` and persist your content in the FS as base64.
When you provide a file path as argument to share, it will be the same as the created file.
Unfortunately you'll need to unlink the file, after sharing.
