### ISSUE TITLE
[iOS] Share.shareSingle shares the filepath instead of the file binary

### ISSUE THREAD

**Issue by padupuy** [react-native-community/react-native-share#106]
Hello @EstebanFuentealba 

I use the latest version of your library 1.0.19 with RN 0.40.0.
I try to share a local PDF file only by mail but 

This code works really well on Android but unfortunately not on iOS, the filepath is shared instead of the file binary.
If I use Share.open instead of Share.shareSingle, the attachment looks good.

In the react-native-share code I can see the code is different to get the file from the url between `GenericShare.m` (https://github.com/EstebanFuentealba/react-native-share/blob/master/ios/GenericShare.m#L22) and `EmailShare.m` (https://github.com/EstebanFuentealba/react-native-share/blob/master/ios/EmailShare.m#L33)

I would love to help but unfortunately I don't know objective-c :(

Here is my code :

```
import {Platform} from 'react-native';
import Share from 'react-native-share';
const RNFS = require('react-native-fs');

const PDF_MIME_TYPE = 'application/pdf';

export function sendPDFFileByMail(fileUrl) {
    const fileName = fileUrl.substr(fileUrl.lastIndexOf('/') + 1);
    const fileDest = `${Platform.OS === 'ios' ? RNFS.DocumentDirectoryPath : RNFS.ExternalDirectoryPath}/${fileName}`;

    const downloadResult = RNFS.downloadFile({
        fromUrl: fileUrl,
        toFile: fileDest,
    });

    downloadResult.promise
        .then(() => {
            shareByMail(fileDest);
        }).catch(e => console.log(error))
}

function shareByMail(url) {
    url = `file://${url}`;

    const shareOptions = {
        title: 'Title',
        message: 'Body',
        url: url,
        subject: 'Subject',
        type: PDF_MIME_TYPE,
        social: 'email'
    };

    Share.shareSingle(shareOptions).catch(e => console.log(e));
}
```

![thumb_img_0054_1024](https://cloud.githubusercontent.com/assets/715255/22829150/5e04d242-efa1-11e6-9dc6-15bd4093a7c8.jpg)

**Comment by enieber** [comment]
@padupuy this error occurs in the last version `1.0.27`?

**Comment by Mavenic** [comment]
This issue still exists

**Comment by MateusAndrade** [comment]
> This issue still exists

Which versions of rn and rn-share are you using?

**Comment by Mavenic** [comment]
> > This issue still exists
> 
> Which versions of rn and rn-share are you using?

Here are the details of this issue, posted on similar thread

https://github.com/react-native-community/react-native-share/issues/438#issuecomment-646216661
