### ISSUE TITLE
Is it possible to "Set image as Lock screen"

### ISSUE THREAD

**Issue by kevando** [react-native-community/react-native-share#112]
I'd like to prompt my users inside my app to set an image as their lock screen as seen here. Is that possible with this plugin?

![screenshot](https://www.howtoisolve.com/wp-content/uploads/2015/07/How-to-Change-lock-Screen-Wallpaper-on-iPhone-6-6-Plus.jpg)

**Comment by enieber** [comment]
@kevando in Android or iOS?

**Comment by jgcmarins** [comment]
I don't think this lib apply for that.
