### ISSUE TITLE
Android: Sharing with Google Inbox doesn't work

### ISSUE THREAD

**Issue by tpedersen123** [react-native-community/react-native-share#114]
I'm sharing images from an app and sharing works fine with text messages, Slack, Facebook etc.
However, sharing on Google Inbox makes Inbox report that it can not share an empty file. 

I have tried with the example code sharing `shareImageBase64` but that doesn't work for me either.

Running Android 7.0 and have checked that sharing works from other apps.

**Comment by packruler** [comment]
Where is the file stored? From what I see this library is not setup to use providers to share files to other apps and therefore cannot share files stored in app specific directories.

**Comment by tpedersen123** [comment]
@packruler I'm choosing it in the gallery, so it should be generally available and can be shared from other apps.

**Comment by enieber** [comment]
try with the new version of lib
