### ISSUE TITLE
[Android] Catch callback not firing

### ISSUE THREAD

**Issue by larryranches** [react-native-community/react-native-share#116]
On IOS, when the user selects cancel or taps the screen under the Share ActionSheet the catch callback fires and an error is returned. If you console.log it, you get  ```error:  User did not share```.  This callback is helpful so that we can call functions when a user cancels the actionsheet.  Is there a fix for this on Android?

```    
 Share.open(shareOptions)
      .catch((err) => {
        console.log('error: ', err.error)
        this.cancelAction()
      })
      .done(this.shareDone)
 }
```

**Comment by zachrnolan** [comment]
Any updates on this one?

**Comment by jan-happy** [comment]
I would also be interested in a fix.

**Comment by schermannj** [comment]
Hey, any luck to fix that crap?

**Comment by jgcmarins** [comment]
PR's are welcome

**Comment by henkkasoft** [comment]
I did some testing and there might be a major problem with android.content.Intent.ACTION_SEND not giving any output. The output is always cancel (0) if you try to read it with startActivityForResult & onActivityResult. If someone figure out a way to solve this, it would be very helpful!

There is a documentation that output is not available:
https://developer.android.com/reference/android/content/Intent#ACTION_SEND
