### ISSUE TITLE
[Android] Difficulty sharing files with proper file names.

### ISSUE THREAD

**Issue by packruler** [react-native-community/react-native-share#118]
I am having difficult sharing files on an Android device. If I get the base64 value of the file I cannot set the name of the file. If I try to share a file the apps that it is shared to receive an empty file. On iOS I can easily share a file and it has the proper file name.

**Comment by packruler** [comment]
This is using files created with [React-Native-Fetch-Blob](https://github.com/wkh237/react-native-fetch-blob)

**Comment by packruler** [comment]
I have setup a bandage fix that allows me to specify the title of a base64 value. You can find this [here](https://github.com/packruler/react-native-share/commit/d4b1afd9bdddf5908850cdb9c191b7fae527f7e5)
I noticed that this is not setup to properly support Android sharing of files stored internally. I am not sure if that is possible but it would be nice if that is possible.

**Comment by ihor** [comment]
How do you share a file with a proper name @packruler? Thanks!

**Comment by packruler** [comment]
On iOS I have not had problems sharing files stored in the apps Document directory as files.

**Comment by enieber** [comment]
try with the new version of lib
