### ISSUE TITLE
How to share an image via url on Twitter?

### ISSUE THREAD

**Issue by DavidKongDesheng** [react-native-community/react-native-share#119]
It looks like only support base64 image file, no support share via image url on Twitter.

Instead using
url: "data:image/png;base64,<base64_data>"
can we add one more parameter like
imageUrl: "<imageUrl>"

**Comment by onlydave** [comment]
Came across this while trying to do the same thing: http://stackoverflow.com/questions/6150289/how-to-convert-image-into-base64-string-using-javascript

**Comment by jgcmarins** [comment]
check example on [readme](https://github.com/react-native-community/react-native-share#example-code)
