### ISSUE TITLE
Can we add one more social app like LinkedIn?

### ISSUE THREAD

**Issue by DavidKongDesheng** [react-native-community/react-native-share#120]

**Comment by anniewey** [comment]
@DavidKongDesheng Did you find any solution?

**Comment by DavidKongDesheng** [comment]
@anniewey Not exactly, I implement this func according this [https://developer.linkedin.com/docs/share-on-linkedin#](url) - Customized URL, should be very easy add this function to this library~

**Comment by enieber** [comment]
@DavidKongDesheng PR is Welcome!
