### ISSUE TITLE
[Android] Sharing data uri silently fails without WRITE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by arv** [react-native-community/react-native-share#125]
Tried with RN 0.44, Android M & N.

I cannot get the `url` option to work to share an image. I'm using a data URI of an image. I've also tried the sample code in this repo.

- If I do `Share.open` and pick:
  - Gmail `url` is ignored. (`subject` and `message` work)
  - "Upload to Photos" I get a toast saying "Error, could not load media"
  - "Save to Drive" I get a toast saying "Upload was unsuccessful, request contained no data"

It seems like the url is dropped on the way. I'm going to see if I can step through the code in Android Studio to make sure the URL gets all the way to the intent.

(FWIW, this works great in iOS)

**Comment by arv** [comment]
I'm seeing a permission denied error.

```
System.err: java.io.FileNotFoundException: /storage/emulated/0/Download/1494541901790.jpg (Permission denied)
```

It seems like I need to get access to `android.permission.READ_EXTERNAL_STORAGE`. If that works I'll work on a PR that reports an error to js so it is less mystical in the future.

**Comment by RUIFERNANDE5** [comment]
@arv have u found the solution? I have . write_external_storage permissions set and still have permission denied error

**Comment by arv** [comment]
Yes. I add the following to AndroidManifest.xml:

```xml
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

Then before calling `Share.open` I called `requestStoragePermission` which is defined as:

```js
import {PermissionsAndroid, Platform} from 'react-native';
import doAlert from './alert.js'; // This is just Alert.alert but wrapped in a promise

async function requestPermission(
  permission: string,
  title: string,
  message: string,
  neverAskAgainTitle: string,
  neverAskAgainMessage: string,
): Promise<boolean> {
  // iOS prompts for permission automatically.
  if (Platform.OS === 'ios') {
    return true;
  }

  try {
    const granted = await PermissionsAndroid.request(permission, {
      title,
      message,
    });
    switch (granted) {
      case PermissionsAndroid.RESULTS.GRANTED:
        return true;
      case PermissionsAndroid.RESULTS.DENIED:
        return false;
      case PermissionsAndroid.RESULTS.NEVER_ASK_AGAIN:
        await doAlert(neverAskAgainTitle, neverAskAgainMessage);
        return false;
    }
  } catch (e) {
    // fall through
  }
  return false;
}

// ...

export function requestStoragePermission() {
  return requestPermission(
    PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
    '...',
    '...',
    '...',
    '...',
  );
}
```

And here is my call to share just for the record:

```js
if (!await requestStoragePermission()) {
  return;
}

const url = 'data:image/jpeg;base64,' + fromByteArray(await blobUint8ArrayP);

try {
  await Share.open({url});
} catch (ex) {
  // User cancelled sharing...
}
```

HTH

I still want to do a PR that surfaces the errors in Java so things do not silently fail...

**Comment by RUIFERNANDE5** [comment]
Thank you for sharing, tough I solved this by setting permissiosAndroid and writing the file I wanted on a external directory since its the only accepted path on all android apps.

**Comment by Michael-Benecaid** [comment]
How to write the file on an external directory? I am using react-native-fetch-blob to write the file,
```
addAndroidDownloads : {
            useDownloadManager : true, // <-- this is the only thing required
            // Optional, override notification setting (default to true)
            notification : true,
            // Optional, but recommended since android DownloadManager will fail when
            // the url does not contains a file extension, by default the mime type will be text/plain
            title:`xxx.pdf`,
            mime : 'application/pdf',
            description : 'File downloaded by download manager.',
            mediaScannable : true,
            path: RNFetchBlob.fs.dirs.DownloadDir+`xxx.pdf`           
          }
```
and share the pdf as 
```
Share.share({
      title: 'xxx',
      url: `${path}`
      }
    )
```
Gmail still ingnore the url, can anyone help this?
