### ISSUE TITLE
Does the share work on the Windows Phone Emulator?

### ISSUE THREAD

**Issue by ndbroadbent** [react-native-community/react-native-share#126]
Hi, right now my "share" button doesn't seem to have any effect in the Windows Phone Emulator. There's no error either, it just doesn't do anything.

Is this expected? Unfortunately I don't have a real device to test it on.

UPDATE: It doesn't seem to work on the desktop build either. I'm getting this error in the share sidebar: "There was a problem with the data"

**Comment by enieber** [comment]
how to are your code?
