### ISSUE TITLE
How to share external video file?

### ISSUE THREAD

**Issue by ok713** [react-native-community/react-native-share#137]
I have tried to share external video file.
here is my codes.

onShare = (title) =>{
        let shareOptions = {
           message: this.state.question,
           url: 'data:video/mp4;base64,'+this.state.video_base64,
       };
      if(title=='facebook' || title=='twitter'){
        Share.shareSingle(Object.assign(shareOptions, {
                      "social": title
          })).then(result=>{
              console.log(result);
          })
          .catch((error) =>{
            console.log(error);
        });
      }
  }

but I could not share.
Please help me.
thanks,

**Comment by pvroosendaal** [comment]
Did you find a solution for this? I'm having trouble as well.
I'm fetching a video from online using RNFetchBlob and using RNFetchBlob.fs.readFile() to get the base64 data. This works, but then somehow it's sharing a .data file. If I rename it to .mp4 it's a working video, but I can't seem to figure out to give it .mp4 extension by default.

**Comment by austin-everts** [comment]
If anyone comes across this in the future and is also using using react-native-fetch-blob. After experimenting I found adding the `appendExt: fileType` to your config obj, will allow you to share the file from the path.

```
RNFetchBlob.config({
  fileCache : true,
  appendExt : 'mp4'
}).fetch('GET', mediaEntry.itemURL, {})
.then((res:any) => {
  let shareOptions = {
    title: "Check out my video",
    message: "Check out my video!",
    url: 'file://' + res.path(),
    type: 'video/mp4',
    subject: "Check out my video!"
  }
  share.open(shareOptions)
    .then((res:any) => console.log('res:', res))
    .catch((err:any) => console.log('err', err))
  });
```

**Comment by keshamtravels** [comment]
@austin-everts solution generates correct res.path() but share is not able to share the file in any of app i tried in android, does it really worked

**Comment by jgcmarins** [comment]
done: https://github.com/react-native-community/react-native-share/issues/137#issuecomment-360208406

**Comment by sevensevener** [comment]
is there a solution for android? @keshamtravels got the same problem.

**Comment by jgcmarins** [comment]
`rn-fetch-blob`?

**Comment by matthova** [comment]
@austin-everts 	I'm a bit late to the party, but I found this didn't work in many cases (on android). For me I had to use a base64 url, not the direct file url. 
```jsx
const res = await RNFetchBlob.config({
  fileCache : true,
  appendExt : 'mp4'
}).fetch('GET', 'YOUR_URL', {})
const filePath = res.path(); use this path to delete the file when you're done
const base64String = await res.base64();
const url = `data:video;base64,${base64String}`;
fs.unlink(filePath); // Unlink the file path when you're done, unless you want the file to be saved locally
```

**Comment by matthova** [comment]
@austin-everts were you able to share video to facebook?

**Comment by MateusAndrade** [comment]
#578

**Comment by sevensevener** [comment]
@matthova thanks, i'll try it later!
