### ISSUE TITLE
Impossible to share an image to Facebook on IOS?

### ISSUE THREAD

**Issue by rjacobskind** [react-native-community/react-native-share#143]
We're trying to use your plugin to share an image to Facebook. We use this code:

```js
              Share.shareSingle({
                title: "Check this out",
                url: `file://${this.props.socialShareImage}`,
                social: 'facebook'
              });
```

When we actually run the code, Facebook redirects us to an error page stating that we need to share a valid URL. Based on the documentation we've been able to find, the `u=` query string param is for the referer URL, and if I read the source code for this plugin correctly, we're trying to pass *anything* in there, including the file path?

What are we doing wrong?

**Comment by sibelius** [comment]
try Share.open

**Comment by rjacobskind** [comment]
@sibelius Do you know of any way to have this work with Share.shareSingle?

**Comment by sibelius** [comment]
nope, you should dig in the code and try to figure it out what is happening

**Comment by MichaelPintos** [comment]
whit email and google+ same problem
