### ISSUE TITLE
Sharing to Twitter not working (logs: TRY OPEN Twitter. Try open view.  [core] Sheet not being presented, calling premature completion)

### ISSUE THREAD

**Issue by canpoyrazoglu** [react-native-community/react-native-share#1443]
### Steps to reproduce
Call ` Share.shareSingle` with social target being Twitter with share options having a URL and a title.

### Expected behavior
It should open Twitter for sharing that URL and title

### Actual behavior
Nothing visible happens. I see the following in _native_ logs in Xcode:
```
2023-08-08 21:24:43.349259+0300 MyApp[19036:2705077] twitter
2023-08-08 21:24:43.349401+0300 MyApp[19036:2705077] TRY OPEN Twitter
2023-08-08 21:24:43.349467+0300 MyApp[19036:2705077] Try open view
2023-08-08 21:24:43.362129+0300 MyApp[19036:2705077] [core] Sheet not being presented, calling premature completion
```

### Environment
- **React Native version**: 0.71.8
- **React Native platform + platform version**: iOS 16.6 (Physical device, iPhone 14 Pro Max)
- **Typescript version** (if using typescript): 5.0.3

### react-native-share
**Version**: ^9.2.3

### Notes
Opening other platforms (e.g. Facebook share) work correctly with the same exact share options.

**Comment by DimaKelek** [comment]
same problem

**Comment by thanhnn-bap-jp** [comment]
Same issue
