### ISSUE TITLE
after update I cannot compile my project

### ISSUE THREAD

**Issue by metamorph-online** [react-native-community/react-native-share#1469]
### Steps to reproduce
1. updated my old project to last version
2. enter command "npm run android"

### Expected behavior
project should compile

### Actual behavior
get an error:
1: Task failed with an exception.
-----------
* Where:
Build file '\node_modules\react-native-share\android\build.gradle' line: 30

* What went wrong:
A problem occurred evaluating project ':react-native-share'.
> Could not set unknown property 'namespace' for extension 'android' of type com.android.build.gradle.LibraryExtension.

### Environment
- **React Native version**:
- 0.72
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc
- android
- **Typescript version** (if using typescript): 3.8+ required, what version is in your environment?

### react-native-share
**Version**: npm version or "master"
"react-native-share": "^9.4.1"

### Link to repo (highly encouraged)
https://github.com/

**Comment by garymazz** [comment]
Marked as stale, but is still broken.

**Comment by cart0uche** [comment]
See here : https://stackoverflow.com/questions/76300671/android-getting-error-namespace-not-specified

**Comment by nurmanbe7ov** [comment]
how did you solve this problem?

**Comment by hayr-hotoca** [comment]
I commented out the namespace line in the React Native Share build.gradle file, and it works perfectly. 

However, this is just a temporary fix; we may need to use the correct Gradle or Gradle plugin version.
