### ISSUE TITLE
what is  'excludedActivityTypes' in open method options

### ISSUE THREAD

**Issue by jariwalabhavesh** [react-native-community/react-native-share#153]
`Share.open(options).catch((err) => { err && console.log(err); })`

In options of open method, there is a  property **excludedActivityTypes** which is optional but what is use of that, i found nothing in the documentation as well.

can any one provide information what is use of **excludedActivityTypes** option

Thanks

**Comment by ataillefer** [comment]
Was added by ebb1364de262972fcb169633a6cfecdaf2b302f7 but there are no occurrences in the code so I think it is useless.

**Comment by yjb94** [comment]
https://developer.apple.com/documentation/uikit/uiactivitytype
you can get infomation from here.
use it like 

excludedActivityTypes: [
                                    'com.apple.UIKit.activity.PostToFacebook',
                                    'com.apple.UIKit.activity.PostToTwitter']

**Comment by jariwalabhavesh** [comment]
@yjb94 
I know it's too late but
Can you please provide more detail what is actual use of this attribute??

**Comment by jgcmarins** [comment]
`excludedActivityTypes` has nothing to do here: https://github.com/react-native-community/react-native-share/search?utf8=%E2%9C%93&q=excludedActivityTypes&type=

**Comment by yjb94** [comment]
@jariwalabhavesh excludedActivityTypes is related to apple iOS. just pass the types like the way I commented. other options(such as email), you shoud google it...

**Comment by jariwalabhavesh** [comment]
@yjb94 
Thanks for response
It is related to #154 ??

**Comment by annelorraineuy** [comment]
@yjb94 The docs here state that **excludedActivityTypes** takes a string but your example is an array of strings. Perhaps the docs should be updated?

**Comment by jgcmarins** [comment]
@annelorraineuy if it makes sense, PRs are welcome \o/

**Comment by rikur** [comment]
I got this to work:
```excludedActivityTypes: ['com.apple.UIKit.activity.SaveToCameraRoll', 'com.apple.UIKit.activity.AssignToContact']```

I couldn't figure out the activity type for "Create Watch Face".. even Apples docs don't include it.
