### ISSUE TITLE
Can we ignore some app from share sheet which is open using open method.

### ISSUE THREAD

**Issue by jariwalabhavesh** [react-native-community/react-native-share#154]
Is there any way to filter out application showing in share sheet in ios. I want to remove some app from the list.

Here is image of share sheet when i open pdf using open method.
![image uploaded from ios](https://user-images.githubusercontent.com/10993666/29809161-befbacc4-8cb8-11e7-806a-e3e354af950d.jpg)

I want to remove **Add to Notes** and some other option from share sheet, it is possible to do that???

**Comment by jariwalabhavesh** [comment]
@ramsagar003 : Thank you

**Comment by vivekshah-zymr** [comment]
> https://developer.apple.com/documentation/uikit/uiactivitytype
> you can get infomation from here.
> use it like
> 
> excludedActivityTypes: [
> 'com.apple.UIKit.activity.PostToFacebook',
> 'com.apple.UIKit.activity.PostToTwitter']

This will work for iOS, but what for android? I want to exclude a few apps while sharing my content on android as well.

**Comment by ketanvault** [comment]
@vivekshah-zymr did you get the solution for this ? I mean for android, how we will ignore our own app from share list?

**Comment by vivekshah-zymr** [comment]
> @vivekshah-zymr did you get the solution for this? I mean for android, how we will ignore our own app from share list?

@ketanvault , Not actually.

**Comment by CodeHunter111** [comment]
Any workaround????????
