### ISSUE TITLE
Cant close the window after successfully posting to any provider

### ISSUE THREAD

**Issue by arjun9toppiks** [react-native-community/react-native-share#156]
Once I post the url onto any provider, it successfully posts the url and shows a blank page. On Debugging, have seen a message in safari saying "Can't close the window as it is not opened by javascript". It happens both on IOS and Android. Please suggest if there is a way out? 
<img width="545" alt="screen shot 2017-08-31 at 11 44 59 pm" src="https://user-images.githubusercontent.com/9283866/29938609-ff2248ea-8ea6-11e7-9442-eba65490b71f.png">
<img width="368" alt="screen shot 2017-08-31 at 11 48 52 pm" src="https://user-images.githubusercontent.com/9283866/29938610-ff232378-8ea6-11e7-9bae-95b05783aac7.png">

**Comment by enieber** [comment]
@arjun9toppiks this occurs in the version in master branch?
