### ISSUE TITLE
Application crash

### ISSUE THREAD

**Issue by rohankangale2011** [react-native-community/react-native-share#162]
Identified app crash for certain conditions.

Steps to reproduce:

Open the share dialog and click on back(device's back button).
Again open the dialog and click on back.
At second time(when back button is pressed), application getting crashed.

Platform: Android

![error](https://user-images.githubusercontent.com/7829122/30744047-e9e0f724-9fbd-11e7-83e1-57a51e361172.JPG)

![err](https://user-images.githubusercontent.com/7829122/30744523-14f23052-9fc0-11e7-891d-a7ab1676c1ec.JPG)

**Comment by enieber** [comment]
@rohankangale2011 can you try again on master branch?
