### ISSUE TITLE
Save image to camera roll option not included?

### ISSUE THREAD

**Issue by mmckinley8** [react-native-community/react-native-share#163]
I am trying to include the save image icon in the action sheet as well as the sharing options, as you would typically see. 

![share](https://user-images.githubusercontent.com/11301364/30755561-d7044e52-9f8c-11e7-9c2b-ee756d1f08f4.png)

Is there any way to achieve this?

**Comment by yeomann** [comment]
Hi there, closing issues assuming latest releases must have addressed this issue. Please feel free to open it again thanks 😃
