### ISSUE TITLE
iOS support for Pinterest?

### ISSUE THREAD

**Issue by vijay-dadhich09** [react-native-community/react-native-share#165]

**Comment by nihp** [comment]
I can able o share the image via pinterest app in ios. Kindly add the detail description for this

**Comment by jgcmarins** [comment]
hey @nihp are you having success sharing on Pinterest via iOS?

**Comment by nihp** [comment]
Yes, I can able to share image successfully with the Pinterest via ios

**Comment by jgcmarins** [comment]
@nihp does it make sense to add this information on [README](https://github.com/react-native-community/react-native-share/blob/master/README.md)?

**Comment by javierbustamante** [comment]
Hi!! The information in README is correct, you can't share with pinterest in iOS with React Native Share.
In planned to add this functionality??

**Comment by jgcmarins** [comment]
We're accepting PRs that aim to add Pinterest support for iOS
