### ISSUE TITLE
Can't share local file on Android

### ISSUE THREAD

**Issue by ricardofavero** [react-native-community/react-native-share#166]
On iOS this code works perfectly, but on Android it shows "unsupported file" or "permission denied" depending on which app I choose.
Does anyone know what's going on?

```javascript
Share.open({
    url: 'file://' + localpath,
    type: 'video/mp4'
});
```

**Comment by kramer9x** [comment]
@ricardofavero try to check and request permission before Share.open call. Something like
 ```javascript
const granted = await PermissionsAndroid.check(
  'android.permission.READ_EXTERNAL_STORAGE'
);
if (!granted) {
  const response = await PermissionsAndroid.request(
    'android.permission.READ_EXTERNAL_STORAGE'
  );
  if (!response) {
    return;
  }
}
Share.open({
    url: 'file://' + localpath,
    type: 'video/mp4'
});```

**Comment by yeomann** [comment]
Hi there, closing issues assuming latest releases must have addressed this issue. Please feel free to open it again thanks 😃
