### ISSUE TITLE
event share success on Android fired not correct

### ISSUE THREAD

**Issue by lytrunghieu** [react-native-community/react-native-share#171]
my code :
 Share.open(shareImageBase64).then(res=>{
                    this.onCompleteShare();
                }).catch(err=>{
                    console.warn("error ", err)
                });
but event share success fired while popup is showing. But in IOS event share success fired after I share complete.  
p/s: I'm using version 1.0.23

**Comment by priyankinfinnov** [comment]
Hey @lytrunghieu, were you able to fix this?
Also, if not did you use any other module?

**Comment by filipef101** [comment]
@lytrunghieu @priyankinfinnov Is it possible to know if the user shared on android?

**Comment by filipef101** [comment]
@EstebanFuentealba Can you let us know?

**Comment by waqas19921** [comment]
@yeomann Is there any way to get what has been selected on android.

**Comment by filipef101** [comment]
@waqas19921 I don't remember well but possibly it is not possible to know if the user actually shared on android. Its an OS limitation/entended behavior
