### ISSUE TITLE
How to share local image as url??

### ISSUE THREAD

**Issue by Rickkorsten** [react-native-community/react-native-share#172]
When I try :

```
let shareOptions = {
            title: "React Native",
            message: "Hola mundo",
            url: 'file://' + './Rick_Sanchez.png',
            //url: IMG,
            type: 'image/png',
            subject: "Share Link" //  for email
        };
```

This is the result:

![screenshot_20171005-111835](https://user-images.githubusercontent.com/13645069/31220006-62ae09c0-a9bf-11e7-8b4d-69519b291a52.png)

This also happens when I upload a .gif

Also the message and title don't work on android!!!

**Comment by coryjb** [comment]
Hi there! I use [react-native-fs](https://github.com/itinance/react-native-fs) to get the base64-encoded version of an image then pass to react-native-share:

`RNFS.readFile(RNFS.DocumentDirectoryPath + '/previews/test.jpg', 'base64').then((image) => {
  Share.open({
    url: 'data:image/jpeg;base64,' + image,
    type: 'image/jpeg'
  }).catch((err) => {
    // Handle error
    // ...
  });
});`

**Comment by yeomann** [comment]
Hi there, closing issues assuming latest releases must have addressed this issue. Please feel free to open it again thanks 😃

**Comment by TeyimPila** [comment]
Does this solution work on Android, @coryjb ?
