### ISSUE TITLE
How to style error screen when app is not found?

### ISSUE THREAD

**Issue by JulioOrellana** [react-native-community/react-native-share#173]
How it is possible to edit/style this screen when the app is not locally found? (e.g) Whatsapp

![screen shot 2017-10-06 at 12 40 45 pm](https://user-images.githubusercontent.com/10372340/31286143-98d4f67e-aa93-11e7-8c8f-aced8320190b.png)

**Comment by enieber** [comment]
@JulioOrellana  this occur in iOS and Android or only in one platform?
