### ISSUE TITLE
Whatsapp share is not working in ios

### ISSUE THREAD

**Issue by vishnuc** [react-native-community/react-native-share#177]
When clicked share , It is opening itunes and itunes has open button , Whereas native whatsapp share button is opening whatsapp directly with our message.

**Comment by sushant6309** [comment]
@vishnuc have you fixed this. @heracek @codeflows @linmic @wasedaigo can you guys help me with this issue.

**Comment by vishnuc** [comment]
no , i  am still waiting for fix

**Comment by jgcmarins** [comment]
@vishnuc could you provide more details, please?
like versions, code etc

**Comment by lynkxyz** [comment]
Is there any solution

**Comment by jgcmarins** [comment]
maybe we can close this due lack of information

**Comment by wasedaigo** [comment]
Isn't this the fix? https://github.com/EstebanFuentealba/react-native-share/pull/121

**Comment by jgcmarins** [comment]
@wasedaigo I think you're right

**Comment by hwde** [comment]
I noticed that sharing to whatsapp on ios always requires message AND url ... maybe this could be documented somewhere? (Or I havn't found it).

**Comment by EJohnF** [comment]
nope, the latest commit still has that problem - can't post message along with image in whatsapp

**Comment by jgcmarins** [comment]
@EJohnF do you have any stack trace?

**Comment by jgcmarins** [comment]
> can't post message along with image in whatsapp

Sorry, I did no make myself clear.
When sharing, there is a crash? There is a stack trace error?

**Comment by EJohnF** [comment]
@jgcmarins I've checked it again, and indeed found this:
```
SLRemoteComposeViewController: (this may be harmless) viewServiceDidTerminateWithError: Error Domain=_UIViewServiceErrorDomain Code=1 "(null)" UserInfo={Terminated=disconnect method}
```
