### ISSUE TITLE
Facebook sharing

### ISSUE THREAD

**Issue by mauricejohn** [react-native-community/react-native-share#180]
Facebook sharing ignores message when there is an image url attached.

**Comment by rohitgoyal** [comment]
+1
And it is happening with iOS 11 only.

**Comment by Jobeso** [comment]
+1

**Comment by gedu** [comment]
+1
And it is happening with URLs in general

**Comment by jgcmarins** [comment]
guys, please, stop doing `+1`
instead, **thumbs up** the comment
thanks :)

**Comment by jgcmarins** [comment]
@mauricejohn could you please provide more details about your problem?
thanks

**Comment by gedu** [comment]
What I found is FB doesn't support a message sharing using the URL, so or you use the FB SDK or the FB app must be installed

**Comment by yeomann** [comment]
Hi there, closing issues assuming latest releases must have addressed this issue. Please feel free to open it again thanks 😃

**Comment by bakaa99** [comment]
it's still not working,

**Comment by yeomann** [comment]
@bakaa99 maybe could you give some more info, what exactly you tried? so that someone here could assit you, Thanks
