### ISSUE TITLE
email share not working

### ISSUE THREAD

**Issue by Avanikothari22** [react-native-community/react-native-share#182]

**Comment by jgcmarins** [comment]
@Avanikothari22 could you provide more details, please?

**Comment by natashache** [comment]
@jgcmarins it's not working for me either. When you tap on email share it doesn't do anything. It does not produce any error message either. This is on iOS. I have not tried android.

**Comment by ConorKelleher** [comment]
I had this happen to me and fixed it by adding a "subject" property to the shareOptions parameter. The sample code shows shareOptions with a subject property and a comment suggesting it's needed for email. Really could use a more strict warning though

**Comment by natashache** [comment]
@ConorKelleher doesn't work for me. I have 'subject' in shareOptions. When tapping on email sharing, the sharing modal disappears and nothing happens. There is no error response either.

**Comment by ardalahmet** [comment]
@natashache It's actually the `message` field. You can see it here:

https://github.com/EstebanFuentealba/react-native-share/blob/9a9f94ddbf5a33c9d7afba669dfae73773fe86b2/ios/EmailShare.m#L19

**Comment by SalviShahzad** [comment]
I am also experiencing the same issue as mentioned above.
Nothing happens when email is clicked.

I do not understand why email share has been provided when it does not work.

**Comment by yeomann** [comment]
can you guys provide a repo please? I can have a look for you. repo can be simple as 
```
react-native init porject_name
yarn add react-native-share
react-native link react-native-share
```
and your example code where you are trying to click on email and nothings happening.

**Comment by SalviShahzad** [comment]
I have made a repo https://github.com/SalviShahzad/react-native-share-email-issue with my sample code.
Please look into it

**Comment by yeomann** [comment]
thank you @SalviShahzad I will look into soon and get back to you!

**Comment by SalviShahzad** [comment]
Sure @yeomann 
you can find the sample code in this file https://github.com/SalviShahzad/react-native-share-email-issue/blob/master/src/Main.js

**Comment by jgcmarins** [comment]
@SalviShahzad could you please update do `1.1.0`?

**Comment by SalviShahzad** [comment]
sure, what is the command for it?

**Comment by yeomann** [comment]
remove `react-native-share` from `package.json` and install from npm again OR change the version mentioned in `package.json` from `react-native-share` to `1.1.0`

**Comment by SalviShahzad** [comment]
I used this command to update : npm update react-native-share --save
and then : react-native link
but now my build fails with this error : library not found for -lRNMail (on ios)

**Comment by jgcmarins** [comment]
`rm -rf node_modules`
`npm install`

**Comment by SalviShahzad** [comment]
Yes I deleted and reinstalled node modules but the error persists

**Comment by jgcmarins** [comment]
which error?
it looks like there's a problem with your link

**Comment by SalviShahzad** [comment]
This is the error: library not found for -lRNMail 
I used react-native link for linking

**Comment by jgcmarins** [comment]
could you please reinstall following docs?
we have no issues with linking

**Comment by yeomann** [comment]
@SalviShahzad alright I have done some testing and created a repo for you. it seems linking was issue in your repo. unfortunately it was same for me when I tried to do a fresh install, after doing all Android based settings Manually I was able to do a Successful test on device. maybe for email you should test on Real device as well.

here's a repo for you https://github.com/yeomann/react-native-share-android-test

we might can close @jgcmarins but must look into linking for android where it doesn't link for `Edit your MainApplication class to implement ShareApplication` mentioned in readme

additionally, If you like we can add this repo as a example repo for android. 
Thanks

**Comment by jgcmarins** [comment]
@yeomann, awesome!
Feel free to open a PR with all additional and relevant information you judge necessary.
Your repo looks great. Maybe we should review our [example](https://github.com/react-native-community/react-native-share/tree/master/example).
Feel free to close this issue when you are done.

**Comment by yeomann** [comment]
thanks @jgcmarins i will try to send PR later for android specific gotcha's 
I remember you told me to send invite for repo, but I think I ain't get it :) that's why I don't have the ability to close this issue or any issues.

**Comment by yeomann** [comment]
Hi @SalviShahzad  @Avanikothari22  issue is being closed as it seems to be resolved already. feel free to report back incase if you still encounter any error. 
thanks
