### ISSUE TITLE
exposed beyond app through ClipData.Item.getUri()

### ISSUE THREAD

**Issue by ravirupareliya** [react-native-community/react-native-share#185]
I am running it with android naugat and while sharing it is showing

    E/unknown:ReactNative: Exception in native call android.os.FileUriExposedException: file:///storage/emulated/0/Download/1509186941926.png exposed beyond app through ClipData.Item.getUri()
    at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
    at android.net.Uri.checkFileUriExposed(Uri.java:2348)
    at android.content.ClipData.prepareToLeaveProcess(ClipData.java:941)
    at android.content.Intent.prepareToLeaveProcess(Intent.java:9735)
    at android.content.Intent.prepareToLeaveProcess(Intent.java:9741)
    at android.content.Intent.prepareToLeaveProcess(Intent.java:9720)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1609)
    at android.app.ContextImpl.startActivity(ContextImpl.java:862)
    at android.app.ContextImpl.startActivity(ContextImpl.java:839)
    at android.content.ContextWrapper.startActivity(ContextWrapper.java:366)
    at android.content.ContextWrapper.startActivity(ContextWrapper.java:366)
    at cl.json.social.ShareIntent.openIntentChooser(ShareIntent.java:79)
    at cl.json.social.GenericShare.open(GenericShare.java:20)
    at cl.json.RNShareModule.open(RNShareModule.java:50)
    at java.lang.reflect.Method.invoke(Native Method)

**Comment by calcazar** [comment]
Are there any updates to this? I'm seeing the same on my end

**Comment by bitshadow** [comment]
+1

**Comment by sibelius** [comment]
@ravirupareliya @calcazar @bitshadow can you try with master version

it should be fixed by https://github.com/EstebanFuentealba/react-native-share/pull/181

reopen if the error still occours

**Comment by bitshadow** [comment]
Tried with master version and got this. Any idea what am I missing here. @sibelius @ygorbarboza 

```
myApp.MainApplication cannot be cast to cl.json.ShareApplication
getURI ShareFile.java:121
open ShareIntent.java:38
open GenericShare.java:18
open RNShareModule.java:50
invoke Method.java
invoke JavaMethodWrapper.java:363
invoke JavaModuleWrapper.java:162
run NativeRunnable.java
handleCallback Handler.java:790
dispatchMessage Handler.java:99
dispatchMessage MessageQueueThreadHandler.java:31
loop Looper.java:164
run MessageQueueThreadImpl.java:194
run Thread.java:764
```

**Comment by ygorbarboza** [comment]
@bitshadow You need to make your `MainApplication` implements `ShareApplication`

**Comment by bitshadow** [comment]
Thanks @ygorbarboza for quick reply.

Currently MyApplication already implements ReactApplication so please consider it in README as well.
`public class MainApplication extends Application implements ReactApplication {}`

**Comment by sagark1510** [comment]
@ygorbarboza I am also stuck at the same issue. Can you share an example for now to make it work quickly?

**Comment by ygorbarboza** [comment]
Something like this

```
class MyApplication extends Application implements ShareApplication, ReactApplication {

...

     @override
     String getFileProviderAuthority() {
            return <File provider authority>
     }

}
```

**Comment by ygorbarboza** [comment]
I updated the Readme on this PR #197

**Comment by sagark1510** [comment]
@ygorbarboza @bitshadow 
After going through all the steps from updated read me I got error as attached in the image.
![whatsapp image 2018-01-19 at 6 44 25 pm](https://user-images.githubusercontent.com/2134076/35152603-05828ca2-fd49-11e7-9f4c-358b03af5581.jpeg)

Any idea what is the issue?

**Comment by ygorbarboza** [comment]
@sagark1510 did you add the provider on the AndroidManifest file? Check the authority path and check if its right

https://stackoverflow.com/questions/30896130/fileprovider-crash-npe-attempting-to-invoke-xmlresourceparser-on-a-null-string

**Comment by sagark1510** [comment]
@ygorbarboza I have not added `meta-data` in the provider as readme doesn't have that snippet. 
Do I also have to create `raw/xml/filepaths.xml` file as well?

**Comment by bitshadow** [comment]
@sagark1510 I think I have added it in the Android section step 5. Can you check if you are not looking at the older version.

You need to create file paths (`filepaths.xml`) only if you want to restrict user to specific file paths otherwise not required.

**Comment by sagark1510** [comment]
@bitshadow 

            <applicaiton>
                <provider
                      android:name="android.support.v4.content.FileProvider"
                      android:authorities="${applicationId}.provider"
                      android:grantUriPermissions="true"
                     android:exported="false">
              </provider>
           </application>

no `meta-data` and if I try to change `${applicationId}.provider` to `${applicationId}.share` I get conflict from `react-native-image-picer` library as there is also added above `provider`.

**Comment by sagark1510** [comment]
@bitshadow @ygorbarboza 

Finally got it working. Thanks to @bitshadow .

Below was the issue 

```
import cl.json.ShareApplication

class MyApplication extends Application implements ShareApplication, ReactApplication {

{

     @Override
     public String getFileProviderAuthority() {
            // ${applicationId} = com.abc (original applicationId from build.gradle)
            return "${applicationId}.provider" 
     }

}
```

**Comment by jgcmarins** [comment]
@sagark1510 do we need a PR to fix it?

**Comment by filipef101** [comment]
@sagark1510 How so, Im facing the same issue and I have that code on main application

**Comment by windydang26** [comment]
i only see crash with android device run android OS >= 8.0
fileuriexposedexception through ClipData.Item.getUri()

**Comment by vivek49452** [comment]
After adding File provider and cl.json.shareapplication ,My project build successfully but my application was crash in android

**Comment by jgcmarins** [comment]
@vivek49452 do you have any error message?
