### ISSUE TITLE
How to custom share with Zalo app in Vietnam?

### ISSUE THREAD

**Issue by ntnamag** [react-native-community/react-native-share#187]
I want to custom a share box, how to setup with this app
Link: [](https://play.google.com/store/apps/details?id=com.zing.zalo)

**Comment by Winglonelion** [comment]
Hi, your message can be share on Zalo or any app have deep link by ```open``` api of ```react-native-sharing```.

When your app open native share UI, choose more  and turn on Zalo sharing option if not found it.
