### ISSUE TITLE
Share Multiple Images at once

### ISSUE THREAD

**Issue by ashishrokr** [react-native-community/react-native-share#191]
How to Share All Images At Once ?
 this.imageData.map((img,index)=>{
       img.toDataURL((dataImage) => {
            this.dataUrl =  this.dataUrl.concat(`${dataImage}`)
        })
    })
    
    Share.open({ url: `data:image/png;base64,${this.dataUrl}`})
this is working only for one image

**Comment by mrishan1993** [comment]
Required.

**Comment by xliank** [comment]
I'm coming from web developer without any JAVA or Android Development, but i think this article will help https://www.programcreek.com/java-api-examples/?class=android.content.Intent&method=ACTION_SEND_MULTIPLE

**Comment by sujitpk-perennial** [comment]
I am also looking for this functionality. Currently I managed as 
I send all images to native iOS/Android. Combined all images into one png file. Send back that single image to react native.

**Comment by jgcmarins** [comment]
Check master branch, please.
We've added this feature.
