### ISSUE TITLE
React Native Built in Share

### ISSUE THREAD

**Issue by Noitidart** [react-native-community/react-native-share#195]
Hi there, I saw your note that react-native supports share out of the box. It doesn't seem to support sharing images, is this true and for this reason will this module continue to be supported?

**Comment by rahamin1** [comment]
@Noitidart Did you get an answer? Can you post it here? Or anybody else?

**Comment by Noitidart** [comment]
@rahamin1 I didn't get reply :(

**Comment by rahamin1** [comment]
Thanks. I am trying in SO: https://stackoverflow.com/questions/54618080/sharing-content-using-react-natives-built-in-share-vs-using-react-native-share

**Comment by mikehardy** [comment]
You guys, this shouldn't be that complicated.

`Open a dialog to share text content`

https://facebook.github.io/react-native/docs/share

That seems like clear documentation to me. **Text** content is shareable with react-native Share API.

**Comment by rahamin1** [comment]
Well, riding bicycle is also difficult for me 😀 

What about the other questions in https://stackoverflow.com/questions/54618080/sharing-content-using-react-natives-built-in-share-vs-using-react-native-share ?

**Comment by Noitidart** [comment]
Thanks @mikehardy that helps. Ill share some research I did on how to share media.

Thanks @rahamin1 I'm also in that boat haha.

**Comment by mikehardy** [comment]
> Well, riding bicycle is also difficult for me 😀

Sadly, reading documentation is no use for bicycles :-). Terribly boring compared to the real thing as well

> What about the other questions in [stackoverflow.com/questions/54618080/sharing-content-using-react-natives-built-in-share-vs-using-react-native-share](https://stackoverflow.com/questions/54618080/sharing-content-using-react-natives-built-in-share-vs-using-react-native-share) ?

Sorry I can't speak authoritatively to whether all the same platforms are supported with built-in share. However if I am understanding native sharing at all, all of the various apps should advertise to the system that they may accept text as a sharing style, so almost any app should be shown as possibilities the user could select when you try to share them. Images however (which would be the react-native-share module) typically are more difficult to consume if you are a share consuming app, so fewer can do it, thus the table in this repo's documentation

**Comment by Noitidart** [comment]
Haha thanks @mikehardy for that docs is harder than bike comment. Its my fault though I should make sense of it. 

Thanks both for all the help here, hopefuly it will help another with same question.

**Comment by rahamin1** [comment]
And, @Noitidart if you have something to share, please do so ("share some research I did on how to share media")

**Comment by Noitidart** [comment]
For sure, searching my bookmarks now.

**Comment by Noitidart** [comment]
A guy here says he could share media with this module by first turning it to base64 - https://www.reddit.com/r/reactnative/comments/absyn3/send_image_via_default_messaging_app_mms/

I would think though we should find a way to make it base64 on native side and keep it on native side, rather then having to send huge base64 back and forth over bridge.

**Comment by Noitidart** [comment]
Here they mention "react-native-share-extension" - I think this held most promise - https://www.reddit.com/r/reactnative/comments/86aus1/how_to_support_share_receiving_of_multiple_images/


https://github.com/alinz/react-native-share-extension

Also they mentioned react-native-share-menu - but I think it didnt work well - https://github.com/meedan/react-native-share-menu

**Comment by jgcmarins** [comment]
We did a new release, can you try it? v1.2.0.
Thank you.

**Comment by Noitidart** [comment]
Thanks @jgcmarins for your continued support!!

**Comment by MateusAndrade** [comment]
With the default react-native share you can pass a URL on the Share. I cant say that this  share a file when passing this param.

Btw, im closing the issue. If you have any doubt, please fell free to reopen this. :D
