### ISSUE TITLE
Does this work with Instagram?

### ISSUE THREAD

**Issue by kunalnagar** [react-native-community/react-native-share#2]
I am trying to share an external image to Instagram. Will this work?

**Comment by EstebanFuentealba** [comment]
could include, checked the instagram documentation and if possible ( https://instagram.com/developer/mobile-sharing/android-intents/ and https://instagram.com/developer/mobile-sharing/iphone-hooks/ ). I should implement it in this library

**Comment by pewh** [comment]
So any progress about this?

**Comment by superandrew213** [comment]
Just submitted a [pr](https://github.com/EstebanFuentealba/react-native-share/pull/34) for this.
