### ISSUE TITLE
com.share01.MainApplication cannot be cast to cl.json.ShareApplication

### ISSUE THREAD

**Issue by monkingame** [react-native-community/react-native-share#200]
I created a test react-native project,but got error:
com.share01.MainApplication cannot be cast to cl.json.ShareApplication

steps:
1)react-native init share01
2)yarn add react-native-share
3)react-native link
4)copy the sample codes to replace index.js
5)react-native run-android and got error

react-native environment:
Environment:
  OS: macOS High Sierra 10.13.2
  Node: 9.3.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.52.0 => 0.52.0

so,what's the error?

Thanks!

![35183311-e198f35e-fe1e-11e7-80e6-f2e10a5a19d7](https://user-images.githubusercontent.com/4568610/35188703-9bebadcc-fe75-11e7-916a-e0af96d64d84.jpg)

**Comment by giturra** [comment]
Same issues here

**Comment by maxocg** [comment]
Same issues here

**Comment by jgcmarins** [comment]
@ygorbarboza maybe this is related to your fix? What do you think?

**Comment by sibelius** [comment]
Follow README instructions

**Comment by monkingame** [comment]
@sibelius @jgcmarins Thanks !
I think the lastest version(v1.0.24) maybe have some bugs or I do not know how to config.
Here are my steps to test(I tested 3 version: v1.0.21 v1.0.23 v1.0.24):

1)react-native init TestShare
the test project will use v1.0.21
and two other project:TestShare23 TestShare24
2)yarn
install node_moudles
)using android studio to open TestShare/android project(for building)
)open android emulator
)react-native run-android
(All above steps sure no problems)
)yarn add react-native-share@1.0.21
here I tested 3 versions in different projects.
version test:1.0.21/1.0.23/1.0.24
)react-native link
)react-native run-android
For rebuilding
)copy sample codes to override index.js
)press r twice to reload app in emulator
)click 3 sample buttons
[Simple Share Image base64]:
v1.0.21 v1.0.23 OK
v1.0.24 got error:
com.testshare24.MainApplication cannot be cast to cl.json.ShareApplication
[Simple Share]:
All versions OK
[Share UI Component]:
All versions OK
<img width="277" alt="wx20180121-073414 2x" src="https://user-images.githubusercontent.com/4568610/35189040-90c24674-fe7d-11e7-9532-4c79d77fe7d7.png">

Thanks again!

**Comment by ozmaat** [comment]
It was working  before. Upgraded the package a couple of days ago. While testing today, noticed the same issue.

**Comment by sibelius** [comment]
Check the latest commits on readme, something changed

**Comment by ozmaat** [comment]
I have made the new changes. Added the provider with meta-data as below

```
<
provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:grantUriPermissions="true"
            android:exported="false">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/filepaths" />
        </provider>

```

Created a  filepaths..xml under the directory - android\app\src\main\res\xml


```
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <files-path name="img" path="."/>
</paths>

```

Now get the following error:
`
Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference

`
Any pointers what could be the issue.

**Comment by jgcmarins** [comment]
@ozmaat this happens because we need to use `com.my.app` instead of `applicationId`, where `com.my.app` is your app's package

**Comment by ozmaat** [comment]
Thanks @jgcmarins  but not sure what we need to do to solve the issue. 

Tested it with ` android:authorities="com.my.app.fileprovider"`, same error occurs.

**Comment by Mikoz93** [comment]
@ozmaat 

Try this:

**AndroidManifest.xml:**

```
<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="com.yourpackage.name.provider"
            android:grantUriPermissions="true"
            android:exported="false">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/filepaths" />
        </provider>
```

**MainApplication.java:**

Add an implementation to the MainApplication class

```
import cl.json.ShareApplication;
public class MainApplication extends Application implements ShareApplication, ReactApplication 
```

Add an override

```
 @Override
     public String getFileProviderAuthority() {
            return "com.yourpackage.name.provider";
     }
```
Notice that I've hard coded the package name, it wouldn't work for me otherwise.

**Comment by inventrix** [comment]
@Mikoz93 this seems to work.

**Comment by ozmaat** [comment]
Thanks @Mikoz93. It solved the xml error.

I  get a different error, I think it is related with the defining the right path for android. 

`Failed to find configured root that contains /storage/emulated/0/Download/1517644516612.png`

I use a snapshot plugin, which  saves png file at "/storage/emulated/0/Download".

I have tried different paths in filepaths.xml but yet to find the correct path to define.

Anyone else faced a similar issue?

**Comment by Jimmy-YMJ** [comment]
@ozmaat try replace `files-path` to `external-path`

**Comment by FlintOFF** [comment]
Fixed for me. Just do next two steps:
1. npm install react-native-share@1.0.23 --save
2. react-native link

**Comment by ozmaat** [comment]
@Jimmy-YMJ - thanks a lot. using the external path solved the issue.

`<external-path name="myexternalimages" path="Download/" />`

**Comment by jgcmarins** [comment]
Great to hear from you @Jimmy-YMJ and @ozmaat .
Could someone send a PR to add this information here: https://github.com/EstebanFuentealba/react-native-share#android
?
Thanks!

**Comment by alsh76** [comment]
I am stuck with same issue in Android version
I am trying to share remote image 
```
RNFetchBlob.config({
    fileCache : true,
    appendExt : 'jpg'
}).fetch('GET', url, {})
.then((res) => {
    let uri = Platform.OS === 'android' ? 'file://' + res.path() : '' + res.path();
    let shareOptions = {
        message: title,
        url: uri,
        type: "image/jpeg",
        subject: title
      }
    Share.open(shareOptions).catch((err) => { err && console.log(err); })
});
```
in version 1.0.23 a compilation error happens
`cannot find symbol import cl.json.ShareApplication;`

in latest version the app crashes with an error
`Missing android.support.FILE_PROVIDER_PATHS meta-data`
probably it requires some xml resource. 
But what kind of resource should be in my case for images saved in the app cache?

**Comment by tribou** [comment]
Thanks to everyone on this thread who helped work towards a solution on getting this current version to work on Android. I've tried so summarize the missing documentation with #228 in case any maintainers would like to take a look. 🙂

**Comment by judemanutd** [comment]
My files are being stored at `/data/user/0/com.example/files/filename.jpg`. 
Could someone tell me what should my file provider look like if i need to share the above file in android ?

It is currently this 
        `<paths>`
          `  <cache-path`
             `  name="images"`
             `  path="." />`
        `</paths>`

I get the `Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference` error. I have implemented  `ShareApplication` and overriden the `getFileProviderAuthority` where i specified the package name, I also specified the package name in the manifest file like so ` android:authorities="com.example.fileprovider"` . Still getting the error

**Comment by Hieutt1704** [comment]
my files save in "/data/data/com.sharedemo/cache/ReactNative-snapshot-image-1345886953.png" .   What is my external path? :( Can someone  solve it for me, plz! :( :( :(

**Comment by jgcmarins** [comment]
https://github.com/react-native-community/react-native-share/pull/228

**Comment by mjm918** [comment]
@Hieutt1704 
try this:

```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path
        name="external_files"
        path="." />
    <files-path
        name="files-path"
        path="." /> <!-- Used to access into application data files -->
</paths>
```

**Comment by Ilario17** [comment]
@Hieutt1704 have you solved that issue?

**Comment by vforvasile** [comment]
@Mikoz93  you are my HERO <3 <3 (love you)

**Comment by jgcmarins** [comment]
Just remembering that all those informations are at [README](https://github.com/react-native-community/react-native-share/blob/master/README.md#android-install) file

**Comment by FabricioCabeca** [comment]
Had the same problem as @Hieutt1704 , fixed adding this inside android/app/src/main/res/xml/filepaths.xml:

`    <cache-path
        name="cache"
        path="." />
`

**Comment by marcio-eric** [comment]
@Mikoz93 Thank you! Worked like a charm!

**Comment by collbreno** [comment]
> @ozmaat
> 
> Try this:
> 
> **AndroidManifest.xml:**
> 
> ```
> <provider
>             android:name="android.support.v4.content.FileProvider"
>             android:authorities="com.yourpackage.name.provider"
>             android:grantUriPermissions="true"
>             android:exported="false">
>             <meta-data
>                 android:name="android.support.FILE_PROVIDER_PATHS"
>                 android:resource="@xml/filepaths" />
>         </provider>
> ```
> 
> **MainApplication.java:**
> 
> Add an implementation to the MainApplication class
> 
> ```
> import cl.json.ShareApplication;
> public class MainApplication extends Application implements ShareApplication, ReactApplication 
> ```
> 
> Add an override
> 
> ```
>  @Override
>      public String getFileProviderAuthority() {
>             return "com.yourpackage.name.provider";
>      }
> ```
> 
> Notice that I've hard coded the package name, it wouldn't work for me otherwise.

It works, but, as you say, you'he hard coded it. There's a right way to do that.
**AndroidManifest.xml**
`...
<provider>
  ...
  android:authorities="${applicationId}.provider"
  ...
</provider>`

**Comment by collbreno** [comment]
> @ozmaat
> 
> Try this:
> 
> **AndroidManifest.xml:**
> 
> ```
> <provider
>             android:name="android.support.v4.content.FileProvider"
>             android:authorities="com.yourpackage.name.provider"
>             android:grantUriPermissions="true"
>             android:exported="false">
>             <meta-data
>                 android:name="android.support.FILE_PROVIDER_PATHS"
>                 android:resource="@xml/filepaths" />
>         </provider>
> ```
> 
> **MainApplication.java:**
> 
> Add an implementation to the MainApplication class
> 
> ```
> import cl.json.ShareApplication;
> public class MainApplication extends Application implements ShareApplication, ReactApplication 
> ```
> 
> Add an override
> 
> ```
>  @Override
>      public String getFileProviderAuthority() {
>             return "com.yourpackage.name.provider";
>      }
> ```
> 
> Notice that I've hard coded the package name, it wouldn't work for me otherwise.

It works, but, as you say, you've hard coded that. There's a right way to do it. Just change these two lines.
**AndroidManifest.xml**
```
...
<provider>
...
  android:authorities="${applicationId}.provider"
...
</provider>
```

**MainApplication.java**
```
@Override
public String getFileProviderAuthority() {
  return BuildConfig.APPLICATION_ID+".provider";
}
```

It's exactly the same thing. But this will take the application Id defined in the build.gradle file. This way you can change the applicationId and it will still work

**Comment by collbreno** [comment]
@Mikoz93 Your code works, but, as you say, you've hard coded that. There's a right way to do it. Just change these two lines.
**AndroidManifest.xml**
```
...
<provider>
...
  android:authorities="${applicationId}.provider"
...
</provider>
```

**MainApplication.java**
```
@Override
public String getFileProviderAuthority() {
  return BuildConfig.APPLICATION_ID+".provider";
}
```
It's exactly the same thing. But this will take the application Id defined in the build.gradle file. This way you can change the applicationId and it will still work.
