### ISSUE TITLE
Linker fail __RCTLogFormat undefined symbol

### ISSUE THREAD

**Issue by tirrorex** [react-native-community/react-native-share#205]
React-native 0.51
react-native-share 1.0.24

Undefined symbols for architecture arm64:
  "__RCTLogFormat", referenced from:
      -[RNShare shareSingle:failureCallback:successCallback:] in libRNShare.a(RNShare.o)
ld: symbol(s) not found for architecture arm64

Imo it is a path issue, struggling to fix it though, it this a known issue ?

**Comment by enieber** [comment]
@tirrorex can you test in the master branch version?

**Comment by tirrorex** [comment]
@enieber Sorry i forgot to close the issue, i moved to something else.
