### ISSUE TITLE
Is it possible to customize preview image and/or url for different apps?

### ISSUE THREAD

**Issue by akirasunny** [react-native-community/react-native-share#206]
Thanks for authors' nice work, I am using this module to create share button for my app.

I'm wondering if it is possible to customize preview image. Below is a screenshot of share page. As it shows, the preview now is a placeholder image, I want to substitute it with a customized one.

Also I wonder if I can use different urls for different apps in simple share.

Thanks in advance.

![img_5487](https://user-images.githubusercontent.com/29238252/35409195-5b962384-01c6-11e8-8d3e-5153dc6b81d5.JPG)

**Comment by enieber** [comment]
@akirasunny is your request for Android and iOS or only one platform?
