### ISSUE TITLE
[iOS] Issues when sharing PDF

### ISSUE THREAD

**Issue by MatiasBontempo** [react-native-community/react-native-share#207]
Hi, we have several issues when sharing a PDF with this package.

When sharing via email, the file is missing the .pdf extension and the name is a 5 digits number.
When sharing vie whatsapp, the file is not attached and only the 'message' is sent.
When sharing via telegram, the file is correctly attached but with the name 'file.pdf'

This is the code we are using:

```
          Share.open({
            title: this.props.title,
            url: `data:application/pdf;base64,${data}`,
            message: `Factura de ${this.props.title}`,
            subject: `Factura de ${this.props.title}`,
          });
```

Everything is working fine in Android (filenames are kind of random, but at least you can attach the files with the correct extension)

Is there any way we can:
1. Solve the email and whatsapp issue?
2. Set a custom name to the file?

Let me know if you need more information.
Thanks!

**Comment by jgcmarins** [comment]
@MatiasBontempo PRs are welcome \o/

**Comment by BigPun86** [comment]
@MatiasBontempo is there any progress according to 

> When sharing via email, the file is missing the .pdf extension and the name is a 5 digits number.

> When sharing vie whatsapp, the file is not attached and only the 'message' is sent.


I am facing the same problem. I tried to dig into the source code, but somehow i am not an iOS expert :D

**Comment by BigPun86** [comment]
@MatiasBontempo never mind, i fixed it => https://github.com/react-native-community/react-native-share/issues/281

**Comment by yeomann** [comment]
related to https://github.com/react-native-community/react-native-share/issues/281
