### ISSUE TITLE
No option to enter recipients for iMessage/SMS

### ISSUE THREAD

**Issue by ajonno** [react-native-community/react-native-share#212]
It displays the share sheet fine, but then the iMessage popup has nowhere(!) to enter actual recipients

![img_23c10f0c7957-1](https://user-images.githubusercontent.com/3005269/36068099-27cc2158-0f21-11e8-859c-7f62383c08a5.jpeg)

**Comment by jasongaare** [comment]
Experiencing the same issue. Seem to be isolated to the iPhone X

**Comment by Vitiell0** [comment]
I am having this problem with my project as well on iPhone X. I started a brand new `create-react-native-app` and tested the Share dialogue. It worked and I could enter recipients on the iPhone X so now am looking to see if there is some xcode config setting that could be causing it.

**Comment by ericlewis** [comment]
The issue appears to be with hiding and showing the status bar on iPhone X. You must show the status bar before displaying the share sheet. This is definitely an apple bug, but you can work around it pretty easily.

**Comment by jgcmarins** [comment]
@ericlewis thanks for your reply.
Could you provide an example of this implementation? Thanks.

**Comment by Vitiell0** [comment]
@jgcmarins I just tested the solution by @ericlewis and it worked. You can simply import StatusBar from react-native and then use `<StatusBar hidden={false} />` inside your container on the screen that you are calling Share from.

**Comment by jgcmarins** [comment]
Great \o/
Thank you @ericlewis and @Vitiell0!
