### ISSUE TITLE
Add Instagram and SnapChat in shareSingle option

### ISSUE THREAD

**Issue by priyankinfinnov** [react-native-community/react-native-share#216]
The headline is self-evident :P

**Comment by priyankinfinnov** [comment]
As far as I understand to add a network one need to do - 
1. Add 1 line in [RNShareModule](https://github.com/EstebanFuentealba/react-native-share/blob/master/android/src/main/java/cl/json/RNShareModule.java) file under the RNShareModule method.
2. Create a class at [path](https://github.com/EstebanFuentealba/react-native-share/tree/master/android/src/main/java/cl/json/social) exactly similar to [WhatsApp Share Classs](https://github.com/EstebanFuentealba/react-native-share/blob/master/android/src/main/java/cl/json/social/WhatsAppShare.java)

PS: this is only for android, idk about iOS.

**Comment by priyankinfinnov** [comment]
Submitted a pull request for this [https://github.com/EstebanFuentealba/react-native-share/pull/219](here)

**Comment by nicholasess** [comment]
@priyankinfinnov your link not work

**Comment by jgcmarins** [comment]
here is the right link: https://github.com/react-native-community/react-native-share/pull/219

**Comment by jgcmarins** [comment]
https://github.com/react-native-community/react-native-share/releases/tag/v1.2.0
