### ISSUE TITLE
Singleshare is giving error on android if twitter is not installed

### ISSUE THREAD

**Issue by nishantagrawal25** [react-native-community/react-native-share#217]
Hi,

When I am trying to do singleshare via twitter and If app is not installed on my phone it is giving following error on android 

![error](https://user-images.githubusercontent.com/13209229/36595006-89505e18-18c6-11e8-9c18-5720e1a41eaa.png)

**Comment by dianazzz** [comment]
Same issue for Facebook... How can I handle it??....

**Comment by Nick-Patrick** [comment]
Getting this for Twitter / Facebook / Google+ at least..

**Comment by priyankinfinnov** [comment]
+1

**Comment by UsovSemen** [comment]
same issue. I think, it should open web to share.

**Comment by profiVideos** [comment]
I also had this issue.  Was able to get it resolved by making a couple of edits in the MainApplication.java file (I think)?  Just closed the issue this morning. See here https://github.com/EstebanFuentealba/react-native-share/issues/229

**Comment by dianazzz** [comment]
The error is gone now. But if Twitter is not present it should open web to share right? But it opens google photo and gallery to share. 👎
