### ISSUE TITLE
Error while trying to display: view is not in the window hierarchy

### ISSUE THREAD

**Issue by Gedzis** [react-native-community/react-native-share#22]
Hey, 
anyone faced issue while trying to display share:

```
 Warning: Attempt to present <UIActivityViewController: 0x14f8baf80> on <UIViewController: 0x14e7306e0> whose view is not in the window hierarchy!
```

After this `warning` share isn't visible. 
I tried to call this in upper level of my app and it helped, but it isn't best solution. 

I there any way to fix this? I am not familiar with native iOS.

**Comment by ayberkanilatsiz** [comment]
@Gedzis did you find solution? I have same issue too.

**Comment by Gedzis** [comment]
@enieber I haven't tried this for a long time now
