### ISSUE TITLE
shareSingle: undefined is not an object 

### ISSUE THREAD

**Issue by agrawalo** [react-native-community/react-native-share#222]
[exp] undefined is not an object (evaluating '_reactNative.NativeModules.RNShare.shareSingle')
- node_modules/react-native-share/index.js:62:30 in <unknown>
- node_modules/promise/setimmediate/core.js:45:7 in tryCallTwo
- node_modules/promise/setimmediate/core.js:200:23 in doResolve
- node_modules/promise/setimmediate/core.js:66:12 in Promise
- node_modules/react-native-share/index.js:61:25 in shareSingle
* components/PreviewImage.js:72:58 in <unknown>
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:154:6 in _callTimer
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:411:17 in callTimers
- ... 5 more stack frames from framework internals

Created question in stackoverflow as well https://stackoverflow.com/questions/49082623/react-native-share-promise-rejection-error

**Comment by GSolari79** [comment]
I am facing the same problem too, anyone with a solution? In my case it occurs only in Android.

**Comment by riyadh89** [comment]
undefined is not an object (evaluating '_reactNative.NativeModules.RNShare.shareSingle')

I am facing the same problem too. anyone with a solution?
Tried upgrading & downgrading the version but not succeed.

    "react": "16.4.1",
    "react-native": "0.55.4",
    "react-native-share": "^1.1.1",

**Comment by jgcmarins** [comment]
is happening on both android and ios?

**Comment by riyadh89** [comment]
@jgcmarins i haven't tried IOS yet.

**Comment by samgermain** [comment]
Make sure you have `import Share from 'react-native-share'` instead of `import {Share} from 'react-native-share'`
