### ISSUE TITLE
Cannot open Facebook app in iOS

### ISSUE THREAD

**Issue by hycwong** [react-native-community/react-native-share#226]
When I use this library in my iOS project, I can't open the singleShare API (Facebook).
The console log is shown below:

> 2018-03-16 10:22:01.046677+0800 <my app name>[303:10759] [] nw_connection_get_connected_socket_block_invoke 103 Connection has no connected handler
2018-03-16 10:22:01.268689+0800 <my app name>[303:10759] [] nw_connection_get_connected_socket_block_invoke 104 Connection has no connected handler
2018-03-16 10:22:01.473 [info][tid:com.facebook.react.JavaScript] trying api: customers/5/socialMedia/reward {"platform":"1"} true POST
2018-03-16 10:22:01.472951+0800 <my app name>[303:10646] trying api: customers/5/socialMedia/reward {"platform":"1"} true POST
2018-03-16 10:22:01.475251+0800 <my app name>[303:10441] facebook
2018-03-16 10:22:01.475727+0800 <my app name>[303:10441] TRY OPEN FACEBOOK
2018-03-16 10:22:01.476055+0800 <my app name>[303:10441] Try open view
2018-03-16 10:22:01.476797+0800 <my app name>[303:10441] [core] SLComposeViewController isAvailableForServiceType com.apple.social.facebook
2018-03-16 10:22:01.480459+0800 <my app name>[303:10441] [core] SLComposeViewController isAvailableForServiceType got serviceType com.apple.social.facebook isAvailable 0
2018-03-16 10:22:01.480699+0800 <my app name>[303:10441] [core] SLComposeViewController isAvailableForServiceType got extension <NSExtension: 0x170362040> {id = com.apple.share.Facebook.post} for extensionIdentifer com.apple.share.Facebook.post
2018-03-16 10:22:01.480903+0800 <my app name>[303:10441] [core] SLComposeViewController isAvailableForServiceType returning YES for overridden extensionIdentifier com.apple.share.Facebook.post
2018-03-16 10:22:01.481122+0800 <my app name>[303:10441] [core] SLComposeViewController isAvailableForServiceType com.apple.social.facebook returning 1
2018-03-16 10:22:01.481441+0800 <my app name>[303:10441] [core] SLComposeViewController initWithServiceType: com.apple.social.facebook
2018-03-16 10:22:01.481824+0800 <my app name>[303:10441] [core] SLComposeViewController initWithServiceType got extension <NSExtension: 0x170362040> {id = com.apple.share.Facebook.post} for identifier com.apple.share.Facebook.post
2018-03-16 10:22:01.482277+0800 <my app name>[303:10441] [core] SLComposeViewController initWithExtension: <NSExtension: 0x170362040> {id = com.apple.share.Facebook.post} requestedServiceType: com.apple.social.facebook
2018-03-16 10:22:01.482993+0800 <my app name>[303:10441] [core] SLComposeViewController initWithExtension got override extension <NSExtension: 0x170362040> {id = com.apple.share.Facebook.post}
2018-03-16 10:22:01.507343+0800 <my app name>[303:10441] [core] SLComposeViewController dealloc <SLComposeViewController: 0x109d1d120>
2018-03-16 10:22:01.519 [info][tid:com.facebook.react.JavaScript] { error: 
   { code: 'ENSCOCOAERRORDOMAIN260',
     nativeStackIOS: 
      [ '0   <my app name>                              0x00000001001bd46c RCTJSErrorFromCodeMessageAndNSError + 152',
        '1   <my app name>                              0x00000001001bd394 RCTJSErrorFromNSError + 264',
        '2   <my app name>                              0x000000010015b1e0 __41-[RCTModuleMethod processMethodSignature]_block_invoke_2.187 + 144',
        '3   <my app name>                              0x00000001000bd260 -[GenericShare shareSingle:failureCallback:successCallback:serviceType:] + 756',
        '4   <my app name>                              0x00000001000bbb88 -[RNShare shareSingle:failureCallback:successCallback:] + 384',
        '5   CoreFoundation                      0x0000000188b40e80 <redacted> + 144',
        '6   CoreFoundation                      0x0000000188a362b4 <redacted> + 292',
        '7   CoreFoundation                      0x0000000188a3ae7c <redacted> + 60',
        '8   <my app name>                              0x000000010015dc64 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2064',
        '9   <my app name>                              0x0000000100202998 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 664',
        '10  <my app name>                              0x0000000100202528 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 132',
        '11  <my app name>                              0x0000000100202498 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 28',
        '12  libdispatch.dylib                   0x0000000100a31a50 _dispatch_call_block_and_release + 24',
        '13  libdispatch.dylib                   0x0000000100a31a10 _dispatch_client_callout + 16',
        '14  libdispatch.dylib                   0x0000000100a36b78 _dispatch_main_queue_callback_4CF + 1204',
        '15  CoreFoundation                      0x0000000188ae90c0 <redacted> + 12',
        '16  CoreFoundation                      0x0000000188ae6cdc <redacted> + 1572',
        '17  CoreFoundation                      0x0000000188a16d94 CFRunLoopRunSpecific + 424',
        '18  GraphicsServices                    0x000000018a480074 GSEventRunModal + 100',
        '19  UIKit                               0x000000018eccf130 UIApplicationMain + 208',
        '20  <my app name>                              0x00000001000375e0 main + 124',
        '21  libdyld.dylib                       0x0000000187a2559c <redacted> + 4' ],
     userInfo: 
      { NSUnderlyingError: 
         { code: '2',
           nativeStackIOS: 
            [ '0   <my app name>                              0x00000001001bd46c RCTJSErrorFromCodeMessageAndNSError + 152',
              '1   <my app name>                              0x00000001001bd7c8 RCTJSErrorFromCodeMessageAndNSError + 1012',
              '2   <my app name>                              0x00000001001bd394 RCTJSErrorFromNSError + 264',
              '3   <my app name>                              0x000000010015b1e0 __41-[RCTModuleMethod processMethodSignature]_block_invoke_2.187 + 144',
              '4   <my app name>                              0x00000001000bd260 -[GenericShare shareSingle:failureCallback:successCallback:serviceType:] + 756',
              '5   <my app name>                              0x00000001000bbb88 -[RNShare shareSingle:failureCallback:successCallback:] + 384',
              '6   CoreFoundation                      0x0000000188b40e80 <redacted> + 144',
              '7   CoreFoundation                      0x0000000188a362b4 <redacted> + 292',
              '8   CoreFoundation                      0x0000000188a3ae7c <redacted> + 60',
              '9   <my app name>                              0x000000010015dc64 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2064',
              '10  <my app name>                              0x0000000100202998 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 664',
              '11  <my app name>                              0x0000000100202528 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 132',
              '12  <my app name>                              0x0000000100202498 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 28',
              '13  libdispatch.dylib                   0x0000000100a31a50 _dispatch_call_block_and_release + 24',
              '14  libdispatch.dylib                   0x0000000100a31a10 _dispatch_client_callout + 16',
              '15  libdispatch.dylib                   0x0000000100a36b78 _dispatch_main_queue_callback_4CF + 1204',
              '16  CoreFoundation                      0x0000000188ae90c0 <redacted> + 12',
              '17  CoreFoundation                      0x0000000188ae6cdc <redacted> + 1572',
              '18  CoreFoundation                      0x0000000188a16d94 CFRunLoopRunSpecific + 424',
              '19  GraphicsServices                    0x000000018a480074 GSEventRunModal + 100',
              '20  UIKit                               0x000000018eccf130 UIApplicationMain + 208',
              '21  <my app name>                              0x00000001000375e0 main + 124',
              '22  libdyld.dylib                       0x0000000187a2559c <redacted> + 4' ],
           userInfo: {},
           message: 'underlying error',
           domain: 'NSPOSIXErrorDomain' },
        NSFilePath: '/var/containers/Bundle/Application/3DDA9D9F-AEDE-4F83-8287-1A55E91D8241/<my app name>.app/<my app name>.com' },
     message: 'The file “<my app name>.com” couldn’t be opened because there is no such file.',
     domain: 'NSCocoaErrorDomain' } }
2018-03-16 10:22:01.521111+0800 <my app name>[303:10646] { error: 
   { code: 'ENSCOCOAERRORDOMAIN260',
     nativeStackIOS: 
      [ '0   <my app name>                              0x00000001001bd46c RCTJSErrorFromCodeMessageAndNSError + 152',
        '1   <my app name>                              0x00000001001bd394 RCTJSErrorFromNSError + 264',
        '2   <my app name>                              0x000000010015b1e0 __41-[RCTModuleMethod processMethodSignature]_block_invoke_2.187 + 144',
        '3   <my app name>                              0x00000001000bd260 -[GenericShare shareSingle:failureCallback:successCallback:serviceType:] + 756',
        '4   <my app name>                              0x00000001000bbb88 -[RNShare shareSingle:failureCallback:successCallback:] + 384',
        '5   CoreFoundation                      0x0000000188b40e80 <redacted> + 144',
        '6   CoreFoundation                      0x0000000188a362b4 <redacted> + 292',
        '7   CoreFoundation                      0x0000000188a3ae7c <redacted> + 60',
        '8   <my app name>                              0x000000010015dc64 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2064',
        '9   <my app name>                              0x0000000100202998 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 664',
        '10  <my app name>                              0x0000000100202528 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 132',
        '11  <my app name>                              0x0000000100202498 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 28',
        '12  libdispatch.dylib                   0x0000000100a31a50 _dispatch_call_block_and_release + 24',
        '13  libdispatch.dylib                   0x0000000100a31a10 _dispatch_client_callout + 16',
        '14  libdispatch.dylib                   0x0000000100a36b78 _dispatch_main_queue_callback_4CF + 1204',
        '15  CoreFoundation                      0x0000000188ae90c0 <redacted> + 12',
        '16  CoreFoundation                      0x0000000188ae6cdc <redacted> + 1572',
        '17  CoreFoundation                      0x0000000188a16d94 CFRunLoopRunSpecific + 424',
        '18  GraphicsServices                    0x000000018a480074 GSEventRunModal + 100',
        '19  UIKit                               0x000000018eccf130 UIApplicationMain + 208',
        '20  <my app name>                              0x00000001000375e0 main + 124',
        '21  libdyld.dylib                       0x0000000187a2559c <redacted> + 4' ],
     userInfo: 
      { NSUnderlyingError: 
         { code: '2',
           nativeStackIOS: 
            [ '0   <my app name>                              0x00000001001bd46c RCTJSErrorFromCodeMessageAndNSError + 152',
              '1   <my app name>                              0x00000001001bd7c8 RCTJSErrorFromCodeMessageAndNSError + 1012',
              '2   <my app name>                              0x00000001001bd394 RCTJSErrorFromNSError + 264',
              '3   <my app name>                              0x000000010015b1e0 __41-[RCTModuleMethod processMethodSignature]_block_invoke_2.187 + 144',
              '4   <my app name>                              0x00000001000bd260 -[GenericShare shareSingle:failureCallback:successCallback:serviceType:] + 756',
              '5   <my app name>                              0x00000001000bbb88 -[RNShare shareSingle:failureCallback:successCallback:] + 384',
              '6   CoreFoundation                      0x0000000188b40e80 <redacted> + 144',
              '7   CoreFoundation                      0x0000000188a362b4 <redacted> + 292',
              '8   CoreFoundation                      0x0000000188a3ae7c <redacted> + 60',
              '9   <my app name>                              0x000000010015dc64 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2064',
              '10  <my app name>                              0x0000000100202998 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 664',
              '11  <my app name>                              0x0000000100202528 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 132',
              '12  <my app name>                              0x0000000100202498 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 28',
              '13  libdispatch.dylib                   0x0000000100a31a50 _dispatch_call_block_and_release + 24',
              '14  libdispatch.dylib                   0x0000000100a31a10 _dispatch_client_callout + 16',
              '15  libdispatch.dylib                   0x0000000100a36b78 _dispatch_main_queue_callback_4CF + 1204',
              '16  CoreFoundation                      0x0000000188ae90c0 <redacted> + 12',
              '17  CoreFoundation                      0x0000000188ae6cdc <redacted> + 1572',
              '18  CoreFoundation                      0x0000000188a16d94 CFRunLoopRunSpecific + 424',
              '19  GraphicsServices                    0x000000018a480074 GSEventRunModal + 100',
              '20  UIKit                               0x000000018eccf130 UIApplicationMain + 208',
              '21  <my app name>                              0x00000001000375e0 main + 124',
              '22  libdyld.dylib                       0x0000000187a2559c <redacted> + 4' ],
           userInfo: {},
           message: 'underlying error',
           domain: 'NSPOSIXErrorDomain' },
        NSFilePath: '/var/containers/Bundle/Application/3DDA9D9F-AEDE-4F83-8287-1A55E91D8241/<my app name>.app/<my app name>.com' },
     message: 'The file “<my app name>.com” couldn’t be opened because there is no such file.',
     domain: 'NSCocoaErrorDomain' } }

The singleShare (FB) works fine in Android, thanks. :)

P.S. When FB app is NOT installed in iOS, the iOS can open Facebook share page as usual.

**Comment by aniiskywalker** [comment]
Same issue

**Comment by enieber** [comment]
@hycwong you can show the implementation code?

**Comment by jgcmarins** [comment]
try on master
