### ISSUE TITLE
file format is not supported on WhatsApp on Android 7.1.1

### ISSUE THREAD

**Issue by profiVideos** [react-native-community/react-native-share#231]
Hi Guys, I'm loving this amazing share module that you have developed!!!

I know it's not easy supporting so many versions of iOS and Android.

I was just wondering if anyone has gotten the base64 images to WhatsApp working?  Or is it even supposed to work?  On my first tests, I was sure to use the .catch(err) when calling the shareSingle method.

Here's what I'm doing;

    const titleStr = `photoDrop - ${card.name}`;
    const imageStr = `data:${card.mimeType};base64,${card.imageThumb}`;
    shareOptions = {
      title: titleStr,
      message: card.desc,
      url: imageStr,
      type: card.mimeType,
      subject: `Shared ${titleStr}`, //  for email
    };
 ... and ...

        <Button 
          iconSrc={{ uri: WHATSAPP_ICON }}
          onPress={() => {
            this.onCancel();
            setTimeout(() => {
              Share.shareSingle(Object.assign(shareOptions, { social: 'whatsapp' }))
              .catch(err => ToastAndroid.show(`Error: ${JSON.stringify(err)}`, ToastAndroid.LONG));
            }, 300);
          }}
        >WhatsApp</Button>

and here's what happens when it invokes WhatsApp on the simulator.

![file-format-unsupported](https://user-images.githubusercontent.com/33458533/37853018-2d765a36-2ee5-11e8-9040-d1cf4a3580ce.png)

**Comment by enieber** [comment]
what version are you using @profiVideos ?

**Comment by Vaibhav21pandit** [comment]
I am facing the same issue when sharing local image on whatsapp on Android.
