### ISSUE TITLE
Share single iOS base64 img problem

### ISSUE THREAD

**Issue by melihberberolu** [react-native-community/react-native-share#232]
Share single method works on android perfectly.

iOS sharing whatsapp, fb, twitter does not show my base64 img

`const storedImg = `data:image/png;base64,${resp.base64Img}`;
  Share.shareSingle({
    title: _('Tone Tone High Score Share'),
    message: "https://apple.co/2pmdyte",
    url: storedImg,
    subject: "https://apple.co/2pmdyte",
    social
  }).then(res => res)
    .catch(e => e);`

**Comment by jgcmarins** [comment]
@melihberberolu could you provide more details about your problem?

**Comment by melihberberolu** [comment]
I'm trying to share image on social media.(Facebook, whatsapp, twitter)
My sharing is works perfectly in android platform.
But my message and base64 string not transform to image.
It's show url + base64 string.

**Comment by jgcmarins** [comment]
@melihberberolu could you provide some code example? Thanks.

**Comment by melihberberolu** [comment]
Yes sure @jgcmarins. You can share any example with me for sharing base64Img on iOS.
```
const share = (base64Img, social = 'facebook') => {
  Share.shareSingle({
    title: "Tone Tone High Score Share",
    message: "https://apple.co/2pmdyte",
    url: `data:image/png;base64,${base64Img}`,
    subject: "https://apple.co/2pmdyte",
    social
 }).then(res => res)
    .catch(e => e);
}
```

**Comment by phillmill** [comment]
@melihberberolu did you solve?

**Comment by ruimfernandes** [comment]
@melihberberolu are you sure your image is well converted into base64? And are you sure your image is **png** or it can have another extension?

Try to paste the result of `data:image/png;base64,${base64Img}` at the website and check if the image is rendered.
https://codebeautify.org/base64-to-image-converter

I'm using `Share.open` and the only problem I have while using base64 it's with Whatsapp
```
        base64Data = `data:image/${type};base64,` + base64Data;
        Share.open({
          url: base64Data
        });
```

**Comment by never00miss** [comment]
did anyone solve this?

**Comment by jgcmarins** [comment]
We have a troubleshooting section about sharing base64 files: https://github.com/react-native-community/react-native-share#troubleshooting

**Comment by atdparvaiz** [comment]
The issue still persists, did anybody solved it?

**Comment by jgcmarins** [comment]
We did a new release, can you try it? v1.2.0.
Thank you.

**Comment by vivekvijayakrishnan** [comment]
Still, It's not working. anybody resolved the issue? I'm using `1.2.1` version

**Comment by phillmill** [comment]
@vivekvijayakrishnan I managed to work around this in 1.2.1- instead of sharing with base64, I used just the actual file uri instead. It worked for me

**Comment by vivekvijayakrishnan** [comment]
@phillmill Thanks for the reply..It didn't solve the issue for me. @IbrahimSulai had a fix for this and it worked fine.

**Comment by YathaarthJamwal** [comment]
I still have this issue. RNShare "3.5.0". RN "0.62.2". Any leads?
The image base64 text (passed as url) just gets appended after the message. I tried using relative file path as well, but same thing happens. Anyone knows how to solve this? Or any alternative method would be of help also.

**Comment by YathaarthJamwal** [comment]
Can we reopen this issue?

**Comment by MateusAndrade** [comment]
Hi, @YathaarthJamwal thanks for sharing this with us. I faced the same issue and decided to pass the image only. 😢 

Personally, I prefer to open an issue dedicated to this, or even updating our docs regarding this problem. Please let me know if there is anything that I can help you.

**Comment by YathaarthJamwal** [comment]
@MateusAndrade I actually needed to send both text and image.

**Comment by MateusAndrade** [comment]
> @MateusAndrade I actually needed to send both text and image.

If you are trying to share both to WhatsApp, currently we have some problems achieving that. Personally I decided to remove one parameter, passing the url only.
