### ISSUE TITLE
image is not getting share in android

### ISSUE THREAD

**Issue by MbF-Sathya** [react-native-community/react-native-share#233]
here is my issue I wrote a question on here - https://stackoverflow.com/questions/49516150/base64-image-not-sharing-in-react-native-android . 
in iOS its working perfect.

**Comment by Mifayo** [comment]
i have the same problem it get confused with react-native-image-crop-picker provider 
+1

**Comment by shubhi15** [comment]
I am facing the same problem. On sharing image unsupported content exception is coming. Although Base 64 Obj is getting created

**Comment by adieunix** [comment]
have the same problem...
+1

**Comment by adieunix** [comment]
Solved!
Added user permission at AndroidManifest.xml
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>

and make sure you've enabled Storage permission for your app

**Comment by adieunix** [comment]
Solved!
Added user permission at AndroidManifest.xml
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`
`<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>`

and make sure you've enabled Storage permission for your app
