### ISSUE TITLE
sharing is not working in above android version 7?

### ISSUE THREAD

**Issue by MbF-Sathya** [react-native-community/react-native-share#235]
Hi all , 
i am using react native share. That i am facing issue in android higher versions. It works fine in below 7 android versions. 7 and above versions are not supporting. 

here is what i tried [https://stackoverflow.com/questions/49794979/react-native-share-not-working-properly-in-android-version-7-and-more]()
this is what i tried 
How to overcome this issue any version permissions available

**Comment by enieber** [comment]
the link of stackoverflow is not correct 

this is [correct link](https://stackoverflow.com/questions/49794979)

**Comment by ParveenChhillar** [comment]
not working for me

**Comment by jgcmarins** [comment]
It looks like this is a problem with link.
Please, follow full README.
Check this comment: https://github.com/react-native-community/react-native-share/issues/323#issuecomment-409853661
With a link to a brand new example: https://github.com/yeomann/react-native-share-android-test
