### ISSUE TITLE
base64 image not working on android targetSDK23

### ISSUE THREAD

**Issue by MrHazimAli** [react-native-community/react-native-share#236]
Hye,
I notice that sharing using base64 image not working on android when the targetSDK is 23.. for 22 it's working.. could be related to overlay permission ?

is there any ways or work around to make sure it's working for 23 because after I published app to play store I cannot change it back to 22

thanks!

**Comment by vhoen** [comment]
You need to request permissions : 

```
const allowedStorage = await PermissionsAndroid.request(
    PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE
  );
```

**Comment by jgcmarins** [comment]
@MrHazimAli did #244 solved?
Can we close this issue?
