### ISSUE TITLE
Display the image as in we see in any social media app in react native

### ISSUE THREAD

**Issue by smhassan90** [react-native-community/react-native-share#237]
Do we have any library that displays images like in social media posts. If there is only 1 image shared then it will occupy the 100% of space. if two images, then it will occupy half of the space and so on. Same goes with video as well. On clicking on the image, it should show the larger image. If video is selected then video should run. Do we have such feature in any of the react native library.

**Comment by enieber** [comment]
this is confused, this why we will close this issue, you can explain to we can reopen?
