### ISSUE TITLE
move to react-native-community 

### ISSUE THREAD

**Issue by sibelius** [react-native-community/react-native-share#238]
What do u think of moving this package to react-native-community ?

I think it is used for a lot of people, and there we could have more people contributing

**Comment by sibelius** [comment]
the easiest way would be to transfer the repo to my account and then I can transfer to react-native-community

other approach would be @brentvatne add you as a react-native-community member and then u could transfer

**Comment by EstebanFuentealba** [comment]
the easiest way :P

**Comment by sibelius** [comment]
fixed https://github.com/react-native-community/react-native-share

tks

**Comment by jgcmarins** [comment]
Great job, folks: https://twitter.com/sseraphini/status/987328105894285313
