### ISSUE TITLE
package id and multiple build types

### ISSUE THREAD

**Issue by embpdaniel** [react-native-community/react-native-share#239]
Hi, we want to use the library to share images. Our app builds different types of the app, each with a different package id (example: com.myapp.dev, com.myapp.rc, com.myapp). The installation instructions require that I hardcode the package id into our manifest and `MainApplication.java` files in order for the library to share as expected. Do you have any recommendation on how to set up the project for this sort of case of variable package ids?

**Comment by kkbhav** [comment]
@embpdaniel You can use BuildConfig.APPLICATION_ID to reference it in MainApplication & for manifest file you can use '${applicationId}.provider' value
