### ISSUE TITLE
text not showing when include image base64 android & ios

### ISSUE THREAD

**Issue by MrHazimAli** [react-native-community/react-native-share#247]
Im trying to share image after convert to base64 and using title and message inside the body..
but when image is share, the text is not share. it's like image override the text itself. is there any possible way to make sure both image and text is share ? 

this is example code that what im trying to do.
`
const IMAGE = 'data:image/png;base64,'+data
let shareOptions = {
  title: "Share my progress",
  message: "Share my progress",
  url: IMAGE
};

Share.shareSingle(Object.assign(shareOptions, {
  "social": "facebook"
}));						    };
`

Thanks!

**Comment by marf** [comment]
Same problem here, but in my case if I use both image and message the image is not displayed, while if I set the `message: ""` the image is shown.

**Comment by jgcmarins** [comment]
@kkbhav what do you suggest?

**Comment by kkbhav** [comment]
@jgcmarins this all depends on the developer, what is more important to share. If sharing image is the priority then do not set the message. Or use singleShare for whatsapp and similar services and Share.open for others.   

There is nothing that can be done from our side

**Comment by jgcmarins** [comment]
Thanks
