### ISSUE TITLE
I am able to send base64 image only for first time Android

### ISSUE THREAD

**Issue by HiteshGunwant** [react-native-community/react-native-share#248]
Hey guys ,
I am able to share base 64 image only for one time for next time in Android I am calling this fun it just displaying message as "Test",And when i kill app next time it again working same as follow
pls let me know solution URJENT!!
Thanks,
  let shareOptions = {
                        "url": 'data:image/png;base64,'+ base64Str,
                        "social": "twitter",
                        "message":"Test",
                        }
                        console.log("shareOptionsshareOptions.base64Image,",shareOptions)
                  
                        Share.shareSingle(shareOptions);

**Comment by jgcmarins** [comment]
@HiteshGunwant could you check if #244 solved this?

**Comment by evilchis94** [comment]
@jgcmarins as @HiteshGunwant I was unable to share base64 image nor downloaded image, it works only for the first time. My Android version is 5.0.1 and targetSdkVersion is 25, I'm asking for WRITE_EXTERNAL_STORAGE before sharing base64 and it always return true.



            let hasPermission = false;
            try {
                const check = await PermissionsAndroid.check(PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE);

                console.log('permiso de escritura ', check)

                if (check) {
                    hasPermission = true;
                }
                else {
                    const granted = await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
                        {
                            'title': 'Cool Photo App Camera Permission',
                            'message': 'Cool Photo App needs access to your camera ' +
                                       'so you can take awesome pictures.'
                        }
                    )
    
                    if (granted === PermissionsAndroid.RESULTS.GRANTED) {
                        hasPermission = true;
                    }
                }
            } catch (err) {
                console.warn(err)
            }

            if (hasPermission) {
                RNFetchBlob
                .fetch('GET', image)
                .then(res => {

                    let url = `data:image/${extension};base64,${res.base64()}`

                        Share.shareSingle({
                                url,
                                title: 'Share on Facebook',
                                social: 'facebook'
                            })
                            .then(async (res) => {
                                // await RNFetchBlob.fs.unlink(res.path());
                            })
                            .catch(async (error) => {
                                console.log(error)
                            })

                })
            }

This is the message

![img_20180522_135640_575](https://user-images.githubusercontent.com/10981327/40384068-260a736a-5dc8-11e8-80eb-9771b4415df1.JPG)

**Comment by kkbhav** [comment]
@jgcmarins I think this is because of using the existing intent for social sharing. While using singleShare only one instance of the shareClass is created and the existing intent is used again.  

I think every-time the user shares something, a new instance of the share class should be created to handle these type of cases. What are your views on this?

**Comment by jgcmarins** [comment]
Makes sense. We should try this approach.

**Comment by kkbhav** [comment]
I will trying to implement it and check the above is replicating or not. Once done, I will raise a PR
