### ISSUE TITLE
Not able to share base64 image to twitter as twitter app crashes

### ISSUE THREAD

**Issue by HiteshGunwant** [react-native-community/react-native-share#249]
I am using react native version 
	"react": "16.0.0-alpha.12",
	"react-native": "0.47.2",
        "react-native-share": "^1.0.27",
As i am sharing base 64 image to twitter my twitter app open and crash ,followed all steps also . done manual linking 
pls help

**Comment by jgcmarins** [comment]
is this related to: https://github.com/react-native-community/react-native-share/issues/248
@HiteshGunwant could you provide a stack trace?
