### ISSUE TITLE
[Android] Linking isn't working, use manual installation

### ISSUE THREAD

**Issue by abarisic86** [react-native-community/react-native-share#250]
Probably there should be a message marked as IMPORTANT that warns that this library requires manual installation on Android (and a few more customization from already submitted PRs) to get it working.

**Comment by jgcmarins** [comment]
@abarisic86 could you send a PR do improve README?
thanks

**Comment by jgcmarins** [comment]
@abarisic86 great!
We are getting back to work.
#67 has conflicts. Can we solve that?

**Comment by mjm918** [comment]
I followed the manual linking but still build failed. I have added everything according to manual installation but during build i am getting the following error:
`error: cannot find symbol
            new RNSharePackage(),
                ^
  symbol: class RNSharePackage
4 errors
:app:compileDebugJavaWithJavac FAILED`

and yes, I have added `compile project` in the app/build.gradle but still same
