### ISSUE TITLE
It doesn't build due to this error: cl.json does not exist 

### ISSUE THREAD

**Issue by xempie** [react-native-community/react-native-share#251]
Hi, I installed this and tried to build my app but I get this error:
Do you have any idea?

```
> Task :app:compileDebugJavaWithJavac
...\android\app\src\main\java\com\asanpakhsh\MainApplication.java:6: error: package cl.json does not exist
import cl.json.RNSharePackage;
              ^
...\android\app\src\main\java\com\asanpakhsh\MainApplication.java:35: error: cannot find symbol
            new RNSharePackage(),
                ^
  symbol: class RNSharePackage

```

**Comment by jgcmarins** [comment]
@xempie which part of README did you stopped?

**Comment by annelorraineuy** [comment]
@xempie Did you do `react-native link react-native-share`? There are additional manual steps on the README docs you need to do as well.

**Comment by yeomann** [comment]
I think its not package issue, was linking issue? can you confirm if you still having this issue? @xempie

**Comment by jgcmarins** [comment]
@xempie follow README instructions to do correct link.
