### ISSUE TITLE
MainApplication cannot be cast to ShareApplication on Android 8

### ISSUE THREAD

**Issue by jgfidelis** [react-native-community/react-native-share#270]
react-native-share version 1.0.27
Testing on an emulator running Android 8

We get this error:
<img width="418" alt="screen shot 2018-05-21 at 14 12 20" src="https://user-images.githubusercontent.com/4925068/40320358-d041a636-5d01-11e8-8038-b14451db06da.png">

This is the line:
`final String authority = ((ShareApplication) reactContext.getApplicationContext()).getFileProviderAuthority();`

Any one with more experience on the bridge can help?

**Comment by jgfidelis** [comment]
I followed the manual installation docs and it worked, thanks.

But please don't make it collapsable, make everyone see it.

**Comment by sibelius** [comment]
@enieber I think some steps of manual installation should be outside of it

as react-native link can't handle all that steps

**Comment by windydang26** [comment]
i see crash only appear with android device run android OS >= 8.0
fileuriexposedexception through ClipData.Item.getUri()
