### ISSUE TITLE
How to share image from app to other by clicking share button?

### ISSUE THREAD

**Issue by sukumardv3101** [react-native-community/react-native-share#272]
Actually, the image from server am getting so how can I share that image to like Facebook or WhatsApp.

Image from the server will get in url format like "http://example.com/image/image.jpg".

**Comment by jgcmarins** [comment]
@sukumardv3101 this is not a bug.
Please, ask this question on stackoverflow, you'll get better answers.
You can also follow README example: https://github.com/react-native-community/react-native-share#usage
