### ISSUE TITLE
Attemp to invoke virtual method 'void cl.json.social.Shareintent.open(com.facebook.react.bridge.ReadableMap)' on null object reference

### ISSUE THREAD

**Issue by KamranKhankhail** [react-native-community/react-native-share#273]
while trying to call 
`Share.shareSingle({
                    title: "test title",
                    url: localImagePath, 
                    "social": "instagram"
                }`
I am getting the following error "Attemp to invoke virtual method 'void cl.json.social.Shareintent.open(com.facebook.react.bridge.ReadableMap)' on null object reference"

![error](https://user-images.githubusercontent.com/31986011/40874632-e1c7a274-668a-11e8-9f48-9c7b57840b2f.png)

It may be worth mentioning that my project is an expo detached project.

**Comment by jgcmarins** [comment]
It looks like `options` parameter is been passed `null`: https://github.com/react-native-community/react-native-share/blob/master/android/src/main/java/cl/json/RNShareModule.java#L63
can you provide more code or a better stack trace?
