### ISSUE TITLE
Sharing to Facebook Messenger

### ISSUE THREAD

**Issue by julienkessels** [react-native-community/react-native-share#274]
Hello,
i've successfully added the lib to my project but I've been looking for an hour how to add Facebook Messenger to the options. 
Can anyone help me out?

Thanks!

**Comment by julienkessels** [comment]
Maybe SMS/Messages is just not working on the simulator..

**Comment by jgcmarins** [comment]
@julienkessels since this is not a bug, I am closing it.
You can share through Facebook Messenger using React Native share API: https://facebook.github.io/react-native/docs/share.html

**Comment by jgcmarins** [comment]
Feature Request: https://github.com/react-native-community/react-native-share/issues/150

**Comment by Luckygirlllll** [comment]
Hello, was this feature added to the lib? It's not possible to share links via react-native share in Android.

**Comment by kalraneeraj24550** [comment]
// with this two lines am able to send link
const sharingUrl = 'www.google.com';
Linking.openURL(fb-messenger://share?link=${sharingUrl});

but anyone plz help how can i send only text message for example. "hello world". no link, no image only text message.

**Comment by abhinavremitly** [comment]
> // with this two lines am able to send link
> const sharingUrl = 'www.google.com';
> Linking.openURL(fb-messenger://share?link=${sharingUrl});
> 
> but anyone plz help how can i send only text message for example. "hello world". no link, no image only text message.

@kalraneeraj24550 Were you able to find the solution to send a simple text message via fb-messenger? Asking because even I am looking for the same answer.
