### ISSUE TITLE
share social media

### ISSUE THREAD

**Issue by kingtross88** [react-native-community/react-native-share#275]
i'm trying to share the through my application. I ended up using Linking but that only brings me to the website to sign in. How am i suppose to implement the code to share the app through a facebook post or twitter post. 

I know the below code is incorrect. Can you please provide me something to use as a reference.
 <Button iconSrc={{ uri: FACEBOOK_ICON }}
                  onPress={()=>{
              Linking.openURL("https://facebook.com")
              setTimeout(() => {
                Share.shareSingle(Object.assign(shareOptions, {
                  "social": "twitter",
                  "url":"https://facebook.com"
                }));
              },300);
            }}>Facebook</Button>

**Comment by jgcmarins** [comment]
please, follow README: https://github.com/react-native-community/react-native-share#usage
