### ISSUE TITLE
Installs React when running "pod install"

### ISSUE THREAD

**Issue by ilyakar** [react-native-community/react-native-share#276]
React is already retrieved from node_modules, installing React through the pods causes all kinds of issues because React is installed twice

**Comment by jgcmarins** [comment]
hello @ilyakar 
thanks to reaching this out
could you help us sending a PR removing React from pods?

**Comment by ilyakar** [comment]
Hi,

Unfortunately, I’m not that familiar with cocoapods to know how to remove it from pods.

My current workaround is temporarily deleting my ios/podfile, running “react-native link react-native-share” (it links normally if it doesn’t find a podfile). Then I add my podfile back.

About 50% of the react-native plugins I come across have this problem and above is the workaround I use to fix it.

Ilya

**Comment by kkbhav** [comment]
This is the intended behaviour of react-native. Workaround mentioned by @ilyakar is the way to resolve this as of now. 
I think we can close this for now.
