### ISSUE TITLE
Instagram "Unable to load image"

### ISSUE THREAD

**Issue by phillmill** [react-native-community/react-native-share#279]
This issue is intermittent, but sometimes after hitting either the "feed" or "stories" button for the Instagram shareSingle option, the Instagram app will show briefly but then return to your app with a toast message reading "Unable to load image".

Has anyone else experienced this / have any ideas?

Thanks

**Comment by jgcmarins** [comment]
I think we should go on this way: provide better stack traces and an example repo to reproduce.
PRs fixing this are also welcome

**Comment by phillmill** [comment]
Closing since this is a duplicate
