### ISSUE TITLE
Share menu not visible when called from Modal

### ISSUE THREAD

**Issue by mschipperheyn** [react-native-community/react-native-share#28]
When the share menu is called from within a Modal. It doesn't become visible. It stays behind the Modal.

**Comment by mschipperheyn** [comment]
Here is the solution from another project on the same problem. Perhaps this could be a solution also? 

https://github.com/instea/react-native-popup-menu/issues/1

**Comment by jordxn** [comment]
I found a solution from another project that seems to work as well

Change: https://github.com/EstebanFuentealba/react-native-share/blob/master/ios/GenericShare.m#L48
`[ctrl.presentedViewController presentViewController:composeController animated:YES completion:Nil]`

ref: https://github.com/naoufal/react-native-activity-view/issues/31

I haven't tested this outside a modal so I haven't done a pull request for it.

**Comment by jordxn** [comment]
Ok I tested the change when it's called from a non-modal context and it doesn't work. So to fix this for both cases the client would have to pass through a new param to specify if this is being called from a modal or not so that GenericShare knows which method to call :(

**Comment by enieber** [comment]
try with the new version of lib

**Comment by rohit-apexon** [comment]
Facing same issue on Android, when opened from modal share options open behind modal.
Any workaround on this?
