### ISSUE TITLE
iOS => Sharing PDF with GMail or WhatsApp does not work...

### ISSUE THREAD

**Issue by BigPun86** [react-native-community/react-native-share#281]
Hey there,

i am trying to share a pdf as base64 with Gmail and WhatsApp. Sharing with the "normal" iOS Mail App works just fine, but sharing with WhatsApp & Gmail fails. On Gmail the shared pdf is some kind of weird data with this structure => 123456.dat 
When sharing to WhatsApp i have several problems. 
1. When title & message of share options is empty i get an error something like: "This object cannot be sent. Please choose another object."
2. If i add title & message i can only share the title & message text without the pdf file

Here is my code: 

    RNFetchBlob.config({ fileCache: true })
        .fetch("GET", fileUrl)
        // the image or pdf is now dowloaded to device's storage
        .then(resp => {
            filePath = resp.path();
            return resp.readFile("base64");
        })
        .then(async base64Data => {
            // here's base64 encoded image or pdf
            // type = application/pdf or image/png
            base64Data = `data:${type};base64,` + base64Data;

            let options = {
                type: type,
                message: "",
                title: "",
                // url: type === MIME_TYPE_PDF ? filePath : base64Data
                url: base64Data
            };

            await Share.open(options);

            // remove the image or pdf from device's storage
            fs.unlink(filePath);
        });

I also tried to share the temp file path instead of the base64 but unfortunatley the file path which is downloaded didn't have the pdf ending :D Anyways... it has to work somehow as it works with the iOS Mail App....

**Comment by komaldeep** [comment]
I have the exact same issue, @BigPun86  you are the coolest man on earth

**Comment by BigPun86** [comment]
related issue => https://github.com/react-native-community/react-native-share/issues/207

**Comment by BigPun86** [comment]
This issue might be more related to the fetch-blob. Never mind, this is how i fixed it. I actually extended the config options for the RNFetchBlob.config and added a clear path with filename to it. For Android i just left the old code sharing via base64. 
Now WhatsApp sharing works perfectly and sharing with Gmail has a extension. I set the pdf extension when filetype is application/pdf else i simply use .png which works for any kind of images shared.

  static shareWithIOS(fileUrl, type) {
    let filePath = null;
    let file_url_length = fileUrl.length;
    const configOptions = {
      fileCache: true,
      path:
        DIRS.DocumentDir + (type === 'application/pdf' ? '/MemoMeister.pdf' : '/MemoMeister.png') // no difference when using jpeg / jpg / png /
    };
    RNFetchBlob.config(configOptions)
      .fetch('GET', fileUrl)
      .then(async resp => {
        filePath = resp.path();
        let options = {
          type: type,
          url: filePath // (Platform.OS === 'android' ? 'file://' + filePath)
        };
        await Share.open(options);
        // remove the image or pdf from device's storage
        await RNFS.unlink(filePath);
      });
  }
  static shareWithAndroid(fileUrl, type) {
    let filePath = null;
    let file_url_length = fileUrl.length;
    const configOptions = { fileCache: true };
    RNFetchBlob.config(configOptions)
      .fetch('GET', fileUrl)
      .then(resp => {
        filePath = resp.path();
        return resp.readFile('base64');
      })
      .then(async base64Data => {
        base64Data = `data:${type};base64,` + base64Data;
        await Share.open({ url: base64Data });
        // remove the image or pdf from device's storage
        await RNFS.unlink(filePath);
      });
  }

**Comment by jgcmarins** [comment]
Nice one, @BigPun86 .
Should we add this information to README?
Can we close this issue?

**Comment by BigPun86** [comment]
@jgcmarins i think it would help to add this to the README, especially when people use this library with remote images using fetch blob and trying to share pdf like my case....So yes, i think its a good idea ;)

We can close it, thanks

**Comment by jgcmarins** [comment]
Great!
@BigPun86 could you send a PR updating README?
Thanks.
