### ISSUE TITLE
Activity completion callback is not used on iOS

### ISSUE THREAD

**Issue by roman01la** [react-native-community/react-native-share#29]
The callback which can be passed as the second argument is not used anywhere in iOS code. So it's not possible to handle completion of the activity.

**Comment by basdvries** [comment]
+1. Important feature imo

**Comment by jasonmerino** [comment]
The `Share.open()` function returns a promise, so you could do something like this to handle completion.

```js
Share.open({
	message: 'message',
	url: 'http://domain.com/page1',
	title: 'Share Page',
}).then((shareInfo) => {
	// this is the equivalent of a completion callback
}).done();
```

**Comment by enieber** [comment]
@roman01la the reply of @jasonmerino  resolved this.
