### ISSUE TITLE
Share on android >= 8.0 crash

### ISSUE THREAD

**Issue by windydang26** [react-native-community/react-native-share#293]
crash only appear with android device run android OS >= 8.0 and i'm using React-native-navigation
fileuriexposedexception through ClipData.Item.getUri()
![screenshot_equix_next_20180629-115058](https://user-images.githubusercontent.com/20814511/42076124-f8b4ff04-7b9d-11e8-94a4-6e0b554fd4f5.png)

**Comment by kkbhav** [comment]
@windydang26 have u completed all the integration steps mentioned in the docs. Also which version of react-native-share are u using?  
This issue was solved in #181 

This happens when the FileProvider is not implemented on android. file uri cannot be exposed directly on android, so we need to convert file uri into content uri using FileProvider.

**Comment by windydang26** [comment]
sorry! i'm using RN 0.55.4 and RN-share 1.0.23. thank u. i will try newest version and feedbacku later

**Comment by windydang26** [comment]
@kkbhav thank u for response. I've updated RNShare to newest version (1.0.27) but i see other issue.
same #270 . But i'm using React-native-navigation so i don't know way to integrated RNShare with RNNavigation. Can u any idea to resolve my issue? thank.
<img width="418" alt="40320358-d041a636-5d01-11e8-8038-b14451db06da" src="https://user-images.githubusercontent.com/20814511/42083279-a2333f44-7bb4-11e8-8726-b10ce796e1c7.png">

**Comment by kkbhav** [comment]
@windydang26 In your MainApplication.java or MyApplication.java file, you should implement ShareApplication as mentioned in the installation instructions. After that add getFileProviderAuthority method in this class which returns the fileprovider authority.

**Comment by windydang26** [comment]
Yes @kkbhav, i have seen installation doc. But i'm using React-native-navigation.  My code in MainApplication.java:
```java
public class MainApplication extends NavigationApplication {
```
so i can't integrated this lib with RNnavigation as guide.

**Comment by jgcmarins** [comment]
@windydang26 we also have an app with react-navigation + react-native-share and we aren't experiencing this behaviour.

**Comment by Shinichi52** [comment]
I have the same issue here. i'm using [wix/react-native-navigation](https://github.com/wix/react-native-navigation). I don't know to how to ``` implements ShareApplication ```  because in my MainApplication.java file see like below. May you help me with this?

```java

// public class MainApplication extends Application implements ReactApplication {
public class MainApplication extends NavigationApplication {

  // private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {

    @Override
    public String getJSBundleFile() {
      return CodePush.getJSBundleFile();
    }

    // @Override
    public String getFileProviderAuthority() {
      return "com.quantedge.equixnext.provider";
    }

  //   @Override
  //   protected boolean getUseDeveloperSupport() {
  //     return BuildConfig.DEBUG;
  //   }
  //
  //   @Override
  //   protected List<ReactPackage> getPackages() {
  //     return Arrays.<ReactPackage>asList(
  //         new MainReactPackage(),
            // new FingerprintPackage(),
            // new RNDeviceInfo(),
            
            
        
  //     );
  //   }
  // };
  //
  // @Override
  // public ReactNativeHost getReactNativeHost() {
  //     return mReactNativeHost;
  // }

  @Override
  public boolean isDebug() {
    return BuildConfig.DEBUG;
  }

  @NonNull
  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
    // Add the packages you require here.
    // No need to add RnnPackage and MainReactPackage
    return Arrays.<ReactPackage>asList(
      new VectorIconsPackage(),
      new LinearGradientPackage(),
      new ReactNativeConfigPackage(),
      new SplashScreenReactPackage(),
      new RNFetchBlobPackage(),
      new PDFView(),
      new RNSoundPackage(),
      new CodePush(BuildConfig.CODEPUSH_KEY, MainApplication.this, BuildConfig.DEBUG), // Add/change this line.
      // new NavigationReactPackage(),
      new RNFirebasePackage(),
        // add these optional packages as appropriate
      new RNFirebaseAdMobPackage(),
      new RNEventSourcePackage(),
      new RNFirebaseAnalyticsPackage(),
      new RNFirebaseAuthPackage(),
      new RNFirebaseRemoteConfigPackage(),
      new RNFirebaseCrashPackage(),
      new RNFirebaseDatabasePackage(),
      // new RNFirebaseMessagingPackage(),
      new RNFirebasePerformancePackage(),
      new RNFirebaseStoragePackage(),
      new BlurViewPackage(),
      new ReactNativeRestartPackage(),
      new LocalAuthPackage(),
      new FIRMessagingPackage(),
      new MPAndroidChartPackage(),
      new ReactMaterialKitPackage(),
      new ReactNativeI18n(),
      new RNSharePackage(),
      new PickerViewPackage(),
      new RNDeviceInfo(),
      new ExtraDimensionsPackage(),
      new RNVersionCheckPackage(),
      new RNDetectNavbarAndroidPackage(),
      new FingerprintPackage(),
      new ReactNativeExceptionHandlerPackage(),
      new OpenSettingsPackage()
    );
  }

  @Override
  public void onCreate() {
    super.onCreate();
    Reprint.initialize(this);
    SoLoader.init(this, /* native exopackage */ false);
  }
}

```

**Comment by windydang26** [comment]
@jgcmarins to resolve this bug have to set:
```java
class MyApplication extends Application implements ShareApplication, ReactApplication {
```
however currently my code:
```java
public class MainApplication extends NavigationApplication {
```
how way to integrate react-native-share with react-native-navigation?

**Comment by jgcmarins** [comment]
can't you use `NavigationApplication` along side `ShareApplication` and `ReactApplication`?

**Comment by kkbhav** [comment]
You should write it like this:

```
public class MainApplication extends NavigationApplication implements ShareApplication {
  @Override
  public void onCreate() {
    // Your code
  }

 // Other methods.....

  @Override
  public String getFileProviderAuthority() {
    return "me.houm.fileprovider";
  }
}
```

**Comment by windydang26** [comment]
i have done by instructions but get error:
![screen shot 2018-07-04 at 9 29 41 am](https://user-images.githubusercontent.com/20814511/42253939-5c70010a-7f6e-11e8-8081-d18b2403ff0d.png)
Have you ever seen it?

**Comment by kkbhav** [comment]
i think you forgot the import the ShareApplication. 
You should insert the following line along with the other imports in the MainApplication file:
```
import cl.json.ShareApplication;
```

**Comment by windydang26** [comment]
@kkbhav no, i'm sure that i already import ShareApplication in my MainApplication.java file
![screen shot 2018-07-04 at 2 06 55 pm](https://user-images.githubusercontent.com/20814511/42261925-e3d1f0ac-7f93-11e8-8306-e52e0f9fc703.png)

**Comment by windydang26** [comment]
@kkbhav , @jgcmarins i'm so sorry! my fault. i haven't update lib to newest version. i'm using react-native-share@1.0.23. after i update to newest version (1.0.27) everything working fine!
this bug can close now.

**Comment by kkbhav** [comment]
Thats great!
