### ISSUE TITLE
Sharing App Url

### ISSUE THREAD

**Issue by sanilcgs** [react-native-community/react-native-share#296]
I have tried react-native-share for sharing files and links. It is worked on my devices. But I want to share my app url with others. Is it possible to share my app url using this package?? If so, how can I implement this functionality.

**Comment by jgcmarins** [comment]
You can always share your app link, just get it from Google Play/App Store.
For better answer, ask this question at https://stackoverflow.com/

**Comment by sanilcgs** [comment]
Sharing a url through email and Facebook works fine. But sharing an app url was not working. It shows like a text only instead of a link.
