### ISSUE TITLE
[Android] modal disappeares when opening share

### ISSUE THREAD

**Issue by zmax92** [react-native-community/react-native-share#297]
I have screen and on that screen modal, modal has a share button, clicking on button Simple Share is open, but first the modal disappeares and screen beneath is shown... This is only case on android, iOS shows correctly. Adding code and screen shot...
```
export default class Screen extends Component {
    constructor(){
        super();
    }

    render() {
        return (
            <View style={styles.container}>
                <Text style={{color: '#fff'}}>Main Page</Text>
                <Modal style={styles.container}
                    visible={true}
                    transparent={false}
                    supportedOrientations={['portrait', 'landscape']}
                    onRequestClose={() => {}}>
                    <TouchableOpacity
                        onPress={() => {
                            let shareOptions = {
                                title: "Example share",
                                message: "Example share",
                                url: "http://example.com",
                                subject: "Example share" //  for email
                              };

                            Share.open(shareOptions);
                        }}
                    ><Text>Share button on modal</Text></TouchableOpacity>
                </Modal>
            </View>
        );
    }
}
```

![unity](https://user-images.githubusercontent.com/12643259/42281897-296efaae-7fa5-11e8-8641-ad8be44d5dac.png)

Any input would be appreciated...

**Comment by jgcmarins** [comment]
@zmax92 hi, could you test master branch?

**Comment by jgcmarins** [comment]
Add this to your `package.json`
"react-native-camera": "git+https://github.com/react-native-community/react-native-share.git#master",

**Comment by zmax92** [comment]
@jgcmarins added it, but it didn't help the problem still exists... opening share, modal disappeares

**Comment by jgcmarins** [comment]
@kkbhav could you check what's going on here?
@zmax92 hey, I've recently merged more code into master, could you try it again?

**Comment by zmax92** [comment]
@jgcmarins I have tried again, with new master, but still no change...

**Comment by zmax92** [comment]
@kkbhav I am using 0.52.2 react-native, after updating to 0.56.0 react-native issue is resolved... thank you
