### ISSUE TITLE
React native share error on android

### ISSUE THREAD

**Issue by sanilcgs** [react-native-community/react-native-share#303]
I have tried react native share package for sharing my app url. In iOS it works fine. But in android it shows something like this.
> Error:Execution failed for task ':react-native-share:processDebugResources'. >com.android.ide.common.process.ProcessException: Failed to execute aapt
> No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

I am using 
```
buildToolsVersion= 26.0.3 
compileSdkVersion = 26
targetSdkVersion = 26
supportLibVersion = "26.1.0"
```

What is the issue and how to solve this??

**Comment by jgcmarins** [comment]
It looks like your link is wrong.

**Comment by sanilcgs** [comment]
I have linked the package using **react-native link react-native-share**.

**Comment by jgcmarins** [comment]
sometimes it cannot work
could you provide more information?

**Comment by sanilcgs** [comment]
Hi @jgcmarins , I have unlinked the package and then added by manually. Then it works.

**Comment by jgcmarins** [comment]
Awesome!
