### ISSUE TITLE
Cannot share base64 data via Whatsapp (iOS)

### ISSUE THREAD

**Issue by IanOnFire** [react-native-community/react-native-share#304]
Hi there,

We're trying to share a .pdf document as base64 string, this is in every use case possibly except for Whatsapp on iOS (Android is working).
We've seen native apps that can do this so we know it is possible.

Has anybody else tried this? Did you succeed in doing this?
Is this a common problem or may there be something we're doing wrong?

I hope I've provided enough information, but please don't hesitate to ask more!

Cheers,

Ian

**Comment by IanOnFire** [comment]
This is the code we have:

`Share.open({
                title: "Share file",
                url: this.state.base64Document,
                subject: "Report",
            }).catch((err) => {
                if (err.error != 'User did not share') {
                    this.props.displayError()
                }
            })  `

**Comment by jgcmarins** [comment]
follow README: https://github.com/react-native-community/react-native-share#share-base-64-file

**Comment by almorak** [comment]
only ios share to whatsapp not work ...
url:"data:image/jpeg;base64,...base64data...."

**Comment by IanOnFire** [comment]
@jgcmarins yes, the link you've shared contained enough information to solve my issue. Still trying to figure out how to set your answer as the correct one though.

**Comment by yung93** [comment]
@IanOnFire Would you mind sharing how did you solve it? I get the exact same result with you. Thank you.

**Comment by IanOnFire** [comment]
@yung93 follow this https://github.com/react-native-community/react-native-share#share-remote-pdf-file-with-gmail--whatsapp-ios

**Comment by idanlevi1** [comment]
> messge:'XXXXXXXXX \n [www.xxx.com](http://www.xxx.com)'
> url:"data:image/jpeg;base64,...base64data...."
> IOS share text + url to :
> Mail : OK
> Message: OK
> Facebook : It turns to a page link 'www.xxx.com' , missing text and image
> Whatsapp: message Only , missing image
> 
> Android share text + url to :
> GMail : OK
> Message app(s): some got both, some only got image.
> Facebook : image only, missing message
> Whatsapp: OK

did you solved the ios issue?

**Comment by MateusAndrade** [comment]
Sharing base64 files dont work for me on whatsapp ios. But sharing the filé relative path works fine.

**Comment by IkarosFeitosa** [comment]
Sharing base64 files dont work for me on Mail ios. The file goes as text in the email.

**Comment by MateusAndrade** [comment]
> Sharing base64 files dont work for me on Mail ios. The file goes as text in the email.
> Note: I am trying to share a csv file.

You tried sharing the archive path?

**Comment by idanlevi1** [comment]
I solved that with using `encodeURI()` , I wrap the `base64`  with this

**Comment by YevheniiShabelnykkk** [comment]
Add `failOnCancel: false` in share options.

**Comment by nadir-karimo** [comment]
Did anyone solve the ios issue?
