### ISSUE TITLE
change default file name 

### ISSUE THREAD

**Issue by Culzean** [react-native-community/react-native-share#305]
Hi, 

So once the share dialog box is opened in iOS, we can select the option to "Save to files" and save it in the "on my iPhone" and it automatically names the file as text.txt. 
Is there any way to pass a name rather than the default "text" ?

**Comment by jgcmarins** [comment]
Yes, follow README: https://github.com/react-native-community/react-native-share#sharesingleoptions-in-ios--android

**Comment by Culzean** [comment]
@jgcmarins  Non of the given props actually change the file name !
