### ISSUE TITLE
Instagram on iOS: the Instagram share option doesn't appear in the standard iOS menu when the message option is passed to open()

### ISSUE THREAD

**Issue by tribou** [react-native-community/react-native-share#310]
I tried installing both the current release and what's on the master branch. Both are producing this issue:

```js
      await RNShare.open({
        url: `data:image/jpeg;base64,${base64data}`,
        type: "image/jpeg",
        message: 'test share message',
      });
```

When you pass a `message` option, the icon to share to Instagram disappears from the standard iOS share menu. If you remove the `message` option, the Instagram option comes back and you can share the image successfully.

Instagram works fine in both scenarios on Android.

**Comment by erikterwiel** [comment]
Also facing the same issue, although this may be working as expected because when you post a picture to Instagram, you first edit the picture then two screens later you provide a message.

**Comment by tribou** [comment]
Right, similar to Facebook share dialogs, I expect Instagram may not allow "default messages" being passed via an SDK. However, the Facebook share option degrades gracefully by ignoring the `message` option but still attaching an image (in my testing). It would be great if the Instagram option did the same instead of the icon disappearing entirely. 😞

**Comment by jgcmarins** [comment]
@tribou do you know any workaround on this?
maybe we can improve `react-native-share`

**Comment by Sharathnasa** [comment]
@erikterwiel yes its working as expected. Instagram doesn't accept the string message. So when we pass string as params, it won't show up in the share pop-up.

As a work around, we can copy the message to clipboard and pass only image as a params to instagram. Later we can paste the string.

**Comment by Sharathnasa** [comment]
something like this

[Share.open(shareImageBase64);
              const strToCopy = this.state.selectedQuote
                .concat("\n.\n")
                .concat(this.generateHashTags());
              Clipboard.setString(strToCopy);
              if (Platform.OS === "android") {
                ToastAndroid.show(
                  "Caption along with hashtag has been copied.",
                  ToastAndroid.SHORT
                );
              } else if (Platform.OS === "ios") {
                AlertIOS.alert("Caption along with hashtag has been copied.");
              }](url)

 [const shareImageBase64 = {
      title: "Auto Captions",
      url: `data:image/png;base64,${this.img.data}`
    };](url)

**Comment by tribou** [comment]
@jgcmarins no workaround yet, but I agree that it would improve `react-native-share` to degrade gracefully by default on iOS (like it does on Android already).

**Comment by erikterwiel** [comment]
Nice Workaround:
React Native has a built in { Share } feature which works as expected on iOS, degrades gracefully on Facebook and Instagram. Only issue with the built in share is that you cannot supply a url for Android, so I just use Platform.OS to use React Native's Share for iOS and react-native-share for Android.

Works perfectly

**Comment by tribou** [comment]
Well, this is strange. I've tried your workaround @erikterwiel, and it's still not working. 😞 Very odd and slightly unsettling that this would be environmental. I can pass a `title` and/or a `subject`, but as soon as I add a `message`, the Instagram icon disappears using React Native's own { Share } module.

**Comment by erikterwiel** [comment]
@tribou I have it working on react-native 0.56 and my message is ~200 characters

**Comment by tribou** [comment]
Ahhh, I'm still on `v0.55.4`. I had tried the 0.56 upgrade, but Babel 7 broke my test suite. I'll have to find some time to redo to just test this workaround... thanks!

**Comment by tribou** [comment]
Posting here since it's the next step I can think of for this issue: Compare `react-native@0.56` iOS share module/ActionSheetManager with `react-native-share` and `react-native@0.55` to see what changed...

- [`react-native@v0.56.0:/Libraries/ActionSheetIOS/RCTActionSheetManager.m](https://github.com/facebook/react-native/blob/3c6a916536da67a4591f71883723c67a0c7be9d7/Libraries/ActionSheetIOS/RCTActionSheetManager.m#L120)
- [`react-native@v0.55.4:/Libraries/ActionSheetIOS/RCTActionSheetManager.m](https://github.com/facebook/react-native/blob/3c6a916536da67a4591f71883723c67a0c7be9d7/Libraries/ActionSheetIOS/RCTActionSheetManager.m#L120)
- [comparison of the two `react-native` versions](https://github.com/facebook/react-native/compare/0.55-stable...0.56-stable?diff=unified&name=0.56-stable#diff-b6ec6c60921763a2cc180dd8ed24ba35)
- [current `react-native-share` iOS implementation of `open()`](https://github.com/react-native-community/react-native-share/blob/9cf40cbcd7c93cc58d5f4e0c91aab54073ccf5fe/ios/RNShare.m#L124)

**Comment by Runaider** [comment]
@erikterwiel solution does not appear to be working with `react-native@v0.57.5`. Did anyone else notice this issue with v0.57?

**Comment by ashnfb** [comment]
@Runaider I'm also having a problem with 0.57

**Comment by webmasterdragon** [comment]
same issue in `"react-native": "^0.57.8"`

**Comment by jgcmarins** [comment]
We did a new release, can you try it? v1.2.0.
Thank you.

**Comment by TxusBlack** [comment]
Same issue...

**Comment by EnclaveAnthony** [comment]
Same issue. Do you have any solution?

**Comment by TxusBlack** [comment]
No, please re-open this issue.

**Comment by nateeither** [comment]
Re-open this issue please!

**Comment by jgcmarins** [comment]
Does anyone have any reproducible bug?
Does it happens with master code?
