### ISSUE TITLE
fatal: Remote branch 1.1.0 not found in upstream origin

### ISSUE THREAD

**Issue by Zishanr** [react-native-community/react-native-share#318]
Hey, guys, As I told you i was trying to install this library via Cocoapods and I'm getting a fatal error that says, "fatal: Remote branch 1.1.0 not found in upstream origin".

<img width="665" alt="43213681-d7399468-9054-11e8-895e-9cc95ec8e6dd" src="https://user-images.githubusercontent.com/6694311/43261848-c42e9894-90fb-11e8-904c-5e3e63244831.png">

And you suggested change
from: https://github.com/EstebanFuentealba/react-native-share.git
to: https://github.com/react-native-community/react-native-share.git

<img width="1123" alt="43251197-f0cc9fc8-90dc-11e8-99ba-0bc1080302d0" src="https://user-images.githubusercontent.com/6694311/43261909-f3db9696-90fb-11e8-9fac-6fb3b2805083.png">

but the thing is I can't change it manually as it is picking from node_modules. As also you can see in the screenshot
source is : https://github.com/EstebanFuentealba/react-native-share.git
while it should be
https://github.com/react-native-community/react-native-share.git

Also, the tag should be like this tag => "v#{s.version}" as your tag is v1.1.0.

Also, my project is not a standalone react native project. It has some native dependencies that's why we are using Cocoapods.

Can you please help me out here

**Comment by enieber** [comment]
this issue is duplicate #317

**Comment by Zishanr** [comment]
Can you please suggest me solution as  I can't change it manually as it is picking from node_modules. As also you can see in the screenshot
source is : https://github.com/EstebanFuentealba/react-native-share.git
while it should be
https://github.com/react-native-community/react-native-share.git

Also, the tag should be like this tag => "v#{s.version}" as your tag is v1.1.0.

**Comment by jgcmarins** [comment]
@Zishanr it was fixed here: https://github.com/react-native-community/react-native-share/pull/319
we are working on a new release soon
