### ISSUE TITLE
Not opening facebook app when tried to shareSingle method.

### ISSUE THREAD

**Issue by ziahm** [react-native-community/react-native-share#320]
Hi,
When I use shareSingle method, it opens facebook in browser not the installed facebook app. Also tried with Instagram. For instagram, it opens instagram page in app store. Is there anything wrong?

Thanks

**Comment by enieber** [comment]
what version you is use @ziahm ?

**Comment by ziahm** [comment]
I am using latest version "react-native-share": "^1.1.0"

**Comment by enieber** [comment]
Can you show the code you use of  shareSingle?

**Comment by ziahm** [comment]
The code is somewhat like below:
let shareOptions = {
              title: "React Native",
              message: "Hola mundo",
              type: 'image/png',
              url: this.props.imageUrl,
              subject: "Share Link" //  for email
            };

Share.shareSingle(Object.assign(shareOptions, {
              social: Share.Social.FACEBOOK
            }))

and getting some warnings when opening the app. Attached screenshot
![screen shot 2018-07-26 at 7 38 04 pm](https://user-images.githubusercontent.com/783713/43266006-1045c404-910c-11e8-99d2-a765970b96d3.png)

**Comment by jgcmarins** [comment]
@ziahm is this happening on android or ios? or both?

**Comment by ziahm** [comment]
I am only trying on IOS. I didn't try on Android yet @enieber

**Comment by jgcmarins** [comment]
Apparently neither [facebook](https://github.com/react-native-community/react-native-share/blob/master/ios/RNShare.m#L90), nor [twitter](https://github.com/react-native-community/react-native-share/blob/master/ios/RNShare.m#L94) ever had share into app.

**Comment by ziahm** [comment]
There are ios apps which can share into facebook app directly @jgcmarins

**Comment by purvotara** [comment]
@jgcmarins  Its only happening in IOS i guess.. Same problem with Whatsapp, instagram, fb etc

**Comment by lizhuoyuan** [comment]
happening in android too...

**Comment by Tsiniloiv** [comment]
I'm experiencing this as well - Facebook returning as being installed when it's not, and nothing happening when I try to shareSingle to Facebook.

I have a theory: The Facebook app can't be uninstalled, only disabled. So it's still 'installed', it just doesn't do anything when you  try to share to it.

**Comment by lizhuoyuan** [comment]
https://github.com/OpenFlutter/flutter_share_me

**Comment by hbarylskyi** [comment]
For anyone to whom that will happen in future on iOS: add your app into LSApplicationQueriesSchemes. So I had to add `instagram` to fix described problem. This should be more clear from README I think.

**Comment by jgcmarins** [comment]
> This should be more clear from README I think.

Absolutely. @hbarylskyi, do you mind sending a PR with this improvement? Thank you.

**Comment by hbarylskyi** [comment]
@jgcmarins will do.

**Comment by amalmohann-dgnl** [comment]
I'm also facing same issue.

platform : iOS and Android

expected : when clicking on the facebook single share, it redirects to the facebook app (deep linking)

current : when clicking on the facebook single share, it redirects to the facebook mobile website. (using browser)

- how to fix this ? 

```
const shareHandle = (title: string): void => {
    let shareOptions: any;
    if (title === 'Link') {
      Clipboard.setString(EventShareURL);
      showSuccessToast('Copy Successful', 'Copied the event link successfully');
    } else {
      switch (title) {
        case 'Facebook':
          shareOptions = {
            url: EventShareURL,
            message: `Hey! Did you heard about '${eventTitle}' on Lounges TV yet?\n\n`,
            stickerImage: `data:${thumbnail}`,
            social: Share.Social.FACEBOOK,
          };
          break;
        case 'Twitter':
          shareOptions = {
            url: EventShareURL,
            message: `Hey! Did you heard about '${eventTitle}' on Lounges TV yet?\n\n`,
            stickerImage: `data:${thumbnail}`,
            social: Share.Social.TWITTER,
          };
          break;
        case 'Mail':
          shareOptions = {
            url: EventShareURL,
            message: `Hey! Did you heard about '${eventTitle}' on Lounges TV yet?\n\n`,
            stickerImage: `data:${thumbnail}`,
            social: Share.Social.EMAIL,
          };
          break;
        default:
          break;
      }
      Share.shareSingle(shareOptions).catch(err => console.log(err));
    }
  };
```

`shareHandle('Facebook');`

**Comment by amalmohann** [comment]
I'm also facing same issue.

platform : iOS and Android

expected : when clicking on the facebook single share, it redirects to the facebook app (deep linking)

current : when clicking on the facebook single share, it redirects to the facebook mobile website. (using browser)

- how to fix this ? 

```
const shareHandle = (title: string): void => {
    let shareOptions: any;
    if (title === 'Link') {
      Clipboard.setString(EventShareURL);
      showSuccessToast('Copy Successful', 'Copied the event link successfully');
    } else {
      switch (title) {
        case 'Facebook':
          shareOptions = {
            url: EventShareURL,
            message: `Hey! Did you heard about '${eventTitle}' on Lounges TV yet?\n\n`,
            stickerImage: `data:${thumbnail}`,
            social: Share.Social.FACEBOOK,
          };
          break;
        case 'Twitter':
          shareOptions = {
            url: EventShareURL,
            message: `Hey! Did you heard about '${eventTitle}' on Lounges TV yet?\n\n`,
            stickerImage: `data:${thumbnail}`,
            social: Share.Social.TWITTER,
          };
          break;
        case 'Mail':
          shareOptions = {
            url: EventShareURL,
            message: `Hey! Did you heard about '${eventTitle}' on Lounges TV yet?\n\n`,
            stickerImage: `data:${thumbnail}`,
            social: Share.Social.EMAIL,
          };
          break;
        default:
          break;
      }
      Share.shareSingle(shareOptions).catch(err => console.log(err));
    }
  };
```

`shareHandle('Facebook');`

**Comment by amalmohann-dgnl** [comment]
@enieber any update on this one?

**Comment by amalmohann-dgnl** [comment]
@jgcmarins any updates?

**Comment by carlos3g** [comment]
any updates?
