### ISSUE TITLE
_reactNative.NativeModules.RNShare.FACEBOOK

### ISSUE THREAD

**Issue by yevheniishabelnyk** [react-native-community/react-native-share#322]
Hello guys. 
Somebody know how to fix this error? 

And it happens, when I only add stroke:
`import Share from 'react-native-share'`

<img width="398" alt="screen shot 2018-07-27 at 9 45 28 am" src="https://user-images.githubusercontent.com/32763735/43306074-951443a6-9182-11e8-92ad-4b063f619a6d.png">

**Comment by yeomann** [comment]
Hey @yevheniishabelnyk is it possible to give example code? I would like to reproduce the error so I can help you. thanks

**Comment by yeomann** [comment]
sounds like a linking problem, maybe you didn't do link properly. we can't help you as I am unable to product this error.

**Comment by jgcmarins** [comment]
@yevheniishabelnyk which version?

**Comment by yevheniishabelnyk** [comment]
"react-native": "https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz",
"react-native-share": "1.1.0"

**Comment by jgcmarins** [comment]
this lib does not work with expo
for that, you can use expo's own share lib: https://docs.expo.io/versions/v28.0.0/react-native/share.md#__next

**Comment by DiksonSamuel** [comment]
after adding RNShare.xcodeproj to library file it worked

**Comment by reactexcel** [comment]
@DiksonSamuel 
but i have added RNShare.xcodeproj but did'nt work

**Comment by jgcmarins** [comment]
@reactexcel can you check if it linked correctly?

**Comment by prabhu73** [comment]
I am also facing the same issue in android.
undefined is not an object (evaluating "n.NativeModules.RNShare.FACEBOOK")
Please help me with this.

**Comment by Jeet007das** [comment]
I am also getting the same problem after updating Library in Xcode in the main Project.

**Comment by devpolish** [comment]
Yeah, definitively adding the .xcodeproject file worked for me.

**Comment by TharinduKetipe** [comment]
First unlink the library 
`react-native unlink react-native-share`
Then uninstall the library 
`npm uninstall --save react-native-share`
Then re-install and link the package.
`npm install react-native-share --save`
`react-native link react-native-share`
This works for me.

**Comment by jakubgrzelak** [comment]
Hey! I am facing the same problem. Everything is linked properly, I checked it a few time ( I uninstall the app, linked it automatically. This was not working so I unlinked it, uninstall and likned it manually - the same, the lib is not working. 
version of:
react-native: 0.57.2 
react-native-share: 1.1.3

**Comment by twp520** [comment]
hey guys, on IOS,  Add the following line of code to the Podfile file：
`pod 'RNShare', :path => 'xxx/node_modules/react-native-share/RNShare.podspec'`
then run `pod install` , now it's right.

**Comment by bunnypavan** [comment]
Add RNShare library on Xcode link library, this avoids the mentioned issue.

**Comment by zeeintanzania** [comment]
it's all for IOS, how to link in android. Same error RNShare.FACEBOOK please help

**Comment by jkLennon** [comment]
if React native version < 0.6.0, my React native version ===  0.59.10, This parameter can be configured according to version v1.2.1
![image](https://user-images.githubusercontent.com/44989491/216218092-e5c1192a-d5ff-4072-9ba3-3de903a0ba03.png)
![image](https://user-images.githubusercontent.com/44989491/216218184-0a888964-2bee-4bf7-8cbb-d6ea21563d69.png)
![image](https://user-images.githubusercontent.com/44989491/216218232-d0326d45-ed2b-4e85-99a0-e5e2cd57919c.png)

if Xcode reports an error
