### ISSUE TITLE
Can't share file with unicode symbols in name on Android

### ISSUE THREAD

**Issue by esomkin** [react-native-community/react-native-share#324]
I'am using `react-native-share` to share files from my application to another (Gmail for example). When file name has numeric or only latin characters share ok. But, when unicode characters is appear in file name (for example `эюя`), Gmail show message Could not attach file. How to fix this? Thank's in advance!

**Comment by jgcmarins** [comment]
what version?
could you try master branch?

**Comment by esomkin** [comment]
@jgcmarins 1.1.0

**Comment by esomkin** [comment]
I’am share a local file which was downloaded earlier from internet

**Comment by jgcmarins** [comment]
Is there any error message?

**Comment by jgcmarins** [comment]
is it happening on both android and ios?

**Comment by esomkin** [comment]
@jgcmarins Only on android, on is all ok

**Comment by esomkin** [comment]
@jgcmarins It is possible to fix a bug by myself?

**Comment by jgcmarins** [comment]
Sure!!! PR's are welcome \o/
