### ISSUE TITLE
Android - Share.Open resolves promise before upload complete

### ISSUE THREAD

**Issue by ruimfernandes** [react-native-community/react-native-share#326]
### Steps to reproduce
1. Share and image with any app
2. As soon as the bottom sheet opens it will resolve the promise

### Expected behaviour
As well as it happens on iOS, the promise resolve/reject of `Share.open` only happens after the upload process is complete.

### Actual behaviour
As soon as the bottom sheet is opened, the `Share.open` resolve its promise. Therefore, I can't know if the share process went successful or not.
Resolve result: 
```
{
  "message": "OK",
}
```

### Environment
- **React Native version**: 0.52.0
- **React Native platform + platform version**: Android 7.0

### react-native-share
**Version**: npm version

**Comment by yeomann** [comment]
I think this feature is not currently present in package?
maybe if you can send PR.

**Comment by jmschlmrs** [comment]
@ruimfernandes this same bug is present for me using the React-Native hare API directly (https://facebook.github.io/react-native/docs/share), not sure that it will be able to be resolved in this package until the underlying behaviour in React-Native is fixed.
