### ISSUE TITLE
Yellow box warning "requires main queue setup since it overrides constantsToExport but doesn't implement requiresMainQueueSetup

### ISSUE THREAD

**Issue by esutton** [react-native-community/react-native-share#330]
### Steps to reproduce
1. Launch app with react-native-share in iOS ( simulator can reproduce )

### Expected behaviour
No Yellow Box Warnings

### Actual behaviour
ellow Box Warnings

### Environment

iOS
		"react": "16.3.1",
		"react-native": "0.55.4",

### react-native-share
		"react-native-share": "^1.1.0",

### Link to repo (highly encouraged)
https://github.com/react-native-community/react-native-share/blob/71737360313e35216062036c8a60416dc2aefc80/ios/RNShare.m#L50

Below this in /ios/RNShare.m
````
@implementation RNShare
- (dispatch_queue_t)methodQueue
{
    return dispatch_get_main_queue();
}
````

Add:
````
+ (BOOL)requiresMainQueueSetup
{
    return YES;
}
````

**Comment by yeomann** [comment]
would appreciate if you can send fix via PR? @esutton

**Comment by jgcmarins** [comment]
done https://github.com/react-native-community/react-native-share/pull/331
