### ISSUE TITLE
iOS yellow box: Module RNShare requires main queue setup since it overrides...

### ISSUE THREAD

**Issue by mikehardy** [react-native-community/react-native-share#332]
### Steps to reproduce
1. create new react-native app and install/link react-native-share
2. react-native run-ios
3. check out yellow box warning with contents including the title

### Expected behaviour
RNShare should load without warnings

### Actual behaviour
There is a compatibility warning containing this text:

"Module RNShare requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of."

### Environment
- react-native 0.56
- iOS 11.3 (in a simulator, model A1586)

### react-native-share
**Version**: npm version 1.1.0

### Possible patch:
Looks like this might be the simplest similar patch (though I suppose you could re-think the whole thing...): https://github.com/kmagiera/react-native-gesture-handler/commit/310c3905dc68d9594861551b070238ab53544b7f

### Workaround:
import { YellowBox } from 'react-native';
YellowBox.ignoreWarnings(
  ['requires main queue setup']
);

**Comment by jgcmarins** [comment]
fixed here: https://github.com/react-native-community/react-native-share/pull/331
try master branch

**Comment by mikehardy** [comment]
Sorry I logged what is obviously a duplicate! And not just once either. I searched issues prior but only open ones (oops! lesson learned). Thanks for the reply, and thanks for this useful library

**Comment by jgcmarins** [comment]
@mikehardy don't worry, that's ok.
Thank you for opening the issue and remembering me to create a new release: https://github.com/react-native-community/react-native-share/releases/tag/v1.1.1

**Comment by jgcmarins** [comment]
@Maple13 done!
