### ISSUE TITLE
Can't share to Instagram anymore on iOS, not listed

### ISSUE THREAD

**Issue by Ahlisen** [react-native-community/react-native-share#333]
### Steps to reproduce
1.    Share.open({
      title: 'XXX',
      message: 'XXX',
      url: sharePath
    })
2. Look for Instagram in iOS
3. Not available
4. Still works for Android though

The warnings about RCT_EXPORT_MODULE not being used are still present like in #329

### Environment
- **React Native version**: 56.0
- **React Native platform + platform version**: iOS 9.0

### react-native-share
**Version**: 1.1.1

**Comment by rickjsantos100** [comment]
Same problem here, just updated react native share

**Comment by jgcmarins** [comment]
@Ahlisen could you try updating versions and check link?

**Comment by facuescobar** [comment]
I've found the reason,

if **message** prop is added to sent options object in **Share.open(options)** the UI won't list instagram or any other apps that doesn't allow a default **message**

**Comment by dprajapati1179** [comment]
How to share only message on Instagram in iOS

**Comment by dprajapati1179** [comment]
I am having same issue the app is not in list
