### ISSUE TITLE
Share.shareSingle(shareOptions) does not pass data to Facebook app

### ISSUE THREAD

**Issue by jaidBinHashem** [react-native-community/react-native-share#337]
I want to share image to Facebook. With `Share.open(shareOptions)` it works but when I am trying to use `Share.shareSingle(shareOptions)` it does not pass data to Facebook app. It only opens the Facebook's new status page with no data on it.

**Comment by lizhuoyuan** [comment]
me too

**Comment by mbret** [comment]
Same problem, the share.open seems to works properly but shareSingle does not work at all for me. Even for a simple message
