### ISSUE TITLE
Flow check fails for styles in Overlay

### ISSUE THREAD

**Issue by luzma87** [react-native-community/react-native-share#341]
### Steps to reproduce
1. create react native app with flow
2. install react-native-share
3. try running flow check

### Expected behaviour
flow check should pass

### Actual behaviour
flow check complains

![react-native-share flow issue](https://user-images.githubusercontent.com/456972/44106469-638e2946-9fba-11e8-9ab3-ac0d0367f3b5.png)

### Environment
"react": "^16.2.0",
"react-native": "0.55.4",
"react-native-share": "^1.1.1",
"flow-bin": "^0.67.0",
"flow-typed": "^2.4.0",

### Possible solution
replace
`overlayStyle: Object,`
with
`overlayStyle: Object | number,`
in  `react-native-share/components/Overlay.js:38:19`

**Comment by jgcmarins** [comment]
nice catch, thanks
could you send a PR fixing it?

**Comment by yeomann** [comment]
since PR is merged I will close it
