### ISSUE TITLE
Using Share.shareSingle() on Android gives back an unknown error

### ISSUE THREAD

**Issue by IronTony** [react-native-community/react-native-share#344]
### Steps to reproduce
1. I am using
```
const shareOptions = {
      url: picture.uri,
      social: Share.Social.INSTAGRAM,
};
Share.shareSingle(shareOptions).then(() => console.log('SUCCESS')).catch(err => console.log('ERROR: ', err));
```
2. The Instagram app seems to start to open, but while it is opened the screen is blank and I have back an error: "An unknown error occured"

### Expected behaviour
It has to open the Instagram app as it happens in the iOS app.

### Actual behaviour
It seems that Instagram app will open, but the screen stays blank and I have a toast back with "An unknown error occured"

### Environment
- **React Native version**: 0.55.4
- **React Native platform + platform version**: Android 7.1.2

### react-native-share
**Version**: npm version

If you need more infos please tell me.

**Comment by jgcmarins** [comment]
looks like this is a problem with your link: https://github.com/react-native-community/react-native-share/search?q=An+unknown+error+occured&unscoped_q=An+unknown+error+occured

**Comment by andreipop-reea** [comment]
I have the same problem when trying to Share.shareSingle() on Instagram. It seems to be an issue with the Instagram service, because other works properly.
I tested on Android 7/8 with the latest version of react-native-share v1.1.1

**Comment by vforvasile** [comment]
Hey while Share.open works, I could not make shareSingle to Instagram to work. Any suggestions? My setups is same as asker's.

**Comment by nicubarbaros** [comment]
Same here.
Have anyone tried the previous version?

**Comment by IronTony** [comment]
@jgcmarins hi, here is a small (fast written) project that shows the problems: https://github.com/IronTony/RNShareExample
Hope it can help.

**Comment by jgcmarins** [comment]
@ddereszewski awesome.
Could you send a PR fixing it?

**Comment by ddereszewski** [comment]
The fix has been merged to master, can you update and check if works for you.

**Comment by jgcmarins** [comment]
it is already on latest release: https://github.com/react-native-community/react-native-share/releases/tag/v1.1.2
