### ISSUE TITLE
Suggestion : Improvement of filename

### ISSUE THREAD

**Issue by o0lwj0o** [react-native-community/react-native-share#347]
Hi,
    I have found the filename was determined by System.currentTimeMillis() from line 130 in the file https://github.com/react-native-community/react-native-share/blob/master/android/src/main/java/cl/json/ShareFile.java

        File file = new File(dir, System.currentTimeMillis() + "." + this.extension);

    Sometimes, it may overwrite the other file which created just at the same time.

**Comment by yeomann** [comment]
how filename can improve? @o0lwj0o Please repo and explain

**Comment by o0lwj0o** [comment]
You can use System.nanotime() instead. I think it's maybe enough.

**Comment by yeomann** [comment]
@codeflows  maybe see if this can help?

**Comment by jgcmarins** [comment]
Interesting. @o0lwj0o would you mind to send a PR improving it?

**Comment by o0lwj0o** [comment]
@jgcmarins  Sure. I will send a PR later.

**Comment by esutton** [comment]
Would a uuid work?

` UUID.randomUUID().toString()`

iOS:

`NSString *uuid = [[NSUUID UUID] UUIDString];`

**Comment by ylac** [comment]
It would be very helpful if we could specify the filename in the options for `Share.open`.
