### ISSUE TITLE
Sharing on messenger only share scheme and host

### ISSUE THREAD

**Issue by Kisepro** [react-native-community/react-native-share#348]
### Steps to reproduce
1.  Share a link on messenger
2.  Clik on the link generated that will open your app
3.  Verify the url that opens your app in the log

### Expected behaviour
It should open "http://myhost/ole/xikjfdihfdijf5487" and generate this url in the html

### Actual behaviour
Following the url on messenger (in the screenshot) it's the good one but in the html it opens : "http://myhost" and the log of my app also

![image](https://user-images.githubusercontent.com/7433141/44646994-645f5200-aa0f-11e8-9b35-fdd6cdbf3de8.png)

It happens only with Facebook messenger !

### Environment
- **React Native version**: 0.55.4
- **React Native platform + platform version**: last Android version

### react-native-share
**Version**:  1.1.1

**Comment by jgcmarins** [comment]
Hi @Kisepro could you explain why this is related to rn share? Thanks

**Comment by yeomann** [comment]
closing as per assuming this might be resolved. Feel free to open again.

**Comment by yernandus** [comment]
Having similar issue. Sharing a dynamic link on email app cuts some of the parameters and link opens the app but not the page that is needed

**Comment by jgcmarins** [comment]
is it being cut by rn share?

**Comment by yernandus** [comment]
the link that is passed to rn share is correct. but when email app opens it is cut. Not sure where it is being cut

**Comment by jgcmarins** [comment]
does it happens when sharing with another apps?

**Comment by yernandus** [comment]
no, only on ios email app

**Comment by MateusAndrade** [comment]
> no, only on ios email app

This looks a behavior related to IOS EMail APp, i got a similar issue when i was handling dynamic links share. 

Did you tried sharing a link that wasn't created using dynamic links?

**Comment by yernandus** [comment]
> > no, only on ios email app
> 
> This looks a behavior related to IOS EMail APp, i got a similar issue when i was handling dynamic links share.
> 
> Did you tried sharing a link that wasn't created using dynamic links?

well I need that share on email only for dynamic links
