### ISSUE TITLE
Sharing both url and image

### ISSUE THREAD

**Issue by EwaGuziejko** [react-native-community/react-native-share#349]
I tried share both url and image using Share.open(). If I pass only image in base64 it works perfectly, if I pass only url it also works ok. When I pass both image in base64 and url to my webpage it shares only link. I'm using version 1.1.1. Is there any way to do that?

**Comment by mahesh963** [comment]
@EwaAexol, Check this once
https://github.com/react-native-community/react-native-share/issues/74#issuecomment-321856542

**Comment by EwaAexol** [comment]
I think this isn't answer for my question (correct me if I'm wrong )
I would like to share image -> and I already have base64 image data and link to some web page. Sth like: "check this out" <link to web page> <image>

**Comment by CmerCy132** [comment]
I'm also having this problem. I need to share both Image and URL on facebook but facebook only detects the URL if I try to pass both Image and URL

below is my sample shareOption

`let options = {
            message: Name ? Name + '\n' + Title + '\n' + URL : Title + '\n' + URL,
            url: Platform.OS === 'android' ? 'file://' + resp.path() : resp.path()
          };`

**Comment by jgcmarins** [comment]
You could try to share link as a message

**Comment by EwaAexol** [comment]
I think the only way to do this is implement webpage with metatags (there you put image and other content you need) and then pass only url to your share dialog :/ I guess fb/messanger/instagram api prevents you from this kind of sharing we want to implement :(

**Comment by kalraneeraj24550** [comment]
how to share text messange via messanger in react-native andorid. plz help me
