### ISSUE TITLE
Any Callback Posted?

### ISSUE THREAD

**Issue by myrsapp** [react-native-community/react-native-share#351]
How do I know they posted or not?

if I use react-native-fbsdk, there is a callback for that. However, it's only facebook tho.
<img width="474" alt="screen shot 2018-08-28 at 16 10 33" src="https://user-images.githubusercontent.com/25725703/44713340-203a8300-aadd-11e8-8458-34ca256eddfc.png">

**Comment by yeomann** [comment]
i'm sorry but what do you mean?

**Comment by jgcmarins** [comment]
guess it is not related to react-native-share
