### ISSUE TITLE
Fail to share PDF file with symbol character on android

### ISSUE THREAD

**Issue by jvaisaonna** [react-native-community/react-native-share#353]
I am going to share pdf file, but if the pdf name include some symbol character like !@#$%^&*()'".  It will prompt the error message when running "Share.open()".  For the iOS, it can share normally.

The error message:
![screen shot 2018-08-29 at 10 58 24](https://user-images.githubusercontent.com/25143307/44762726-a5c04080-ab7a-11e8-8f9f-15342f7b9382.png)

**Version**.
android: 8.1.0
react-native: 0.39.2
react-native-share : 1.1.1

Thank You!

**Comment by jgcmarins** [comment]
hey @jvaisaonna could you send a PR fixing it?

**Comment by kkbhav** [comment]
On android, special characters and not supported by android file system itself. So, it would be not possible to handle these file names. 
@jvaisaonna, you must pre-validate file that it is readable or not

**Comment by jgcmarins** [comment]
makes sense
it is on user land to make this validation
