### ISSUE TITLE
Instagram single video share

### ISSUE THREAD

**Issue by nicubarbaros** [react-native-community/react-native-share#355]
### Steps to reproduce
```
RNFetchBlob.config({
  fileCache : true,
  appendExt : 'mp4'
}).fetch('GET', mediaEntry.itemURL, {})
.then((res:any) => {
  let shareOptions = {
    url: 'file://' + res.path(),
   type: "video/mp4"
  }
  Share.shareSingle(shareOptions)
    .then((res:any) => console.log('res:', res))
    .catch((err:any) => console.log('err', err))
  });
```

### Expected behaviour
[First image of the instagram](https://scontent-otp1-1.xx.fbcdn.net/v/t39.2365-6/31739640_2065459473743293_5455162868888502272_n.png?_nc_cat=0&oh=576eba79d6618640dc99a4ffd6668e15&oe=5BF83231)
### Actual behaviour
It opens the dialog with all the apps. Just as  `Share.open()`

### Environment
- **React Native version**: 0.56.0
- **React Native platform + platform version**: iOS 9.0

### react-native-share
**Version**: 1.1.1

**Comment by jgcmarins** [comment]
it is missing `social` property on `shareOptions`
take a look at this: https://github.com/react-native-community/react-native-share#static-values-for-social
it should be:
```jsx
import Share from 'react-native-share';

const shareOptions = {
    title: 'Share via',
    url: 'some share url',
    social: Share.Social.INSTAGRAM
};
Share.shareSingle(shareOptions);
```

**Comment by nicubarbaros** [comment]
In fact I have the social property. And it still has the same behavior.

**Comment by nicubarbaros** [comment]
https://github.com/react-native-community/react-native-share/issues/358#issuecomment-418648657  - Made the solution here.

**Comment by jgcmarins** [comment]
Awesome! Let's keep tracking on #358
