### ISSUE TITLE
Share function does not work in iOS

### ISSUE THREAD

**Issue by ryuheimat** [react-native-community/react-native-share#361]
Share does not work in iOS, But android is fine.
The problem I cannot understand is that when I do Share.open({url: '.....'}), the Share UI appeared, but cannot share to any - cannot copy, send email with empty string, ....
There is no crash or nothing.

Only function does not work.

**Comment by jgcmarins** [comment]
@ryuheimat could you provide code sample or github repository to reproduce?

**Comment by indapublic** [comment]
Looks same as mine #404
