### ISSUE TITLE
Not opening the app but the browser in iOS

### ISSUE THREAD

**Issue by lrcen** [react-native-community/react-native-share#362]
### Expected behaviour
 open the installed app like facebook、twitter.

### Actual behaviour
open in the browser. (
It should happen without downloading the corresponding app)

### Environment
- **React Native version**: v0.56.0
- **React Native platform + platform version**: iOS 11.4

### react-native-share
**Version**: ^1.1.1

Android is working fine.

**Comment by IronTony** [comment]
The same happened to me and debugging I saw that it returns an error with the message:
"Not Installed".

**Comment by jgcmarins** [comment]
duplicated: https://github.com/react-native-community/react-native-share/issues/320
