### ISSUE TITLE
Couldn't Get the Success Response after Completion of Share

### ISSUE THREAD

**Issue by mahesh963** [react-native-community/react-native-share#363]
Hi, Thanks for the best Share module.

### Steps to reproduce
1.I'm Using the **Share.Open()** Method to Share Image along with the Text in My Application.
2.It's Working fine. but, there is no callback Success response after Completion of the Share.

### Expected behaviour
Get Callback Success Response after post(Image/Text) is Shared successfully

### Actual behaviour
Not Getting Success Response after Completion of Share. The dialog **{message:ok}** is calling before sharing.

### Environment
- **React Native version**: V 0.48.3

### react-native-share
**Version**: ^1.1.0

Can anyone help me how to resolve this and get success response after shared successfully.

**Comment by jgcmarins** [comment]
hi @mahesh963,
> Hi, Thanks for the best Share module.

Happy to know that.

PRs are always welcome \o/

**Comment by logicfab-awais-yaseen** [comment]
is there any solution for this ?
