### ISSUE TITLE
Runtime Error: Attempt to invoke virtual method \'android.content.res.XmlResourceParser

### ISSUE THREAD

**Issue by Ilario17** [react-native-community/react-native-share#368]
{ error: 'Attempt to invoke virtual method \'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)\' on a null object reference' }

I take an image with react-native-view-shot that saves it in:

**file:///data/data/com.my.package/cache/ReactNative-snapshot-image-385792666.jpg**

Now I'm trying this filepaths.xml:

`<cache-path name="ReactNative" path="." />`

I have already tried `files-path` or `external-path`, none of this works.

AndroidManifest.xml

```
     <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:grantUriPermissions="true"
            android:exported="false">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/filepaths"
                tools:replace="android:resource"/>
        </provider>
```

### Environment
- *React Native version*: 0.57
- *React Native platform + platform version*:  Android 5.1

### react-native-share
**Version**: 1.1.2

PS. I have already seen the issue with the same title but it has not solved my problem

**Comment by jgcmarins** [comment]
@Ilario17 did you solved?

**Comment by Ilario17** [comment]
Too much time in front of the PC to write code will make you see bugs where there are not...

missing  ".provider" in `getFileProviderAuthority`

Sorry for creating this issue and thank you for your work.

**Comment by jgcmarins** [comment]
@Ilario17 thats ok, don't worry \o/

**Comment by Shanie1331** [comment]
> getFileProviderAuthority

@Ilario17  I still have the same issue can you please help me on the same.

> "missing ".provider" in getFileProviderAuthority"
is this available in new version or I have to add it manually.

**Comment by Shanie1331** [comment]
@mlazari @nguyenvanphuc2203 @jgcmarins @heracek
Android 8.1.0, api 27...

build.gradle(module app)

android {
    compileSdkVersion 27
    buildToolsVersion '28.0.3'
}
build.gradle (project: xxx)

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'com.google.gms:google-services:4.0.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}


task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}

subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "27.1.1"
            }
        }
    }
}
Android.manifest...

`

<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
<uses-permission android:name="android.permission.READ_PHONE_STATE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

<application
  android:name=".MainApplication"
  android:label="@string/app_name"
  android:icon="@mipmap/ic_launcher"
  android:allowBackup="false"
  android:theme="@style/AppTheme">
  <activity
    android:name=".MainActivity"
    android:label="@string/app_name"
    android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
    android:windowSoftInputMode="adjustPan">
      <intent-filter>
          <action android:name="android.intent.action.SEND" />
          <category android:name="android.intent.category.DEFAULT" />
          <data android:mimeType="text/plain" />
          <data android:mimeType="image/*" />
      </intent-filter>
    <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
        <action android:name="android.intent.action.DOWNLOAD_COMPLETE"/>
    </intent-filter>
  </activity>
  <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    <provider
        android:name="android.support.v4.content.FileProvider"
        android:authorities="${applicationId}.fileprovider"
        android:grantUriPermissions="true"
        android:exported="false">
        <meta-data
            android:name="android.support.FILE_PROVIDER_PATHS"
            android:resource="@xml/file_paths"/>
    </provider>
</application>
` I am taking permissions from android like this : ----->
if(Platform.OS ==='android'){try {
      const granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE,
        {
          title: 'Cool Photo App Camera Permission',
          message:
            'Cool Photo App needs access to your camera ' +
            'so you can take awesome pictures.',
          buttonNeutral: 'Ask Me Later',
          buttonNegative: 'Cancel',
          buttonPositive: 'OK',
        }
      );
      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        console.log('You can READ camera');
      } else {
        console.log('Camera permission denied');
      }
    } catch (err) {
      console.warn(err);
    }
    try {
      const granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
        {
          title: 'Cool Photo App Camera Permission',
          message:
            'Cool Photo App needs access to your camera ' +
            'so you can take awesome pictures.',
          buttonNeutral: 'Ask Me Later',
          buttonNegative: 'Cancel',
          buttonPositive: 'OK',
        }
      );
      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        console.log('You can WRITE camera');
      } else {
        console.log('Camera permission denied');
      }
    } catch (err) {
      console.warn(err);
    }}
this is what I am doing ------>

            let base64Str = res;
            const fs = RNFetchBlob.fs
            const dirs = RNFetchBlob.fs.dirs;
            let imageLocation = dirs.DownloadDir +'/'+'reactNew.png';
            fs.writeFile(imageLocation, base64Str, 'base64');
            console.log(imageLocation)
            // RNFetchBlob.fs.scanFile([ { path : imageLocation } ])
            RNFetchBlob.fs.readFile(imageLocation, 'base64')
              .then((res) => {
                const URL = "data:image/png;base64,"+res;
                let shareOptions = {
                  // title: "React Native Share Example",
                  // message: "Check out this photo!",
                  url: URL,
                  // url: res,
                  type: 'image/png',
                  // subject: "Check out this photo!"
                }
                Share.open(shareOptions)
                  .then((result) => console.log('result:', result))
                  .catch(err => console.log('err', err))
                  console.log("scan file success")
              })
              .catch((err) => {
                console.log("scan file error")
              })
Response in debugger is :

/storage/emulated/0/Download/reactNew.png ------> console.log(imageLocation)

scan file success ------> console.log("scan file success")

err {error: "Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference"} ---------> .catch(err => console.log('err', err))
