### ISSUE TITLE
Issue when used with other Media Libraries for Image,Video & PDf

### ISSUE THREAD

**Issue by garg-aviral** [react-native-community/react-native-share#369]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
When we are using it with other Libraries.This Library is creating issue to other libaries like for Image,Video,Files.Just when we add required code for android It clashes with other libraries

### Actual behaviour
Tell us what happens instead

### Environment
- **React Native version**:
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc

### react-native-share
**Version**: npm version or "master"

### Link to repo (highly encouraged)
https://github.com/

**Comment by yeomann** [comment]
can you provide some example please?
