### ISSUE TITLE
Unable to share image via Skype and Flickr

### ISSUE THREAD

**Issue by nihp** [react-native-community/react-native-share#375]
I am using react-native-share to share my images to other apps. It working as expected in Facebook, twitter, Instagram, Pinterest, SnapChat etc. 

But it not working in Skype and Flickr. 

### Expected behaviour
Need to share the image via skype and Flickr

### Actual behaviour
I can't able to share image, if i click the image to share it showing the text box not the shared image.

Note: Here I did not send the message in my code. 
`return { title, url: dataUrl };`

### Environment
- **React-native version: 0.53.3**:

### react-native-share
**Version**: 5.6.0

**Comment by jgcmarins** [comment]
> **Version:** 5.6.0

?

**Comment by nihp** [comment]
Npm Version: 5.6.0

**Comment by jgcmarins** [comment]
got it

**Comment by nihp** [comment]
@jgcmarins 
Any update here

**Comment by lrcen** [comment]
@nihp Hi, are u using open or shareSingle? 
@jgcmarins  
When I share the image with the shareSingle method, title and message will be displayed as domain name on Facebook. 
![11539055966_ pic](https://user-images.githubusercontent.com/32728756/46645341-14031480-cbb7-11e8-8eb0-2f981b7ce3af.jpg)

The message can be displayed correctly on Twitter, but the image is displayed as a link.
![31539056151_ pic](https://user-images.githubusercontent.com/32728756/46645428-7fe57d00-cbb7-11e8-9267-afb597d2682a.jpg)


Is there a way to display the image correctly with the message I want?

**Comment by alkaffkhanvrv** [comment]
@jgcmarins I am using open.

**Comment by alkaffkhanvrv** [comment]
aew

**Comment by nihp** [comment]
@jgcmarins I am using Share.open and I can able to see the message and image correctly.

**Comment by theone3nu** [comment]
Any update on this i am also unable to share image in skype. Works fine for whatsapp.
