### ISSUE TITLE
Unable to share via YouTube

### ISSUE THREAD

**Issue by zenara** [react-native-community/react-native-share#376]
I'm using React native for the purpose of sharing links among social networks. But it's not working for YouTube.

### Expected behaviour
Need to share among YouTube

### Actual behaviour
Tell us what happens instead

### Environment
- **React Native version**: 0.57
- **npm version**: 6.4.1

**Comment by lrcen** [comment]
I have a similar problem. First of all, I am very grateful for this solve some of my current problems. Now I want to share to Telegram, but it seems that it is not supported yet. I hope it can also be supported, THANK YOU!

**Comment by chpq95** [comment]
I have a question, does react-native-share support sharing to youtube in ios? because i cant see youtube is listed when i click sharing. but it listed in android
