### ISSUE TITLE
Getting error: package cl.json does not exist 

### ISSUE THREAD

**Issue by AakashRainaClairvoyant** [react-native-community/react-native-share#378]
After installing, linking and doing all the further configuration steps mentioned in the README for android, I get the following error when I try to buid the app. Along with the error I get the following errors as well:

1) java:12: error: package cl.json does not exist
import cl.json.RNSharePackage;
              ^
2) java:13: error: package cl.json does not exist
import cl.json.ShareApplication;

My mainapplication.java looks like:

package host.exp.exponent;

import com.facebook.react.ReactPackage;

import java.util.Arrays;
import java.util.List;

import expolib_v1.okhttp3.OkHttpClient;

// Needed for `react-native link`
// import com.facebook.react.ReactApplication;
import cl.json.RNSharePackage;
import cl.json.ShareApplication;
import com.rt2zz.reactnativecontacts.ReactNativeContacts;
import com.geektime.rnonesignalandroid.ReactNativeOneSignalPackage;

public class MainApplication extends ExpoApplication implements ShareApplication {

  @Override
  public boolean isDebug() {
    return BuildConfig.DEBUG;
  }

  // Needed for `react-native link`
  public List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
        // Add your own packages here!
        // TODO: add native modules!

        // Needed for `react-native link`
        // new MainReactPackage(),
        new RNSharePackage(), new ReactNativeContacts(), new ReactNativeOneSignalPackage());
  }

  @Override
  public String gcmSenderId() {
    return getString(R.string.gcm_defaultSenderId);
  }

  @Override
  public boolean shouldUseInternetKernel() {
    return BuildVariantConstants.USE_INTERNET_KERNEL;
  }

  @Override
  public String getFileProviderAuthority() {
    return "com.tether.android.provider";
  }

  public static OkHttpClient.Builder okHttpClientBuilder(OkHttpClient.Builder builder) {
    // Customize/override OkHttp client here
    return builder;
  }
}

**Comment by jgcmarins** [comment]
it looks like your link is wrong
which command did you use to link?
