### ISSUE TITLE
Black screen on android share to instagram story

### ISSUE THREAD

**Issue by ronywix** [react-native-community/react-native-share#379]
When trying to share to instagram stories i get a black screen. Instagram feed works ok
Works fine on ios (although kind of a different flow)

happens on react-native-share **1.0.27**
```
let imageData = await RNFS.readFile(localUrl, 'base64');
Share.open({url: 'data:image/png;base64,' + imageData, type: 'image/png'})
.then (result -> {
})
.catch(error => {
    console.log('ShareSheet - error: ', error);
})
```

**Comment by jgcmarins** [comment]
could you try `v1.1.2`?

**Comment by Jagni** [comment]
Got the same issue testing on v1.1.2

Occurs on Android
Works fine on ios

**Comment by jgcmarins** [comment]
@Jagni, yesterday we had a new release to 1.1.3
could you check it please?

**Comment by Jagni** [comment]
Turns out the files were saved with wrong extensions (e.g. jpeg files saved as .png)
v1.1.2 worked fine on both iOS and Android after fixing that

**Comment by ryanhomer** [comment]
I have the same issue. When I look at the file in a hex editor, I can see PNG in the header so I don't think it's a JPEG with the wrong extension. Yet, when I convert to base64 and share to Twitter, the transparent background goes black.

**Comment by MateusAndrade** [comment]
You can try this with the master branch?

**Comment by ryanhomer** [comment]
I just tried with master branch and same results. If I download the picture from Twitter, I end up with a JPEG, so somewhere in the process (either this library or Twitter itself?) the image is being converted to JPEG.

**Comment by ryanhomer** [comment]
In fact, the images with white background that were posted via iOS, when I download those images from Twitter, they too are JPEG but for some reason they got a white background.

**Comment by ryanhomer** [comment]
Upon further research, seems like this happens at Twitter. What's weird is that on iOS we get white and on Android we get black.

https://lifehacker.com/stop-twitter-from-turning-your-pngs-into-jpgs-1822461989

**Comment by ryanhomer** [comment]
Sorry, I just realized I hi-jacked a thread about Instagram and I'm talking about Twitter.

**Comment by Rizaldinurm** [comment]
Can someone tell me how to setup options for Share Instagram Story, I have to write
`return ShareData.shareSingle({
          url: 'data:image/png;base64,' + imageData,
          type: 'image/png',
          message: 'Share to instagram',
          social: ShareData.Social.INSTAGRAM,
          forceDialog: true,
        });`

But redirect to Feed Instagram, I run in Android.

**Comment by MateusAndrade** [comment]
> But redirect to Feed Instagram, I run in Android.

Currently i think that its not possible to share to Instagram Stories with the last version on npm/master. 

However, we got a PR that aims to reimplement that. Im looking for some help to test that and ship #600 . 😄
