### ISSUE TITLE
Using with different androir flavors

### ISSUE THREAD

**Issue by uncledent** [react-native-community/react-native-share#380]
### Steps to reproduce
trying to use it with  
```  
@Override
     public String getFileProviderAuthority() {
            return "${applicationId}.provider";
     }
```
In MainApplication.java

and 

```
<provider
        android:name="android.support.v4.content.FileProvider"
        android:authorities="${applicationId}.provider"
        android:grantUriPermissions="true"
        android:exported="false">
        <meta-data
            android:name="android.support.FILE_PROVIDER_PATHS"
            android:resource="@xml/filepaths" />
    </provider>
```
in AndroidManifest.xml

### Expected behaviour
Will work

### Actual behaviour
Does not as written in docs actually

### react-native-share
1.1.2

Is there a way to use the library with multiple flavours? It works with one flavor only for me. When using with 
```
@Override
     public String getFileProviderAuthority() {
            return "${applicationId}.provider";
     }
```
I get an error:
<img width="249" alt="screen shot 2018-10-11 at 17 16 02" src="https://user-images.githubusercontent.com/6542981/46814589-5e33f380-cd79-11e8-91df-69979424e1b4.png">

**Comment by brycepavey** [comment]
@uncledent I had the same issue, I did some research and came across this https://stackoverflow.com/questions/30896130/fileprovider-crash-npe-attempting-to-invoke-xmlresourceparser-on-a-null-string and applied the fix here in my fork. 
I've only done bare minimal testing for this, so I'm not sure if it covers all cases so I won't submit a PR for it, but it suits my case so hopefully helps you out too.

fix: https://github.com/brycepavey/react-native-share/commit/26a1d7fe107cff94f2f08922366a7e3803f6cc08
