### ISSUE TITLE
Instagram Share Failing On iOS After Latest Instagram Update

### ISSUE THREAD

**Issue by shannaleri** [react-native-community/react-native-share#382]
### Steps to reproduce
1. Update instagram to latest version
2. Log in to Instagram, or ensure you are logged in
3. Attempt to share an image with shareSingle such as (exact code follows):

`Share.shareSingle({title:"Share On Instagram", url: "file://" + res.url, social: Share.Social.INSTAGRAM})`

`res.url` in the above returns a path to an image saved to tmp. 

### Expected behaviour
Users share directly to instagram. This code was working perfectly well until this latest Instagram update (yesterday). I have verified on three separate iPhones that the code works before the Instagram update and fails immediately after.

### Actual behaviour
Instagram opens, with message "Unable to open file. You must be logged in."
![img_2552](https://user-images.githubusercontent.com/1909343/47054402-74212a00-d166-11e8-97bf-3ba7fa1153a6.jpg)

As previously stated, I have verified on three separate iPhones that the code works before the Instagram update and fails immediately after.

No errors or issues are appearing in debug. 

### Environment
- React Native 0.56.0
- iOS 12

### react-native-share
Version 1.1.2

**Comment by jgcmarins** [comment]
maybe instagram sharing path change?

**Comment by ilcesco** [comment]
Same happens to me 😢

**Comment by jgfidelis** [comment]
might be a bug on instagram

**Comment by shannaleri** [comment]
I think you're right, @jgfidelis . I just checked and sharing directly from Spotify to stories (Spotify has a direct IG share feature) has a similar issue. It brings me to a login screen, and I never end up being able to share the song even after logging in (no "unable to share, must be logged in" message in this case though).

You can bet that if it's breaking Spotify's sharing that it's a bug.

**Comment by jgfidelis** [comment]
It is probably an authentication bug within Instagram. If it is, this is a bit critical so they should fix it soon.

**Comment by nicubarbaros** [comment]
Same thing happened to our app today. 

After testing spotify, buffer (if you know) and some others, all of them have the same problem

**Comment by jgcmarins** [comment]
thanks everyone
let's keep an eye on Instagram future notes

**Comment by shannaleri** [comment]
The latest instagram update (v 68.0) fixes this issue. The instagram sharing is working as expected again.
