### ISSUE TITLE
Change share message base on selected app

### ISSUE THREAD

**Issue by sonlexqt** [react-native-community/react-native-share#383]
Hi, I'm using this package to implement external sharing in my application. I have a question, is it possible to change the share message base on the app that user has chosen ? For example:
- If user selects "Messages", "Whatsapp" or "Messenger", the share message will be **this is message A**
- If user selects other apps, the share message will be  **this is message B**

**Comment by jgcmarins** [comment]
I guess it is possible, but it is a kind of logic that is on your land.

**Comment by jgcmarins** [comment]
For more details about how to implement this, I recommend asking on https://stackoverflow.com/

**Comment by jigartankhupp** [comment]
@sonlexqt Did you get any solution?
