### ISSUE TITLE
Android local file share doesn't share contents of file

### ISSUE THREAD

**Issue by acb** [react-native-community/react-native-share#385]
### Steps to reproduce
1. Attempt to share a local text file via `Share.open` using the local path as described in the docs, e.g. `url: "file:///storage/emulated/0/test.txt"`

### Expected behaviour
The contents of the file should be shared to the selected app

### Actual behaviour
Instead of the file contents the file url is shared to the app, e.g. if I share to Gmail the string "file:///storage/emulated/0/test.txt" is copied into the email.

### Environment
- **React Native version**: .55.3
- **React Native platform + platform version**: Android 8.1.0

### react-native-share
**Version**: 1.1.2

**Comment by svetlanakaida** [comment]
I see this too, same steps for reproduction.

**Comment by suwu150** [comment]
when i share file of pdf.i add next code in option obejct.Add it works ok.
```
                const options = {
                  url: `file://${item.path}`,
                  type: 'application/pdf',
                  showAppsToView: true,
                  title: `${item.name || ''}`
                };
```
so add ` type: 'application/pdf',` try again.or other.

**Comment by indapublic** [comment]
Weird, but it's not working for me in iOS. There is no content to share. Base64 working well except Whatsapp

**Comment by watchtower314** [comment]
Have the same issue; my code works well on iOS, but on Android, it sends the string of the path.
Also what @suwu150 suggested didn't work for me :/

```
export async function send(path)
{
Share.open({
	title: strings.share,
	message: strings.shareMessage,
	url: path,
	type: 'application/pdf',
	subject: strings.shareSubject,
	}).then((res) => {
		console.log('CORTEX: TKT_371: send(): res: '+res)})
		.catch((err) => {console.log('CORTEX: TKT_373: send(): error for some reason: '+err);});
}
```
(variable `path` looks like something like this: 
`/data/user/0/com.appName/cache/123456.pdf`)

@acb did you find a solution? :pray:

**Comment by suwu150** [comment]
@watchtower314 add below code
add app/src/main/AndroidManifest.xml

```
        <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:grantUriPermissions="true"
            android:exported="false">
            <meta-data
                tools:replace="android:resource"
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/filepaths" />
        </provider>
```
and  in res/xml/filepaths.xml
```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path name="myexternalimages" path="Download/" />
    <root-path name="root" path="" />
    <files-path
        name="files-path"
        path="." /> <!-- Used to access into application data files -->
</paths>
```

**Comment by watchtower314** [comment]
@suwu150 's solution did the trick! Although at first it seemed not to work; it caused a different error that  said `failed to find configured root that contains /file:/storage/emulated/0/123456.pdf` but after removing the app from my device and rebuilding, it worked perfectly!

Thanks!!

**Comment by jgcmarins** [comment]
Great!

**Comment by ofreitas** [comment]
App it's work, but don't share the image:

`        <TouchableOpacity onPress={()=>{
          Share.open({
            url: 'file:///src/imgs/share.png',
            type: 'image/png'
          });
        }}>
          <View>
            <Text>Share Image Test</Text>
          </View>
        </TouchableOpacity>`

**Comment by ansarikhurshid786** [comment]
For me working
