### ISSUE TITLE
Release version with error in Android

### ISSUE THREAD

**Issue by mendesfelipe87** [react-native-community/react-native-share#393]
### Steps to reproduce
1. apply the component in any react-native project
2. use the version 1.1.3
3. generate a release android APK 

### Expected behaviour
Generate a release signed apk

### Actual behaviour
The command ./gradle assembleRelease gives the following error
Failed to generate resource table for split ''
.gradle/caches/transforms-1/files-1.1/appcompat-v7-28.0.0.aar/51d229a6f3b32738f6fbcfda621df688/res/values-v28/values-v28.xml:5:5-8:13: AAPT: No resource found that matches the given name (at 'dialogCornerRadius' with value '?android:attr/dialogCornerRadius').

### Environment
- React-Native version 0.57.1

### react-native-share
**Version**: 1.1.3

**Comment by jgcmarins** [comment]
hello @mendesfelipe87 why is this related to react-native-share?

**Comment by mendesfelipe87** [comment]
Hi @jgcmarins, because of this info that the gradle display 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-share:verifyReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by mikehardy** [comment]
I just attempted to reproduce this:
```
mike@isabela:~/work/react-random/react-native-share/example/android (master *) % ./gradlew verifyReleaseResources
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :app
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /home/mike/Android/Sdk/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.


> Configure project :react-native-share
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /home/mike/Android/Sdk/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.


BUILD SUCCESSFUL in 8s
6 actionable tasks: 6 executed
```

What am I doing wrong?

I´ll continue poking around myself for a little bit to try to make this happen, but currently I´m not seeing it :man_shrugging:

**Comment by mendesfelipe87** [comment]
Hi @mikehardy are you trying to generate a release ? because this happens only when you create a release version of the RN project that uses this as component

when you use react-native run-android, works normally

**Comment by mikehardy** [comment]
My command line was included above. I directly called the gradle task that you posted had failed, using our example project

**Comment by mikehardy** [comment]
This also worked - and generated an apk. I want to be clear I'm not saying we don't have a problem! :-), just that I'm not seeing it. Maybe there's something subtle though. I'd just need a more explicit reproduction

```
mike@isabela:~/work/react-random/react-native-share/example/android (master *) % ./gradlew assembleRelease

> Configure project :app
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /home/mike/Android/Sdk/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.


> Configure project :react-native-share
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /home/mike/Android/Sdk/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.


> Task :app:bundleReleaseJsAndAssets
Scanning folders for symlinks in /home/mike/work/react-random/react-native-share/example/node_modules (6ms)
Scanning folders for symlinks in /home/mike/work/react-random/react-native-share/example/node_modules (8ms)
Loading dependency graph, done.
warning: the transform cache was reset.
bundle: Writing bundle output to: /home/mike/work/react-random/react-native-share/example/android/app/build/intermediates/assets/release/index.android.bundle
bundle: Done writing bundle output

> Task :react-native-share:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/mike/work/react-random/react-native-share/example/node_modules/react-native-share/android/src/main/java/cl/json/ShareFiles.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :app:lintVitalRelease
Calling mockable JAR artifact transform to create file: /home/mike/.gradle/caches/transforms-1/files-1.1/android.jar/e235c904d4c75a682a36fa1e2a8c677a/android.jar with input /home/mike/Android/Sdk/platforms/android-28/android.jar

BUILD SUCCESSFUL in 36s
53 actionable tasks: 47 executed, 6 up-to-date
mike@isabela:~/work/react-random/react-native-share/example/android (master *) % ls -lat app/build/outputs/apk/release/
total 7368
drwxr-xr-x 2 mike mike    4096 Oct 25 16:18 ./
-rw-r--r-- 1 mike mike     252 Oct 25 16:18 output.json
-rw-r--r-- 1 mike mike 7532240 Oct 25 16:18 app-release-unsigned.apk
drwxr-xr-x 4 mike mike    4096 Oct 25 16:18 ../
mike@isabela:~/work/react-random/react-native-share/example/android (master *) % 
```

**Comment by mendesfelipe87** [comment]
I've tried clean the yarn cache and gradle dependencies, maybe is this ? try to clear it and rebuild again

**Comment by mikehardy** [comment]
Looks like it might be a classic Android gradle + support library + compile library version issue: https://stackoverflow.com/questions/49280632/error9-5-error-resource-androidattr-dialogcornerradius-not-found

Please confirm you have all your versions lined up (that link is pretty good about explaining how)

**Comment by yeomann** [comment]
@mikehardy i agree with mike. all those fights with Gradle and support and compile version ...pfff
