### ISSUE TITLE
 Share.shareSingle(Object.assign(shareOptions, { "social": "instagram" }));

### ISSUE THREAD

**Issue by tunm1228** [react-native-community/react-native-share#394]
### Steps to reproduce
1.shareOption: {
                                title: "TITUT",
                                message: 'TITUT',
                                url: 'https://www.instagram.com/',
                                subject: 'Invite to TiTut'
                            }
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Environment
- **React Native version**:
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc

### react-native-share
**Version**: npm version or "master"

### Link to repo (highly encouraged)
https://github.com/

**Comment by yeomann** [comment]
ahm.... 

> Tell us what happens instead

Please?
