### ISSUE TITLE
Url with string is not clickable

### ISSUE THREAD

**Issue by theone3nu** [react-native-community/react-native-share#397]
### Steps to reproduce
1. const shareOptions = {
  title: 'Test',
  message: 'New Test',
  url: 'testapp://app',
  subject: 'Share Link', //  for email
};
Share.open(shareOptions).catch(error => console.log(error))

2. when i shared this to other apps url is not clickable in the other app.

### Expected behaviour
Tell us what should happen
I am trying to open reactnative app using Linking. when i type testapp:// in the browser it says open cancel the app and when i click open it opens testapp. 
Similarly when i share the link 'testapp://' to other apps it should be clickable and if possible hide the link and show just the text.

### Actual behaviour
Tell us what happens instead
It simply shows string and it is not clickable.

### Environment
- **React Native version**:0.55.2
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc
ios 11.4

### react-native-share
**Version**: npm version or "master" 1.1.3

### Link to repo (highly encouraged)
https://github.com/

**Comment by jgcmarins** [comment]
It's on developer land to make it touchable

**Comment by yeomann** [comment]
i don't really understand this issue...

**Comment by enieber** [comment]
@theone3nu this problem is not in react-native-share because this module is only share data.
