### ISSUE TITLE
Extension was interrupted while PDF sharing on IOS

### ISSUE THREAD

**Issue by indapublic** [react-native-community/react-native-share#404]
### Steps to reproduce

```
RNFetchBlob.config({
  fileCache: true,
  path: `${RNFetchBlob.fs.dirs.DocumentDir}/${fileName}.${fileExt}`,
  appendExt: fileExit
}).fatch(method, url, headers).then(res => {
  const path = res.path();
  await Share.open({
    type: 'application/pdf',
    url: Platform.OS === 'android' ? `file://${path}` : path,
  });
})
```

Then try to share with ICloud drive/Whatsapp

### Expected behaviour
File is shared

### Actual behaviour
I see `Extension was interrupted` error on ICloud sharing
<img width="260" alt="screen shot 2018-11-20 at 19 11 36" src="https://user-images.githubusercontent.com/856260/48763069-23b66280-ecf8-11e8-8b4f-2125c57f9993.png">

and `Item cannot be shared` on Whatsapp sharing
![img_5933](https://user-images.githubusercontent.com/856260/48763206-7001a280-ecf8-11e8-9f9c-215b54c674f7.jpg)

`path` on device looks like:
![img_5934](https://user-images.githubusercontent.com/856260/48763329-c2db5a00-ecf8-11e8-8b52-7159a286cbf9.PNG)

### Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
      Memory: 38.09 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: 0.57.5 => 0.57.5
    npmGlobalPackages:
      react-native-cli: 2.0.1

### react-native-share
"react-native-share": "^1.1.3"

**Comment by jgcmarins** [comment]
isn't this related to our [troubleshooting section](https://github.com/react-native-community/react-native-share#troubleshooting)?

**Comment by indapublic** [comment]
btw working only if file in base64 (except Whatsapp and Gmail, it's described in troubleshooting section).
If I using path - no file in IMessage/Mail/Whatsapp etc.

**Comment by indapublic** [comment]
Closed as non reproducible for clean demo

**Comment by export-mike** [comment]
@indapublic 

i'm finding on iOS i'm getting a blank pdf when I share?
![image](https://user-images.githubusercontent.com/2983327/50651750-40db8380-0f7c-11e9-9b2a-3c6cb548cc68.png)

react-native-share@1.1.3
rn-fetch-blob@0.10.14
react-native-fs@2.13.3

any ideas?

**Comment by indapublic** [comment]
@export-mike Could you repeat it on clean demo? It would be excellent and helpful

**Comment by export-mike** [comment]
@indapublic git@github.com:export-mike/react-native-share-pdf-ios-android-example.git
seems to be working!

```
├─ react-native-fs@2.13.3
├─ react-native-share@1.1.3
├─ react-native@0.57.8
└─ rn-fetch-blob@0.10.15
```
