### ISSUE TITLE
undefined is not an object (evaluating 'n.NativeModules.RNShare.FACEBOOK')

### ISSUE THREAD

**Issue by prabhu73** [react-native-community/react-native-share#406]
### Steps to reproduce
1. After I run the project I got the error like 

![image](https://user-images.githubusercontent.com/22490455/48884129-22487f80-ee49-11e8-842e-4cd1fa40c01b.png)

11-22 11:27:13.019 10512-10568/com.fpthome E/ReactNativeJS: undefined is not an object (evaluating 'n.NativeModules.RNShare.FACEBOOK')
11-22 11:27:13.020 10512-10568/com.fpthome E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
    
    --------- beginning of crash
11-22 11:27:13.057 10512-10569/com.fpthome E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.fpthome, PID: 10512
    com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'n.NativeModules.RNShare.FACEBOOK'), stack:
    <unknown>@559:4962
    v@2:1496
    d@2:949
    o@2:435
    <unknown>@343:233
    v@2:1496
    d@2:949
    o@2:435
    <unknown>@312:433
    v@2:1496
    d@2:949
    o@2:435
    <unknown>@11:51
    v@2:1496
    d@2:879
    o@2:435
    global code@578:4
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:135)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:818)

Build process is successful but when I am running the project I got the above error.

**Comment by jgcmarins** [comment]
this is a bug
do we have same behaviour on ios?

**Comment by loubacking** [comment]
I got this error also, and I need it to share image in Android platform, as the same situation for you? If I fix it in my env, I'll share here

**Comment by loubacking** [comment]
Well, I fixed it here, and to be honest this isn't a bug, because if you implement like Getting Started shows, you will only get a specify errors in version of your application dependencies, to help you follow these steps:

**(android/app/build.gradle)**
_Change_ compileSdkVersion and buildToolsVersion version;
_Input_ `compile project(':react-native-share')` at dependencies;
_Change_ compile "com.android.support:appcompat-v7:28.0.0"

**(Terminal)**

Run `react-native link react-native-share`

**Comment by prabhu73** [comment]
> Well, I fixed it here, and to be honest this isn't a bug, because if you implement like Getting Started shows, you will only get a specify errors in version of your application dependencies, to help you follow these steps:
> 
> **(android/app/build.gradle)**
> _Change_ compileSdkVersion and buildToolsVersion version;
> _Input_ `compile project(':react-native-share')` at dependencies;
> _Change_ compile "com.android.support:appcompat-v7:28.0.0"
> 
> **(Terminal)**
> 
> Run `react-native link react-native-share`

No luck @loubacking Tried as you suggested. 

settings.gradle
rootProject.name = 'FPTHome'
include ':react-native-share'
project(':react-native-share').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-share/android')

include ':app'

android/app/gradle
dependencies {
implementation project(':react-native-share')

**Comment by TimurAsayonok** [comment]
Hello, I have same problem

**Comment by loubacking** [comment]
@TimurAsayonok You can use react-native link, and after this check if all files was correctly following manual installation. I suggest the same to @prabhu73 

Hope help y'all

**Comment by TimurAsayonok** [comment]
> @TimurAsayonok You can use react-native link, and after this check if all files was correctly following manual installation. I suggest the same to @prabhu73
> 
> Hope help y'all

Thanks, but what I have written, It helps for me. And it was my mistake.

**Comment by jobino** [comment]
Just do it: uninstall the app, after - react native run-android.

**Comment by rahamin1** [comment]
@TimurAsayonok  @prabhu73 

Can you elaborate? Not sure what exactly I need to change.

Here is my build.gradle:

```
apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {
        applicationId "com.share"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2, "arm64-v8a": 3]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    implementation project(':react-native-share')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

```

**Comment by jgcmarins** [comment]
@rahamin1 take a loot at this [build.gradle](https://github.com/react-native-community/react-native-share/blob/master/example/android/app/build.gradle) from example.

**Comment by rahamin1** [comment]
Thanks @jgcmarins   
I used your file instead of mine, and then:

- `react-native unlink react-native-share`
- deleted node_modules
- `npm instal`l and `react-native link react-native-share`

And then `react-native run-android`

This is what I get:
```
>react-native run-android
Starting JS server...
Building and installing the app on the device (cd android && gradlew.bat installDebug)...

FAILURE: Build failed with an exception.

* Where:
Settings file 'C:\esites-native\share\android\settings.gradle' line: 3

* What went wrong:
Could not compile settings file 'C:\esites-native\share\android\settings.gradle'.
> startup failed:
  settings file 'C:\esites-native\share\android\settings.gradle': 3: unexpected char: '\' @ line 3, column 113.
     ode_modules\react-native-share\android')
                                   ^
```

Any idea?

**Comment by rahamin1** [comment]
Thanks @jgcmarins 

I used your file instead of mine, and now I get: 
```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

This error is located at:
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:33)
createFiberFromTypeAndProps
    C:\esites-native\share1\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:5679:10
createFiberFromElement
    C:\esites-native\share1\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:5707:4
createChild
    C:\esites-native\share1\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:9857:12
reconcileChildrenArray
    C:\esites-native\share1\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:10200:10
reconcileChildFibers
    C:\esites-native\share1\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:10655:8
reconcileChildren
    C:\esites-native\share1\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:11096:6
updateHostComponent
    C:\esites-native\share1\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:11784:4
beginWork
    C:\esites-native\share1\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:12752:8
performUnitOfWork
    C:\esites-native\share1\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:16075:21
workLoop
    C:\esites-native\share1\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:16115:41
renderRoot
    C:\esites-native\share1\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:16219:15
performWorkOnRoot
    C:\esites-native\share1\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:17198:17
performWork
    C:\esites-native\share1\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:17099:24
performSyncWork
    C:\esites-native\share1\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:17060:14
requestWork
    C:\esites-native\share1\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:16925:19
scheduleWork
    C:\esites-native\share1\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:16724:16
scheduleRootUpdate
    C:\esites-native\share1\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:17413:15
updateContainerAtExpirationTime
    C:\esites-native\share1\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:17447:28
updateContainer
    C:\esites-native\share1\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:17537:4
render
    C:\esites-native\share1\node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:18191:20
renderApplication
    C:\esites-native\share1\node_modules\react-native\Libraries\ReactNative\renderApplication.js:59:34
run
    C:\esites-native\share1\node_modules\react-native\Libraries\ReactNative\AppRegistry.js:101:10
runApplication
    C:\esites-native\share1\node_modules\react-native\Libraries\ReactNative\AppRegistry.js:195:26
__callFunction
    C:\esites-native\share1\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:366:47
<unknown>
    C:\esites-native\share1\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:106:26
__guard
    C:\esites-native\share1\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:314:10
callFunctionReturnFlushedQueue
    C:\esites-native\share1\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:105:17

```

**Comment by mikehardy** [comment]
If it were me, I'd do react native create app fresh, install react native share fresh and make sure it works with a clean starter app.

**Comment by rahamin1** [comment]
I did this as well. To make sure, I will do it again.

**Comment by rahamin1** [comment]
Works now. Thanks much for your help, @jgcmarins  and @mikehardy

**Comment by jgcmarins** [comment]
@rahamin1 great!
If there is any missing docs you would like to add, feel free to open a pull request.

**Comment by gopinav** [comment]
The 'almost automatic installation' did not work for me on iOS. I was facing the error posted by the author. Make sure you also follow the manual installation steps. It worked for me after that.

**Comment by rahul-desai3** [comment]
The solutions mentioned in the comments here did not work for me.
I copied the code in the description into a expo snack and I see the same issue: https://snack.expo.io/BJRu9ewdN

What am I missing here?

**Comment by mikehardy** [comment]
This has become a catch-all multi-bug. It should be closed in favor of distinct issues I think.

@rahul-desai3 if I understand correctly you are using an Expo project and attempting to access a module with native code? Expo snack is just a server-based demo Expo project with what they build in, but not with react-native-share? I have never heard of Expo working with native code so you need to read the docs, and likely eject your project, if you must have native code support (like react-native-share uses...)

**Comment by jgcmarins** [comment]
Agreed with @mikehardy.
To everyone reading this thread, feel free to open a new issue with specific bug reports/questions/feature requests.
