### ISSUE TITLE
Cannot pass tests via jest if react-native-share was used

### ISSUE THREAD

**Issue by indapublic** [react-native-community/react-native-share#407]
### Steps to reproduce
1. Add `import Share from 'react-native-share';` to any component.
2. Run `jest`

### Expected behaviour
Test should be passed.

### Actual behaviour
```
  ● Test suite failed to run

    TypeError: Cannot read property 'FACEBOOK' of undefined

    >  9 | import Share from 'react-native-share';
```

### Environment
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
      Memory: 33.05 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.13.0 - ~/.nvm/versions/node/v8.13.0/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.13.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.4, macOS 10.13, tvOS 11.4, watchOS 4.3
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 9.4.1/9F2000 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1
      react-native: 0.57.5 => 0.57.5
    npmGlobalPackages:
      react-native-cli: 2.0.1

### react-native-share
`"react-native-share": "^1.1.3"`

**Comment by indapublic** [comment]
Added repository for bug illustrating https://github.com/indapublic/rn-share-and-jest

Example:
https://github.com/indapublic/rn-share-and-jest/blob/master/components/Test.js

**Comment by jgcmarins** [comment]
great
I'll take a look as soon as possible

**Comment by indapublic** [comment]
Thanks!

Simple solution I found is mock library in jest. Not sure is the best solution but my tests were passed

**Comment by jgcmarins** [comment]
@indapublic it would be awesome if we add those tests to this repo
since we have ci build, we could add then to ci routine
what do you think?

**Comment by jgcmarins** [comment]
> Simple solution I found is mock library in jest. Not sure is the best solution but my tests were passed
yep, totally agreed
it is something I would suggest

**Comment by indapublic** [comment]
> it would be awesome if we add those tests to this repo

You mean my repo? If yes, it's already https://github.com/indapublic/rn-share-and-jest/blob/master/components/__tests__/Test.test.js

**Comment by jgcmarins** [comment]
I've added you to repo as a contributor... feel free to send PR adding basic/failing tests...
tests are awesome

**Comment by indapublic** [comment]
Oh, i got it. Will prepare, but not sure about today

**Comment by jgcmarins** [comment]
`react-test-renderer` is deprecated...
I think we could use [react-testing-library](https://github.com/kentcdodds/react-testing-library)

**Comment by Under-Warz** [comment]
I'm using a mock file to bypass the FACEBOOK error. Here is the content of my react-native-share.js mock file 

```
module.exports = {
  open: jest.fn()
};
```

**Comment by mikehardy** [comment]
On another repo (https://github.com/react-native-community/react-native-device-info) I help maintain, [we explicitly tell people to mock](https://github.com/mikehardy/react-native-device-info/blame/master/README.md#L1143):

```
[tests] - Cannot run my test suite when using this library
react-native-device-info contains native code, and needs to be mocked. Jest Snapshot support may work though.

Here's how to do it with jest for example:

// in your package.json:
"jest": {
  "setupFiles": [
    "./testenv.js"
  ],


// testenv.js:
jest.mock('react-native-device-info', () => {
  return {
    getModel: jest.fn(),
  };
});
```

Though we did just merge something that may make jest snapshots work (I don't use them (yet?) so I don't know):
https://github.com/react-native-community/react-native-device-info/pull/375

Which is just to say this may be completely expected behavior. The fix may just be documentation

**Comment by elisechant** [comment]
The code you need in your jest setup file is:

```
jest.mock('react-native-share', () => {
  return {
    open: jest.fn(),
  };
});
```

**Comment by SimaRajput** [comment]
Add this line in your setupTest.js (testing base file).

jest.mock('react-native-share', () => ({
}));

Hope,this will wotk.
