### ISSUE TITLE
Callback send success message after press cancel button

### ISSUE THREAD

**Issue by mgiorgi-github** [react-native-community/react-native-share#410]
### Steps to reproduce
return Share.open(shareOptions)
    .then((res) => { console.log("OK: "+res) })
    .catch((err) => { console.log("ERROR: "+err); });
}

### Expected behaviour
Facebook and Instagram app, after press "Cancel" button on share dialog make show ERROR message

### Actual behaviour
Only Facebook give correct message, Instagram return "OK" if i press "Cancel" or "Share" dialog button

### Environment
react-native-cli: 2.0.1
react-native: 0.57.1
iOS 12.1

### react-native-share
react-native-share: 1.1.3

**Comment by matheusnascgomes** [comment]
Same issue, it is possible to have a confirmation when the share action is successful and an error when not? @jgcmarins

**Comment by jgcmarins** [comment]
I guess it is possible to control this flow on developer land
