### ISSUE TITLE
node_module does not exist

### ISSUE THREAD

**Issue by sobyyialatiq** [react-native-community/react-native-share#412]
I am getting the error react-native-share module does not exist

### Environment
- **React Native version**: 0.55.1
- **React Native platform + platform version**:  Android 5.0

**Comment by mikehardy** [comment]
This sounds like not doing the react-native --link react-native-share step from the README, or (if you want to do it manually) not following the steps here https://github.com/react-native-community/react-native-share#Android-Install

Can you confirm you have linked the module in so gradle can find it? Also, the error message in full is useful, not just a paraphrased excerpt
