### ISSUE TITLE
content share via messanger

### ISSUE THREAD

**Issue by kalraneeraj24550** [react-native-community/react-native-share#417]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
it should open messanger to share content 

### Actual behaviour
Tell us what happens instead

### Environment
- **React Native version**:
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc

### react-native-share
**Version**: npm version or "master"

### Link to repo (highly encouraged)
https://github.com/

**Comment by jgcmarins** [comment]
hello @kalraneeraj24550 
what is this issue about?

**Comment by kalraneeraj24550** [comment]
i want to share message via messanger in react-native

**Comment by jgcmarins** [comment]
could you provide more details about errors you're experiencing?

**Comment by kalraneeraj24550** [comment]
![screenshot from 2018-12-13 18-20-53](https://user-images.githubusercontent.com/44640902/49939817-df3b7280-ff03-11e8-815a-ac3ae560052a.png)

in my app i want to share a message via messanger.

**Comment by kalraneeraj24550** [comment]
working fine for facebook, whatsapp., but not for messanger can you plz guide me

**Comment by jgcmarins** [comment]
sure, could we share some code example?

**Comment by kalraneeraj24550** [comment]
do you want the code that am using currently for messanger, right?

**Comment by kalraneeraj24550** [comment]
plase help ,me

**Comment by jgcmarins** [comment]
> do you want the code that am using currently for messanger, right?

just some code example

**Comment by kalraneeraj24550** [comment]
shareWithMessanger() {
        Linking.openURL('messenger://send?text=code is:');
      }
i am using this. it doesnt open messanger but plz helpme. to share content via messanger in react-native

**Comment by jgcmarins** [comment]
@kalraneeraj24550 I am sorry, but I could not understand why it is related to react-native-share.
Is there any piece of code that uses react-native-share?

**Comment by jgcmarins** [comment]
@kalraneeraj24550 could you take a look at this PR: https://github.com/react-native-community/react-native-share/pull/428 and check if it address your feature request?
It would be awesome if you try to run this PR on a living example.
Thanks in advice.
