### ISSUE TITLE
share image base64 not showing on social

### ISSUE THREAD

**Issue by nguyenvanphuc2203** [react-native-community/react-native-share#418]
here my code: 
```
captureScreen({
            format: "png",
            quality: 0.8,
            result:'data-uri'
          })
          .then(
            uri =>{
                console.log("Image saved to", uri)
                let shareImage = {
                    title: 'share image',//string
                    message: 'share image description',//string
                    url:uri,
    
                };
                Share.open(shareImage).catch(err => console.log(err));
            },
            error => console.error("Oops, snapshot failed", error)
          );
```
my console.log:
![image](https://user-images.githubusercontent.com/33291479/49786513-add17400-fd56-11e8-86a9-2c715ce1ef67.png)
but image not showing anymore when sharing, for example share with email:
![image](https://user-images.githubusercontent.com/33291479/49786797-8038fa80-fd57-11e8-908e-13a6db36e8fa.png)

### Environment
- **React Native version**: 0.55.4
- **React Native platform + platform version**: Android 8.0

### react-native-share
**Version**: 1.0.27

**Comment by jgcmarins** [comment]
hello, could try version 1.1.3?

**Comment by mlazari** [comment]
Actually it works fine if I put that data URL in a constant like in the examples from Readme. But if I use the value from https://github.com/iddan/react-native-canvas#canvastodataurl it doesn't work. I log it in console and it has the same value.

**Comment by Shanie1331** [comment]
@mlazari please elaborate a bit. I am also in same issue. Also I am unable to share any base64 uri.
@nguyenvanphuc2203 Did you resolved ? or any workaround please suggest.

**Comment by mlazari** [comment]
@Shanie1331 I had the base64 url generated by other library and it was `'"data:image/png;base64,iVBO...gg=="'` instead of `'data:image/png;base64,iVBO...gg=='`. I had to remove surrounding quotes before passing it to `Share.open()` and that fixed it.

**Comment by Shanie1331** [comment]
@mlazari I am unable to share base 64 with react native share it gives me "Attempt to invoke virtual method in  android.content. xml parser " error. Its is in debug mode. I have done every changes suggested by all the masters like permission issue, manifests change and taking permissions on app launch but nothing worked for me. Can you please help me out.

**Comment by mlazari** [comment]
@Shanie1331 I don't know, I didn't have this issue. Can you post the full stack trace for that `Attempt to invoke virtual method` exception?

**Comment by Shanie1331** [comment]
this is what I am doing

`let base64Str = res;
                const fs = RNFetchBlob.fs
                const dirs = RNFetchBlob.fs.dirs;
                let imageLocation = dirs.DownloadDir +'/'+'reactNew.png';
                fs.writeFile(imageLocation, base64Str, 'base64');
                console.log(imageLocation)
                // RNFetchBlob.fs.scanFile([ { path : imageLocation } ])
                RNFetchBlob.fs.readFile(imageLocation, 'base64')
                  .then((res) => {
                    const URL = "data:image/png;base64,"+res;
                    let shareOptions = {
                      // title: "React Native Share Example",
                      // message: "Check out this photo!",
                      url: URL,
                      // url: res,
                      type: 'image/png',
                      // subject: "Check out this photo!"
                    }
                    Share.open(shareOptions)
                      .then((result) => console.log('result:', result))
                      .catch(err => console.log('err', err))
                      console.log("scan file success")
                  })
                  .catch((err) => {
                    console.log("scan file error")
                  })`


"Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference"

**Comment by jgcmarins** [comment]
We did a new release, can you try it? v1.2.0.
Thank you.

**Comment by Sanan4li** [comment]
I am having the same issue. When I tries to share base64 image to any social app it does not share the actual image but shares a unsupported image like "24232212456755.null". My base64 string is actually a real image I have tested it by converting base64 string to an image online.

**Comment by Sanan4li** [comment]
> I am having the same issue. When I tries to share base64 image to any social app it does not share the actual image but shares a unsupported image like "24232212456755.null". My base64 string is actually a real image I have tested it by converting base64 string to an image online.

I solved it by correcting the format " url: "data:image/jpeg;base64,"+uri,  "
I have been using jpg instead of jpeg as it was said "extension name" in docs.
