### ISSUE TITLE
Use shareSingle to send MMS via default messaging app

### ISSUE THREAD

**Issue by dcanora** [react-native-community/react-native-share#422]
**Feature request**:  Expand shareSingle capability to include launch into the default messaging app to send an MMS message (with image) on ios and Android.

_*edit: reworded as a feature request._

**Comment by jgcmarins** [comment]
@dcanora could you take a look at this PR: https://github.com/react-native-community/react-native-share/pull/428 and check if it address your feature request?
I would be awesome if you try to run this PR on a living example.
Thanks in advice.

**Comment by dcanora** [comment]
This looks like it does address the request - does it support Android and iOS?  I can definitely try it out on Android if it gets merged (I'm working on Android first, but will also implement on iOS).  Thanks!

**Comment by jgcmarins** [comment]
We did a new release, can you try it? v1.2.0.
Thank you.

**Comment by Mudassirhasan** [comment]
Hey, did anybody find the solution to this? @dcanora

**Comment by dcanora** [comment]
@Mudassirhasan - IIRC I worked around it and moved on. I missed the last post from @jgcmarins about v1.20... it looks like it was fixed it but I'm sorry I cannot confirm.
