### ISSUE TITLE
message share via facebook

### ISSUE THREAD

**Issue by kalraneeraj24550** [react-native-community/react-native-share#423]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
when i share throught facebook it should share my message too 

### Actual behaviour
but it only send link

### Environment
- **React Native version**: 0.57.5
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc

### react-native-share
**Version**: npm version or "master"
react-native-share": "^1.1.3

it only share link not text message

**Comment by matheusnascgomes** [comment]
Same issue

**Comment by kalraneeraj24550** [comment]
i am able to share message when i pass the property "quote". 
@matheusnascgomes  sir, do you know how to share text message via messanger in react-native

**Comment by matheusnascgomes** [comment]
@kalraneeraj24550  What do you mean by "property quote"? I keep up with this issue.
By the way, it's everything is working fine on share text message via messanger.

**Comment by kalraneeraj24550** [comment]
i  used this.
 shareViaFbLinkWithShareDialog() {
        const shareLinkContent1 = {
            contentType: 'link',
            quote: `code is:= ${this.state.code}`,
            contentUrl: 'https://google.com',
            contentDescription: 'Wow, check out this great site!'
        };
        ShareDialog.canShow(shareLinkContent1)
            .then((canShow) => {
                if (canShow) {
                    return ShareDialog.show(shareLinkContent1);
                }
            }
            ).then((error) => {
                    console.log('Share fail with error: ' + error);
                }
            ).catch(() => {
                this.setState({ 
                    alertVisible: true,
                    errorMessageText: 'Could not share using facebook'
                   });
            });
        }

**Comment by kalraneeraj24550** [comment]
sir .could you plz guide me how to share text msg via messanger . am begging . plz guide me @matheusnascgomes

**Comment by kalraneeraj24550** [comment]
sir, can you plz share me your code that how to send tex message via messanger plzzz

**Comment by Juliocbr** [comment]
Has anyone found a solution?

**Comment by kalraneeraj24550** [comment]
@Juliocbr  mam, do you know how to share text message via messanger in react-native.? can you plz help me

**Comment by Juliocbr** [comment]
@kalraneeraj24550 can use this plugin or the official react native solution https://facebook.github.io/react-native/docs/share

**Comment by kalraneeraj24550** [comment]
mam
![screenshot from 2018-12-13 18-20-53](https://user-images.githubusercontent.com/44640902/51014015-a7b7f880-158b-11e9-9576-4030322589b2.png)
in my app there is seperate single share option of messanger.

**Comment by jgcmarins** [comment]
@kalraneeraj24550 could you take a look at this PR: https://github.com/react-native-community/react-native-share/pull/428 and check if it address your feature request?
It would be awesome if you try to run this PR on a living example.
Thanks in advice.

**Comment by BaderSerhan** [comment]
@Juliocbr the message doesn't show also if we share through FB SDK
