### ISSUE TITLE
message is not shared in facebook and messenger if I share the url

### ISSUE THREAD

**Issue by Juliocbr** [react-native-community/react-native-share#425]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Sharing base64 image string (url) and message through messenger and facebook.

### Actual behaviour
Only the url is shared and not the message in messenger, facebook. In whatsapp works well. But if I share only the message and not the url with the base64 image string then the message if it is shared on facebook and messenger.

### Environment
- **React Native version**: 0.55
- **React Native platform + platform version**: Android 8.0

### react-native-share
**Version**: 1.1.3

Example:
`let imgBase64;

      RNFetchBlob
        .config({
          fileCache: true,
        })
        .fetch('GET', img.url)
        .then(resp => resp.readFile('base64')).then((base64Data) => {
          if (base64Data.charAt(0) === '/') imgBase64 = 'data:image/jpeg;base64,' + base64Data;
          else if (base64Data.charAt(0) === 'i') imgBase64 = 'data:image/png;base64,' + base64Data;
          else console.info('image extension not supported');

          const shareOptions = {
            message:  event.name + '? TIckets here: -> ' + event.url,
            url: imgBase64,
          };
      
          Share.open(shareOptions)
            .then(() => {})
            .catch((err) => { console.error('error share event', err); });
        });
`

**Comment by jgcmarins** [comment]
duplicated https://github.com/react-native-community/react-native-share/issues/423
