### ISSUE TITLE
[android] Cannot share using productflavors

### ISSUE THREAD

**Issue by almorak** [react-native-community/react-native-share#427]
### Steps to reproduce
1. Create a project and use this library.
2. build the project with the productflavor.
**the applicationId is different from the default one.
default id : com.xxxx

following is the settings:
    productFlavors {
        client {
            minSdkVersion 16
            applicationId 'com.aaa.bbb'
            targetSdkVersion 25
            resValue "string", "build_config_package", "com.aaa.bbb"
            dimension 'app'
        }
3.Build & install it, try to share a image. 
Its show the following error at android studio Logcat.
**Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference**

If not use the productFlavors, it works fine.

"dependencies": {
    "react": "^16.2.0",
    "react-native": "^0.53.0",
    "react-native-share": "^1.1.1",
     ...

**Comment by evanjmg** [comment]
I have the same issue. I cannot use this library unless this is resolved

**Comment by jgcmarins** [comment]
@evanjmg do you have a reproducible repo?

**Comment by evanjmg** [comment]
I figured out my issue - Seems my provider was wrong as I'm using product flavors. If you use react native config - no envs need to be added. It automatically adds the ID to your envs and you can just use it like so:
```
  @Override
  public String getFileProviderAuthority() {
    return BuildConfig.APPLICATION_ID + ".provider";
  }
``` 
@jgcmarins I would close this and use my solution as the correct fix - perhaps add the recommendation to the readme? I saw this solution in https://github.com/react-native-community/react-native-share/pull/210 and it was a sufficient fix! So feel free to close this

**Comment by jgcmarins** [comment]
@evanjmg great to know!
Feel free to add any comments to #210 so we can merge it.
Thanks!
