### ISSUE TITLE
Unable to share mp4 to instagram on ios 

### ISSUE THREAD

**Issue by ingviso** [react-native-community/react-native-share#429]
### Steps to reproduce
1. Have mp4 video on phone
2. Call Share.open with the mp4 file
3. See instagram as option in sharing activites on ios

### Expected behaviour
Being able to see instagram as sharing options in general ios sharing options

### Actual behaviour
All other "activities" in sharing options are shown gmail, facebook etc..., instagram is missing.

### Environment
- **React Native version**: 0.55.2
- **React Native platform + platform version**: iOS 12.0

### react-native-share
**Version*1.1.3*: npm version

**Comment by jgcmarins** [comment]
is there any error message?

**Comment by jgcmarins** [comment]
looks like instagram does not support mp4 all the time: https://www.google.com/search?q=does+instagram+support+mp4

**Comment by hsuchil** [comment]
I'm running into this, are you passing a message as part of your sharing options?
I've noticed that if I remove the message, sharing mp4s to Instagram works fine.

**Comment by jgcmarins** [comment]
is it happening on both platforms?

**Comment by ingviso** [comment]
no only on ios, taking out the message fixed the issue.

**Comment by hsuchil** [comment]
Same, I'm only seeing this on iOS

**Comment by webmasterdragon** [comment]
Same issue on ios

**Comment by jgcmarins** [comment]
We did a new release, can you try it? v1.2.0.
Thank you.

**Comment by rdonerTechtonic** [comment]
With the new release (v1.2.1) and the previous version I used (v1.1.3), I have been unable to share videos to certain social accounts on iOS including Facebook, Twitter, and Instagram. However, I do see Slack, email, and messaging. Furthermore, sharing photos and sharing on android allows me to see all of these social apps. Is there an issue with sharing to these accounts specifically for video on iOS?
