### ISSUE TITLE
React-Native-Share ignores set orientation

### ISSUE THREAD

**Issue by MichaelHancock** [react-native-community/react-native-share#43]
In the manifest.xml I have set the orientation of my application to be portrait. 
`android:screenOrientation="portrait"`
But upon opening the RN-share dialog the app responds to the orientation of the device until the dialog is closed. This causes visual glitches in apps that are not responsively designed.

![screen shot 2016-08-02 at 16 31 54](https://cloud.githubusercontent.com/assets/10632072/17334709/21ba0c94-58cf-11e6-8025-75bb19ab947d.png)

**Comment by enieber** [comment]
what is the version not work this @MichaelHancock ?

**Comment by enieber** [comment]
this will close because not response
