### ISSUE TITLE
[Android] Unable to share files on the internal storage

### ISSUE THREAD

**Issue by a-koka** [react-native-community/react-native-share#431]
### Steps to reproduce
I'm using `react-native-fs` to download files to the local internal storage. Using such a file with a `file://` url works great on iOS but fails on Android. Looks like the filepath is being tampered with and Android is unable to find the file.

**URL from `react-native-fs`**
`file:///data/user/0/com.myapp/files/myapp/art/invitation.jpg`

**Error**
`Failed to find configured root that contains /data/data/com.myapp/files/myapp/art/invitation.jpg`

### Environment
- **React Native version**: 0.57.8
- **React Native platform + platform version**: Android 8.0

### react-native-share
**Version**: 1.1.3

**Comment by jgcmarins** [comment]
hello @a-koka 
could you please check if our troubleshooting section can help: https://github.com/react-native-community/react-native-share#troubleshooting
?
thanks!

**Comment by a-koka** [comment]
Thanks for following up @jgcmarins. I did read the documentation and it's unclear as to why my issue is happening. I have a simple repository that recreates the problem. As you'll notice, the same code works flawlessly on iOS but not on Android. Something's not quite working right with internal storage files.

`git clone https://akbn@bitbucket.org/akbn/share-failure.git`

**Comment by jgcmarins** [comment]
maybe it is something related to react-native-fs + react-native-share

**Comment by mikehardy** [comment]
It looks to me like your configured / allowed paths for the FileProvider in Android are straight from the documentation: https://bitbucket.org/akbn/share-failure/src/57be70939f19875efaaa44203c83725460e5e322/android/app/src/main/res/xml/filepaths.xml?at=master&fileviewer=file-view-default

But, for instance, if you are trying to share from 
`Failed to find configured root that contains /data/data/com.myapp/files/myapp/art/invitation.jpg`

Then you would need the directory that contains the file (`Failed to find configured root that contains /data/data/com.myapp/files/myapp/art/`) to be in the file paths if I understand correctly.

I would watch the output of logcat carefully and you'll probably see security / permissions errors until that is correct, as Android is rightfully saying no - you can't share a file from a directory that you haven't allowed for sharing. 

It's a bit heavy to recommend the full Android Studio download just to watch logcat, but I can at least recommend it as a sure way to easily watch the logs, if you're not familiar with watching logcat from and android device/emulator: https://developer.android.com/studio/debug/am-logcat#running

**Comment by a-koka** [comment]
Thanks again. I will dig into this further and report back.

**Comment by jgcmarins** [comment]
Great!
@a-koka feel free to open a PR improving README \o/

**Comment by a-koka** [comment]
Done! #432

**Comment by anastely** [comment]
@a-koka hey, can you give an explanation this code what do exactly and what's the difference between it and in the documentation.
_Thanks in advance_

```

<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path path="Download/" name="myExternalImages" />
    <files-path path="myInternalDir/" name="myInternalImages" />
</paths>
```
