### ISSUE TITLE
Could not find method google() 

### ISSUE THREAD

**Issue by pramodkumar005** [react-native-community/react-native-share#437]
### Steps to reproduce
1.Install the react-native-share
2.Link react-native-share
3.react-native run-android

### Expected behaviour
Should build without error

### Actual behaviour
Getting Error---
Could not find method google() for arguments [] on repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.

### Environment
- **React Native version**: 16.3.0-alpha.1 
- **React Native platform + platform version**: Android

### react-native-share
**Version**: 1.1.3

<img width="666" alt="2" src="https://user-images.githubusercontent.com/11612240/51792000-8ed95500-21d1-11e9-9e61-d8b7a6c1149b.png">

**Comment by mikehardy** [comment]
A search shows many answers for this online as top results. Upgrade gradle to at least 4. Additionally it appears you have quoted a reaction version number, not a react native one.

**Comment by jgcmarins** [comment]
We did a new release, can you try it? v1.2.0.
Thank you.
