### ISSUE TITLE
How to use simple share success callback ?

### ISSUE THREAD

**Issue by dc198689** [react-native-community/react-native-share#44]
Hello, i success to share through the whatsapp, but i don't know how to use the callback,
because i want use success callback to close my modal box. thanks very much.

`Share.open(shareOptions);`

**Comment by EstebanFuentealba** [comment]
Hi

```javascript

Share.open(shareOptions).then((info) => {
  //  ok close 
}).catch((err) => {
  //  error close
});

```

**Comment by basdvries** [comment]
@EstebanFuentealba does that work for ios and android?

**Comment by asciiman** [comment]
@EstebanFuentealba Is there something similar for shareSingle()?  Nothing seems to be fired when I try:

```
Share.shareSingle(shareOptions).then((info) => {
  //  ok close 
}).catch((err) => {
  //  error close
});
```

**Comment by shafips** [comment]
Yeah! same issue here... :(
Nothing is firing

**Comment by suryakant-t-yadav** [comment]
even I am Facing this error. 
have any one got the call back after successfully post or error post 
mine code is 

Share.shareSingle(Object.assign(shareOptions, {"social": "twitter"})).catch((err) => {
                if (err) {
                    console.log("TWITTER::::" + err + "::::")
                } else {
                    console.log("TWITTER::::" + "SUCCESS" + "::::");
                }
            })
