### ISSUE TITLE
Multiple files sharing in android is not working

### ISSUE THREAD

**Issue by kiritnim** [react-native-community/react-native-share#440]
### i am getting below error 
error: 'Attempt to invoke interface method \'int android.database.Cursor.getColumnIndexOrThrow(java.lang.String)\' on a null object reference'

### Actual behaviour

sendData =[ 'file:///storage/emulated/0/Download/il2pfyaphtduzjrlsan3.jpg',
      'file:///storage/emulated/0/Download/il2pfyaphtduzjrlsan3.jpg',
      'file:///storage/emulated/0/Download/dxvdnt1ks4oevqzbbays.jpg',
      'file:///storage/emulated/0/Documents/Riddhi ShahResumeFree.pdf' ]
   let shareOptions = {
                title: "test",
                message: "Hello  " + this.state.ResumeName + ' please see below attachment.',
                // url: html,
                urls: sendData,
                // type: 'application/pdf',
                subject: Title//  for email
            };
            Share.open(shareOptions)
                .then((res) => { console.log(res, 'hello') })
                .catch((err) => { err && console.log(err, 'Error'); });
### Environment
- **React Native version**:
react-native-cli: 2.0.1
react-native: 0.56.0
### react-native-share
**Version**: npm version or "master"

**Comment by ddereszewski** [comment]
Does single share work? 
The error occour after you select the application or you don't see application selector ?

I guess the problem is before file:///storage/emulated/0/Download/il2pfyaphtduzjrlsan3.jpg is not accessable from the other application, you need to put it to the place which is shared space, it's mentioned in the manual how to do that. 

Try to save to cameraRoll and check if that works 
```js
await CameraRoll.saveToCameraRoll(
            url,
            'photo'
        );
```

**Comment by jgcmarins** [comment]
check this comment: https://github.com/react-native-community/react-native-share/issues/435#issuecomment-457819104

**Comment by rollsroyc3** [comment]
Multiple file sharing on Android is also not working for me, get the same error. Odd thing is it only happens with local files, I tried your imageBase64 code from the example and sharing those 2 images worked fine. So I could read the local file into memory, then convert it to base64, but just seems like a waste to have to convert to base64 just to send the images.

Heres a screenshot of the error:
https://www.dropbox.com/s/058jjg5a1i2f9oj/Screenshot%202019-02-08%2013.15.06.png?dl=0

Looking at the error it mentions the database cursor, and looking in the file (ShareFiles.java) that I see that android.database.Cursor is imported. The only time I see the cursor being used is in the getRealPathFromURI function, but not well versed in Java so not sure what to look for here..

**Comment by rollsroyc3** [comment]
> check this comment: [#435 (comment)](https://github.com/react-native-community/react-native-share/issues/435#issuecomment-457819104)

Read through this but not sure it helps much..

**Comment by rollsroyc3** [comment]
Comparing the function getRealPathFromURI in the files ShareFiles.java and ShareFile.java they are slightly different, not sure if that could be an issue. I'm going to try to look into it further..

**Comment by priti-nimble** [comment]
Solved issue multiple files sharing in android 👍 
**

1. please just reply this code in your android studio =
2. 1)go in react-native-share=>ShareFiles.java and replace this

**
private String getRealPathFromURI(Uri contentUri) {
String[] proj = { MediaStore.Images.Media.DATA };
CursorLoader loader = new CursorLoader(this.reactContext, contentUri, proj, null, null, null);
Cursor cursor = loader.loadInBackground();
String result = null;
if (cursor != null && cursor.moveToFirst()) {
int column_index = cursor.getColumnIndexOrThrow(MediaStore.Images.Media.DATA);
result = cursor.getString(column_index);
cursor.close();
}
return result;

}
