### ISSUE TITLE
Text/Message not visible on Social Share like Facebook, Instagram

### ISSUE THREAD

**Issue by KPS250** [react-native-community/react-native-share#441]
### Steps to reproduce
1. Share Image wiith base64 and Text/Message text on Social Apps like Instagram, Facebook 

### Expected behaviour
Image should be visible with Text/message during posting

### Actual behaviour
Image is visible but without Text/message during posting on social apps. Its works for WhatsApp, Twitter but not for Instagram, Facebook etc.

### Environment
- **React Native version**:0.57.8
- **React Native platform + platform version**: Android 5.0, etc

### react-native-share
**Version**: 1.1.3

### Link to repo (highly encouraged)
NA

Code:

Method:
shareSocial = (social) => {
        const shareOptions = {
            title: 'Caption App',
            message: 'My First Post'
            url: 'data:image/png;base64,'+ this.props.navigation.state.params.image.base64,
            subject: 'Caption App',
            social: social
        };
        Share.shareSingle(shareOptions)
    }

Method Call:
this.shareSocial(Share.Social.INSTAGRAM)

**Comment by jgcmarins** [comment]
hello,
recently we've merged this PR: https://github.com/react-native-community/react-native-share/pull/428
could you test on master branch and see if it solves?

**Comment by bharatidudhjiya** [comment]
I have same issue.
Have you solved this one ?

**Comment by quy-thi** [comment]
I face the same issue, any solution?

**Comment by quy-thi** [comment]
some social network like facebook does not support pre-filling the message for users as seen in their Policy. https://developers.facebook.com/policy/#socialplugins

**Comment by KPS250** [comment]
Thanks @quy-thi for the clarification. The issue can be closed now.

**Comment by jgcmarins** [comment]
> some social network like facebook does not support pre-filling the message for users as seen in their Policy. https://developers.facebook.com/policy/#socialplugins

Great!
