### ISSUE TITLE
Twitter shareSingle error: url

### ISSUE THREAD

**Issue by koo27** [react-native-community/react-native-share#443]
### Steps to reproduce
Run a simple 
```
Share.shareSingle(shareOptions)
                    .then((res) => { console.log(res) })
                    .catch((err) => { err && console.log(err); })
```
where shareOptions has the deafult values (title, message, urls (with base64 encoded images) and subject).
use "twitter" as social

### Expected behaviour
Open twitter app if is installed, otherwise just open the default sharing dialog.

### Actual behaviour
Nothing happens, and it throws the following error:
`{error: "url"}`

### Environment
- **React Native version**: 0.57.5
- **React Native platform + platform version**: Android 8

### react-native-share
**Version**:  "master" (currently 1.1.3)

N.B
I use the same code for: facebook, instagram, googleplus, whatsapp and email, and it works perfectly.

**Comment by koo27** [comment]
For now I just did this workaround.
I open a simple share dialog in case of error to not stuck the app if twitter button has clicked.

```
Share.shareSingle(shareOptions)
                    .then((res) => { console.log(res) })
                    .catch((err) => {
                        if (err) {
                            console.log(err);
                            Share.open(shareOptions)
                        }
                    })
```

I noticed that this happens also with Facebook and Google Plus if I don't have the apps installed on the smartphone (tested only on android so far).

**Comment by jgcmarins** [comment]
We did a new release, can you try it? v1.2.0.
Thank you.
