### ISSUE TITLE
sharing a base 64 file leaves the file in android Downloads folder

### ISSUE THREAD

**Issue by vrajeshkanna** [react-native-community/react-native-share#444]
### Steps to reproduce
1. Share any base 64 file with react-native-share
2. Check the Downloads folder for the file after share

### Expected behaviour

The file should be deleted after sharing

### Actual behaviour

File is not deleted from Downloads folder

### Environment
- **React Native version**: 0.57.8
- **React Native platform + platform version**:  Android 9.0

### react-native-share
**Version**: 1.1.3

**Comment by mikehardy** [comment]
Duplicate of #419 - it's just adding an API call during file create to fix it

**Comment by jgcmarins** [comment]
duplicated #419
