### ISSUE TITLE
While click on the share it not opening the share modal in ios 

### ISSUE THREAD

**Issue by nihp** [react-native-community/react-native-share#445]
@jgcmarins I am using react-native share and RN FetchBlob to share the remote image. But the share modal is not get opened after click on the share and the error is there is no file in that path

`{ [Error: No such file '/Users/xxxxxxxx/Library/Developer/CoreSimulator/Devices/357BD908-5069-43F2-9BBF-9DB29E2B381E/data/Containers/Data/Application/HDBWUYDUYEDUYD_DEHBDEUDBEUDB/Documents/RNFetchBlob_tmp/RNFetchBlobTmp_vso6su3qnpfvefvefwvwefvwefvewfvefv`

**Comment by jgcmarins** [comment]
take a look at [troubleshooting docs with react-native-fetch-blob](https://github.com/react-native-community/react-native-share#troubleshooting)

**Comment by nihp** [comment]
@jgcmarins It sharing the image url not the image, how can I make the image visible instead of the url

**Comment by nihp** [comment]
Here I have used RNFS to download the image. It sharing the image url not the image. Kindly refer the code snippet and let me know your inputs

```
downloadImageAndShareImage(fileUrl, type) {
   let filePath = uri;
    const name = shorthash.unique(filePath);
     const extension = (Platform.OS === 'android')? 'file://': ''
     const path = `${extension}${RNFS.CachesDirectoryPath}/${name}.png`;

     RNFS.downloadFile({fromUrl:filePath, toFile: path}).promise.then (resp => {
              let options = {
          type: type,
          url: filePath // (Platform.OS === 'android' ? 'file://' + filePath)
        };
        return Share.open(options);
      }).catch(error => {
       console.warn(error);
    });
  }
```

**Comment by jgcmarins** [comment]
it looks quite different from our [troubleshooting section](https://github.com/react-native-community/react-native-share#troubleshooting)
do you have any reproducible repo?

**Comment by nihp** [comment]
No

But I am using RNFS instead of RNFetch blob. If you have any other solution which download the remote url and save in the local library and then need to share via all social app means kindly let me know.

Clarification: If we change the [pdf file sharing example](https://github.com/react-native-community/react-native-share#share-remote-pdf-file-with-gmail--whatsapp-ios) to image means does it works or not?

**Comment by jgcmarins** [comment]
> Clarification: If we change the [pdf file sharing example](https://github.com/react-native-community/react-native-share#share-remote-pdf-file-with-gmail--whatsapp-ios) to image means does it works or not?

Yes, it should work.

**Comment by nihp** [comment]
I am getting unsupported url error while using the above. I think I have done mistake in the file path conversion. I need to convert the image. In the above example which path I need to set here DIRS.DocumentDir

Thanks 

```
Task <BE29AA21-A005-4EC8-B907-2A9ABF67AE48>.<1> finished with error - code: -1002
2019-02-18 12:16:20.095441+0530 Fashion[2234:49647] Task <BE29AA21-A005-4EC8-B907-2A9ABF67AE48>.<1> load failed with error Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x600002eb9260 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <BE29AA21-A005-4EC8-B907-2A9ABF67AE48
```

**Comment by nihp** [comment]
@jgcmarins I have fixed the above issue

If we use like this we can able to share image. 

```
downloadImageAndShareImage(fileUrl, type) {
   let filePath = uri;
    const name = shorthash.unique(filePath);
     const extension = (Platform.OS === 'android')? 'file://': ''
     const path = `${extension}${RNFS.CachesDirectoryPath}/${name}.png`;

     RNFS.downloadFile({fromUrl:filePath, toFile: path}).promise.then (resp => {
              let options = {
          type: type,
          url: filePath // (Platform.OS === 'android' ? 'file://' + filePath)
        };
        return Share.open(options);
      }).catch(error => {
       console.warn(error);
    });
  }
```

**Comment by jgcmarins** [comment]
@nihp great!
Is there something we can add to docs that will help future debug?

**Comment by nihp** [comment]
@jgcmarins 
 
From my answer we can able to share the remote url (image) by downloading it using RNFS and save in local file. 

I can able to share image in iOS via following apps

1. Instagram
2. WhatsApp
3. Tumblr
4. Facebook
5. Flickr
6. Pinterest
7. SnapChat
8. WeChat
9. Skype
10. Viber

Note: These are the apps which I can able to share the image

Thanks
