### ISSUE TITLE
The example's Simple Share Image Base 64 issues fails (undefined is not a function)

### ISSUE THREAD

**Issue by rahamin1** [react-native-community/react-native-share#448]
### Steps to reproduce
1. Install the example on android
2. Click on 'Simple Share Image Base 64'

### Environment
- **React Native version**: 0.58.4
- **React Native platform + platform version**: android 7.1

### react-native-share
**Version**: ^1.1.3

### Actual behaviour
I get the following error:
```

undefined is not a function (evaluating 'Object.keys(styles)[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()')
assembleStyles
    index.delta?platform=android&dev=true&minify=false:24797:114
createCommonjsModule
    index.delta?platform=android&dev=true&minify=false:23490:44
<unknown>
    index.delta?platform=android&dev=true&minify=false:24719:42
<unknown>
    index.delta?platform=android&dev=true&minify=false:23483:75
<unknown>
    index.delta?platform=android&dev=true&minify=false:23484:5
loadModuleImplementation
    index.delta?platform=android&dev=true&minify=false:265:14
guardedLoadModule
    index.delta?platform=android&dev=true&minify=false:153:47
metroRequire
    index.delta?platform=android&dev=true&minify=false:88:92
onUnhandled
    index.delta?platform=android&dev=true&minify=false:23029:32
onUnhandled
    index.delta?platform=android&dev=true&minify=false:23445:30
<unknown>
    index.delta?platform=android&dev=true&minify=false:26651:26
_callTimer
    index.delta?platform=android&dev=true&minify=false:26568:17
callTimers
    index.delta?platform=android&dev=true&minify=false:26775:19
__callFunction
    index.delta?platform=android&dev=true&minify=false:2481:49
<unknown>
    index.delta?platform=android&dev=true&minify=false:2238:31
__guard
    index.delta?platform=android&dev=true&minify=false:2435:15
callFunctionReturnFlushedQueue
    index.delta?platform=android&dev=true&minify=false:2237:21

```

**Comment by jgcmarins** [comment]
@rahamin1 do you know how to fix?

**Comment by rahamin1** [comment]
@jgcmarins No, I don't

**Comment by rahamin1** [comment]
But I cannot reproduce it this morning. I have other issues. I will try to resolve them myself, thank you!

**Comment by mironiasty** [comment]
I had similar issue in my code. Turns out that it is bug(?) in RN 0.58. I was getting warning from `rn-share` but it could not be displayed correctly.

You can open `node_modules/react-native/Libraries/Promise.js` and replace:
```js
message = require('pretty-format')(error);
```
with just:
```js
message = error; // or message = error.error;
```
you will then get proper error from `react-native-share` that will tell you what is wrong.

**Comment by rahamin1** [comment]
Thanks much, @mironiasty 

The error I got is the one discussed here: https://github.com/react-native-community/react-native-share/issues/270

As suggested there, I will try to perform manual installation.

**Comment by jgcmarins** [comment]
@mironiasty which message did you get? Is this something related to react-native-share?
maybe we should add something to docs?

**Comment by rahamin1** [comment]
I gave a reference to it:
https://github.com/react-native-community/react-native-share/issues/270

**Comment by mironiasty** [comment]
@jgcmarins No need to update docs. I was just missing one param to `shareSingle` (which generate fully expected warning ;) ).

**Comment by rahamin1** [comment]
The solution in my case (android) was to perform manual installation (https://github.com/react-native-community/react-native-share#Android-Install) instead of `react-native link react-native-share`
