### ISSUE TITLE
crashes in release and works in debug

### ISSUE THREAD

**Issue by ankithtv** [react-native-community/react-native-share#450]
"react-native": "0.57.7"
"react-native-share": "^1.1.3",

### Actual behaviour
works in debug mode crashes in release mode.no error caught

### Environment
- **React Native version**:0.57.7
- **Platform version**:Android 5.0, etc

### react-native-share
**Version**: 1.1.3"

**Comment by mikehardy** [comment]
Others have no problem, suggesting this is a problem with code. Do you have a minimal repo you can share with a reproduction? Are you able to reproduce the crash yourself with a clean react-native sample app and minimal react-native-share integration following the docs?

**Comment by ankithtv** [comment]
The problem was with my code it was referring react-native-share from .cache folder .I don't know much detail.renaming the referred file in .cahe folder solved my issue

**Comment by jgcmarins** [comment]
check this: https://gist.github.com/jarretmoses/c2e4786fd342b3444f3bc6beff32098d
