### ISSUE TITLE
PDF Share crashes the app on Android

### ISSUE THREAD

**Issue by alexmngn** [react-native-community/react-native-share#452]
### Steps to reproduce
1. Follow the steps from https://github.com/react-native-community/react-native-share#share-remote-pdf-file-with-gmail--whatsapp-ios using `sharePDFWithAndroid` 
2. Execute

This is my own code which is similar:
```

const share = () => {
    const uri = 'https://www.apple.com/support/products/pdf/applecare_ipod_t_and_c_11182003.pdf';
    const type = 'application/pdf';

    RNFetchBlob.config({
      fileCache: true,
    })
      .fetch('GET', uri)
      .then(resp => {
        return resp.readFile('base64');
      })
      .then(async base64Data => {
        const url = `data:${type};base64,` + base64Data;
        await Share.open({ url });
      });
  };
```

### Expected behaviour
The Share panel opens

### Actual behaviour
The application crashes with the following error:

![screenshot 2019-02-18 at 18 24 31](https://user-images.githubusercontent.com/4203845/52970343-68ab6d00-33ab-11e9-8eed-eb0c8795d699.png)

Works fine on iOS.

### Environment
- **React Native version**: 0.58
- **React Native platform + platform version**: Android 9

### react-native-share
**Version**: 1.1.3

**Comment by jgcmarins** [comment]
@alexmngn did you solve it?

**Comment by mikehardy** [comment]
Ironically, I have this exact same error message on my screen this exact moment! So I'm also curious. I'm certain it is my fault, but if you just fixed the same in your code I'd love to know ;-). Thanks

**Comment by mikehardy** [comment]
for what it's worth, I'm still working through the underlying issue but this specific error was a masking error in the react-native Promise.js Library. I don't know *why* it's causing a problem, but the pretty-print of the error in that library is causing a problem and the workaround is described here: https://github.com/react-native-community/react-native-share/issues/448#issuecomment-464749536

**Comment by mikehardy** [comment]
Predictably, me not following the docs was the root cause (https://github.com/react-native-community/react-native-share/pull/197) - users are terrible aren't they? Never following the docs ;-)

**Comment by mikehardy** [comment]
Last followup in case someone lands here from google searching for the error message. If you see `'undefined is not a function (evaluating 'Object.keys(styles)[typeof Symbol === "function" ? Symbol.iterator: "@@iterator']()]')` as an error message, it is an as-yet-unreported bug in react-native/Libraries/Promise.js where the 'pretty-print' library is messing up error message display.

If you replace the line in Promise.js that requires pretty-print with a straight print of error.message you will see the unmasked message is that there is a possible unhandled Promise rejection. 

And if you think through that, you will realize that you probably have an async function in your code, with a try/catch block that looks right, *but in your try block you forgot to actually **await** on whatever API you called that returns a Promise*. You just called the API directly with no await keyword. So the Promise rejection is not handled and you need to study Javascript async/await more to improve your skills. And you also need to fix whatever is causing the rejection but that's also a problem in your code. Good luck :-)
