### ISSUE TITLE
Instagram, Whatsapp etc App not opening on Share in iOS

### ISSUE THREAD

**Issue by KPS250** [react-native-community/react-native-share#454]
### Steps to reproduce
1. Share text with Social App like Instagram, Whatsapp

### Expected behaviour
IT should open app for sharing

### Actual behaviour
It opens up app page in AppStore even if app is installed

### Environment
- **React Native version**: 0.57
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc

### react-native-share
**Version**: npm version or "master" : 5.6.0

### Link to repo (highly encouraged)
NA

**Comment by dsemennyuk** [comment]
@KPS250 Hey yo. Add `<key>LSApplicationQueriesSchemes</key>
<array>
  <string>whatsapp</string>
  <string>mailto</string>
</array>` to your Info.plist

**Comment by webmasterdragon** [comment]
Same issue here.
```
<array>
		<string>FACEBOOK</string>
		<string>WHATSAPP</string>
		<string>TWITTER</string>
		<string>LINKEDIN</string>
		<string>INSTAGRAM</string>
		<string>GOOGLEPLUS</string>
		<string>EMAIL</string>
	</array>
```

Added like this but not showing Instagram I have already installed.

**Comment by KPS250** [comment]
Yeah I too added this and it opens up the desired app.We can close this issue.

**Comment by webmasterdragon** [comment]
This issue is related to #310

**Comment by jgcmarins** [comment]
maybe we need few improvements docs?

**Comment by Desintegrator** [comment]
same issue

**Comment by mikehardy** [comment]
@Desintegrator please confirm you have the keys set appropriately in your Plist, provide versions of plugin, react-native, ios etc. This issue was close to being resolved and the likely resolution would be a PR to instruct people about how to add keys to the plist if I understand correctly...

**Comment by Desintegrator** [comment]
@mikehardy Hello. Adding keys in Plist helped me. But now i can't share base64 pictures in iOS (works in Android)

**Comment by mikehardy** [comment]
We definitely need a PR for the docs here then as that's multiple reports of success with adding Plist entries, and this issue should be closed...

**Comment by jgcmarins** [comment]
It is the 6th step in [iOS Install](https://github.com/react-native-community/react-native-share#ios-install)

**Comment by dylan-westbury** [comment]
I needed to add `instagram-stories` to LSApplicationQueriesSchemes to get instagram opening instead of app store.

![Screen Shot 2020-07-15 at 9 25 43 am](https://user-images.githubusercontent.com/16129043/87485892-3031c080-c67d-11ea-9618-5d6311449476.png)

Debugged with iOS device logs.

![Screen Shot 2020-07-15 at 9 19 44 am](https://user-images.githubusercontent.com/16129043/87485831-0ed0d480-c67d-11ea-9a15-ddd95704d526.png)

**Comment by MateusAndrade** [comment]
Hi @dylan-westbury. I think we need to update our docs regarding of this. 🤔

**Comment by nicollasmatheus** [comment]
hey folks. any news ?

**Comment by MateusAndrade** [comment]
> hey folks. any news ?

Did you following @dylan-westbury suggestion?

**Comment by makozlo** [comment]
I tried the fix that @dylan-westbury suggested and am having no luck. When I call `Share.shareSingle(options)` the app just redirects to the App Store, even though the app is installed (Instagram in my case).

**Comment by dylan-westbury** [comment]
```
  const shareToInsta = async () => {
    if (Platform.OS === 'android') {
      const result = await PermissionsAndroid.requestMultiple([ PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE, PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE ]);
    }

    let shareOptions = {
      stickerImage: SHARE_STAR_IMAGE_BASE64,
      backgroundBottomColor: '#FEFEFE',
      backgroundTopColor: '#FEFEFE',
      social: Share.Social.INSTAGRAM_STORIES,
      failOnCancel: false,
      forceDialog: true
    };

    try {
      if (Platform.OS === 'android') {
        //TODO: bug with android -> only share background and sticker image works https://github.com/react-native-community/react-native-share/issues/808
        shareOptions.method = Share.InstagramStories.SHARE_BACKGROUND_AND_STICKER_IMAGE;
        shareOptions.backgroundImage = SHARE_STAR_IMAGE_BASE64;
      } else {
        shareOptions.method = Share.InstagramStories.SHARE_STICKER_IMAGE;
      }

      await Share.shareSingle(shareOptions);
    } catch (err) {
      Alert.alert('Could not share to Instagram');
    }
  };
```

@makozlo this is the code for share to insta stories
