### ISSUE TITLE
How to share hyperlink with text

### ISSUE THREAD

**Issue by KPS250** [react-native-community/react-native-share#455]
### Steps to reproduce
1. Need to have app link for download in shared message

Example
Shared by MyApp. Download Now [www.google.com](url)

### Expected behaviour
Need to embed hyperlink with text message

### Actual behaviour
Need to embed hyperlink with text message

### Environment
- **React Native version**: 0.57
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc

### react-native-share
**Version**: npm version or "master"

### Link to repo (highly encouraged)
NA

**Comment by danielsGit** [comment]
I have the same issue. @KPS250 have you resolved this issue? How can we add hyperlink text while sharing text to other apps?

**Comment by MateusAndrade** [comment]
> I have the same issue. @KPS250 have you resolved this issue? How can we add hyperlink text while sharing text to other apps?

Do you mean sharing a message with a link? Just appending this to the `message` dont works?

**Comment by danielsGit** [comment]
I mean hyperlink. In html, like <a /> tag.
So <a href="https://google.com">Tap here to google</a> will allows you to tap "Tap here to google" to open https://google.com

**Comment by KPS250** [comment]
@danielsGit I couldn't find such hyperlink feature in the library and did solve it by just concating the URL in share message like:

```
 shareApp = () =>{

        let  text = 'Want more buzz around your photos on Insta, Facebook, Twitter, Whatsapp posts?\n\nLet\'s make your stories get more eyeballs..\nDownload TagWag App '
        if(Platform.OS === 'android')
            text = text.concat('https://bit.ly/2XmmQ7S')
        else
            text = text.concat('http://itunes.apple.com/app/id1453977874')

        Share.share({
            subject: 'Download TagWag App Now',
            title: 'Download TagWag App Now',
            message: text,
            url:'app://tagwag',
            
        }, {
            // Android only:
            dialogTitle: 'Share TagWag App',
            // iOS only:
            excludedActivityTypes: []
        })
    }
```

**Comment by MateusAndrade** [comment]
> I mean hyperlink. In html, like a tag.
> 
> So [Tap here to google](https://google.com) will allows you to tap "Tap here to google" to open https://google.com

I think using the @KPS250  is the most reliable way. Also, i dont know if its possible to share a link using the approach that you described on Android/IOS. 

However, if you need a "special" link, you can give a look at: https://firebase.google.com/docs/dynamic-links?hl=pt-br.

**Comment by danielsGit** [comment]
Thanks guys. Btw, @KPS250 url: 'app://tagwag' is for deep link feature, yeah? Tap it to open the app. right?

**Comment by MateusAndrade** [comment]
> Thanks guys. Btw, @KPS250 url: 'app://tagwag' is for deep link feature, yeah? Tap it to open the app. right?

I think yes, but this got a different behavior on Android and IOS. Also, using dynamic links is a way to use this feature on your application.

**Comment by KPS250** [comment]
@danielsGit Yes, that's a deep link. But I couldn't see it functional on Android
