### ISSUE TITLE
Share.isPackageInstalled is not a function

### ISSUE THREAD

**Issue by igortice** [react-native-community/react-native-share#456]
Share.isPackageInstalled('com.instagram.android').then(({ isInstalled }) =>
      console.log(isInstalled)
    );

Share.isPackageInstalled is not a function

![screenshot_1551223908](https://user-images.githubusercontent.com/1306646/53454359-a771a080-3a05-11e9-9376-a6923b6026e7.png)

**Comment by jgcmarins** [comment]
hello, could please provide rn share version?
also rn version, thanks

**Comment by Soaple** [comment]
I also have a same problem on Android.

"react-native-share": "^1.1.3"

**Comment by mikehardy** [comment]
This usually indicates a failure to link or install correctly. Check the example out and try it, it should work - and if it does it proves it *can* work, so then carefully adapt what the example does into your app, following the install instructions closely. Should work

**Comment by Soaple** [comment]
> This usually indicates a failure to link or install correctly. Check the example out and try it, it should work - and if it does it proves it _can_ work, so then carefully adapt what the example does into your app, following the install instructions closely. Should work

I installed again and again, but isPackageInstalled() still does not exist.

Also, I had checked v1.1.3 source code downloaded from release link.
https://github.com/react-native-community/react-native-share/releases/tag/v1.1.3

But there is no isPackageInstalled() function.
![스크린샷 2019-04-02 오전 9 35 53](https://user-images.githubusercontent.com/34570624/55368043-d4483480-552a-11e9-9141-b22fe375ceb2.png)

PR for isPackageInstalled() was merged 21 Nov 2018.
https://github.com/react-native-community/react-native-share/pull/403

But v1.1.3 released 23 Oct 2018.
So, v1.1.3 does not have isPackageInstalled() function.
And I think new version have to be released.

**Comment by mikehardy** [comment]
Yes - if you want an unreleased feature you either have to wait or run from master. I was using master yesterday and it's fine, or at least did not seem to have any regressions

**Comment by Soaple** [comment]
> Yes - if you want an unreleased feature you either have to wait or run from master. I was using master yesterday and it's fine, or at least did not seem to have any regressions

Now, I am using master, and it works fine.
Thank you for your response.

**Comment by jgcmarins** [comment]
@Soaple it is great to hear that `master` branch is just working fine.
Thanks for your feedback, we're planning a new release soon.

**Comment by MateusAndrade** [comment]
@igortice with the last version of rn-share released on npm you can use the isPackageInstalled. :smile:
