### ISSUE TITLE
This item cannot be shared. Please select a different item when sharing on whatsApp on iOS

### ISSUE THREAD

**Issue by KPS250** [react-native-community/react-native-share#457]
### Steps to reproduce
1. Share text/image on whatsapp using shareSingle

### Expected behaviour
It must share text/image. It works well on Android but gives error on iOS

### Actual behaviour
Getting the below error:
This item cannot be shared. Please select a different item when sharing

### Environment
- **React Native version**:
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc

### react-native-share
**Version**: npm version or "master"

### Link to repo (highly encouraged)
NA

**Comment by chathuralakmal** [comment]
This is still not working.
