### ISSUE TITLE
Question: Share photo with link and description

### ISSUE THREAD

**Issue by a-koka** [react-native-community/react-native-share#460]
The following code ignores all other fields and shares only the photo. Is it not possible to pass along a URL and a description with a photo?

```
    ShareDialog.show({
      contentType: 'photo',
      photos: [{ imageUrl: 'file://some.local.file' }],
      contentUrl: 'http://some.url.com',
      contentDescription: 'Some description'
    });
```

I have the photo available on a public URL as well if another approach works better for this use case. I've failed after trying `contentType` of `link` as well.

### Environment
- **React Native version**: 0.57.8
- **React Native platform + platform version**: iOS 12.0

### react-native-share
**Version**: 1.1.3

**Comment by jgcmarins** [comment]
We did a new release, can you try it? v1.2.0.
Thank you.

**Comment by a-koka** [comment]
No luck. Works pretty much the same when it comes to Facebook sharing. As a matter of fact, `shareSingle` opens up the browser to a broken link on facebook.com.

**Comment by KingTigre** [comment]
Did you have any success?

**Comment by a-koka** [comment]
Based on my research, this is not possible. The closest I'm able to get to this is by using a Branch.io share URL.
