### ISSUE TITLE
Error occurred. Unable to share. 

### ISSUE THREAD

**Issue by watchtower314** [react-native-community/react-native-share#465]
### Steps to reproduce
1. Write a simple code that generates a pdf
2. share that pdf with WeChat on an iOS device

### Expected behaviour
pdf file should be shared through WeChat

### Actual behaviour
File doesn't get shared and I get this error:
Error occurred. Unable to share.

### Environment
- **React Native version**: 0.55.4
- **React Native platform + platform version**:  IOS 12.1.14

### react-native-share
**Version**: 5.6.0

code:
```
Share.open({
     title: 'Share',
     url: path,
     type: 'application/pdf',
     subject: 'Product PDF',
}).then((res) => {})
.catch((error) => {console.log('CORTEX: TKT_376: send(): error for some reason: '+error);})
```

path contains a url similar to this:
`/var/mobile/Containers/Data/Application/D6920592-26FC-488E-A261-91C600E4C220/Documents/AC01080299.pdf'`

**iOS**: This code works with sharing through WhatsApp, email etc, but gives an error for WeChat.
**Android**: Works fine with all shares

I have also tried creating a new blank project only with a share button, I have added 'wechat' and 'weixin' to the info.plist key LSApplicationQueriesSchemes, but still get this error.

![WhatsApp Image 2019-03-17 at 17 12 45](https://user-images.githubusercontent.com/30501647/54493535-e6df2e80-48d9-11e9-91e0-1f47e48a0db4.jpeg)

![WhatsApp Image 2019-03-17 at 17 12 46](https://user-images.githubusercontent.com/30501647/54493543-fe1e1c00-48d9-11e9-9d9d-39166c6f8f84.jpeg)

**Comment by jgcmarins** [comment]
We did a new release, can you try it? v1.2.0.
Thank you.

**Comment by yufangzhang** [comment]
Hi, I'm seeing the exact same issue on my iOS device. Has no problem with sharing on WhatsApp and iMessage etc.  My phone is running on iOS 13.1.3.

**Comment by wangru1993** [comment]
I have encountered the same problem, share pdf to WeChat, report the type of sharing that is not supported, can not share to WeChat, my iphone is running on iOS 13.1.3

**Comment by nolife08021** [comment]
any solution?
