### ISSUE TITLE
share message working for ios but not on android

### ISSUE THREAD

**Issue by bakaa99** [react-native-community/react-native-share#466]
let shareOptions = {
            title: "SHared via app",
            message: `shared via app `,
            subject: "Shared via app", //  for email
        };

 When i actually try to share this on facebook via the share menu, i works perfectly on ios, i get a nice facebook share post pop-up with the message, 

The issue is when i try to share the same with android....
There are no popups for facebook in android , it actually opens the app on share , so maybe that's why the message is ignored..??

    "react-native-share": "^1.1.3",
    "react-native": "0.58.4",

**Comment by bakaa99** [comment]
I did some research and apparently facebook changed their policy on sharing via their sharer api(That's what we are using right now). Is there gonna be any update on this. I can update it for android if someone can point me in the right direction...thx

**Comment by jgcmarins** [comment]
@bakaa99 we did a new release, can you try it? v1.2.0.
Thank you.

**Comment by brambang** [comment]
same issue in 1.2.1 version
