### ISSUE TITLE
eslint: use React Native Community rules

### ISSUE THREAD

**Issue by jgcmarins** [react-native-community/react-native-share#468]
## Describe the Feature

Looking for standardisations, we should add [`eslint-config-react-native-community`](https://github.com/facebook/react-native/tree/master/packages/eslint-config-react-native-community) to react-native-share lint rules.

## Possible Implementations

Just add the rule and run lint.

**Comment by MateusAndrade** [comment]
@jgcmarins i'm making a PR adding this, but i found that there is a eslint config on this project. Would be a problem just add react-native-community lint?

**Comment by MateusAndrade** [comment]
There is a `"lint": "eslint src --max-warnings=0"`, but i dont see thsi got any usage at the project at this moment. Would be a problem apply a : `"lint": "eslint '*.js' '**/*.js'"`?

**Comment by jgcmarins** [comment]
I think that we can replace all rules with [`eslint-config-react-native-community`](https://github.com/facebook/react-native/tree/master/packages/eslint-config-react-native-community).

**Comment by MateusAndrade** [comment]
@jgcmarins  i send a PR applying the react-native-community linter on the index.js file. But im not sure that using the lint with index.js will be a good approach. #479

**Comment by jgcmarins** [comment]
very enough for now
we can improve this later on
