### ISSUE TITLE
Giving Error: Can't send empty message

### ISSUE THREAD

**Issue by mayankmittal242** [react-native-community/react-native-share#469]
### Steps to reproduce
I have tried with these options 
Share.share({	title: "Share",
			url: "file:///storage/emulated/0/DCIM/Screenshots/Screenshot_20181214-200716_Instagram.jpg",	
			}); 
2. on sharing with whatsapp its giving error can send empty message

### Expected behaviour
should send an image through WhatsApp

### Actual behaviour
Giving error

### Environment
- **React Native version**: 0.59.2
- **React Native platform + platform version**:  Android 8.0, etc

**Comment by mikehardy** [comment]
In general the example works, so you could check it out and then just do what it does.

In specific, I have success (just now, with RN0.59.2 and Android 9 but that shouldn't matter) sharing to whatsapp via the share chooser with this code. Maybe something similar would work for you

```javascript
private async shareDeviceInfo() {
    // offer the JSON of the device info to the Android system as a shareable file
    console.log('Attempting to share device info');

    const fs = RNFetchBlob.fs;
    let dirs = RNFetchBlob.fs.dirs;
    let deviceInfoFile = dirs.DocumentDir + '/device-info-json.txt';
    let deviceInfoUrl = 'file://' + deviceInfoFile;
    try {
      await fs.writeFile(deviceInfoFile, JSON.stringify(this.state.deviceinfo), 'utf8');
    } catch (e) {
      console.log('some sort of problem writing device info out: ', e);
      return;
    }

    console.log('finished writing device info out: ' + deviceInfoUrl);

    let shareDeviceInfo = {
      title: 'KScoreApp',
      message: 'Caracteristicas del Dispositivo',
      url: deviceInfoUrl,
      type: 'text/plain',
      subject: 'Caracteristicas del Dispositivo', //  for email
    };

    try {
      // ...after the file is saved, send it to a system share intent
      await Share.open(Object.assign(shareDeviceInfo));
      console.log('successfully opened a share');
    } catch (e) {
      console.log('some sort of problem sharing device info out: ', e);
    }
  }
```

**Comment by MateusAndrade** [comment]
Im facing something similar, when i try to share a imagem with WhatsApp on Android is ok, but doing the same on Ios doenst Send the image. Just the captions, if i choose to save the image on IOS, send with Messenger it works, but with whatsapp i got this problem. 

Here is what im doing: 

```javascript  
const shareInfo = {
    title,
    message,
    url: base64Image,
    subject,
  };

  const shareResponse = ShareCustom.open(shareInfo)
    .then(res => ({ error: '', payload: res, success: true }))
    .catch(err => ({ error: (err && err.error) || 'User did not share', payload: {}, success: false }));
```

Im generating my base64 using a library that takes a ScreenShot of the desired View.

It would be related to sending a base64 directly to whatsapp? Perhaps sending the image relative path would work?

**Comment by MateusAndrade** [comment]
I found that sharing a image with base64 on some apps dont work on ios. I started to to share the archive location and was able to share on WhatsApp, Messenger without problem. =D

Perhaps, on Android you will need to add [this](https://github.com/react-native-community/react-native-share/issues/218) config on your fileprovider or AndroidManifest.xml
