### ISSUE TITLE
No enum constant cl.json.RNShareModule.SHARES.sms

### ISSUE THREAD

**Issue by rudiw** [react-native-community/react-native-share#473]
### Steps to reproduce
I just created a simple application React Native like:
```jsx
import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View, TouchableOpacity} from 'react-native';
import Share from 'react-native-share';

const instructions = Platform.select({
  :
});

type Props = {};
export default class App extends Component<Props> {
  render() {

    const shareOptions = {
      title: 'Share Title',
      message: 'Message Body',
      // url: 'https://id.yahoo.com',
      social: 'sms'
    }

    console.log('App| on render method here...');
    
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Welcome to React Native!</Text>
        <Text style={styles.instructions}>To get started, edit App.js</Text>
        <Text style={styles.instructions}>{instructions}</Text>
        <TouchableOpacity onPress={()=>{
          Share.shareSingle(shareOptions);
        }}>
          <View style={styles.instructions}>
            <Text>Simple Share</Text>
          </View>
        </TouchableOpacity>
      </View>
    );

  }//end of render

}//end of class

const styles = StyleSheet.create({
  container: {
    :
});

```

### Expected behaviour
The application should show (Sharing) SMS dialog.

### Actual behaviour
But, I got warning: 
```
Possible Unhandled Promise Rejection (id: 0):
Object {
  "error": No enum constant cl.json.RNShareModule.SHARES.sms",
}
```

If I changed value in key `social` to `email', it was working by showing Gmail Application.

### Environment
- **"react": "16.8.3**:
- **"react-native": "0.59.3"**
-**Android PIXEL_XL_API_25**
-**Windows 10**

### react-native-share
**^1.1.3**: 
npm -v: 6.4.1

I got error on image...

Thank you in advance..

![image](https://user-images.githubusercontent.com/1597815/55958535-1859d880-5c93-11e9-98be-ba5397808ccb.png)

**Comment by jgcmarins** [comment]
Hello @rudiw, how was the link process?
Did you linked manually?
It looks like the problem is related to it.

**Comment by rudiw** [comment]
Hello @jgcmarins, what is the link process? I am sorry, I didn't catch your mean.
I just did:
1. `npm install react-native-share --save`
2. `react-native run-android`

**Comment by mikehardy** [comment]
It is the second of 2 steps https://github.com/react-native-community/react-native-share#mostly-automatic-install

**Comment by jgcmarins** [comment]
react-native-share has native modules which means there are native dependencies to be added to your project

**Comment by rudiw** [comment]
@jgcmarins, so what should I do to solve the problem?

**Comment by mikehardy** [comment]
@rudiw 

> It is the second of 2 steps [react-native-community/react-native-share#mostly-automatic-install](https://github.com/react-native-community/react-native-share#mostly-automatic-install)

**Comment by rudiw** [comment]
@mikehardy okay, I have run command:
`react-native link react-native-share`
but still got the same error on image..
![image](https://user-images.githubusercontent.com/1597815/56008875-f9e1f480-5d07-11e9-8993-eac0ea11b1b8.png)

**Comment by mikehardy** [comment]
I don't know what to tell you - the example works - try it, then very carefully apply what it does to your project :man_shrugging:

**Comment by rudiw** [comment]
@mikehardy that's okay... I hope I can figure out by miracle way... thank you @mikehardy 👍

**Comment by jgcmarins** [comment]
Good.
Can you try to run react-native bundle with this command: `node ./node_modules/react-native/local-cli/cli.js start --reset-cache`
and also delete the app from the simulator and reinstall it?
It is a good practice, after linking.

**Comment by jgcmarins** [comment]
Try to wrap your code with a try/catch statement.
Are you using Promise or async/await approach?

**Comment by rudiw** [comment]
Hello @jgcmarins, I still got error with run command: `node ./node_modules/react-native/local-cli/cli.js start --reset-cache`

I just run this command:
```
<TouchableOpacity onPress={()=>{
          Share.shareSingle(shareOptions);
        }}>
```

![image](https://user-images.githubusercontent.com/1597815/56469942-552f8780-646a-11e9-929a-5a30ef777c01.png)

**Comment by MateusAndrade** [comment]
@rudiw you can use npm start --reset-cache too. I will start a fresh project using the example you provided to see what can cause this issue.

**Comment by rudiw** [comment]
Here the sample of project:
https://github.com/rudiw/share-simle-react-native

@MateusAndrade @jgcmarins 

thank you in advance

**Comment by MateusAndrade** [comment]
@rudiw  i think i found that the cause of your problem is that the version you are using dont have the SMS specific version set. Its caused because the npm version was published a time ago. 

You can use the master version of this repo settinh this on your package.json:

```json
    "react-native-share": "git+https://github.com/react-native-community/react-native-share.git"
```
By doing this, you can use the master version, achieving what you want. But i dont recommend doing this on a production environment, since there may be some errors.

I write a simple function to share using SMS:

```javascript
  shareToSMS = async () => {
    const shareOptions = {
      title: 'Share via',
      message: 'some message',
      social: 'sms',
    };

    try {
      const shareRes = await Share.shareSingle(shareOptions);      
    } catch (error) {
      console.log('====================================');
      console.log(error);
      console.log('====================================');  
    }
  };
```

@jgcmarins i found that using Share.Social.SMS returns a undefined definition. This can be caused because the SMS enum wasn't set on the static of the RNShare?

```javascript
  static Social = {
    FACEBOOK: NativeModules.RNShare.FACEBOOK || 'facebook',
    PAGESMANAGER: NativeModules.RNShare.PAGESMANAGER || 'pagesmanager',
    TWITTER: NativeModules.RNShare.TWITTER || 'twitter',
    WHATSAPP: NativeModules.RNShare.WHATSAPP || 'whatsapp',
    INSTAGRAM: NativeModules.RNShare.INSTAGRAM || 'instagram',
    INSTAGRAM_STORIES: NativeModules.RNShare.INSTAGRAM_STORIES || 'instagram-stories',
    GOOGLEPLUS: NativeModules.RNShare.GOOGLEPLUS || 'googleplus',
    EMAIL: NativeModules.RNShare.EMAIL || 'email',
    PINTEREST: NativeModules.RNShare.PINTEREST || 'pinterest',
  };
```
I can try if setting the SMS const here get rid of this problem on a PR. Because on the Android code i dont found any problem, since the SMS class is defined, etc.

**Comment by rudiw** [comment]
@MateusAndrade 
I have used the master version:
![image](https://user-images.githubusercontent.com/1597815/56480245-6c5e8b80-64e3-11e9-96c3-74ef8e69f5b8.png)

And I did uninstall the application before `react-native run-android', showed up new error:
![image](https://user-images.githubusercontent.com/1597815/56480310-b0ea2700-64e3-11e9-968a-89c8d018132c.png)

for code like:
![image](https://user-images.githubusercontent.com/1597815/56480334-c9f2d800-64e3-11e9-88ed-7f7d8e498e10.png)

**Comment by mikehardy** [comment]
That's a totally different error. Looks to me like you simply don't have anything installed that has registered for the intent you sent. Try some super basic intent anything can handle (like pure text) just to make sure your intent sending code works, and if that works then you just need to make sure you actually have an app installed that takes the intent you want (or that your intent does what you think it does with content types etc)
