### ISSUE TITLE
Cannot share image with message parameter on IOS on some applications

### ISSUE THREAD

**Issue by MateusAndrade** [react-native-community/react-native-share#474]
### Steps to reproduce
I got this function to share a image that i store on my application run time(it was generated using react-native-view-shot).

```javascript
export const shareImage = async (image, message, title, subject) => {
  const shareInfo = {
    title,
    url: image,
    subject,
  };

  const shareResponse = ShareCustom.open(shareInfo)
    .then(res => ({ error: '', payload: res, success: true }))
    .catch(err => ({ error: (err && err.error) || 'User did not share', payload: {}, success: false }));

  return shareResponse;
};
```

If i pass this payload to react-native-share, i can share the image without any problem.

```javascript
  const shareInfo = {
    title,
    url: image,
    subject,
  };
```

But if i pass this payload i can share the image on some application with a message, but specifically on WhatsApp on IOS the image doesn't open on WhatsApp. :(

```javascript
  const shareInfo = {
    title,
    message,
    url: image,
    subject,
  };
```

This can be a bug with the library, or something about a specific application share option?

### Expected behaviour
Share the image on WhatsApp passing a URL and a Message.

### Actual behaviour
If i pass a message param and a URL, when i share on WhatsApp(IOS) the app dont get the photo url. But other applications works as expected.

### Environment
- **React Native version**: 0.57.7
- **React Native platform + platform version**: iOS 12.2

### react-native-share
**Version**: 1.1.3

**Comment by jgcmarins** [comment]
Thanks for letting us know. Can you dig into this problem to understand what is happening? Thanks.

**Comment by divyamantri1292** [comment]
Any update on this issue?

**Comment by mehthabt** [comment]
any update on this ?

**Comment by mikehardy** [comment]
This issue closed nearly 2 years ago has no update in the publicly visible comments no. If you discover an issue in the library that still exists somehow, it would be great to see a new issue with an example https://stackoverflow.com/help/minimal-reproducible-example and a PR that corrects it. Cheers
