### ISSUE TITLE
Share on iOS throws fatal error when user cancels share

### ISSUE THREAD

**Issue by jasonmerino** [react-native-community/react-native-share#48]
When trying to share with the following code on iOS when the user hits the Cancel button a fatal error is thrown [by this line](https://github.com/EstebanFuentealba/react-native-share/blob/master/index.js#L45).

``` js
Share.open({
    message: 'message',
    url: 'http://domain.com/page1',
    title: 'Share Page',
}).done();
```

It seems to me like this should be a `resolve` rather than a `reject` along with whether or not the user shared or not. Throwing an error because the user tapped a valid button seems a little strange to me.

This is probably more a suggestion rather than an issue, because I can easily append a `.catch()` before the `.done()`.

**Comment by nouveller** [comment]
Agreed, it's not really an error. The resolve could just return a something to indicate the user cancelled incase you wanted to action something based of it.
