### ISSUE TITLE
On Android sharing a json file does not always show mime type

### ISSUE THREAD

**Issue by PositronicBrain** [react-native-community/react-native-share#483]
In Android when sharing a file with mime type json
 ```
      Share.open({
        type: 'application/json',
        url: 'file://android_file_path/foo.json'
      })
```
The file is shared, but some messaging apps do not show the mime type (which results in the file not being handled by the correct application). For example Whatsapp and Signal do not show it. Instead Telegram works correctly.

**Comment by MateusAndrade** [comment]
Did you try omiting the type? I got  similar problem with the message and URL, when sharing a file on WhatsApp

**Comment by PositronicBrain** [comment]
Omitting the type makes the problem worse: the file path gets passed instead of the actual file.

**Comment by jgcmarins** [comment]
Hello, could you please take a look at this example and see if it helps?
https://github.com/react-native-community/react-native-share/issues/411#issuecomment-442220259
Thanks.

**Comment by PositronicBrain** [comment]
> Hello, could you please take a look at this example and see if it helps?
> [#411 (comment)](https://github.com/react-native-community/react-native-share/issues/411#issuecomment-442220259)

I had seen that issue, but it does not help. It is a workaround for a different problem, and the solution suggests using the incorrect 'text/plain'(for json)  mime type.

However out of curiosity I tried to set the mime type and the result it's the same: no mime type appears in the attached file in Whatsapp and Signal.

**Comment by MateusAndrade** [comment]
@PositronicBrain you can try the latest version please? I think someone send a pr changing mime, etc.

**Comment by JacopoKenzo** [comment]
Same problem here!

**Comment by JacopoKenzo** [comment]
Same problem here! If I set `type` to `application/json` and i'm sharing base64 data, the exported file is named (randomly) `3520963895159068.null` - the content of the file is correct tho.

**Comment by JacopoKenzo** [comment]
If I share the file url, the file takes the name from the `message` param but is limited to 15chars - file extension is `.txt` and not `.json` and file content is my full `message` param.. using version 1.2.1 on Expo ejected app sdk-32

**Comment by AlexandrDobrovolskiy** [comment]
Any updates here?
