### ISSUE TITLE
new version release

### ISSUE THREAD

**Issue by MateusAndrade** [react-native-community/react-native-share#484]
## Describe the Feature

Since the last release on npm was 6 months ago. Would be a good idea release a new version, using everything on the master? Since i started using this project, and reading some issues apparently the version on branch master is ok. But btw, it would be a good idea define a milestone before release a new version with this changes? 

## Possible Implementations

- [ ] Define a milestone, with what is needed to test before releasing a new version to npm.
- [ ] Define the changelog and breaking changes.

Since in a newbie to contributing to projects, what else would be a good idea to implement our test before releasing this version?

## Related Issues
#470

**Comment by jgcmarins** [comment]
Can someone help me with release notes? Thanks.

**Comment by MateusAndrade** [comment]
> Can someone help me with release notes? Thanks.

Sure! I can give a look at this today. We just need to pick the commits and describe the changes? We can comments the release notes on this issue.

**Comment by jgcmarins** [comment]
Commits following [our commit lint rules](https://github.com/react-native-community/react-native-share/blob/master/commitlint.config.js) will be automatically added to release notes.
Everything else won't.
It doesn't need to be that much, just list major changes and if they have any possible breaking changes.
It's also good to list everybody involved on those changes \o/

**Comment by MateusAndrade** [comment]
I run a `git log --pretty="%h - %s (%an)" v1.1.3..HEAD >> release-notes.txt` and get the following commit list:

4055990 - Implemented succeed and failed test using jest and react-native-testing-library (#408) (Vasilii)
a389cf9 - Merge pull request #495 from MateusAndrade/feature/example-md (Mateus Andrade)
9de2ff7 - Merge branch 'master' into feature/example-md (Mateus Andrade)
2ffc8ce - Adding explanation about pod install on README.MD (MateusAndrade)
f2dab69 - Adding install-pods script (MateusAndrade)
aa3a3f9 - Adding README.MD example (MateusAndrade)
47565da - Making FileProvider implementation optional (#490) (kkbhav)
9e7767c - Merge pull request #489 from mikehardy/quiet-xcode-warnings (Mateus Andrade)
f72dbe1 - chore: update iOS target to 9.0 to match react-native min version (Mike Hardy)
bb00a3f - Calling success callback at right time in Android (#482) (kkbhav)
cd231a2 - feature/updating example version (#481) (Mateus Andrade)
3849e95 - Adding react-native-community lint (#479) (Mateus Andrade)
24a1deb - Fixing some flow types on index.js on isPackageInstalled function (#476) (Mateus Andrade)
96e4bcd - Create PULL_REQUEST_TEMPLATE.md (João Marins)
d0b2a11 - Update bug_report.md (João Marins)
769bba9 - Create question.md (João Marins)
b0a2b27 - Delete ISSUE_TEMPLATE.md (João Marins)
a72deb7 - Create bug_report.md (João Marins)
c1cd252 - Create feature_request.md (João Marins)
8c77210 - Update README.md (João Marins)
266f484 - fixed error for android (#467) (bakaa99)
c1a571e - Update README.md (João Marins)
e4d8ebd - Instagram stories (#449) (Logachev Nikita)
58e3c17 - Fix docs on return file provider string (#210) (Eddie)
99f02a1 - SingleShare forceDialog option (#442) (Dawid Dereszewski)
5d53ad6 - Fix flow types for ShareSheet (#439) (Sergey)
e74c3a5 - Add sms, snapchat and messenger share feature for Android (#428) (Muhsin.K)
5fe8d5f - Update README.md, to work canOpenURL correctly (#416) (Landon)
876bf13 - DOC/FIX - message property is mandatory (#413) (libre)
03183de - expose isPackageInstalled  (#403) (Shimon Shvartsbroit)
ac72673 - add issuehunt (Sibelius Seraphini)
be8822e - Update README.md (João Marins)
67fb59e - build: fix all deprecation and lint in ShareFile(s) (#374) (Mike Hardy)
d14d349 - Delete package-lock.json (João Marins)

Do you think this is a good start? Im a newbie to changelogs, release-notes on open-source projects. Do you have another way to get something similar to this?

**Comment by mikehardy** [comment]
Nice! That looks like a great start

I would think of the audience, and what their goal is - this is for devs trying to scan to see if it affects them I think?

So I'd remove all doc references, and all merge references, and all maintainer-stuff (like "delete package-lock.json", ISSUE_TEMPLATE or PULL_TEMPLATE etc)

If I do that it looks like so:

f2dab69 - Adding install-pods script (MateusAndrade)
47565da - Making FileProvider implementation optional (#490) (kkbhav)
f72dbe1 - chore: update iOS target to 9.0 to match react-native min version (Mike Hardy)
bb00a3f - Calling success callback at right time in Android (#482) (kkbhav)
24a1deb - Fixing some flow types on index.js on isPackageInstalled function (#476) (Mateus Andrade)
e4d8ebd - Instagram stories (#449) (Logachev Nikita)
99f02a1 - SingleShare forceDialog option (#442) (Dawid Dereszewski)
5d53ad6 - Fix flow types for ShareSheet (#439) (Sergey)
e74c3a5 - Add sms, snapchat and messenger share feature for Android (#428) (Muhsin.K)
03183de - expose isPackageInstalled (#403) (Shimon Shvartsbroit)
67fb59e - build: fix all deprecation and lint in ShareFile(s) (#374) (Mike Hardy)


(while in the process I manually looked at a couple like "fixed error for android" and that one was just a README.md change even, so I deleted it)

These are the things left that I think affect library consumers.

Not sure if this is the format we'd want forever (there are automated release notes + release systems like semantic-release if changelog conventions are followed) but if I were just using this library and I was looking at this changelog, I'd feel like I knew how to handle the release

**Comment by MateusAndrade** [comment]
> Not sure if this is the format we'd want forever (there are automated release notes + release systems like semantic-release if changelog conventions are followed) but if I were just using this library and I was looking at this changelog, I'd feel like I knew how to handle the release

I think that adding the update to the example is a important too. Since the project was made form the scratch hahahaha. What do you think about this:

f2dab69 - Adding install-pods script (MateusAndrade)
47565da - Making FileProvider implementation optional (#490) (kkbhav)
f72dbe1 - chore: update iOS target to 9.0 to match react-native min version (Mike Hardy)
bb00a3f - Calling success callback at right time in Android (#482) (kkbhav)
cd231a2 - feature/updating example version (#481) (Mateus Andrade)
3849e95 - Adding react-native-community lint (#479) (Mateus Andrade)
24a1deb - Fixing some flow types on index.js on isPackageInstalled function (#476) (Mateus Andrade)
e4d8ebd - Instagram stories (#449) (Logachev Nikita)
99f02a1 - SingleShare forceDialog option (#442) (Dawid Dereszewski)
5d53ad6 - Fix flow types for ShareSheet (#439) (Sergey)
e74c3a5 - Add sms, snapchat and messenger share feature for Android (#428) (Muhsin.K)
03183de - expose isPackageInstalled (#403) (Shimon Shvartsbroit)
67fb59e - build: fix all deprecation and lint in ShareFile(s) (#374) (Mike Hardy)

I was reading about automate this process, but i dont find any good example. Do you have a example from another projects that you contribute?

**Comment by mikehardy** [comment]
This looks great to me - if anyone feels a commit is worth mentioning, it probably is :-). Not like our changelog is 2 pages, we're not overwhelming people I don't think


look at [react-native-netinfo](https://github.com/invertase/react-native-firebase/issues/1954) in general for all the react-native-community automation, @matt-oakes is building a utopia there - community-standards linting, e2e testing in CI, semantic-release etc. I believe semantic-release is what you're looking for here

**Comment by matt-oakes** [comment]
Some links for you:

* [About Semantic Release](https://semantic-release.gitbook.io).
* [The way it's configured in the NetInfo project](https://github.com/react-native-community/react-native-netinfo/pull/6/files). This has since changed slightly, but not significantly.

Speak to @Titozzz if you want to enable this as he needs to configure CircleCI and Github with the correct environment variables and permissions.

**Comment by MateusAndrade** [comment]
> Some links for you:
> 
> * [About Semantic Release](https://semantic-release.gitbook.io).
> * [The way it's configured in the NetInfo project](https://github.com/react-native-community/react-native-netinfo/pull/6/files). This has since changed slightly, but not significantly.
> 
> Speak to @Titozzz if you want to enable this as he needs to configure CircleCI and Github with the correct environment variables and permissions.

WOW! Thanks, im going to give a look at this for future releases! This looks Looks much better than generating the release notes in hand.  :grinning:

**Comment by donysukardi** [comment]
Would love to have semantic release for this library! :D

**Comment by daner06** [comment]
Do you have any estimated date for when you think you will release the new version? I look forward!

**Comment by jgcmarins** [comment]
Guys,
We gonna release a new version tomorrow.
Feel free to [DM me at Twitter](https://twitter.com/jgcmarins) for any question.

**Comment by jgcmarins** [comment]
We did it \o/
https://twitter.com/jgcmarins/status/1132688044635643904
Thanks everyone!

**Comment by MateusAndrade** [comment]
🎉🎉🎉🎉🎉🎉
