### ISSUE TITLE
Message text not populating in Facebook share dialog via SimpleShare

### ISSUE THREAD

**Issue by alyssawolejko** [react-native-community/react-native-share#485]
### Steps to reproduce
1. Pass a message & url parameter to simpleShare
2. Share to Facebook 

### Expected behaviour
Message should populate in the dialog with the url below.

### Actual behaviour
Message is not populated in the dialog when a url is provided.

### Environment
- React Native 0.57.5:
- iOS 12.2

### react-native-share
master

### Code
These only populate the url for Facebook:
```
    Share.open({
        message: 'Test Message',
        url: 'https://www.google.com',
    });
    Share.open({
        message: 'Test Message. Share this https://www.google.com',
    });
```
This populates the message field correctly (no url) for Facebook: 
```
    Share.open({
        message: 'Test Message',
    });
```

#### Screenshots: same message & url params shared to Slack vs Facebook using Simple Share

| Simple Share             |  Slack  |   Facebook  |
:-------------------------:|:-------------------------:|:-------------------------:
![IMG_1905](https://user-images.githubusercontent.com/8005760/56732123-5b538b80-672a-11e9-92fa-3004cdf00ede.JPG)  | ![IMG_1907](https://user-images.githubusercontent.com/8005760/56732124-5bec2200-672a-11e9-85b0-6d18e98d0cb1.JPG) | ![IMG_1904](https://user-images.githubusercontent.com/8005760/56732125-5bec2200-672a-11e9-9de6-691886e913e8.JPG)

**Comment by MateusAndrade** [comment]
I got a similar problem using whatsapp to Share. But my behaviour is that the image wasn't share, but the message was. Can you dig on this problem? Maybe it could be related to the library used to share on IOS. 

This happened on Android?

#474

**Comment by AnandaRafaele** [comment]
Did you solve your issue?

**Comment by nevin22** [comment]
hope this could help .. https://developers.facebook.com/policy/#socialplugins

**Comment by jgcmarins** [comment]
is it still a thing?

**Comment by MateusAndrade** [comment]
> is it still a thing?

I need to test to this on IOS, but it looks related to how facebook manages their deeplink properties. We need to document this scenarios  on a Troubleshoot section. I see a similar problem when someone tries to share a base64 on some apps

**Comment by brambang** [comment]
> is it still a thing?

yes, it's still happen in 1.2.1 version

**Comment by MateusAndrade** [comment]
> yes, it's still happen in 1.2.1 version

As far i remember i don't get this error using this version. You can try and let us know if this still a problem?

**Comment by tolik85** [comment]
I have a similar problem in WhatsApp. Sharing only url image works, but sharing message with url doesn't (only message got shared). This happens only on iOS.

Are you familiar with this issue?

**Comment by MateusAndrade** [comment]
@tolik85 I was haveing this problem. Unfortunately it look's related to a specific way on how WhatsApp handle that content. I solved that, removing the message when i was sharing a image to whatsapp. 😢

**Comment by tolik85** [comment]
@MateusAndrade So basically no way to share both image and text on WhatsApp iOS? Weird it does work on Android

**Comment by MateusAndrade** [comment]
> @MateusAndrade So basically no way to share both image and text on WhatsApp iOS? Weird it does work on Android

Until now yep, i don't found a way to pass that. Needed to set a `Platform.OS === "os"`, but maybe there is some update on the last version WhatsApp, etc. Btw, you can give a try with our master version.

**Comment by tolik85** [comment]
OK, thanks for the answer.
