### ISSUE TITLE
Conflict with rn-fetch-blob

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-community/react-native-share#486]
Version: 1.1.3

Doing the manifest changes, I get the following:

> Task :app:processDebugManifest FAILED
..../android/app/src/debug/AndroidManifest.xml Error:
        Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/filepaths) from (unknown)
        is also present at [:rn-fetch-blob] AndroidManifest.xml:43:17-55 value=(@xml/provider_paths).
        Suggestion: add 'tools:replace="android:resource"' to <meta-data> element at AndroidManifest.xml to override.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

Linking, but without doing such changes, the library just doesn't work when calling .open().

**Comment by mikehardy** [comment]
> Doing the manifest changes

Could you link the particular lines you were following? all the changes made? I think this will be a documentation change more than anything (at the moment) so precision is vital

I think there will be a PR from a contributor shortly that may make the FileProvider issue go away by default, so perhaps in the future the whole thing disappears, which would be nice as FileProvider configuration is a subtle thing in Android

**Comment by cristianoccazinsp** [comment]
Basically, I ran link.

After that, all steps from 5 and below (edit manifest, add xml file, update main class, etc.)

The issue is most likely related to rn-fetch-blob already configures its own file provider path.

**Comment by cristianoccazinsp** [comment]
Update2 / Summary: Let me summarize the issue again and what "fixed" it (extremely ugly / unreliable fix).

Doing the manifest.xml changes will FAIL if you have rn-fetch-blob installed. This is because they already export such changes in their manifest. However, if you have rn-fetch-blob installed, this means you can skip the manifest change.

However, rn-fetch-blob changes to provider_paths.xml does not include ```"<root-path name="root" path="" />"``` which is required to access some folders of the app (such as the cache folder).
So, edit node_modules/rn-fetch-blob/android/src/main/res/xml/provider_paths.xml and add the above line.

Is there a way to properly add the following change without monkey patching the rn-fetch-blob file?

**Comment by mikehardy** [comment]
yeah, tools:replace for that attribute I believe. In my opinion rn-fetch-blob should not publish that but I don't run that project. In a project I have that similarly requires a FileProvider I chose not to provide it (for these collision reasons) and simply document the requirement: https://github.com/mikehardy/react-native-update-apk#manual-steps-for-android  :man_shrugging:

**Comment by cristianoccazinsp** [comment]
@mikehardy you are right. rn-fetch-blob is also a culprit here :(

By the way, grats on making a library even better than React's own...

**Comment by mikehardy** [comment]
> By the way, grats on making a library even better than React's own...

well thank you :-), but I'll say regardless of formal ownership (official React/react-native, community, independent), there is no "them", "your" or "my", it's all "us". All the way to react/react-native main repos it's built on PRs and detailed issues from everyone (like this one). My packages in particular are based on forks from others - kind of crazy it all works but it sure does move fast so it seems to work well

**Comment by flashman2** [comment]
@mikehardy Thank you for such a great library!
It works like a charm on iOS. However, on Android I faced the same issue as @cristianoccazinsp - automatic linking simply not work for Android! Manual changes in files is required after react-native link. Also, I can confirm - current version conflicts with rn-fetch-blob.

I realise, fix could take some time. In the meantime, is it possible to add notifications to README about these problems? So that everyone know how to fix these problems.

Personally I want to thanks @cristianoccazinsp  for a fix! Saved me a lot of time!

**Comment by MateusAndrade** [comment]
> @mikehardy Thank you for such a great library!
> It works like a charm on iOS. However, on Android I faced the same issue as @cristianoccazinsp - automatic linking simply not work for Android! Manual changes in files is required after react-native link. Also, I can confirm - current version conflicts with rn-fetch-blob.
> 
> I realise, fix could take some time. In the meantime, is it possible to add notifications to README about these problems? So that everyone know how to fix these problems.
> 
> Personally I want to thanks @cristianoccazinsp for a fix! Saved me a lot of time!

You can give a try with this [fork](https://github.com/kkbhav/react-native-share). There are some changes applied on android. If it works with rn-blob, please let us know.

**Comment by jgcmarins** [comment]
It's already on master branch.

**Comment by mikehardy** [comment]
Also I want to say I have nearly nothing to do with how useful this library is - I think I improved the example so far and that's about it :-) !! Lots of contributors doing real work, and @jgcmarins as the shepherd - they get the credit for sure

**Comment by mikehardy** [comment]
For this specifically, @kkbhav is the workers - he seems to have completely fixed Android file provider conflicts with a neat trick

**Comment by flashman2** [comment]
Sure, thanks and greetings goes to all contributors! You made awesome library, guys! :-)

**Comment by cristianoccazinsp** [comment]
Sorry to bring this back up, but I'm wondering what's the current status now? Are custom providers still required? I have tried to remove my custom provider definition from the manifest but then sharing files from the internal storage won't work.

However, I also seem to be getting the following warning, even if everything works fine with the custom provider. Question is, do we need the custom provider in order to share files from the internal storage?
```
> Task :app:processReleaseManifest
/Users/cristiano/Desktop/trabajo/zinspector/mobileRN/zinspector_rn/android/app/src/main/AndroidManifest.xml:15:9-25:20 Warning:
        provider#cl.json.RNShareFileProvider@android:authorities was tagged at AndroidManifest.xml:15 to replace other declarations but no other dec
laration present
/Users/cristiano/Desktop/trabajo/zinspector/mobileRN/zinspector_rn/android/app/src/main/AndroidManifest.xml Warning:
        meta-data#android.support.FILE_PROVIDER_PATHS@android:resource was tagged at AndroidManifest.xml:0 to replace other declarations but no other declaration present
```

**Comment by mikehardy** [comment]
related to https://github.com/react-native-community/react-native-share/pull/490

**Comment by cristianoccazinsp** [comment]
Hmm, I can still find the reason for this warning to happen, I believe I have followed everything from the readme.

manifest.xml
```
<provider
  android:name="android.support.v4.content.FileProvider"
  android:authorities="${applicationId}.provider"
  android:exported="false"
  android:grantUriPermissions="true">
  <meta-data
      android:name="android.support.FILE_PROVIDER_PATHS"
      android:resource="@xml/provider_paths"
    />
</provider>

```

xml/provider_paths.xml
```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <cache-path name="cache-path" path="" />
    <external-path
        name="external_files"
        path="." 
     />
    <files-path
        name="files-path"
        path="." /> <!-- Used to access into application data files -->
</paths>
```

MainApplication.java (also implement ShareApplication
```
@Override
public String getFileProviderAuthority() {
    return BuildConfig.APPLICATION_ID + ".provider";
}
```

**Comment by jgcmarins** [comment]
I am facing this warning:
```
Task :react-native-share:processDebugManifest
~/app/node_modules/react-native-share/android/src/main/AndroidManifest.xml:8:9-18:20 Warning:
        provider#cl.json.RNShareFileProvider@android:authorities was tagged at AndroidManifest.xml:8 to replace other declarations but no other declaration present
~/app/node_modules/react-native-share/android/src/main/AndroidManifest.xml:14:13-17:52 Warning:
        meta-data#android.support.FILE_PROVIDER_PATHS@android:resource was tagged at AndroidManifest.xml:14 to replace other declarations but no other declaration present
```

**Comment by MateusAndrade** [comment]
> p

This is crashing your build?

**Comment by MateusAndrade** [comment]
> I am facing this warning:
> 
> ```
> Task :react-native-share:processDebugManifest
> ~/app/node_modules/react-native-share/android/src/main/AndroidManifest.xml:8:9-18:20 Warning:
>         provider#cl.json.RNShareFileProvider@android:authorities was tagged at AndroidManifest.xml:8 to replace other declarations but no other declaration present
> ~/app/node_modules/react-native-share/android/src/main/AndroidManifest.xml:14:13-17:52 Warning:
>         meta-data#android.support.FILE_PROVIDER_PATHS@android:resource was tagged at AndroidManifest.xml:14 to replace other declarations but no other declaration present
> ```

Maybe it can be related to: 

```xml
        <provider
            android:name=".RNShareFileProvider"
            android:authorities="${applicationId}.rnshare.fileprovider"
            android:exported="false"
            tools:replace="android:authorities"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/share_download_paths"
                tools:replace="android:resource" />
        </provider>
```

Did you tested whats happens after removing this?

**Comment by jgcmarins** [comment]
Nice. I'll give a try.

**Comment by Bilal-Abdeen** [comment]
Check out: [#399](https://github.com/react-native-share/react-native-share/issues/399#issuecomment-442029692)
