### ISSUE TITLE
Possible to set "To" field when sharing with email?

### ISSUE THREAD

**Issue by cristianoccazinsp** [react-native-community/react-native-share#487]
Is it possible to specify the to field when sharing with email? I would really love to avoid having to install a separate library just to send emails.

**Comment by MateusAndrade** [comment]
You can use the subject field

**Comment by cristianoccazinsp** [comment]
Yes, the subject just sets the email subject. I want to set the "TO" field.

**Comment by MateusAndrade** [comment]
Sorry i missundertstanding what you are asking hahahaha. I read through the android code, and unfortunalley i dont found anything about setting this options. You can give a tri [here](https://github.com/react-native-community/react-native-share/blob/master/android/src/main/java/cl/json/social/ShareIntent.java).

PRS are alaways welcome! =D
