### ISSUE TITLE
Share content one after the other

### ISSUE THREAD

**Issue by gopalrathore** [react-native-community/react-native-share#491]
I want to share images and some text but i want to share the images first and when its successful then share the text, is it possible? or any way of doing it?

**Comment by jgcmarins** [comment]
I think it is possible since share method is Promise based.

**Comment by gopalrathore** [comment]
I also thought soo but the promise is resolved as soon as i land on the sharing app (eg. Whatsapp).
So when i go back to my app there is no event to trigger to share the second content.

**Comment by jgcmarins** [comment]
And if you try to trigger when the promise resolved?
