### ISSUE TITLE
Could not resolve all files for configuration ':react-native-share:debugCompileClasspath'

### ISSUE THREAD

**Issue by idoor88** [react-native-community/react-native-share#493]
### Steps to reproduce
1. npm install --save react-native-share
2. react-native link react-native-share
3. follow instructions to do manual install and configuration
4. react-native run-andorid

### Expected behaviour
Be able to compile and run without build errors

### Actual behaviour
 A long list of errors:
Could not resolve all files for configuration ':react-native-share:debugCompileClasspath'.
> Could not resolve com.android.support:appcompat-v7:27.1.1.
  Required by:
      project :react-native-share
   > Cannot find a version of 'com.android.support:appcompat-v7' that satisfies the version constraints: 
        Dependency path 'myapp:react-native-share:unspecified' --> 'com.android.support:appcompat-v7:27.1.1'
        Constraint path 'myapp:react-native-share:unspecified' --> 'com.android.support:appcompat-v7' strictly '27.1.1' because of the following reason: debugRuntimeClasspath uses version 27.1.1
        Dependency path 'myapp:react-native-share:unspecified' --> 'com.android.support:appcompat-v7:27.1.1'
        Constraint path 'myapp:react-native-share:unspecified' --> 'com.android.support:appcompat-v7' strictly '27.1.1' because of the following reason: debugRuntimeClasspath uses version 27.1.1
        Dependency path 'myapp:react-native-share:unspecified' --> 'com.android.support:appcompat-v7:27.1.1'
        Constraint path 'myapp:react-native-share:unspecified' --> 'com.android.support:appcompat-v7' strictly '27.1.1' because of the following reason: debugRuntimeClasspath uses version 27.1.1
        Dependency path 'myapp:react-native-share:unspecified' --> 'com.android.support:appcompat-v7:27.1.1'
        Constraint path 'myapp:react-native-share:unspecified' --> 'com.android.support:appcompat-v7' strictly '27.1.1' because of the following reason: debugRuntimeClasspath uses version 27.1.1
        Dependency path 'myapp:react-native-share:unspecified' --> 'com.android.support:appcompat-v7:27.1.1'
        Constraint path 'myapp:react-native-share:unspecified' --> 'com.android.support:appcompat-v7' strictly '27.1.1' because of the following reason: debugRuntimeClasspath uses version 27.1.1
        Dependency path 'myapp:react-native-share:unspecified' --> 'com.android.support:appcompat-v7:27.1.1'
        Dependency path 'myapp:react-native-share:unspecified' --> 'com.facebook.react:react-native:0.59.6' --> 'com.android.support:appcompat-v7:28.0.0'

> Could not resolve com.android.support:support-annotations:27.1.1.
  Required by:
      project :react-native-share
   > Cannot find a version of 'com.android.support:support-annotations' that satisfies the version constraints: 
        Dependency path 'myapp:react-native-share:unspecified' --> 'com.android.support:appcompat-v7:28.0.0' --> 'com.android.support:support-annotations:28.0.0'

### Environment
info 
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
      Memory: 2.26 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.4.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-22 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.6 => 16.8.6 
      react-native: ^0.59.6 => 0.59.6 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-cn-richtext-editor: 1.0.33
      react-native-git-upgrade: 0.2.7

### react-native-share version: "^1.1.3", also tried to get from master

package.json:

  "dependencies": {
    "@babel/polyfill": "^7.4.3",
    "@babel/runtime": "^7.4.3",
    "@pigzbe/react-native-stellar-sdk": "^1.0.6",
    "autobind-decorator": "^2.1.0",
    "axios": "0.18.0",
    "ethers": "3.0.27",
    "identicon.js": "2.3.2",
    "mobx": "5.1.0",
    "mobx-react": "^5.4.3",
    "moment": "2.22.2",
    "react": "^16.8.6",
    "react-native": "^0.59.6",
    "react-native-actionsheet": "^2.4.2",
    "react-native-cached-image": "^1.4.3",
    "react-native-camera": "^2.6.0",
    "react-native-country-picker-modal": "^0.7.1",
    "react-native-dropdownalert": "^3.10.0",
    "react-native-elements": "^0.19.1",
    "react-native-gesture-handler": "^1.1.0",
    "react-native-jwt-io": "^1.0.3",
    "react-native-keyboard-aware-scroll-view": "^0.8.0",
    "react-native-linear-gradient": "^2.5.4",
    "react-native-loading-spinner-overlay": "^1.0.1",
    "react-native-modal": "6.5.0",
    "react-native-permissions": "1.1.1",
    "react-native-phone-input": "^0.2.1",
    "react-native-picker-select": "^6.1.0",
    "react-native-qrcode-svg": "^5.1.2",
    "react-native-randombytes": "^3.5.2",
    "react-native-reanimated": "^1.0.1",
    "react-native-render-html": "^4.1.2",
    "react-native-sensitive-info": "5.2.4",
    "react-native-share": "^1.1.3",
    "react-native-side-menu": "^1.1.3",
    "react-native-snackbar": "0.5.0",
    "react-native-svg": "^6.5.3",
    "react-native-table-component": "^1.2.0",
    "react-native-vector-icons": "^4.6.0",
    "react-navigation": "^2.18.2",
    "rn-fetch-blob": "^0.10.15",
    "url": "^0.11.0"
  },
  "devDependencies": {
    "@babel/core": "^7.4.3",
    "@babel/plugin-external-helpers": "^7.0.0",
    "@babel/plugin-proposal-class-properties": "^7.4.0",
    "@babel/plugin-proposal-decorators": "^7.4.0",
    "@babel/plugin-proposal-export-default-from": "^7.0.0",
    "@babel/plugin-proposal-export-namespace-from": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.4.3",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^9.0.0",
    "babel-plugin-module-resolver": "^3.2.0",
    "babel-plugin-require-context-polyfill": "^1.0.0",
    "enzyme": "3.5.0",
    "enzyme-adapter-react-16": "1.3.0",
    "eslint-config-rallycoding": "3.2.0",
    "jsdom": "12.0.0",
    "metro-react-native-babel-preset": "^0.50.0",
    "react-native-dotenv": "^0.2.0",
    "react-native-mock-render": "0.1.1",
    "react-test-renderer": "16.6.1",
    "schedule": "^0.4.0"
  },
  "jest": {
    "preset": "react-native"
  }

Also tried to retrieve from:
"react-native-share": "git+https://github.com/react-native-community/react-native-share.git",
    still got the errors.

Build.gradle file:
buildscript {
   
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "27.1.1" //27.1.1
    }
    repositories {
         google()
        jcenter()
    }
    dependencies {
        //classpath 'com.android.tools.build:gradle:3.1.4'
        classpath 'com.android.tools.build:gradle:3.3.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
         google()
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        // ADD THIS
        maven { url 'https://maven.google.com' }

        // ADD THIS
        maven { url "https://jitpack.io" }
        maven {
          // Local Maven repo containing AARs with JSC library built for Android
          url "$rootDir/../node_modules/jsc-android/dist"
        }
        
    }
}

subprojects {
    afterEvaluate {project ->
    // force libs to use recent buildtools
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion = 28  // change to match your desired version
                buildToolsVersion = "28.0.3" // ....
            }
        }
    }
}

task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}

### Link to repo (highly encouraged)
https://github.com/

**Comment by mikehardy** [comment]
Interesting - if I recall correctly react-native 0.59.6 was pulled. 0.59.5 is the actual latest react-native stable.
Your support libs are old
etc - please confirm the example works for you

**Comment by jgcmarins** [comment]
is https://github.com/react-native-community/react-native-share/issues/492 related?

**Comment by baj9032** [comment]
getting same error any solution??

**Comment by dapowell** [comment]
I have this occur with react-native 0.60.0

**Comment by D3vlin** [comment]
[Here I found a solution that has helped me](https://github.com/react-native-community/lottie-react-native/issues/504)
