### ISSUE TITLE
Unhandled JS exception: null is not an object. evaluating _reactNative.NativeModules.RNShare.FACEBOOK

### ISSUE THREAD

**Issue by vikalpjain** [react-native-community/react-native-share#494]
### Steps to reproduce
1. npm install react-native-share --save
2. react-native link react-native-share
3. Copy-paste example code in a SocialShare.js file and export 
4. Import it from another file :
`import {SocialShare} from '../../components/SocialShare';`
5. Call SocialShare:
`<View>
   <SocialShare />
</View>`

### Expected behaviour
Share icons should appear

### Actual behaviour
I am getting a null error:
![Screenshot 2019-05-07 at 4 04 30 PM](https://user-images.githubusercontent.com/1462005/57293301-f3198800-70e1-11e9-85ea-cef28d0d7571.png)

### Environment
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
      Memory: 79.52 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.14.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 26, 28
        Build Tools: 28.0.3
        System Images: android-26 | Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.4 => 0.58.4 
    npmGlobalPackages:
      react-native-cli: 2.0.1

### react-native-share
**Version**: react-native-share@1.1.3

### Link to repo (highly encouraged)
https://github.com/

**Comment by MateusAndrade** [comment]
What version are you using?

**Comment by vikalpjain** [comment]
Version: react-native-share@1.1.3



> Which version are you using?

Version: react-native-share@1.1.3

**Comment by MateusAndrade** [comment]
You can give a try with the master? There sometime since the latest release, and currently the master branch is stable and got some differences from the last release.

**Comment by vikalpjain** [comment]
Also, I am running it on iOS simulator. Hope that does not affect the behaviour.

**Comment by vikalpjain** [comment]
> You can give a try with the master? There sometime since the latest release, and currently the master branch is stable and got some differences from the last release.

Newbie questions - How do I install that branch?

**Comment by vikalpjain** [comment]
When I do npm install, won't it install master by default?

**Comment by MateusAndrade** [comment]
@vikalpjain Just add to your `package.json`:

 ```json
"react-native-share": "git+https://github.com/react-native-community/react-native-share.git"
```

**Comment by MateusAndrade** [comment]
@vikalpjain when testing features that require access to hardware, performance, etc i recomend test on a real device. Since the simulator have some differences on some cases

**Comment by vikalpjain** [comment]
Tried that,  ran react-native run-ios after that. Still same error.

**Comment by vikalpjain** [comment]
@MateusAndrade any other information I can provide you which can help you in identifying the cause.

**Comment by vikalpjain** [comment]
null is not an object (evaluating '_reactNative.NativeModules.RNShare.FACEBOOK')

<unknown>
    index.bundle?platform=ios&dev=true&minify=false:146950:49
loadModuleImplementation
    index.bundle?platform=ios&dev=true&minify=false:265:14
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:146317:62
loadModuleImplementation
    index.bundle?platform=ios&dev=true&minify=false:265:14
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:145521:33
loadModuleImplementation
    index.bundle?platform=ios&dev=true&minify=false:265:14
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:88149:62
loadModuleImplementation
    index.bundle?platform=ios&dev=true&minify=false:265:14
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:88040:57
loadModuleImplementation
    index.bundle?platform=ios&dev=true&minify=false:265:14
<unknown>
    index.bundle?platform=ios&dev=true&minify=false:1367:48
loadModuleImplementation
    index.bundle?platform=ios&dev=true&minify=false:265:14
guardedLoadModule
    index.bundle?platform=ios&dev=true&minify=false:153:47
global code
    index.bundle?platform=ios&dev=true&minify=false:147263:4

**Comment by MateusAndrade** [comment]
> @MateusAndrade any other information I can provide you which can help you in identifying the cause.

You can provide the sample code on a repo? I can clone the code and test it here. :)

**Comment by jgcmarins** [comment]
`null is not an object (evaluating '_reactNative.NativeModules.RNShare.FACEBOOK')`

probably a link problem

**Comment by vikalpjain** [comment]
Did 'unlinking' and 'linking' again. Still same issue.

**Comment by twhoff** [comment]
Re-linking may not fix the issue. For me I needed to clear out the Pods directory:

```
> cd ios
> rm -Rfd Pods
> pod install
```

Then re-build the project.

**Comment by mikehardy** [comment]
@twhoff I worked on the react-native-clean-project package recently for this very reason - my current best recommendation for these cases prior to losing any more hair is to use the most recent release with my PR in there like so `npm i react-native-clean-project && react-native clean-project-auto && cd ios && pod install`

Sparkly fresh project after that

**Comment by twhoff** [comment]
Cheers for the hot tip!

**Comment by mikehardy** [comment]
I'm going to close this as the original author hasn't followed up, and we know this works. It's not a module problem, it's an app install problem and the example shows how to do it

**Comment by kisakyegordon** [comment]
I had a similar error like @vikalpjain - After sometime i realised the issue was because i had another `react-native` app running on the same port - when i closed the other app my app ran as expected

**Comment by nkjaiswal** [comment]
I am also facing the same error. I have just imported the lib and it is failing with the same error
import Share from 'react-native-share';
