### ISSUE TITLE
Share via instagram DM's?

### ISSUE THREAD

**Issue by karanpratapsingh** [react-native-community/react-native-share#496]
Is there a way to share some text via instagram DM??

Thank you

**Comment by MateusAndrade** [comment]
> Is there a way to share some text via instagram DM??
> 
> Thank you

This option does not appear when you call the default Share option?

**Comment by karanpratapsingh** [comment]
Yes it appears then, but what if I want to share via instagram DM using my own custom component?? not the native iOS/Android component

**Comment by MateusAndrade** [comment]
> Yes it appears then, but what if I want to share via instagram DM using my own custom component?? not the native iOS/Android component

Oh, do you mean calling a specific Share. Currently on the master branch there is some a option to call Instagram Stories. Maybe you can inspect ho this works, and implement a Share to Instagram DMS. Unfortunately i dont find anything on Instagram Docs about this 😢

**Comment by karanpratapsingh** [comment]
@MateusAndrade You are right, Instagram docs are pretty old and there is no option to share via dm as of now
