### ISSUE TITLE
Bugs in Android versions

### ISSUE THREAD

**Issue by mdfateh** [react-native-community/react-native-share#497]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Environment
- **React Native version**:
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc

### react-native-share
**Version**: 1.0.25 & 1.1.3

I tried lowest version of 1.0.25 (when latest (1.1.3) version didn't work), but it only working well on Android 6 version and giving exception:

**Possible Unhandled Promise Rejection (id: 0):
Object {
  "error": "com.bytes.app.MainApplication cannot be cast to cl.json.ShareApplication",
}**

in higher android versions. The library gives the same exception for all Android versions, when using the latest version of library.

**Comment by MateusAndrade** [comment]
You can try with the master branch? There os been sometime since se release a New version. Also, the master looks stable now and almost ready for a release

**Comment by mdfateh** [comment]
@MateusAndrade Yes, I imported the cl.json.ShareApplication in MainApplication.java file. But it still gives the same exception.
Kindly cross check the issue.

**Comment by MateusAndrade** [comment]
You can provide the repo with the code?

**Comment by mikehardy** [comment]
Also, from master, try the example app. If it works, you've clearly got something local with your install/link going on. Even if it does not, it might even just be incorrect state somewhere - I've had a similar casting issue that was solved by purging all state similar to: https://github.com/pmadruga/react-native-clean-project (soon to have a [command-line plugin style](https://github.com/pmadruga/react-native-clean-project/pull/12) so you can just say "react-native clean-project" or "react-native clean-project-auto" to know you have good state, if you want to test that)
