### ISSUE TITLE
It should work as Bottom sheet.

### ISSUE THREAD

**Issue by waleedarshad-vf** [react-native-community/react-native-share#50]
I Have a scenario where i wanted to show share sheet on clicking button in child component. if i put share sheet in parent it show as bottom sheet, if i put the same in child. It show in the middle of screen where child components end. 

Is there any workaround to acheive this.

**Comment by waleedarshad-vf** [comment]
I used custom sheets instead of shareSheet and it is working well. rest of the content is yours :)

**Comment by waleedarshad-vf** [comment]
I resolved it with the mixture of https://github.com/eyaleizenberg/react-native-custom-action-sheet

but Awesome work. Thanks

**Comment by yokohama199121** [comment]
hello waleedarshad-vf! 
u can help me how do that???? 
thank you!!!
