### ISSUE TITLE
Share both url and message in LINE

### ISSUE THREAD

**Issue by binbingol** [react-native-community/react-native-share#511]
### Steps to reproduce
const shareOptions = {
            title: 'Share',
            message: 'Welcome!'),
            url: `file://${image_path}`,
            social: Share.Social,
          }
          Share.open(shareOptions)
2. Select LINE

### Expected behaviour
Within LINE, both message and url (image) should appear

### Actual behaviour
It used to be able to share both message and url (image) together. However, suddenly, it only able to share image only and no message.

### Environment
- **React Native version**: 0.59.1
- **React Native platform + platform version**: Android 9.0, etc

### react-native-share
**Version**: ^1.1.3

**Comment by ospfranco** [comment]
Same issue here, cannot share but a url and a message

**Comment by jgcmarins** [comment]
looks like we have a bug
@ospfranco would you mind to relate all issues into one describing whole problem, please?
