### ISSUE TITLE
Are you able to share a CSV file, encoded as a base64 string.

### ISSUE THREAD

**Issue by fendorio** [react-native-community/react-native-share#512]
## Ask your Question

**Platform: iOS** 

I'm trying to share a base64 representation of a CSV file's contents. What I get is the correct application open, e.g. my email client if I select Email, however there is no attachment, no reference to the CSV.

I've also saved this directly to my files, this places a file 'data' in the files directory, 0 bytes in size, i.e it's empty. 

Given the following function, which generates the CSV URL, then calls the open method on share API. 
    
    function testShare() {
        // This is the contents of the CSV
        const contents = "name,age,Lee brindley, 26";

        // Simple encoding to base64, this outputs
        // bmFtZSxhZ2UsbGVlIGJyaW5kbGV5LCAyNg==
        const encoded = convertToBase64(contents);

        // I have validated this, it is valid base64, and decodes back
        // back to the value of 'contents'

        // Construct the share URL.
       const shareUrl = `data:text/csv;base64,${encoded}`;

        // Call 'open', I select email for example, this then opens
       // the email client, with no CSV attachment!
       Share.open({
           url: shareUrl,
           type: "text/csv"
       });
    }

Any ideas? Is this achievable?

What i'm trying to achieve here is sharing a CSV file, _without_ having to write a 'physical' file to disk.

**Comment by MateusAndrade** [comment]
Try sending the CSV path using the Share. Like: 

```javascript
  const shareInfo = {
    title,
    url: your_csv,
    subject,
  };

  const shareResponse = ShareCustom.open(shareInfo);

```

**Comment by fendorio** [comment]
Thanks for the response to my question. I'm running low on time this evening but I will be back on this all day tomorrow at work, so will post back with the result of running your suggestion. 

Whether me being stupid, or I come up with a solution that differs from what's suggested, i'll come back and update the thread with the result.

**Comment by fendorio** [comment]
@MateusAndrade  Tried your suggestion, same output, which makes sense. 

Debugging continues.

**Comment by IkarosFeitosa** [comment]
I'm having the same problem on ios, I no longer run android without problems.

**Comment by fendorio** [comment]
I ended up sharing the file as the url on iOS, and base64'ing the CSV contents on android (and passing base64 representation to the url field)

**Comment by mikehardy** [comment]
on android at least you will be liable to overflow the various data exchange mechanisms between apps if shared this way (Intent Bundles only hold so much).

Either way, the easiest way to collaborate would be to make an example app similar to the one in this repo public on github so others could play with it and fork/test etc

Sounds like the original author (who just posted followup now, thanks!) worked around things though, so I'm going to close this for now, but obviously feel free to discuss + collaborate as desired

**Comment by mikehardy** [comment]
also, pull requests to the example app *in* the repo are always welcome, and help future people know how to use things successfully :-)

**Comment by fendorio** [comment]
@mikehardy Happy to do a PR with a minimal working example of what i've done, will send that along in the coming days, feel free to merge or blow away!

**Comment by Amaan630** [comment]
How did you end up getting this to work? I tried putting the CSV string into the url and it didn't work for me. (ios btw)

**Comment by Amaan630** [comment]
Nevermind, figured it out. Kind of a noob. If anyone else is having the same problem, I'll share what I found on stackoverflow, from Micah Stubbs. You need to install "react-native-fetch-blob". Then, here's the example code:

`const values = [
            ['build', '2017-11-05T05:40:35.515Z'],
            ['deploy', '2017-11-05T05:42:04.810Z']
        ];

        // construct csvString
        const headerString = 'event,timestamp\n';
        const rowString = values.map(d => `${d[0]},${d[1]}\n`).join('');
        const csvString = `${headerString}${rowString}`;

        // write the current list of answers to a local csv file
        const pathToWrite = `${RNFetchBlob.fs.dirs.DocumentDir}/data.csv`;
        console.log('pathToWrite', pathToWrite);
        // pathToWrite /storage/emulated/0/Download/data.csv
        RNFetchBlob.fs
            .writeFile(pathToWrite, csvString, 'utf8')
            .then(() => {
                Share
                    .open({ url: `file://${pathToWrite}` })
                    .then(() => {
                        setTimeout(() => {
                            RNFetchBlob
                                .fs
                                .unlink(pathToWrite)
                                .catch((err) => {
                                    console.log(err);
                                });
                        }, 500);
                    })
                    .catch(err => {
                        console.log(JSON.stringify(err));
                    });
            })
            .catch((err) => {
                console.log(err.message);
            });`

**Comment by vytautasvargonas** [comment]
@fendorio interested to see what solution you came up with
