### ISSUE TITLE
Android : Unable to get provider cl.json.RNShareFileProvider

### ISSUE THREAD

**Issue by tgensol** [react-native-community/react-native-share#515]
Hi there,

I was using your plugin for weeks, and it was working well. But today, after updating some plugins -which yours-, I am getting my Android app crashing on launch :

` Unable to get provider cl.json.RNShareFileProvider: java.lang.ClassNotFoundException: Didn't find class "cl.json.RNShareFileProvider" on path: DexPathList`

If I removed your plugin, my application works just fine. Any idea to solve this issue ? I followed the manual link installation

### Environment
- **React Native version**: 0.59.8
- **React Native platform + platform version**: Android

### react-native-share
**Version**:  1.21

Thanking you in advance

**Comment by mikehardy** [comment]
This is some sort of install failure - that class was added and should be found
Recommend installing react-native-clean-project then doing `react-native clean-project-auto` followed by a reinstalling modules and rebuilding (don't forget pod install if you use pods)

You can check to make sure it works by looking at the example in the module itself - it builds correctly

**Comment by tgensol** [comment]
Hi @mikehardy ,

Thanks for your quick reply. I tried the what you said, but I am still getting the error... Plus, It is happening on the APK from my circle.ci (which is every time from a fresh install then).

I can create the APKs, but I cannot launch them. Any idea ?

**Comment by mikehardy** [comment]
Most CIs do some sort of caching, that has tripped me up before. Not saying that's the case, just that I don't assume CI is clean unless I verify it.

All I can say is, clone the project, and run the example. It should work. If it doesn't we have a real bug, if it does run, there is something different between the example and your project, and it must be related to https://github.com/react-native-community/react-native-share/pull/490

**Comment by cassioseffrin** [comment]
@mikehardy  Have you tested in android 4.4 sdk 19? This issue is happening for me just with android4, after I started a new project with react-native init myproject.

#adb logcat *:E
`Caused by: java.lang.ClassNotFoundException: Didn't find class "cl.json.RNShareFileProvider" on path: DexPathList[[zip file "/data/app/com.prevendamovel-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.prevendamovel-1, /vendor/lib, /system/lib]]`

#My environment: 
#react-native info

> info Fetching system and libraries information...
>   Binaries:
>     Node: 11.10.0 - /usr/local/bin/node
>     Yarn: 1.13.0 - /usr/local/bin/yarn
>     npm: 6.7.0 - /usr/local/bin/npm
>     Watchman: 4.9.0 - /usr/local/bin/watchman
>   SDKs:
>     iOS SDK:
>       Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
>     Android SDK:
>       API Levels: 23, 24, 25, 26, 27, 28, 29
>       Build Tools: 27.0.3, 28.0.3
>       System Images: android-19 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
>   IDEs:
>     Android Studio: 3.4 AI-183.6156.11.34.5522156
>     Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
>   npmPackages:
>     react: 16.8.6 => 16.8.6 
>     react-native: 0.60.3 => 0.60.3 
>   npmGlobalPackages:
>     react-native-alert-async: 1.0.3
>     react-native-clean-project: 3.2.4
>     react-native-cli: 2.0.1
>     react-native-git-upgrade: 0.2.7
>     react-native-html-to-pdf: 0.8.0
>     react-native-navigation: 2.16.0
>     react-native-rename: 2.4.1
>     react-native-share: 1.1.3

**Comment by mikehardy** [comment]
Seems like it be some sort of MultiDex issue if it's Android 4 only. MultiDex goes away in Android 5 so 4 vs 5 differences are almost always MultiDex.

I just checked my autolinking/RN60 example PR #570 and it worked fine in API18 and didn't crash on API16 but did have a problem there. something isn't perfect about the fileprovider, but it isn't a ClassNotFoundException.

I'd suspect you aren't extending MultiDexApplication or similar in MainApplication, or don't have multidex enabled etc?

**Comment by cassioseffrin** [comment]
Thks @mikehardy 

I have isolated the libraries and also added this in app/build.gradle:
```
android {
    defaultConfig {
       multiDexEnabled true
    }
}
```
