### ISSUE TITLE
Crash on Android after sharing to Google Drive

### ISSUE THREAD

**Issue by elliscarvalho** [react-native-community/react-native-share#517]
### Steps to reproduce
1. Share to Google Drive using:
```
const result = await Share.open({
      message: "message",
      subject: "subject",
      title: "title"
    });
```
2. Wait for the callback
3. App crashes
Before the crash, I can see the result:
```
{
app: "com.google.android.apps.docs/com.google.android.apps.docs.shareitem.UploadMenuActivity", 
message: "com.google.android.apps.docs/com.google.android.apps.docs.shareitem.UploadMenuActivity"
}
```

### Error on logcat: 
`java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=16845, result=-1, data=Intent { dat=content://com.google.android.apps.docs.storage.legacy/enc=hwS2P-QLZXeplE6wliNceO9lduRF6MaJHht7KkEMtWX-olNpX0S5laUmKOPmMBE0NnnhjD_ZzRB0
    LS-zLUFkB4eE8DPDjGNP01YlUizxqUo3xx8b3oenNLEPzQhPYToVt1Crhw==
     launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } (has extras) }} to activity {br.com.test/br.com.test.MainActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.google.android.apps.docs.cello.data.CelloEntrySpec
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4520)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4563)
        at android.app.ActivityThread.-wrap22(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.google.android.apps.docs.cello.data.CelloEntrySpec
        at android.os.Parcel.readParcelableCreator(Parcel.java:2555)
        at android.os.Parcel.readParcelable(Parcel.java:2481)
        at android.os.Parcel.readValue(Parcel.java:2384)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2737)
        at android.os.BaseBundle.unparcel(BaseBundle.java:269)
        at android.os.BaseBundle.getString(BaseBundle.java:992)
        at android.content.Intent.getStringExtra(Intent.java:6749)
        at com.facebook.internal.CallbackManagerImpl.isPurchaseIntent(CallbackManagerImpl.java:130)
        at com.facebook.internal.CallbackManagerImpl.onActivityResult(CallbackManagerImpl.java:90)`
### Expected behaviour
Application should not crash

### Actual behaviour
Application is crashing

### Environment
- **React Native version**: 0.59.8
- **React Native platform + platform version**: Android (multiple versions)

### react-native-share
**Version**: 1.2.1

## Important
If I downgrade react-native-share version to 1.1.3, it works.

**Comment by mikehardy** [comment]
Interesting! From the class name, this looks like an example app. Could you share it on github so we can see/try?

**Comment by elliscarvalho** [comment]
actually, I changed the namespace to 'test' manually to paste it here. sorry :(

**Comment by mikehardy** [comment]
I see - maybe you could reproduce it here: https://github.com/react-native-community/react-native-share/blob/master/example/App.js#L93  ? The example should work, so if you can make it fail, we can reproduce it easily and hopefully fix

**Comment by elliscarvalho** [comment]
okay, I'll try that

**Comment by mikehardy** [comment]
@MateusAndrade the main difference, if I understand correctly, is the result handling code for android on share was altered so that results were actually obtained and passed on now.

It may be that the new code in there is not robust enough or has an error - that *seems* to be the case here but I haven't seen it myself.

As a quick bit of triage, if we had a clean reproduction, would be to wrap all that java code in a big try/catch and just log+eat the exception. My hypothesis is that it would result in an exception logged and behavior like 1.1.3.

I am not sure if it is related to #520

**Comment by jeno5980515** [comment]
Have the same issue when trying to share a base64 pdf to google drive in android.

It's working at google drive in ios and others option in android.

**Comment by bojanmitevski** [comment]
I managed to solve this issue by passing the pdf file path to the url param from sharing options.
sharePDf = async (pdfPath) => {
//Be sure that  PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE is already granted
const shareOptions = {

        url: 'file://'+pdfPath,
        mimeType: 'application/pdf',
        title: 'Pdf test'
        };

Platform.OS === 'ios' ?   
          Share.open(shareOptions)
        :
          this.sharePDFWithAndroid(pdfPath, 'application/pdf');
}

My share function for android is :

sharePDFWithAndroid(pdfPath, type) {
    const { fs, fetch, wrap } = RNFetchBlob;
      RNFetchBlob.fs.readFile(pdfPath, 'base64').then(
         base64Data => {
          base64Data = `data:${type};base64,` + base64Data;
           Share.open({ url: base64Data });
        });
    }

After a lot of research, I found out that only base64 data for pdf file can be shared using react-native-share. Is not possible to share using url with "file://...pdfPath....".

I hope that someone will find this helpfull.

This is also related to #520

**Comment by MateusAndrade** [comment]
Looking at some issues and a project that i worked recently, i found that sharing base64 on android is problematic with some applications. 

Following what @bojanmitevski said, if its possible you can share the file path without getting a similar exception on Drive, and other applications.

**Comment by bojanmitevski** [comment]
> Looking at some issues and a project that i worked recently, i found that sharing base64 on android is problematic with some applications.
> 
> Following what @bojanmitevski said, if its possible you can share the file path without getting a similar exception on Drive, and other applications.

Did you try it? According to my research, only base64 data can be used for URL params in share options to get a successful share of the file. Please let me know if you need any assistance.

**Comment by MateusAndrade** [comment]
> Did you try it? According to my research, only base64 data can be used for URL params in share options to get a successful share of the file. Please let me know if you need any assistance.

Did you mean sharing a base64? When i was working on a daily project with rn-share i faced this problem. My workaround was to share the file relative path, wich worked without any problem.

**Comment by jeno5980515** [comment]
Still having this issue with 2.0.0 version, any update?

**Comment by jeno5980515** [comment]
Find a solution.

Modify below code in social/ShareIntent.java

Change
```java
        activity.startActivityForResult(chooser, RNShareModule.SHARE_REQUEST_CODE);
```
To
```java
        activity.startActivity(chooser);
```

**Comment by jgcmarins** [comment]
@jeno5980515 awesome!
Do you mind helping us with the fix? I can help with code review.

**Comment by jeno5980515** [comment]
I think it should use startActivity for ACTION_SEND instead of startActivityForResult.

However, it will not know the user cancel it or not. It means that failOnCancel will be useless.
It works for my use case, I'm not sure it also works for others?
