### ISSUE TITLE
Android: Passing filename to base64 file.

### ISSUE THREAD

**Issue by fendorio** [react-native-community/react-native-share#519]
## Describe the Feature

Base64 file names are hard-coded. I have a requirement on android to provide a custom filename to the exported file, currently it's using a timestamp. 

## Possible Implementations

Add an optional field for passing in a filename. 

## Related Issues

I've looked over the android project, this seems simple enough to do, i'm happy to do the PR if you guys would accept. 

Need to look into the iOS side to see how that would work. 

Would you accept a PR for this on Android, or would it need to be on both to be accepted?

**Comment by mikehardy** [comment]
Hi there, I don't see why this wouldn't be something we could merge? Cross-platform is always a plus, backwards-compatibility is always a plus, adding example usage to the example and documentation are also gigantic helps in getting it to release quickly. Missing any of those bogs it down incrementally. Good luck :-)

**Comment by shiqian123** [comment]
I need!!!

**Comment by mikehardy** [comment]
@shiqian123 pull requests happily accepted
