### ISSUE TITLE
Base64 URL fails to interpret extension / mimetype

### ISSUE THREAD

**Issue by Cnordbo** [react-native-community/react-native-share#521]
### Steps to reproduce
1. Create file using react-native-fs (.csv)
2. Read the file back out with base64 (`readFile(path, "base64")`)
3. `Share.open({url: "data:text/csv;base64, <content>})`
4. Share to Google Disk

### Expected behaviour
File to be exported/uploaded with .csv extension

### Actual behaviour
`.null` as extension

### Environment
- **React Native version**: 0.59.9
- **React Native platform + platform version**: Android 9? (Api 28)

### react-native-share
**Version**: 1.2.1

Full code: 
```js
exportCsv = async () => {
    let data = this.getCsvData();
    var path = RNFS.DocumentDirectoryPath + "/MyData.csv";
    try {
      RNFS.writeFile(path, data, "utf8");
    } catch (err) {
      Alert.alert("Export failed", "Failed to write file to disk");
      return;
    }
    try {
      const content = await RNFS.readFile(path, "base64");
      Share.open({
        url: "data:text/csv;base64," + content
      });
    } catch (err) {
      console.log("Failed to share");
    }
  };
```

**Comment by mikehardy** [comment]
With a couple issues going at once, you're going to have the most success creating an example app that demonstrates it and cracking open the debugger (or console logging) yourself to step through this stuff and see exactly what's going on. These don't sound like obvious things I have a quick answer for and I'm not going to have time to step through them myself unfortunately

**Comment by Cnordbo** [comment]
I created a repository that showcases this error in its simplest form. 

https://github.com/Cnordbo/RNShare-reproduction-of-extension-error

Im unfamiliar with how to debug this in android studio / java, but I'm looking into it, will try to help out the best I can, but this is currently beyond my knowledge.

**Comment by Cnordbo** [comment]
Stepping trough the application, it seems like the error is within `android.webkit.MimeTypeMap;`
Its terrible at mimetype mapping actually. (tried several)

![image](https://user-images.githubusercontent.com/385693/59278043-928de580-8c61-11e9-8bdf-7d97bacac185.png)

Switching to `text/comma-separated-values` fixes the issue as a workaround for my case. 

I found this mimetype by looking at the `getMimeTypeFromExtension("csv")`, and so this might help others facing the same issue. 

There is some mention about a similar issue here, regarding MimeTypeMap: 
https://stackoverflow.com/questions/44667125/getmimetypefromextension-returns-null-when-i-pass-json-as-extension

- But fixing it in Android Q? Seems like it would be a big enough issue to fix in a patch for Pie and the others as well ? 

I can confirm that the issue is solved in Android Q+, and that it doesnt work with API 27 either. 
![image](https://user-images.githubusercontent.com/385693/59280239-8e63c700-8c65-11e9-8771-50fa458d648a.png)

**Comment by Cnordbo** [comment]
As this will fail for all older versions, and we are talking almost all basic types here, (text, csv, json), might i suggest setting up an internal mapper for the most common types if the call to MimeTypeMap returns `null` ? 

Mimetypes: https://www.freeformatter.com/mime-types-list.html

These numbers from October 2018 indicates that the issue will be present on a lot of systems. 
![image](https://user-images.githubusercontent.com/385693/59282389-231bf400-8c69-11e9-9ec3-35835cadfa15.png)

I can try to do a PR if the feature is wanted. 

OR - 

Is there a way to get the code for MimeTypeMap? Maybe we could throw the supported mimetypes in a wiki?

**Comment by mikehardy** [comment]
A PR like that sounds useful, but behold the power of the community: https://github.com/jshttp/mime-types :-)

So I think the PR would just be adding that dependency, and implementing the lookup in react-native-share to bind mime-types and react-native-share together?

**Comment by jameshuimin** [comment]
> Stepping trough the application, it seems like the error is within `android.webkit.MimeTypeMap;`
> Its terrible at mimetype mapping actually. (tried several)
> 
> ![image](https://user-images.githubusercontent.com/385693/59278043-928de580-8c61-11e9-8bdf-7d97bacac185.png)
> 
> Switching to `text/comma-separated-values` fixes the issue as a workaround for my case.
> 
> I found this mimetype by looking at the `getMimeTypeFromExtension("csv")`, and so this might help others facing the same issue.
> 
> There is some mention about a similar issue here, regarding MimeTypeMap:
> https://stackoverflow.com/questions/44667125/getmimetypefromextension-returns-null-when-i-pass-json-as-extension
> 
> * But fixing it in Android Q? Seems like it would be a big enough issue to fix in a patch for Pie and the others as well ?
> 
> I can confirm that the issue is solved in Android Q+, and that it doesnt work with API 27 either.
> ![image](https://user-images.githubusercontent.com/385693/59280239-8e63c700-8c65-11e9-8771-50fa458d648a.png)

Thank you. Solved my problem

**Comment by akiid777** [comment]
> 

did you solve it?
