### ISSUE TITLE
How to skip the dialog window asking whether to post to Story or Feed?

### ISSUE THREAD

**Issue by ondrej-merkun** [react-native-community/react-native-share#524]
I'm using SingleShare to post an image to Instagram. However, upon calling the method, I get a dialog window asking whether I want to share to Direct, Story, or Feed. I want to always share to Feed and not have this window show up at all. How can I do that?
Thanks in advance.

**Comment by MateusAndrade** [comment]
@merkur0 on the latest release some options was added to Share on Instagram. You can give a look at the README.MD to find If It attends your needs.

You will need to using something similar to: https://github.com/react-native-community/react-native-share/blob/master/README.md#sharesingleoptions-in-ios--android

**Comment by Elabar** [comment]
> @merkur0 on the latest release some options was added to Share on Instagram. You can give a look at the README.MD to find If It attends your needs.
> 
> You will need to using something similar to: https://github.com/react-native-community/react-native-share/blob/master/README.md#sharesingleoptions-in-ios--android

I know this is an old topic, but I am trying to achieve the similar thing, where I want it to skip the dialog as I always want to share to Stories. Can you point out what options I should use? I can't find the correct one to restrict the type.

**Comment by gustavopch** [comment]
> @merkur0 on the latest release some options was added to Share on Instagram. You can give a look at the README.MD to find If It attends your needs.
> 
> You will need to using something similar to: https://github.com/react-native-community/react-native-share/blob/master/README.md#sharesingleoptions-in-ios--android

Do you mean the `forceDialog` option? It doesn't help on what the OP asked.

**Comment by MateusAndrade** [comment]
@gustavopch do you want to share directly to Instagram Stories? You can try #600 to see if this helps you. I see that using `forceDialog` achieves a different behaviour and it only works on Android to set your option as the default.

**Comment by gustavopch** [comment]
@MateusAndrade I'm not actually using this lib; gone the manual way and implemented my own native module. The PR you linked solves half of this issue. The other half would be sharing to Feed without an intermediate action sheet.

**Comment by MateusAndrade** [comment]
> @MateusAndrade I'm not actually using this lib; gone the manual way and implemented my own native module. The PR you linked solves half of this issue. The other half would be sharing to Feed without an intermediate action sheet.

Would you mind the help us with that? New contributions are always welcome! 🎉 🎉

**Comment by gustavopch** [comment]
@MateusAndrade I won't have the time to submit a PR, but sharing directly to Instagram's Feed goes along the following on Android:
```java
final String packageName = "com.facebook.katana";
final Intent intent = new Intent(Intent.ACTION_SEND);
intent.setPackage(packageName);
intent.setClassName(packageName, "com.facebook.composer.shareintent.ImplicitShareIntentHandlerDefaultAliasCustomization");
intent.setType(type);
intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
intent.putExtra(Intent.EXTRA_STREAM, contentUri);
activity.startActivity(intent);
```
Not sure if this might break in the future though as it's not an official API. Also I don't have the iOS implementation yet.

**Comment by alinavaie** [comment]
Do you find any solution? I'm going to share on the feed directly without showing the dialog window. forceDialog is for android and not working on iOS devices.
