### ISSUE TITLE
Unable to share local file on Android 

### ISSUE THREAD

**Issue by mikeKane** [react-native-community/react-native-share#526]
### Steps to reproduce

Here is my function call to share. 

```
 var sharingURL =
      "file:///data/user/0/com.myApp/files/ji_1560855618.txt";
    console.log("opening url " + sharingURL);
    Share.open({
      title: "React Native",
      message: "Hola mundo",
      url: sharingURL,
      subject: "Share Link" //  for email
    });
```
I also check permissions before calling share and it says it is granted 
```
async askPermission() {
    console.log("asking permission");
    const granted = await PermissionsAndroid.check(
      "android.permission.READ_EXTERNAL_STORAGE"
    );
    if (!granted) {
      console.log("Permission not granted");
      const response = await PermissionsAndroid.request(
        "android.permission.READ_EXTERNAL_STORAGE"
      );
      if (!response) {
        console.log("Permission not granted & non respinse");
        return;
      }
    } else {
      console.log("Permission granted");
    }
  }
```
### Expected behaviour
Tell us what should happen
The file to be attached to an email

### Actual behaviour
Tell us what happens instead
No file is attached 

### Environment
```  React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
      Memory: 16.07 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: ^0.59.4 => 0.59.4 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
```

### react-native-share
**Version**: npm version or "master"
```
"react-native-share": "git+https://git@github.com/react-native-community/react-native-share.git",
```

**Comment by jtweaver** [comment]
Also having this issue. Is this just a bug with the most recent npm version, or has this been around for a while?

**Comment by jgcmarins** [comment]
is there any error message?

**Comment by mikeKane** [comment]
No, that's the stranger part. Permissions have been enabled. The file exists bc I load it into a string just to be sure its there. Android just doesn't attach it

**Comment by jgcmarins** [comment]
did you follow this setup: https://github.com/react-native-community/react-native-share/blob/master/README.md#adding-your-implementation-of-fileprovider
?

**Comment by mikeKane** [comment]
I am able to send files via native android with files so Id think the provider is working fine. And yes I have followed that. But thank you for your suggestion.

**Comment by johnny09003525** [comment]
it there any update for this problem?

It seems that the file cannot attached while click share

**Comment by xliank** [comment]
docs : 

Name | Type | Description
-- | -- | --
url | string | URL you want to share (you can share a base64 file url only in iOS & Android )

I will send pull request to update it. Shoud've read : 

> (only support base64 string in iOS & Android ).

**Comment by xliank** [comment]
Try remove `/` from uri

> "file://data/user/0/com.myApp/files/ji_1560855618.txt";
    console.log("opening url " + sharingURL);

**Comment by bojanmitevski** [comment]
I managed to solve this issue by passing the pdf file path to the url param from sharing options.
sharePDf = async (pdfPath) => {
//Be sure that  PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE is already granted
const shareOptions = {

        url: 'file://'+pdfPath,
        mimeType: 'application/pdf',
        title: 'Pdf test'
        };

Platform.OS === 'ios' ?   
          Share.open(shareOptions)
        :
          this.sharePDFWithAndroid(pdfPath, 'application/pdf');
}

My share function for android is :

sharePDFWithAndroid(pdfPath, type) {
    const { fs, fetch, wrap } = RNFetchBlob;
      RNFetchBlob.fs.readFile(pdfPath, 'base64').then(
         base64Data => {
          base64Data = `data:${type};base64,` + base64Data;
           Share.open({ url: base64Data });
        });
    }

After a lot of research, I found out that only base64 data for pdf file can be shared using react-native-share. Is not possible to share using url with "file://...pdfPath....".

I hope that someone will find this helpfull.

This is also related to #520

**Comment by ramonscampos** [comment]
After few days stuck in this problem, I figured out that files in cache folder are able to be shared without any problem. 
But I still waiting a solution to share files from 'files' folder.

**Comment by bojanmitevski** [comment]
> After few days stuck in this problem, I figured out that files in cache folder are able to be shared without any problem.
> But I still waiting a solution to share files from 'files' folder.

Did you try to share url with base64 data as I suggested it. With my solution I  can share the files from my app folder.

**Comment by mikeKane** [comment]
We fixed this issue by providing a sub class of Fileprovider.  We were using one instance to share logs via support but that blocked the sharing of individual files. 

Make sure the files you want to share are in the declared file provider instantiation and if you use it elsewhere you must subclass it.

**Comment by ramonscampos** [comment]
@mikeKane the file provider was setup right. I already tried do share with 'content://' in url and 'file://'..
When I use 'content' the app crashes and when I use 'file' the share goes on with no file (empty).

> > After few days stuck in this problem, I figured out that files in cache folder are able to be shared without any problem.
> > But I still waiting a solution to share files from 'files' folder.
> 
> Did you try to share url with base64 data as I suggested it. With my solution I can share the files from my app folder.

Yeah, but I have other file types to share.

**Comment by bojanmitevski** [comment]
@ramonscampos please let me know what file types you need to share? I can try to share it as well.

**Comment by ramonscampos** [comment]
.realm for example @bojanmitevski 

Another detail is that base64 conversion make file to be much larger.

**Comment by mikeKane** [comment]
Just a quick note also, we did run into an issue when we copied our file in android the buffer was too small which resulted in a file that was 0kb in size. So I would check your file by logging and opening it in java land first.

**Comment by jameshuimin** [comment]
Same problem, I want to share local XLS file, but can't share

**Comment by jameshuimin** [comment]
> is there any error message?
同样的问题，当分享到微信的时候，

提示微信：获取资源失败

**Comment by jameshuimin** [comment]
> @ramonscampos please let me know what file types you need to share? I can try to share it as well.

.xls

**Comment by jameshuimin** [comment]
> @ramonscampos please let me know what file types you need to share? I can try to share it as well.

hello。I tried to share the.xls file, but it didn't work。

import {
    writeFile,
    readFile,
    unlink,
    DocumentDirectoryPath,
    ExternalDirectoryPath,
} from 'react-native-fs'

  writeFile(file, output(wbout), 'base64')
                    .then(res => {
                        console.log(file)
                        this.readFile(filePath)
                        // resolve(file)
                    })

 readFile(filePath, "base64").then((res)=>{
       console.log(res)
        const dataUri = `data:excel/xls;base64,${res}`;
         Share.open({
            url: dataUri,
        });

**Comment by jameshuimin** [comment]
> > @ramonscampos please let me know what file types you need to share? I can try to share it as well.
> 
> hello。I tried to share the.xls file, but it didn't work。
> 
> import {
> writeFile,
> readFile,
> unlink,
> DocumentDirectoryPath,
> ExternalDirectoryPath,
> } from 'react-native-fs'
> 
> writeFile(file, output(wbout), 'base64')
> .then(res => {
> console.log(file)
> this.readFile(filePath)
> // resolve(file)
> })
> 
> readFile(filePath, "base64").then((res)=>{
> console.log(res)
> const dataUri = `data:excel/xls;base64,${res}`;
> Share.open({
> url: dataUri,
> });
I finally solved the problem of android sharing excel files.Here is the full code。
```
import XLSX from 'xlsx'
import {
    writeFile,
    readFile,
    unlink,
    DocumentDirectoryPath,
    ExternalDirectoryPath,
} from 'react-native-fs'
import { Platform } from 'react-native'
import { Toast } from '@ant-design/react-native'
import Share from 'react-native-share';


/**
 * excel
 * @param data
 * @param fileName
 */
const exportExcel = (data: Array, fileName: string) => {
    let ipt = new Promise(function(resolve, reject) {
        try {
            const output = str => str
            const path = Platform.select({
                ios: `${DocumentDirectoryPath}/`,
                android: `${ExternalDirectoryPath}/`
            })
            const fileType = 'xls'
            if (data && data.length > 0) {
                let ws = XLSX.utils.aoa_to_sheet(data)
                let wb = XLSX.utils.book_new()
                XLSX.utils.book_append_sheet(wb, ws, fileName)
                const wbout = XLSX.write(wb, {
                    type: 'base64',
                    bookType: fileType
                })
                const file = `${path}${fileName}.${fileType}`
                writeFile(file, output(wbout), 'base64')
                    .then(res => {
                        console.log(file)
                        wxShareFile(fileName, file, resolve, reject)
                        // resolve(file)
                    })
                    .catch(err => {
                        Toast.fail(err)
                        console.log(err)
                        reject(err)
                    })
            } else {
                alert('没有可分享的数据')
            }
        } catch (e) {
            console.log(e)
            reject(e)
        }
    })

    return ipt
}

const wxShareFile = async (fileName, filePath, resolve, reject) => {
    readFile(filePath,"base64").then((res)=>{
       console.log(res)
        const dataUri = `data:application/vnd.ms-excel;base64,${res}`;
         Share.open({
            url: dataUri,
        });
         // unlink(path);

    })

}



export { exportExcel }
```

**Comment by MateusAndrade** [comment]
@mikeKane you managed to solve your problem following one of the suggestions ?

**Comment by jameshuimin** [comment]
> > > is there any error message?
> > > 同样的问题，当分享到微信的时候，
> > 
> > 
> > 提示微信：获取资源失败
> 
> 你好，我也遇到了同样的问题，分享本地图片，微信提示获取资源失败，请问这个问题您是如何解决的？

我在上面贴了完整的代码，你可以看看

**Comment by imdadhussain004** [comment]
I added 
`<uses-permission tools:node="remove" android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`
In manifestFile. 
After removing it, share is working fine for me.

**Comment by liwei3927** [comment]
https://github.com/react-native-community/react-native-share/issues/808
