### ISSUE TITLE
Can't share image!

### ISSUE THREAD

**Issue by uraniumreza** [react-native-community/react-native-share#527]
### Steps to reproduce
1. Install react-native-share
2. Copy paste this code - https://github.com/react-native-community/react-native-share#example-code
3. Run; and try this `shareImage` method -
```javascript
   const shareImageBase64 = {
      title: 'React native',
      // message: 'Test 1 2 3',
      type: 'image/png',
    };

    const shareImage = (
      fileUrl = 'https://yt3.ggpht.com/a/AGF-l7-BBIcC888A2qYc3rB44rST01IEYDG3uzbU_A=s900-mo-c-c0xffffffff-rj-k-no',
      type = 'image/png',
    ) => {
      let filePath = null;
      // let fileUrlLength = fileUrl.length;
      const configOptions = { fileCache: true };
      RNFetchBlob.config(configOptions)
        .fetch('GET', fileUrl)
        .then((resp) => {
          filePath = resp.path();
          return resp.readFile('base64');
        })
        .then(async (base64Data) => {
          const imageBase64 = `data:${type};base64,${base64Data}`;
          await Share.open({ ...shareImageBase64, url: imageBase64 });
          // console.log(imageBase64, { ...shareImageBase64, url: imageBase64 });
          // remove the image or pdf from device's storage
          await RNFetchBlob.fs.unlink(filePath);
        });
    };
```

### Actual behaviour
Messenger: https://imgur.com/a6IgLTg
Whatsapp: https://imgur.com/E8PAVlh

### Environment
- **React Native version**: 0.59.9
- **React Native platform + platform version**: Android 8.1

### react-native-share
**Version**: npm version 1.2.1

**Comment by jgcmarins** [comment]
is there any error logs?

**Comment by jgcmarins** [comment]
can you try to run [example](https://github.com/react-native-community/react-native-share/tree/master/example)?

**Comment by uraniumreza** [comment]
> is there any error logs?

No, don't have any error log; And I couldn't run the example app though! @jgcmarins

**Comment by uraniumreza** [comment]
Yeah, I've tried the example app and `Share Single Image` occurs the same error!

**Comment by xliank** [comment]
Try my code :
`let Pictures= pics.map(item =>
      RNFetchBlob.config({
        fileCache: true
      })
        .fetch("GET", item.pic_url)
        .then(resp => {
          let base64s= RNFetchBlob.fs
            .readFile(resp.data, "base64")
            .then(data => "data:image/jpeg;base64," + data);
          return base64s;
        })
    );
    Promise.all(Pictures).then(completed => {
      const options = {
        title: "Share via",
        urls: completed
      };
      Share.open(options);
    });`
