### ISSUE TITLE
How to use SingleShare to open WhatsApp chat screen from My App by passing Mobile Number of user.

### ISSUE THREAD

**Issue by shubhamdeol** [react-native-community/react-native-share#531]
**What I want** is to send pdf file to my App user from my App using **Share.singleShare** function by passing user's **phone number**. In android this is done using **indent** I guess
So, Is there a way to generate share indent with user phone number, So that user directly jumps into his **whatsapp's** chat screen, with pdf attached, All user have to do is click on send button.

**Here is some code**
```javascript
  const res = await Share.shareSingle({
        url: file.uri,
        title: 'Share via',
        message: 'some message',
        type:'application/pdf',        
        social: Share.Social.WHATSAPP,
  })
```

Is there any way to pass user's **whatsApp** mobile number with this, options object which is getting passed to singleShare.

**Comment by shubhamdeol** [comment]
I have added this feature for Android only this fork: 
https://github.com/shubhamdeol/react-native-share
Now I can send message directly to user's whatsapp number:

```javascript
import Share from 'react-native-share';

const shareOptions = {
    title: 'Share via',
    message: 'some message',
    url: 'some share url',
    social: Share.Social.WHATSAPP,
    whatsAppNumber: "9199999999"  // country code + phone number
};
Share.shareSingle(shareOptions);

```

**Comment by MateusAndrade** [comment]
WOW! This looks really good @shubhamdeol. We would be happy to see this PR landing on react-native-share. :smile:

**Comment by shubhamdeol** [comment]
@MateusAndrade  Thanks. I will create a pull request soon.

**Comment by gypsicoder** [comment]
@shubhamdeol From which version we can use this feature? My react-native-share version is 1.2.1

**Comment by gypsicoder** [comment]
@shubhamdeol  On what files you have made changes for this feature?

**Comment by gypsicoder** [comment]
@shubhamdeol I have made the changes in ShareIntent.java as yours. But, it does not open the contact. I haven't tested in device yet. I have checked in emulator. Does it work in emulator? I have whatsapp in emulator. It's opening whatsapp but not opening the screen with the selected contact.

**Comment by shubhamdeol** [comment]
Hi @gypsicoder 
This is not published on npm yet, You can install this to your project using.
```yarn add pathToRepository```

**Comment by gypsicoder** [comment]
Thank you @shubhamdeol . Is there any possibility that it will be published in npm in near future?

**Comment by gypsicoder** [comment]
Hi @shubhamdeol  and @jgcmarins I have pulled the code from this repo. I have got a crash when trying to use Share.open(options) and when I didn't add the parameter 'social' in options.

I have fixed the problem myself by changing the codes in ShareIntent.java as follows:

String socialType = options.getString("social");
        if(!socialType.isEmpty()) {
            if (socialType.equals("whatsapp")) {
                String whatsAppNumber = options.getString("whatsAppNumber");
                if (!whatsAppNumber.isEmpty()) {
                    String chatAddress = whatsAppNumber + "@s.whatsapp.net";
                    this.getIntent().putExtra("jid", chatAddress);
                }
            }
        }

I think you should change that too.

**Comment by gypsicoder** [comment]
@jgcmarins  I haven't checked that.

**Comment by gypsicoder** [comment]
If I use a number which is not in my contact list will it open that number also with the text?

**Comment by shubhamdeol** [comment]
@gypsicoder  that won't happen for now. I couldn't find any way to do this. 
But you have can ask user write contact permission and save that data to user's phone.
I wish we could do that directly.

**Comment by shubhamdeol** [comment]
@gypsicoder  you can create different issue for this.

**Comment by gypsicoder** [comment]
@shubhamdeol  thank you for the information.

**Comment by khalidahmedshalabi** [comment]
@gypsicoder post the new issue url please so I can follow it

**Comment by manjunathgk22** [comment]
any update on this ?

**Comment by shkibrahim** [comment]
> I have added this feature for Android only this fork: https://github.com/shubhamdeol/react-native-share Now I can send message directly to user's WhatsApp number using this below code:
> 
> ```js
> import Share from 'react-native-share';
> 
> const shareOptions = {
>     title: 'Share via',
>     message: 'some message',
>     url: 'some share url',
>     social: Share.Social.WHATSAPP,
>     whatsAppNumber: "9199999999"  // country code + phone number
> };
> Share.shareSingle(shareOptions);
> ```

not working on my device

**Comment by ba2n0shriya** [comment]
this was very helpfull . it worked as expected thankyou
