### ISSUE TITLE
Share not Working in release APK 

### ISSUE THREAD

**Issue by NikitaShelar** [react-native-community/react-native-share#532]
### Steps to reproduce
1.Share pdf not working in react-native version 0.59.9 after making release APK 
2. I have added the steps as  per react-native-share npm it working fine in latest version but when make release APK it gets failed.  
3.https://github.com/react-native-community/react-native-share/ i had refer this link

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Environment
- **React Native version**:  0.59.9
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc

### react-native-share
**Version**: npm version or "master"

### Link to repo (highly encouraged)
https://github.com/

**Comment by MateusAndrade** [comment]
Hi @NikitaShelar , what error are you experiencing? You can provide any logs?
