### ISSUE TITLE
Share multiple images with Share.shareSingle

### ISSUE THREAD

**Issue by ondrej-merkun** [react-native-community/react-native-share#533]
Hi,

I need to share multiple images within one app, with one dialog.
I know this is now possible with `Share.open`, but **I need to do this with just one specific social app**, so I am looking for a way to share multiple image files with one `Share.shareSingle` dialog.
How could this be done?

Thanks in advance.

**Comment by jgcmarins** [comment]
Yes, it is possible. It's on developer land.
You can add an if statement and check it before call the share function.

**Comment by merkur0** [comment]
> You can add an if statement and check it before call the share function.

What do you mean by that? How would an if statement help me with sharing multiple image files using a method that seems to only support one image file?

**Comment by jgcmarins** [comment]
Check the example:
https://github.com/react-native-community/react-native-share/blob/05c2b6a1aeb74853ef16265f690b3ba48cd0198f/example/App.js#L58-L78

**Comment by merkur0** [comment]
> Check the example:
> 
> https://github.com/react-native-community/react-native-share/blob/05c2b6a1aeb74853ef16265f690b3ba48cd0198f/example/App.js#L58-L78

I am aware of this, however, as I mentioned in my original post, I need to share the image files within one app (just like with Share.shareSingle). Share.open can't do that, therefore I can't use this example.

**Comment by ronal2do** [comment]
@merkur0 I think you can if you look to types 
```ts
declare namespace Share {
    function shareSingle(
        options: Options & { social: SupportedSocialApps }
    ): Promise<ShareSingleReturn>;
}

interface Options {
    url?: string;
    urls?: string[];
    type?: string;
    message?: string;
    title?: string;
    subject?: string;
    excludedActivityTypes?: string;
    failOnCancel?: boolean;
    showAppsToView?: boolean;
}

type SupportedSocialApps =
    | "facebook"
    | "pagesmanager"
    | "twitter"
    | "whatsapp"
    | "instagram"
    | "googleplus"
    | "email";
```

**Comment by kkbhav** [comment]
Multiple image share will not work with shareSingle on iOS. Somebody will have to raise PR for this feature. For Android, it is already implemented.

**Comment by xliank** [comment]
Here is my script, 
Simple explain, I need to download the pictures and convert to base64 using rn-fetch-blob.
I theory you can share files/pictures/etc with some library.

> import RNFetchBlob from "rn-fetch-blob";
import Share from "react-native-share";
import {
  PermissionsAndroid,
  ToastAndroid,
  Alert,
  Platform
} from "react-native";

const _shareImage = async pics => {
  try {
    ToastAndroid.show("Progress will started soon", ToastAndroid.SHORT);
    const checkVersion = Platform.Version > 22;
    const granted = await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
      {
        title: "Access Require",
        message:
          "Press Allow Permission to start progress"
      }
    );

    //cannot progress without permission || sdk < 23 bypass
    if (granted !== PermissionsAndroid.RESULTS.GRANTED && checkVersion) {
      Alert.alert("Cancel, permission denied");
      return;
    }
    let Pictures= pics.map(item =>
      RNFetchBlob.config({
        fileCache: true
      })
        .fetch("GET", item.pic_url)
        .then(resp => {
          let base64s= RNFetchBlob.fs
            .readFile(resp.data, "base64")
            .then(data => "data:image/jpeg;base64," + data);
          return base64s;
        })
    );
    Promise.all(Pictures).then(completed => {
      const options = {
        title: "Share via",
        urls: completed
      };
      Share.open(options);
    });
  } catch (err) {
    Alert.alert("Error, Permission denied", err);
  }
};
export default _shareImage;

**Comment by jgcmarins** [comment]
@xliank awesome!
Do you believe it's missing any information about this on docs?

**Comment by xliank** [comment]
> @xliank awesome!
> Do you believe it's missing any information about this on docs?

I think it wasn't developer fault to not include example in docs.
But they actually include in docs about how to share multiple urls / arrays:
![image](https://user-images.githubusercontent.com/19347346/61029704-d3eeed80-a3e5-11e9-8ef3-190aeab04e08.png)

Also rn-fetch-blob isn't really well maintain, they haven't any update since dec 2018. https://github.com/joltup/rn-fetch-blob. I'm still using it to download file from server before share it.

You can use any third party plugin or create your own. 
I found this package from https://github.com/itinance/react-native-fs, which you can read file list  using `readDir` and using `readFile` to encoding each file of list as base64. 

Any packages should've works if they support base64

**Comment by jgcmarins** [comment]
done https://github.com/react-native-community/react-native-share/pull/545?

**Comment by MateusAndrade** [comment]
https://github.com/react-native-community/react-native-share/issues/533#issuecomment-508459727

**Comment by sepowitz** [comment]
Hi, 

I’m also looking for an answer to this question. It seems to have been prematurely closed.

Has anyone determined whether there is a way to share multiple attachments (urls) via the Share.ShareSingle method?

Any help is much appreciated!

**Comment by MateusAndrade** [comment]
@sepowitz you tried passing a ```urls``` to Share.single?

**Comment by deepanshu-shopG** [comment]
@xliank Thanks a lot, this worked well for me
Is there also a way we can pass multiple mssgs, different mssg along with every image being shared?
Any help is much appreciated!

**Comment by chiny20035** [comment]
It doesn't work for IG. If I send

**Comment by mehthabt** [comment]
Does multiple image share using single share works on ios now?
