### ISSUE TITLE
Follow React Native Community instructions

### ISSUE THREAD

**Issue by jgcmarins** [react-native-community/react-native-share#534]
check this: https://github.com/react-native-community/.github/issues/40

**Comment by mikehardy** [comment]
@jgcmarins I was just in the react-native-share settings recently, looking at whether we should enforce only GPG signed commits or not, and I also read this (and fixed one of my other repos) today - I think react-native-share is good in this department. I’m going to close this but I will also double-check at the same time :-)

💪

**Comment by mikehardy** [comment]
yep - looks good to me - requires a PR with 1 review and circleci passing, but an admin could override if they really wanted to. Maintainers are not equal to admins, and @kelset gave lots of people maintainer (write access) across react-native-community - a “default open” stance, but admins are per-repository and tighter - “great power to select few just in case” setup.

seems well balanced and react-native-share should move along nicely I hope. Mostly @MateusAndrade  at this point anyway :-), who is now an admin if I recall correctly (he’ll be able to see the branch protection settings if so)

**Comment by MateusAndrade** [comment]
I will give a look at this on the weekend, because im too busy at the work. 😢 

Btw, i think we should apply some changes on react-native-share using the standards from the community.

**Comment by jgcmarins** [comment]
Awesome, guys.
Thanks for the hard work \o/
