### ISSUE TITLE
Photo Share not working. 

### ISSUE THREAD

**Issue by manujbahl** [react-native-community/react-native-share#537]
### Steps to reproduce
1.  Try to share a base64 image or a local file from the gallery with a message.
2.  Image and message show up in email/message sharing but not on facebook sharing.
3.  Facebook sharing only shows image.

### Expected behaviour
Image and message should show up on FB sharing.

### Actual behaviour
Only Image shows up in FB sharing.

### Environment
- **React Native version**:  0.59
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc  
ios 10.0 (actual device)

### react-native-share
**Version**: npm version or "master"   1.1.3

### Link to repo (highly encouraged)
https://github.com/
Here is the code.
```
var shareImageBase64 = {
                                type: 'image/png',
                                title: "React Native",
                                message: "Hi There",
                                url: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAd4klEQVR42u1d....',
                                subject: "Share Link"
                              };

                           
                                await Share.open(shareImageBase64);
```

I also tried selecting from the gallery ( using  ImagePicker - react-native-image-picker ) and send a local file url but that also did not work. That gives an error

6a25cda9-135b-4791-a…-b4a2985938a9:58938 Possible Unhandled Promise Rejection (id: 1):
Error: ShareDialog encounters error
Error: ShareDialog encounters error
    at createErrorFromErrorData (blob:http://10.0.0.8:8081/6a25cda9-135b-4791-aaf4-b4a2985938a9:2455:17)
    at blob:http://10.0.0.8:8081/6a25cda9-135b-4791-aaf4-b4a2985938a9:2407:27

 ``` 
 ImagePicker.showImagePicker(options, (response) => {

                                        const photoUri = response.uri;
                                        const sharePhotoContent = {
                                            contentType: 'photo',
                                            caption: "Tets Message",
                                            photos: [{ imageUrl: photoUri }],
                                        }
            
                                        ShareDialog.show(sharePhotoContent);
```

**Comment by MateusAndrade** [comment]
HI @manujbahl . sorry for the late answer. When i used react-native-share on a daily project, i faced a similar issue with another applications.  I recommend use the ```file: ../``` path to share your image.

By doing this, i successfully managed to share a photo on whatsapp on IOS, wich have a similar problem.

If you want to manage, access local files you can give a look at: https://github.com/joltup/rn-fetch-blob.

Btw, i hope it helps. :)

**Comment by jgcmarins** [comment]
Take a look at our [Troubleshooting](https://github.com/react-native-community/react-native-share#troubleshooting) section related to `rn-fetch-blob` + `base64`

**Comment by tolik85** [comment]
I have the same issue on iOS WhatsApp. Any solution to this?

**Comment by jgcmarins** [comment]
@tolik85 could you provide more details?
Thanks
