### ISSUE TITLE
Cannot read property shareSingle of undefined

### ISSUE THREAD

**Issue by matsossah** [react-native-community/react-native-share#54]
In my Buttons, the onPress function throws the error I copied in the title.  Any idea why?  I imported Share at the top of my file like so: import Share, { ShareSheet, Button } from 'react-native-share';

`<Button
                iconSrc={{ uri: EMAIL_ICON }}
                onPress={() => {
                  this.onCancel();
                  setTimeout(() => {
                    Share.shareSingle(Object.assign(shareOptions, {
                      social: 'email',
                    }));
                  }, 300);
                }}
              >
               Email
              </Button>`

**Comment by tststs** [comment]
Had the same issue.
I fixed it by removing the `libRNShare.a` and manually add it again within Xcode.

You can find it under the `General` tab.

![bildschirmfoto 2016-08-24 um 16 22 49](https://cloud.githubusercontent.com/assets/3591665/17934213/622f0532-6a17-11e6-9072-f3288e0e7d62.png)

**Comment by matsossah** [comment]
Thanks @tststs I ended up doing a manual install instead of rnpm and everything worked fine. A lot was missing with rnpm it seemed like

**Comment by seque1990** [comment]
I have the same problem in iOS (In Android is working perfectly), I did setup everything manually and did the change in `libRNShare.a` as @tststs mentioned. `Share.open()` is working, so I guess it's not related to the setup. Any idea?

**Comment by tienhieu67** [comment]
I have the same problem in iOS. Fixing it by add Twitter account to your Iphone, Android is working perfectly because you don't have to add twitter acc to your phone.

**Comment by seque1990** [comment]
@tienhieu67 sorry I think I didn't get that one. What do you mean specifically by adding Twitter to my iPhone? Downloading the App or something I need to setup. Thanks. :)

**Comment by tienhieu67** [comment]
@seque1990 switch to Setting and select Twitter then add your acc here.

**Comment by FarhadMahmudi1990** [comment]
I have the same problem in Android 
Cannot read property shareSingle of undefined....

**Comment by agrawalo** [comment]
Facing same issue with Android and ios both. What should I do to fix this? https://stackoverflow.com/questions/49082623/react-native-share-promise-rejection-error

**Comment by aaronkchsu** [comment]
I fixed this by running pod install in the iOS folder!
