### ISSUE TITLE
Compatibility with React Native v0.60 

### ISSUE THREAD

**Issue by cassioseffrin** [react-native-community/react-native-share#541]
## Describe the Feature
Compatibility with React Native v0.60 

 ## Related Issues
The current version of react-native-share is not compatible  with React Native v0.60

**Comment by mikehardy** [comment]
Duplicate search issues

**Comment by mikehardy** [comment]
I pinned the original to stem the flow.

**Comment by jgcmarins** [comment]
duplicated: https://github.com/react-native-community/react-native-share/issues/540
