### ISSUE TITLE
Android 4.x version error

### ISSUE THREAD

**Issue by ramonscampos** [react-native-community/react-native-share#542]
In some specific versions (like 4.x) of Android I'm getting this error message:

java.lang.RuntimeException: Unable to get provider cl.json.RNShareFileProvider: java.lang.ClassNotFoundException: Didn't find class "cl.json.RNShareFileProvider" on path: DexPathList[[zip file "/data/app/com.q2milk-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.q2milk-1, /system/lib]]

Versions 5> and iOS works perfectly.

**Comment by Kulsoom-1** [comment]
Run pod install in your ios directory and then build again.

**Comment by xliank** [comment]
Same problem here with Emulator Android 4.2 , any way to fix it ?

**Comment by jgcmarins** [comment]
which rn-share version are you using?

**Comment by xliank** [comment]
>     "react": "^16.8.6",
>     "react-native": "^0.60.4",
>     "react-native-share": "^2.0.0"

Project was upgrade from react-native < 0.60. No problem on fresh project.  I will try remove node_modules and yarn cache.
