### ISSUE TITLE
Facebook sharing 

### ISSUE THREAD

**Issue by faustoct** [react-native-community/react-native-share#544]
### Steps to reproduce
1. Share on facebook
2. Facebook app not installed
3. `{ title: "React Native", message: "Hola mundo", url: "http://facebook.github.io/react-native/", subject: "Share Link", social: social}`

get's the error 

````
undefined is not a function (evaluating 'Object.keys(styles)[typeof Symbol==="function"? Symbol.iterator : "@@iterator"]()')
````

**Comment by MateusAndrade** [comment]
Did you link rn-share following the instructions on README.MD?
