### ISSUE TITLE
Runtime Error: Attempt to invoke virtual method \'android.content.res.XmlResourceParser 

### ISSUE THREAD

**Issue by A7madXatab** [react-native-community/react-native-share#548]
ive looked in all issues mentioned about this error, but unfortunatly none of them worked for me, here is my setup, only on android
`
RNFetchBlob.config({
      fileCache: true
    }).fetch("GET", image)
      .then(res => {
      alert(JSON.stringify(res));
      alert(res.path())

        const something= res.base64();
        res.readFile("base64")
        .then(res => {
          const path= `data:image/png;base64,` + res;
          Share.open({
            url: path,
            title: "Share",
          }).catch(err => alert(JSON.stringify(err)));
        })
    })
`
when im printing the res it has a value but when passing the path to Share i get that error

AndroidManafest.xml

` <provider
        android:name="android.support.v4.content.FileProvider"
       
        android:authorities="${applicationId}.provider"
        android:grantUriPermissions="true"
        android:exported="false">
        <meta-data
         tools:replace="android:resource"
            android:name="android.support.FILE_PROVIDER_PATHS"
            android:resource="@xml/filepaths" />
    </provider>`

**Comment by MateusAndrade** [comment]
Hi @A7madXatab sorry for the late answer. It looks something related to your fileprovider, i got a similar problem sometime ago and solved this, setting my providers on android. 

You can check if your project config follow the guide on the docs?
