### ISSUE TITLE
Autolinking for React Native > 0.60

### ISSUE THREAD

**Issue by vikalpjain** [react-native-community/react-native-share#551]
## Describe the Feature

React Native now supports Autolinking of libraries. But the installation instructions for this library still says that we need to run react-native link command. Will we be updating the library to support autolinking?

**Comment by MateusAndrade** [comment]
Hi @vikalpjain you currently got a [PR](https://github.com/react-native-community/react-native-share/pull/550) that updates react-native-share to 0.60 enabling auto-linking.  

While this still on review you can try it by yourself using this PR. =)
