### ISSUE TITLE
List of apps available to share to

### ISSUE THREAD

**Issue by fresnel-bruno** [react-native-community/react-native-share#553]
Hi,
We can share base64 files to some apps listed, but we can't figure out why some apps are not listed.
For example, we would like to open pdf files in the acrobat reader app, but is not appearing in the list of apps. Is there any way to show all possible applications? many thanks!

**Comment by jgcmarins** [comment]
Hello, maybe [isPackageInstalled](https://github.com/react-native-community/react-native-share#ispackageinstalled-in-android) function is what you're looking for?

**Comment by fresnel-bruno** [comment]
Hi @jgcmarins , thanks for the advice. the issue there is that I will have to know in advance all the possible packages for pdf's that are out there. The idea is that if I install an app/package for viewing PDFs I can open it with it without having to get a new version.
Also, it needs to work for ios and android). thanks again!
Any other ideas?

**Comment by jgcmarins** [comment]
Besides `isPackageInstalled` function, I've found some thoughts:
- [Android](https://stackoverflow.com/a/17453242/3995248)
- [iOS](https://stackoverflow.com/a/26883898/3995248)

**Comment by lguardado** [comment]
I'm facing the same issue.... I tried using 
```<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>com.adobe.adobe-reader</string>
		<string>pdfreader</string>
        <array>``` in the `Info.plist` file and I couldn't make `Acrobat PDF Reader` to show up there nor being able to toggle it from the "more" options.
note: there are a lot of apps missing in the "more", "suggestions" section of the share modal.

**Comment by jgcmarins** [comment]
> note: there are a lot of apps missing in the "more", "suggestions" section of the share modal.

Thanks. Any idea on how could we add more?

**Comment by lguardado** [comment]
Thanks for the reply @jgcmarins, I wish I knew.... in my particular case, adding more apps there, will partially solve the problem since the user could be able to find his option by tapping "more", but I'd still need the app to show in the first menu. If I find something I'll let you know of course.

**Comment by shafiqruslan95** [comment]
Im also having this issue. Does anyone solved it?
