### ISSUE TITLE
Instagram Stories on v2

### ISSUE THREAD

**Issue by ithustle** [react-native-community/react-native-share#556]
## Ask your Question

Is instagram stories working on this version?

**Comment by jgcmarins** [comment]
v2 was a great opportunity to release instagram stories
but we were focused on RN 0.60
if you're interested, I can help you with instructions to rollback instagram stories and release a v3
we just need to bring these changes: https://github.com/react-native-community/react-native-share/pull/505

**Comment by ithustle** [comment]
@jgcmarins , yes I am. I would like to

**Comment by hbarylskyi** [comment]
was any work done on this?

**Comment by MateusAndrade** [comment]
> was any work done on this?

As i remember, we needed to remove some implementations related to stories on this version. But, we released some updates on the last weeks. @hbarylskyi you can give a try with that to help us know what is the actual state of this feature?

**Comment by hbarylskyi** [comment]
@MateusAndrade I'm looking into the issue. I don't have much experience with rn libraries. How do you test the code in the library? copy it to a react-native project's node_modules manually and run functions from that react-native project?

**Comment by MateusAndrade** [comment]
> @MateusAndrade I'm looking into the issue. I don't have much experience with rn libraries. How do you test the code in the library? copy it to a react-native project's node_modules manually and run functions from that react-native project?

You can clone this repo, run a ```yarn```at the root folder, and then at a example folder run a ```yarn```and a ```yarn dev-sync```. This command will copy everything from the root folder, to the node_modules folder at the example app.

**Comment by hbarylskyi** [comment]
@MateusAndrade thank you!

**Comment by hbarylskyi** [comment]
I managed to build and install in release mode after I disabled Dead Code Stripping in `example` target. Disabling it in RNShare didn't make any difference. So not sure if it's a solution since users would have to change their apps to make them build with this library. Any thoughts @MateusAndrade? Btw, here's the error I was getting:

```
Undefined symbols for architecture x86_64:
  "_RCTSetLogFunction", referenced from:
      -[exampleTests testRendersWelcomeScreen] in exampleTests.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by MateusAndrade** [comment]
@hbarylskyi you got this trying to run the example with ```react-native run-ios?```? I will give a look at this tomorrow and warn you if i face this problem. :)

**Comment by hbarylskyi** [comment]
@MateusAndrade I ran the example from Xcode. 
First i did a `git revert ec7ff153015da25ff7f861643c30bcef705a632d`. Then I belive I got the error. Then disabled Dead Code Stripping. Should I push my changes to a fork so that you can try it?

**Comment by MateusAndrade** [comment]
> @MateusAndrade I ran the example from Xcode.
> First i did a `git revert ec7ff153015da25ff7f861643c30bcef705a632d`. Then I belive I got the error. Then disabled Dead Code Stripping. Should I push my changes to a fork so that you can try it?

Sure! This will help me a lot. :smile:

**Comment by hbarylskyi** [comment]
Ok. Will do later today.

**Comment by hbarylskyi** [comment]
@MateusAndrade #600 👽
