### ISSUE TITLE
sms share on samsung duplicates first sentence. 

### ISSUE THREAD

**Issue by yernandus** [react-native-community/react-native-share#558]
### Steps to reproduce
1. open share
2. select sms and share several sentences
3. check first sentence, it will be repeated

### Expected behaviour
no sentences should be repeated

### Actual behaviour
first sentence is repeated

### Environment
- **React Native version**: 0.59.5
- **React Native platform + platform version**: S9 and the version is G960FXXU5CSF2 / G960FOXM5CSF2 / G960FXXU5CSF2

### react-native-share
**Version**: 1.2.1

### Link to repo (highly encouraged)
https://github.com/

**Comment by jgcmarins** [comment]
happening on both android and iOS?

**Comment by yernandus** [comment]
Only on Android and Samsung

**Comment by MateusAndrade** [comment]
Did you tested it on another android devices? Also, this happened on the example project?

**Comment by yernandus** [comment]
Yes, Android one plus was ok. Did not test example project

**Comment by MateusAndrade** [comment]
Im really busy on the last few days, so i cant test the example application to reproduce your issue. Please, let us know if this is happening on the example project.
