### ISSUE TITLE
"Null is not an object" on import

### ISSUE THREAD

**Issue by ebellumat** [react-native-community/react-native-share#559]
### Steps to reproduce
1. Type on code
``` import Share from 'react-native-share'```
### Expected behaviour
Load view

### Actual behaviour
```null is not an object``` <- message

![image](https://user-images.githubusercontent.com/26942680/62220754-f80b7200-b386-11e9-83c9-7e09a60a5596.png)

### Environment
"react": "16.8.6",
"react-native": "0.60.4",

### react-native-share
"react-native-share": "^2.0.0",

**Comment by ebellumat** [comment]
Sorry guys, i forgot to run pod install.

**Comment by jgcmarins** [comment]
Don't worry
