### ISSUE TITLE
Send original image using share function

### ISSUE THREAD

**Issue by Kuhne1** [react-native-community/react-native-share#563]
I need to send the original image file with no compression. This is possible using the airdrop function from this library but sharing using any social function or even saving the image changes it. I calculate a sha256 has over the file to test if there's any change in the image. 

I have read online that if you send images as pdf's type they won't be compressed and have seen other apps utilise sending images as files to avoid compression. 

I tried to tag my files with the application/pdf mime but they always just send as JPGS.

Any help would be appreciated. :)

**Comment by jgcmarins** [comment]
I guess that the compression happens on the user land, like whatsapp, for example.
