### ISSUE TITLE
Sharing a dynamic link on ios email app cuts some of the parameters and link opens the app but not the page that is needed

### ISSUE THREAD

**Issue by yernandus** [react-native-community/react-native-share#564]
### Steps to reproduce
1.share via email on ios
2.check the url in the body of email. it will be shorter than the one shared
3.

### Expected behaviour
the url should not change

### Actual behaviour
shared url is shorter
### Environment
- **React Native version**: 0.59
- **React Native platform + platform version**: iOS 12.0

### react-native-share
**Version**: 1.2.1

### Link to repo (highly encouraged)
https://github.com/

**Comment by jgcmarins** [comment]
what happens if you console.log it before using share?

**Comment by yernandus** [comment]
I tested it that way. Because that link is shared on other apps too and it works well. only email on ios is having problems. the link is a dynamic link. so it has several params to open needed page later when app starts

**Comment by hrc7505** [comment]
I facing same issue

**Comment by yernandus** [comment]
I found one solution to this problem. Just use link shortener. for example this one https://bitly.com

**Comment by jgcmarins** [comment]
Great
can we close?

**Comment by yernandus** [comment]
> Great
> can we close?

sure
