### ISSUE TITLE
declaration of 'RCTConvert' must be imported from module 'React' before it is required

### ISSUE THREAD

**Issue by grafosecondo** [react-native-community/react-native-share#566]
### Steps to reproduce
1. RN share 1.2.1 on React Native 0.59.3, library linked, libRNShare.a in Link Binary with Libraries
2. Podfile containing following line under Project-tvOSTests
> pod 'RNShare', :path => '../node_modules/react-native-share'

3. Build or Archive in XCode 10.2.1

### Expected behaviour
The project should build without any error

### Actual behaviour
Approx. 4 out of 5 timese building fails with followig error while compiling WhatsAppShare.m
> declaration of 'RCTConvert' must be imported from module 'React' before it is required
```
node_modules/react-native-share/ios/WhatsAppShare.m:21:27: error: declaration of 'RCTConvert' must be imported from module 'React' before it is required
        NSString *text = [RCTConvert NSString:options[@"message"]];
```
A random mix of XCode clean build folder, watchman del, and npm --reset-cache makes it work, but I can't determinate the trick.

### Environment
- **React Native version**: 0.59.3
- **React Native platform + platform version**: iOS 12.1

### react-native-share
npm 1.2.1

### Link to repo (highly encouraged)
https://github.com/

**Comment by mikehardy** [comment]
you might try using the legacy build system for a "sometimes fails" ios build error.

**Comment by grafosecondo** [comment]
@mikehardy unfortunately the process isn't stable even under legacy build system. I am inspecting some kind of collision or effect coming from other libraries. Thank you for your answer, I'll keep you guys posted on the issue

**Comment by jliberacki** [comment]
I have similar problems and i found out that under product->scheme->manage shemes->targets i have react (missing)

**Comment by grafosecondo** [comment]
@jliberacki currently testing your solution, thanks. I'll try a few times because of the randomness of the bug, and let you know

**Comment by nubwang** [comment]
This component cannot be used for 0.59.2

**Comment by mikehardy** [comment]
With existing minor patch versions up to 0.59.10 I wouldn't stay on 0.59.2 so that doesn't seem like a restriction really?

**Comment by grafosecondo** [comment]
@jliberacki  Unfortunately your solution doesn't solve the problem. The library keeps building now and then.
@nubwang @mikehardy when the building succeedes everything works just fine under 0.59.3

**Comment by MateusAndrade** [comment]
@grafosecondo you tried with recent versions?
