### ISSUE TITLE
Can't share to Facebook

### ISSUE THREAD

**Issue by dijimon** [react-native-community/react-native-share#57]
I'm getting this error when trying to share to facebook

https://www.dropbox.com/s/pte1vd6m2m3050d/Screen%20Shot%202016-09-02%20at%2012.24.33.png?dl=0

Any idea?

**Comment by dijimon** [comment]
Nobody knows?

**Comment by dijimon** [comment]
Any suggestion?

**Comment by codefo** [comment]
@dijimon Maybe you run that app on Android emulator without a Facebook app?

**Comment by rohitgoyal** [comment]
Does Facebook share not work on Android when there is no Facebook App on the phone? 
In case no, any way to make it work?

**Comment by virgil9306** [comment]
@rohitgoyal If no Facebook app, and you're able to tell, perhaps you can just open a browser intent to the appropriate Facebook URL.

**Comment by nicholasess** [comment]
@dijimon the error persists?
