### ISSUE TITLE
Can't share audio file on a real device

### ISSUE THREAD

**Issue by farshed** [react-native-community/react-native-share#571]
### Steps to reproduce
1. Try to share a local mp3 file on a real Android device.

### Expected behaviour
Opens an app intent to share the selected file on all devices.

### Actual behaviour
**ON EMULATOR**: Sharing works as expected.

**ON ACTUAL DEVICES**: An empty intent (with no file) is opened when shared with Gmail. Shows a toast message, "Sharing failed. Please try again" on all other apps (WhatsApp, Messenger etc).

### Environment
- **React Native version**: 0.59.9
- **React Native platform + platform version**: Tested on Android Emulator (Oreo 8.0), Oppo F11 & Nokia 6 (both running Pie 9.0)

### react-native-share
**Version**: 1.2.1

### Code
```
let path = /storage/emulated/Audio/SomeTrack.mp3;

onShare = () => {
     Share.open({
         url: 'file://'+path,
         type: 'audio/mp3',
         failOnCancel: false
     });
};
```

**Comment by eff-society** [comment]
I'm only building for android so I haven't tested it on iOS.

**Comment by MateusAndrade** [comment]
hi @eff-society you can try the last version published on npm/github?

**Comment by eff-society** [comment]
@jgcmarins what do you mean? There's no audio sharing example in the [example](https://github.com/react-native-community/react-native-share/tree/master/example).

**Comment by eff-society** [comment]
@MateusAndrade I'm on react-native 0.59.9 so can't try react-native-share v2.0.0. And I can't update to RN >= 0.60.0 because it'll likely break my app.

**Comment by MateusAndrade** [comment]
@eff-society you tried sharing a file that is stored on the Downloads folder?

**Comment by farshed** [comment]
@MateusAndrade sorry for replying so late. I found the problem. It seems that I can only share audio files stored in the Download folder and that's why it was only working in the emulator. I haven't tested with other default folders yet.

**Comment by wezzy-web** [comment]
@farshed  you can just change your share_download_path xml file  with <root-path name="root" path="." /> hope it will help you

**Comment by farshed** [comment]
@wezzy-web what should I change it too?

**Comment by stepupithubapp** [comment]
@farshed share_download_path.xml file  so it solved mine will may help you too

**Comment by ericduarte** [comment]
> @farshed share_download_path.xml file so it solved mine will may help you too

What must be done in share_download_path.xml ?

**Comment by washim-suuni** [comment]
react-native-share/android/src/main/res/xml/share_download_path.xml

**Comment by nitinf22labs** [comment]
In iOS it's not working, I tried with Android it's working fine.
