### ISSUE TITLE
if sent android side . then res . not got?

### ISSUE THREAD

**Issue by appa3151** [react-native-community/react-native-share#573]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Environment
- **React Native version**:
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc

### react-native-share
**Version**: npm version or "master"

### Link to repo (highly encouraged)
https://github.com/

**Comment by jgcmarins** [comment]
sorry, it's not clear what is this problem related to
