### ISSUE TITLE
Sharing video to instagram app fails when using the filepath (ANDROID)

### ISSUE THREAD

**Issue by albrewot** [react-native-community/react-native-share#574]
### Steps to reproduce

- Download Video to the device using RNFetchBlob or Using Cameraroll
- Get the file path
- Use the filepath with Share.shareSingle method to instagram

### Expected behaviour

- Video is shared and loaded to instagram app

### Actual behaviour

![IMG_20190830_150038](https://user-images.githubusercontent.com/27984613/64045505-73ec0c00-cb37-11e9-89df-6ce887114991.jpg)

Using RNFetchBlob or CameraRoll filepaths always results in the same behaviour

### Code

Using just the filepath from RNFetchBlob
```JavaScript
let shareOptions = {
    url: `file://${this.state.files[0].data}`, //FetchBlob file path
    type: `video/${file.extension}`, //file.extension contains the extension of the file
    social: Share.Social.INSTAGRAM
};
await Share.shareSingle(shareOptions);
```

Using CameraRoll

```JavaScript
const saveCameraRoll = await CameraRoll.saveToCameraRoll(
    this.state.files[0].path()
);

const last = await CameraRoll.getPhotos({
    first: 1,
    assetType: "Videos"
});
let shareOptions = {
    url: last.edges[0].node.image.uri,
    type: `video/${file.extension}`,
    social: Share.Social.INSTAGRAM
};
await Share.shareSingle(shareOptions);
```

I already verified that the paths point to the correct file

example of filepaths given: 

RNFetchBlob:  /data/user/0/APP_PACKAGE/files/RNFetchBlobTmp_6l8lz5r3hf4ju3ptneklr.mp4

CameraRoll: file:///storage/emulated/0/Pictures/RNFetchBlobTmp_f72tuixtrlqpbrn5hdrnb.mp4

### Additional Note

It works fine using base64 as the file but since i'm working with videos and most of the time large size videos (20mb or more) if i use base64 as the file and it's more than 15mb, it makes my app crash or perma-freeze most of the time

### Environment

- React Native version: 0.59.5
- react-native-share Version: 1.2.1

**Comment by jgcmarins** [comment]
is there any other error message besides "video not provided?"

**Comment by sergiombravo** [comment]
I found a solution, at least working in my case. 

`return await RNFetchBlob
      .config({
        // response data will be saved to this path if it has access right.
        fileCache: true,
        path: RNFetchBlob.fs.dirs.DownloadDir + `/${filePath}`
      })
      .fetch('GET', url)
`
and then share as follow:

`
const shareOptions = {
              url: `file://${url.path()}`,
              social: Share.Social.INSTAGRAM
            };
await Share.shareSingle(shareOptions);
`

The trick is not to let the file store in your app package but in the download dir instead. I don't know why but I can access and upload any video or picture to instagram ever since I changed the destination. Hope it works for you as well 😄

**Comment by albrewot** [comment]
> is there any other error message besides "video not provided"?

I dit a try-catch and it doesn't display any errors



> I found a solution, at least working in my case.
> 
> ```
> return await RNFetchBlob
>       .config({
>         // response data will be saved to this path if it has access right.
>         fileCache: true,
>         path: RNFetchBlob.fs.dirs.DownloadDir + `/${filePath}`
>       })
>       .fetch('GET', url)
> ```
> 
> and then share as follow:
> 
> ```
> const shareOptions = {
>   url: `file://${url.path()}`,
>   social: Share.Social.INSTAGRAM
> };
> await Share.shareSingle(shareOptions);
> ```
> 
> The trick is not to let the file store in your app package but in the download dir instead. I don't know why but I can access and upload any video or picture to instagram ever since I changed the destination. Hope it works for you as well 😄

This fix works for me too, thanks.

Maintainers should add this to the readme so people with the same problem can use the library with filepaths too.

**Comment by jgcmarins** [comment]
@albrewot great to know
Do you mind sending a PR updating README?

**Comment by patelhari** [comment]
> I found a solution, at least working in my case.
> 
> ```
> return await RNFetchBlob
>       .config({
>         // response data will be saved to this path if it has access right.
>         fileCache: true,
>         path: RNFetchBlob.fs.dirs.DownloadDir + `/${filePath}`
>       })
>       .fetch('GET', url)
> ```
> 
> and then share as follow:
> 
> ```
> const shareOptions = {
>   url: `file://${url.path()}`,
>   social: Share.Social.INSTAGRAM
> };
> await Share.shareSingle(shareOptions);
> ```
> 
> The trick is not to let the file store in your app package but in the download dir instead. I don't know why but I can access and upload any video or picture to instagram ever since I changed the destination. Hope it works for you as well 😄

@sergiombravo This is work for me, Thank you.
