### ISSUE TITLE
How to make Instagram post to feed?

### ISSUE THREAD

**Issue by fredrik-jarnbrost** [react-native-community/react-native-share#578]
## Ask your Question

I'm trying to post to Instagram, but I can't make it work properly on either platform.

Here's my call:
```
Share.shareSingle({
    url: 'https://myserver.url',
    social: Share.Social.INSTAGRAM,
})
```

### What happens on iOS
Device: iPhone 6S, iOS 12.2

It opens AppStore.

![IMG_6768](https://user-images.githubusercontent.com/44670720/64320924-cdcd5580-cfbf-11e9-87af-2e60cf91730e.PNG)

### What happens on Android
Device: Sony Xperia Z5 Compact, Android 7.1.1

It opens the app, but in DMs.

![Screenshot_20190905-075949](https://user-images.githubusercontent.com/44670720/64320933-d3c33680-cfbf-11e9-8101-16a6033ef0b6.png)

**Comment by MateusAndrade** [comment]
Did you tried sharing a ```url``` to see if this opens the feed?

**Comment by fredrik-jarnbrost** [comment]
Ok, so I think I figured it out. Instagram needs image upload (NOTE: it needs to be jpeg as well!) so giving a remote link like I did above does not work.

I use https://github.com/joltup/rn-fetch-blob to download the file then I put the local path as the url (`url: 'file://' + response.path()`). Then it works.

**Comment by jgcmarins** [comment]
That's great!
