### ISSUE TITLE
Illegal callback invocation from native module. This callback type only permits a single invocation from native code

### ISSUE THREAD

**Issue by Arjan-Zuidema** [react-native-community/react-native-share#583]
Crash with error `Illegal callback invocation from native module. This callback type only permits a single invocation from native code` when you cancel sharing

### Steps to reproduce
1. Use iOS 13
2. Open share dialog using Share.open
3. Tap message for example
4. Cancel message
5. Cancel share
6. Crash

### Expected behaviour
There should be no crash

### Actual behaviour
It crashed

### Environment
- **React Native version**: 0.60.5
- **React Native platform + platform version**: iOS 13.0

### react-native-share
**Version**: 2.0.0

### Link to repo (highly encouraged)
https://github.com/

**Comment by knivesq** [comment]
Hello, I am still having this problem and not only email, but facebook too.
I added : 
 else if (completed) {
            successCallback(@[@(completed), RCTNullIfNil(activityType)]);
        }

and it did not work

**Comment by MalyanaSkyrim** [comment]
this worked for me  
```
 if (completed){
      if (activityError) {
        failureCallback(activityError);
      } else {
        successCallback(@[@(completed), RCTNullIfNil(activityType)]);
      }
    }
```
