### ISSUE TITLE
ActionSheetIOS.showShareActionSheetWithOptions

### ISSUE THREAD

**Issue by Arjan-Zuidema** [react-native-community/react-native-share#585]
## Ask your Question

Why use `ActionSheetIOS.showShareActionSheetWithOptions` on iOS when not using urls?
This currently crashes on iOS 13, but has been fixed in RNShare.open

**Comment by jgcmarins** [comment]
Hello @Arjan-Zuidema.
Thanks for your question.
I am afraid I couldn't understand what you mean. Could you give an example or link to piece of code?
Thanks.

**Comment by Arjan-Zuidema** [comment]
When using Share.open with the option urls not set it internally uses `ActionSheetIOS.showShareActionSheetWithOptions `

Why? Because there was a bug fixed in this package for iOS 13 that a successCallback was called twice which has not been fixed in react-native. So when using Share.open it still crashes because of the react-native bug

**Comment by jgcmarins** [comment]
Got it.
You mean this one: https://github.com/react-native-community/react-native-share/pull/584 ?

**Comment by Arjan-Zuidema** [comment]
Almost. That codes fixes using `options.urls`. But when I use `options.url`, the code uses the react-native Share module, which stil has that same bug that was fixed in #584. See [this](https://github.com/react-native-community/react-native-share/blob/master/index.js#L177) if statement in de code

**Comment by jgcmarins** [comment]
Now I get it.
Great appointment. Do you have any solution?
Mind to send a PR?

**Comment by tomtargosz** [comment]
Just a heads up, I submitted a PR to React Native for this bug and the fix got merged in a few days ago. Not sure how long it will take to make it to a release though.

https://github.com/facebook/react-native/pull/26429

**Comment by tomtargosz** [comment]
My fix has been merged into React Native, this issue shouldn't happen as of RN 0.61.1

https://github.com/facebook/react-native/blob/0.61-stable/Libraries/ActionSheetIOS/RCTActionSheetManager.m

**Comment by jgcmarins** [comment]
That's great!

**Comment by Arjan-Zuidema** [comment]
Still I think a dependency of the Share module from react-native should not be necessary, just to prevent things like this in the future.

**Comment by tomtargosz** [comment]
I agree, better to keep as much of the code in this repo as possible. Just wanted to let people know there's a solution now.
