### ISSUE TITLE
Has anyone tested this in iOS 13? 

### ISSUE THREAD

**Issue by chppatel** [react-native-community/react-native-share#587]
We are trying to test this in ios 13 but doesnt seem to work. Is anyone aware of this?

**Comment by jgcmarins** [comment]
what is not working?
there is any error message?

**Comment by squid17** [comment]
Same issue, 1.2.1 version of  the library. After calling function open, nothing happened.

**Comment by mikehardy** [comment]
My read on the releases page indicates there were 83 commits between 1.2.1 and 2.0.0 https://github.com/react-native-community/react-native-share/releases

I recognize not everyone wants to upgrade to react-native 0.60 right now (especially if you are busy testing ios13) but you should be able to use the 2.0.0 version despite AndroidX include if you use `jetifier -r` mode in postinstall in your package.json

**Comment by chppatel** [comment]
We are running on react-native 0.60.4. WHen I press the share button nothing happens. On iOS 12 the share button works as intended but on iOS 13 Beta 2, our app freezes.

**Comment by tomtargosz** [comment]
@chppatel can you share a code snippet?

**Comment by chppatel** [comment]
@tomtargosz here is our sample code that works on iOS 12 but not on 13.

`const configOptions = {
        fileCache: true,
        path:
          fs.dirs.DocumentDir + (type === 'application/pdf' ? '/Sample.pdf' : '/Sample.png') // no difference when using jpeg / jpg / png /
      };
      RNFetchBlob.config(configOptions)
        .fetch('GET', fileUrl)
        .then(async resp => {
          filePath = resp.path();
          let options = {
            type: type,
            url: filePath 
          };
          this.setState({loading: false});
          await Share.open(options);

          await RNFS.unlink(filePath);
        });`

**Comment by chppatel** [comment]
Issue was at RNFetchBlob --> https://github.com/joltup/rn-fetch-blob

Is there any other library you guys can recommend to share files?

**Comment by mikehardy** [comment]
I'm still using that one too but it is incredibly poorly maintained IMHO, 15 commits in a year, 216 outstanding issues and 46 pull requests. If you find a better one I would *love* to know. Or if a team could get together and collaborate on a fork

**Comment by tomtargosz** [comment]
Agreed, would be great to get a replacement library. If a better maintained one came out I'm sure it would get a lot of use. @chppatel, can you build with Xcode and see what the output is? I'm using RNFetchBlob as well and my code is very similar (minus the `async` notation) and I haven't had any issues on iOS 13.

**Comment by chppatel** [comment]
@tomtargosz would you be able to share a sample code you are using? For last week now we've been trying to fix this with no luck. I'm sure others are also going to run into this issue.

**Comment by CorvinSteindl** [comment]
Have same Issue as @chppatel. As a workaround, it works, if you use base64 version like on Android but then you do not have pdf support for WhatsApp and G-Mail.

@jgcmarins It hard crash the app directly when calling the function ` await Share.open(options);` like in the example to fix the iOS PDF Issue related to WhatsApp and G-Mail.

**Comment by CorvinSteindl** [comment]
@chppatel i upgraded React Native from 0.60.4 to 0.60.5 and it is working as before.

**Comment by tomtargosz** [comment]
@CorvinSteindl as in it's working correctly now? If so that could definitely be the issue, I'm on 0.60.5 as well and haven't faced any issues.

**Comment by CorvinSteindl** [comment]
@tomtargosz yes it is working correctly now on React Native 0.60.5 and iOS 13.

**Comment by chppatel** [comment]
@CorvinSteindl are you by any chance also using the rn-fetch-blob and your code also share a file correct?

**Comment by jgcmarins** [comment]
I think https://github.com/react-native-community/react-native-share/pull/586 can solve iOS 13 for us

**Comment by chppatel** [comment]
> @tomtargosz yes it is working correctly now on React Native 0.60.5 and iOS 13.

Just confirming. iOS 13 problem was solved by upgrading to React native 0.60.5 for us as well.

**Comment by AlgirdasVZ** [comment]
I've bumped into a crash while testing this on iOS 13
Versions used: React Native 0.60.5, react-native-share 2.0.0, rn-fetch-blob 0.11.2 

File in question is a simple pdf. The share menu is opened correctly, and the file is also identified correctly, but after selecting "save to files" option, and then trying to close the menu, this error is caught:

> Error: No callback found with cbID 8165 and callID 4082 for  ActionSheetManager.showShareActionSheetWithOptions - most likely the callback was already invoked. Args: '[false,null]'

react-native-share version seems to be irrelevant in this case, as the same crash was caught on v1.0.27. Everything works ok on iOS 12.*

**Comment by oleksandr-dziuban** [comment]
@AlgirdasVZ On iOS 13 we have another issue:
If user clicks on new iOS 13 UI close button - .catch() callback doesn't fire, so Promise is not rejected in this case. On iOS 12 with previous UI Cancel button it works correctly

**Comment by oleksandr-dziuban** [comment]
Created separate issue for this:
https://github.com/react-native-community/react-native-share/issues/601

**Comment by erdenayozkanl** [comment]
I have solved this problem. Open RNshare.m which located in node_modules/react-native-share,
After that comment out like this.

**_UIViewController *controller = RCTPresentedViewController();
    shareController.completionWithItemsHandler = ^(NSString *activityType, BOOL completed, __unused NSArray *returnedItems, NSError *activityError) {
        if (activityError) {
            //failureCallback(activityError);
        } else {
            //successCallback(@[@(completed), RCTNullIfNil(activityType)]);
        }
    };_**


and this part


**for (int i=0; i<urlsArray.count; i++) {
        NSURL *URL = [RCTConvert NSURL:urlsArray[i]];
        if (URL) {
            if ([URL.scheme.lowercaseString isEqualToString:@"data"]) {
                NSError *error;
                NSData *data = [NSData dataWithContentsOfURL:URL
                                                     options:(NSDataReadingOptions)0
                                                       error:&error];
                if (!data) {
                   // failureCallback(error);
                    return;
                }
                [items addObject:data];
            } else {
                [items addObject:URL];
            }
        }
    }**

Be careful where I commented out. Good luck.
