### ISSUE TITLE
Unintuitive behaviour in specific applications (Slack, Whatsapp)

### ISSUE THREAD

**Issue by Amirh24** [react-native-community/react-native-share#589]
### Steps to reproduce
1. Use the library in a react native app, tested on IOS (not android yet)

### Expected behaviour
Slack and Whatsapp should see both the message and the url that is inserted in the options

### Actual behaviour
On Slack and Whastapp it should send the url (image in my case) but it just sends the message

### Environment
React  Native  2.0.1
IOS 12

### react-native-share
^2.0.0 on yarn

**Comment by MateusAndrade** [comment]
@Amirh24 i ended up with the same issue sometime ago, unfortunately i choose to remove the message param when sharing a ```url``` because WhatsApp sharing on ios has a different behaviour than android. 

Please, let me know if you find any way to help you with that. 😃

**Comment by Katedam** [comment]
I'm having a similar issue and think this should be reopened. Whenever I share to slack, I only see the URL shared and not the message. Slack recently updated their native share option - are there plans to update this package or does anyone know of a good work around?

**Comment by mikehardy** [comment]
@Katedam I don't think there are any plans in a concrete sense with the package - I watch this repo (and occasionally help) and I haven't seen any at any rate. Effectively all the PRs last year or two are community driven, so you or someone else would need to post one
