### ISSUE TITLE
iOS: share base64 in .csv format

### ISSUE THREAD

**Issue by latusdenis** [react-native-community/react-native-share#590]
I need to share the CSV to file system or any of the social media, like Telegram. The CSV file is received, like a stream from the back-end.

![image](https://user-images.githubusercontent.com/34662936/65284540-86f46980-db42-11e9-98dc-812d7e493a9b.png)

Then, I convert it into Base64 and share, but the file is called "data" without the .csv extension. Is it possible to share the file, like data.csv?
![image](https://user-images.githubusercontent.com/34662936/65286724-41876a80-db49-11e9-962f-ea877881562e.png)

![image](https://user-images.githubusercontent.com/34662936/65284603-b905cb80-db42-11e9-96b8-c5205a6f930a.png)

Thanks in advance!

**Comment by jgcmarins** [comment]
check this comment: https://github.com/react-native-community/react-native-share/issues/520#issuecomment-532596351

**Comment by latusdenis** [comment]
@jgcmarins Thanks! I've found a solution, but still curious, is it possible to save the file to Android file system? I don't see such option and FileProvider doesn't help.
![image](https://user-images.githubusercontent.com/34662936/65330957-6ff65b80-dbc4-11e9-9984-8bd86a969d4d.png)

**Comment by jgcmarins** [comment]
I think it's possible to do that with [rn-fetch-blob](https://github.com/joltup/rn-fetch-blob)

**Comment by MateusAndrade** [comment]
@latusdenis how you managed to solve your issue? 😄
