### ISSUE TITLE
Can't share PDF file with WhatsApp or email (Android)

### ISSUE THREAD

**Issue by prasad456** [react-native-community/react-native-share#592]
### Steps to reproduce
1. Implemented as instructed for PDF Share
2. Added FileProvider(Local) in Manifest
3. Added Two different method to share on Android & iOS

### Expected behaviour
Tell us what should happen
Must share options for pdf share
### Actual behaviour
Tell us what happens instead
Nothing
### Environment
- **React Native version**:
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc
    "react": "16.8.6",
    "react-native": "0.60.0",

### react-native-share
**Version**: npm version or "master"
  "react-native-share": "^2.0.0",
### Link to repo (highly encouraged)
https://github.com/

**Comment by jgcmarins** [comment]
do you have any reproducible repo?

**Comment by prasad456** [comment]
@jgcmarins 
I just implemented the instructions as mentioned here for sharingpdf
https://github.com/react-native-community/react-native-share

But while adding File provider in manifest, having merge issues the android defailt file providing already iusing other package called react-native-image-crop-picker. So I created a File provider same as Android ones.
Build errors are fixes but can't share the pdf

The below line is not working while i had logs within the method
await Share.open({ url: base64Data });

**Comment by MateusAndrade** [comment]
Hi @prasad456 , you can provide a sample code showing how you are calling rn-share? Also, have you tried sharing the PDF relative path?

**Comment by prasad456** [comment]
This is code trying for share 
My reference of the bloew code is https://github.com/react-native-community/react-native-share#troubleshooting

`

    sharePDF = (item) => {
        const url = item.docLink
        if (Platform.OS == 'ios') {
            this.sharePDFWithIOS(url, 'application/pdf')
        }
        else {
            console.log('PDF share with android', item)
            this.sharePDFWithAndroid(url, 'application/pdf')
        }
    }

    sharePDFWithAndroid(fileUrl) {
        let filePath = null;
        let file_url_length = fileUrl.length;
        const configOptions = { fileCache: true };
        console.log('PDF android share', filePath)
        RNFetchBlob.config(configOptions)
            .fetch('GET', fileUrl)
            .then(resp => {
                filePath = resp.path();
                console.log('PDF RNF then1', filePath)
                return resp.readFile('base64');
            })
            .then(async base64Data => {
                base64Data = await `data:application/pdf;base64,` + base64Data;
                console.log('PDF RNF then2', base64Data)

                try {
                    await Share.open({ url: base64Data });
                    // remove the image or pdf from device's storage
                    await RNFS.unlink(filePath);
                } catch (error) {
                    console.log('PDF then2 err', error)
                }
            });
    }

    sharePDFWithIOS(fileUrl, type) {
        let filePath = null;
        let file_url_length = fileUrl.length;
        const configOptions = {
            fileCache: true,
            path:
                DIRS.DocumentDir + (type === 'application/pdf' ? '/SomeFileName.pdf' : '/SomeFileName.png') // no difference when using jpeg / jpg / png /
        };
        RNFetchBlob.config(configOptions)
            .fetch('GET', fileUrl)
            .then(async resp => {
                filePath = resp.path();
                let options = {
                    type: type,
                    url: filePath // (Platform.OS === 'android' ? 'file://' + filePath)
                };
                await Share.open(options);
                // remove the image or pdf from device's storage
                await RNFS.unlink(filePath);
            });
    }`

**Comment by tuncaulubilge** [comment]
@prasad456 
For me, `RNFS.unlink` was causing the issue, so try to remove it and see if that fixes the issue for you. Whatsapp or gmail might still be uploading the image so we shouldn't remove that file right away.

**Comment by jgcmarins** [comment]
@efecantekin check if it's related
