### ISSUE TITLE
share local image don't work

### ISSUE THREAD

**Issue by IsmetGlumcevic** [react-native-community/react-native-share#593]
tested device ios iphone 7
RN 0.60

Shared only message, url don't send file. I have error can't find variable setResult and ReferenceError: setResult is not defined
 This is code

      onShareImg = async (shareimg) => {
        let sharetitle = shareimg.englishName + " ";
        let shareimgurl= "../slike/page" + shareimg.url + ".png";
        let shareimgurl2= 'require(../slike/page' + shareimg.url + '.png)';
        let sharetext= shareimg.text;
        let poruka= sharetitle.concat(sharetext);
         console.log(shareimgurl)
         console.log(shareimgurl2)
        const shareOptions = {
        title: 'Share via',
        message: poruka,
        url: shareimgurl2,
        failOnCancel: false,
       };
       try {
        const ShareResponse = await Share.open(shareOptions);
        setResult(JSON.stringify(ShareResponse, null, 2));
       } catch (error) {
        console.log('Error =>', error);
        setResult('error: '.concat(getErrorString(error)));
       }
      };

**Comment by jgcmarins** [comment]
which react-native-share version are you using?

**Comment by IsmetGlumcevic** [comment]
"react-native-share": "^2.0.0",

**Comment by jgcmarins** [comment]
`setResult` isn't a function you've created?

**Comment by jgcmarins** [comment]
maybe you've missed this: https://github.com/react-native-community/react-native-share/blob/0e9af38b86f2d48cda27913f6f94b007ca5d20d2/example/App.js#L30
?

**Comment by IsmetGlumcevic** [comment]
i set result, now i don't have error, image isn't  shared, why?

**Comment by jgcmarins** [comment]
is it iOS?
can you run this example locally? https://github.com/react-native-community/react-native-share/blob/master/example/App.js

**Comment by IsmetGlumcevic** [comment]
work with url: images.image1
don't work with  url: "file://" + shareimgurl,

**Comment by MateusAndrade** [comment]
> how to define file_path, images are png, do i ned to use react-native-fs?

You can use react-native-fs or react-native-fetch-blob. Both of them access the file system on the user device. I think that maybe #431 can help you with that.

But, the basic idea is just recover the path with one of that libraries and send that on the ```url``` params.

**Comment by IsmetGlumcevic** [comment]
I try this and don't share image only share message.

       onShareImg = async () => {
        if(Platform.OS === 'ios') {
         RNFS.readFile(RNFS.MainBundlePath + '/slike/page1.png',  'base64').then(resultat => {
          const shareOptions = {
               title: "test",
               message: "Some message",
                url: resultat,
                failOnCancel: false
             };
              console.log(shareOptions);
             try {
                const ShareResponse = ShareRN.open(shareOptions);
                 console.log('ok');
              } catch (error) {
                 console.log('Error =>', error);
               }
            })
         }
      }

**Comment by IsmetGlumcevic** [comment]
This work on ios :)
       onShareImg = async (shareimg) => {
       if(Platform.OS === 'ios') {
           let sharetitle = shareimg.englishName + " " + shareimg.url;
           let shareimgurl= "/slike/page" + shareimg.url + ".png";
           let imageURIPath = 'file://' + RNFS.MainBundlePath + shareimgurl;
           let options = {
            title: 'Share via',
            message: sharetitle,
            type: 'image/png',
            url: imageURIPath
           };
            await ShareRN.open(options);
         } }

**Comment by IsmetGlumcevic** [comment]
fo android I add in androidmanifest.xml

           <provider
                android:name="androidx.core.content.FileProvider"
                android:authorities="${applicationId}.provider"
                android:grantUriPermissions="true"
                android:exported="false">
                <meta-data
                    android:name="android.support.FILE_PROVIDER_PATHS"
                    android:resource="@xml/filepaths" />
            </provider>

and create filepaths.xml in res/xml folder

          <?xml version="1.0" encoding="utf-8"?>
          <PreferenceScreen xmlns:android="http://schemas.android.com/apk/res/android">
           <paths>
                <external-path path="Download/" name="myExternalImages" />
                <files-path path="slike/" name="myInternalImages" />
             </paths>
         </PreferenceScreen>

instead image share /data/user/0/com.mojapp/files/slike/page2.png this is code
 
         onShareImg = async (shareimg) => {
             let shareimgurl= "/slike/page" + shareimg.url + ".png";
              let imageURIPath = RNFS.DocumentDirectoryPath + shareimgurl;
             let options = {
                title: 'Share via',
                message: sharetitle,
                type: 'image/png',
                 url: imageURIPath
            };
            await ShareRN.open(options);
          };

**Comment by cfranchella** [comment]
@IsmetGlumcevic were you able to make it work on android? i think at url you're missing `file://` although i tried that solution but couldn't get it to work
I'm trying to share a local asset (They're at my javascript code) but can't make it work

**Comment by IsmetGlumcevic** [comment]
I try with adding  file://, with ExternalDirectoryPat, ExternalStorageDirectoryPath and don't work. My folder 'slike' is unknown.

**Comment by jgcmarins** [comment]
> Do we need to add images to android/app/src/main/assets/ like fonts?

No.

Does your app is asking the right permissions to read/write on the device?

**Comment by IsmetGlumcevic** [comment]
No, app didn't ask for permission.

**Comment by jgcmarins** [comment]
> No, app didn't ask for permission.

I think this is the problem. App should ask permissions to read/write before it access device storage.

**Comment by IsmetGlumcevic** [comment]
I add  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />  in AndroidManifest.xml, again app should not ask permissions.

**Comment by IsmetGlumcevic** [comment]
I try with rn-fetch-blob, can't get result

      RNFetchBlob.fs.asset('/slike/page1.png')
      let path = RNFetchBlob.fs.asset('/slike/page1.png')
     <Image   style={{width: 250, height: 250}}  source={{uri: path}} />

**Comment by jgcmarins** [comment]
- [supported formats for sharing local files](https://github.com/react-native-community/react-native-share/blob/master/README.md#url-format-when-sharing-a-file)

- [troubleshooting sharing pdf with whatsapp and gmail](https://github.com/react-native-community/react-native-share/blob/master/README.md#share-remote-pdf-file-with-gmail--whatsapp-ios)

**Comment by IsmetGlumcevic** [comment]
I read all docs, what is absolute path for android local images?

**Comment by jgcmarins** [comment]
I think it's `file://<file_path>`

**Comment by IsmetGlumcevic** [comment]
> I think it's `file://<file_path>`

How get <file_path>?

**Comment by jgcmarins** [comment]
which apps have you tried to share?
did it work for any of them?

**Comment by IsmetGlumcevic** [comment]
> which apps have you tried to share?
> did it work for any of them?

whatsup, viber, messenger, gmail. Work on iOS, android didn’t work.

**Comment by sujatha2016** [comment]
Did it work ?

**Comment by IsmetGlumcevic** [comment]
No, i don't find solution for share locale image on android. We can take online image and share it.

**Comment by aadityapaliwal94** [comment]
@IsmetGlumcevic How you did it for online images?
