### ISSUE TITLE
Implement without androidx true

### ISSUE THREAD

**Issue by ravifullestop** [react-native-community/react-native-share#594]
### Steps to reproduce
1. Implemented react native share
2. Not working in android 
3. Androidx true is asked.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Environment
- **React Native version**:
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc

### react-native-share
**Version**: npm version or "master"

### Link to repo (highly encouraged)
https://github.com/

**Comment by MateusAndrade** [comment]
@ravifullestop you can provide more info about that?

**Comment by ravifullestop** [comment]
Problem is that, it is giving me error of androidx, where I am having react native version 0.59. I don't want to enable androix, what is the solution?

**Comment by mikehardy** [comment]
Use jetifier in reverse mode https://github.com/mikehardy/jetifier#to-reverse-jetify--convert-node_modules-dependencies-to-support-libraries

You are fighting an uphill battle though. It is time to convert to AndroidX

**Comment by jgcmarins** [comment]
can we close?
