### ISSUE TITLE
How to mock with jest

### ISSUE THREAD

**Issue by ricardocolares** [react-native-community/react-native-share#598]
## Describe the Feature
I realised that my tests broken right after imported `react-native-share` and I spent some time to know the right way to mock it. So I think would be a great idea to prevent someone doing the same thing by adding this information on ReadMe.

## Possible Implementation
I was trying to mock this way
```javascript
jest.mock('react-native-share');
```
and I faced this error:
`TypeError: Cannot read property 'FACEBOOK' of undefined`

`import Share from 'react-native-share';`

`at Object.FACEBOOK (node_modules/react-native-share/index.js:168:37)`
`at Object.<anonymous> (js/src/data/helpers/shareDocument/index.js:3:1)`

my solution was mocking this way:
```javascript
jest.mock('react-native-share', () => ({
  default: jest.fn(),
}));
```
How about let this suggestion on readme?

## Related Issues

https://github.com/react-native-community/react-native-share/issues/360#issuecomment-441146397

**Comment by jgcmarins** [comment]
Great!
If just adding:

```tsx
jest.mock('react-native-share', () => ({
  default: jest.fn(),
}));
```

did the trick, I think we can improve README.
Would you mind sending us a PR? Thanks.
