### ISSUE TITLE
i can't share mp3 file from real device in react native by using react-native-share library it gives me error sharing failed please try any one plz can solve 

### ISSUE THREAD

**Issue by stepupithubapp** [react-native-community/react-native-share#602]
## Ask your Question

Sharing = async () => {
//i'm getting path like "/storage/etc/etc/etc/filename.mp3"
        let path = global.itmes[global.identity].path 
        const Options = {
            message: 'message',
            url: "file://${path}",
            type: 'audio/mp3',
            failOnCancel: false
        }

        await Share.open(Options);

    }

**Comment by jgcmarins** [comment]
is there any error message?

**Comment by stepupithubapp** [comment]
sorry for late raply but it show me error sharing failed plz try later 
what to do i can't understand

**Comment by stepupithubapp** [comment]
hey https://github.com/jgcmarins

**Comment by stepupithubapp** [comment]
f

**Comment by jgcmarins** [comment]
can you share mp3 through other apps?

check if this helps: https://github.com/react-native-community/react-native-share/issues/603#issuecomment-539701183

**Comment by MateusAndrade** [comment]
@jgcmarins i think we need a example app sharing files with rn-share

**Comment by wezzy-web** [comment]
solved ...... but i can share mp3 from my app to whatsapp and email but it not sharing msg which i have given

**Comment by wezzy-web** [comment]
no i'm not using base64 i'm sharing from local storage whareever it is in external or internal

**Comment by wezzy-web** [comment]
@jgcmarins @MateusAndrade  hey there..

**Comment by jgcmarins** [comment]
great news
could you share the final solution?

**Comment by wezzy-web** [comment]
@jgcmarins yes i can share it i have changed share_download_paths.xml with <root-path name="root" path="." /> and it's working too good i can share any file from my real device
but now the thing is when i share on whatsapp it only shares that perticular file not message 
and when i share it on email it works subject message and file too so what to do now

**Comment by jgcmarins** [comment]
maybe the API is different for each of this app
is there any chance trying to debug this and figure out what's different?
