### ISSUE TITLE
shareSingle Facebook & Twitter on iOS not working

### ISSUE THREAD

**Issue by DenisDovganiuc** [react-native-community/react-native-share#604]
### Steps to reproduce
```
      const shareOptions = {
        url,
        social: Share.Social[social]
      }; // url is base64 data of png and social is 'FACEBOOK', 'TWITTER'

      const res = await Share.shareSingle(shareOptions);
```
### Expected behaviour
It should open the Facebook and Twitter

### Actual behaviour
App crashes

### Environment
- **React Native version**: 0.60.5
- **React Native platform + platform version**: iOS 12.3.1

### react-native-share
**Version**: 2.0.0
![IMG_20191009_200058](https://user-images.githubusercontent.com/41055443/66479960-3a97ac00-eaa6-11e9-885d-4ee5c59494cd.jpg)

**Comment by jgcmarins** [comment]
does it happens when running with [example](https://github.com/react-native-community/react-native-share/tree/master/example)?

**Comment by DenisDovganiuc** [comment]
@jgcmarins 
I didn't check the example project.
This issue happens in my react native project

**Comment by josh-deprogram** [comment]
share a strring of type `SupportedSocialApps` not `Social`
I  have a setup like this and seems all G

```
import Share, { SupportedSocialApps } from "react-native-share";
const socialType: SupportedSocialApps = "instagram";
...

const ShareOptions = {
        social: socialType
        message: shareMsg,
        url: baseImg,
        type: "image",
 };
const shareResult = await Share.shareSingle(ShareOptions);
```
