### ISSUE TITLE
cant install pod on version 1.2.1

### ISSUE THREAD

**Issue by michan85** [react-native-community/react-native-share#605]
### Steps to reproduce
1. npm i -s react-native-share@1.21
2. add to Podfile: pod 'RNShare', :podspec =>'../node_modules/react-native-share/RNShare.podspec'
3. pod install

### Expected behaviour
it should install correctly

### Actual behaviour
fails because it cant find the git tag to download

### Environment
- **React Native version**: 59.9
- **React Native platform + platform version**: iOS

### react-native-share
**Version**: 1.2.1

### Resolution
please rename/add  tag 1.2.1 to v1.2.1

### Work around
edit node_modules/react-native-share/RNShare.podspec
change source line to: (added v in front of #{s.version})
s.source       = { :git => "https://github.com/react-native-community/react-native-share.git", :tag => "v#{s.version}" }

**Comment by jgcmarins** [comment]
[v1.2.1](https://github.com/react-native-community/react-native-share/releases/tag/v1.2.1) is the last version before react native 60, so it does not support pod install
pod install is only supported by is [v2.0.0](https://github.com/react-native-community/react-native-share/releases/tag/v2.0.0)
<img width="1022" alt="Screen Shot 2019-10-13 at 13 48 39" src="https://user-images.githubusercontent.com/5133450/66718970-3a5a2200-edc0-11e9-8726-f588bb55e96f.png">
