### ISSUE TITLE
android:  Share PDF on gmail not attaching file. title is passed

### ISSUE THREAD

**Issue by SunilPandey-** [react-native-community/react-native-share#608]
### Steps to reproduce

let options = {
      type: 'application/pdf',
      subject: 'RoadMapPdf',
      showAppsToView: true,
      url: Platform.OS === 'android' ? 'file://' + this.state.fileLocation : this.state.fileLocation, // (Platform.OS === 'android' ? 'file://' + filePath)
    };
      await Share.open(options);

### Expected behaviour
Tell us what should happen
it should attach file as well. which is not happening
### Actual behaviour
Tell us what happens instead

### Environment
- **React Native version**: 0.59
- **React Native platform + platform version**: iOS 9.0, Android 5.0, etc: Android

### react-native-share
**Version**: npm version or "master"

### Link to repo (highly encouraged)
https://github.com/

**Comment by jgcmarins** [comment]
is this related: https://github.com/react-native-community/react-native-share/issues/414
?

**Comment by SunilPandey-** [comment]
Ok. used used base64 format for android and it's working.

base64 =await RNFS.readFile(fileLocation, 'base64');
      actualData = `data:application/pdf;base64,` + base64;
      await Share.open({ url: actualData });

**Comment by sudharsanvishnu** [comment]
is it possible to share the file without converting to base64.. 

item.pdf = 'http;//domain.name/randomg/sample.pdf'

eg : my code 
 const onShare = async () => {
        const shareOptions = {
            message: item.title.rendered,
            // testing 
            url: 'data:application/pdf;' + item.pdf,
            type: 'application/pdf',
            // url: 'file://' + item.pdf
        }
        try {
            const ShareResponse = await Share.open(shareOptions);
            console.log(JSON.stringify(ShareResponse));
        } catch (error) {
            console.log(' Error ', error);
        }
    };
