### ISSUE TITLE
problem with links which starts with https

### ISSUE THREAD

**Issue by lasharela** [react-native-community/react-native-share#609]
In options I'm adding url which starts with `http`. So, after https mobile is cutting a text.
I putted link in middle of the text manually but mobile is cutting rest of the text anyway.

Do you know anything about this issue guys and what is a solution?

### Environment
-  react native: 0.59.10
-  device:  samsung SM-A505U,  Android 9.0

**Comment by jgcmarins** [comment]
links with https are broken?
links with http works?
