### ISSUE TITLE
Android filename base64 is not working

### ISSUE THREAD

**Issue by brunojs02** [react-native-community/react-native-share#611]
### Steps to reproduce
1. Create a react native project.
2. Install react native share lib (yarn add react-native-share).
3. Write a basic application to share an image in base64.

### Expected behaviour
When I call Share.open({ filename: 'myimage', url: '...' }), I want that file exported to gmail with the filename passed to open method.

### Actual behaviour
The actual filename is the current timestamp.

![image](https://user-images.githubusercontent.com/7714813/67242117-39159e80-f42b-11e9-9f36-86e2b45e51f9.png)

### Environment
- 0.61.2
- Android 8.0 (emulator)

### react-native-share
2.0.0

### code example
// App.js
import React from 'react';
import {View, Button} from 'react-native';
import Share from 'react-native-share';
import {image} from './mock.json'; // image in base64

export default () => (
  <View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
    <Button title="Share" onPress={() => Share.open({filename: 'myfilename', url: image})} />
  </View>
);

### Link to repo (highly encouraged)
[Project](https://github.com/brunojs02/react-native-share-example)

**Comment by brunojs02** [comment]
Looking at the sources, i found the possible problem, in the repo the class ShareIntent has a method called getFileShare
```
String filename = null;
if (ShareIntent.hasValidKey("filename", options)) {
    filename = options.getString("filename");
}
if (ShareIntent.hasValidKey("type", options)) {
    return new ShareFile(options.getString("url"), options.getString("type"), filename, this.reactContext);
} else {
    return new ShareFile(options.getString("url"), filename, this.reactContext);
}
```
but on the version published on the npm, the source look like this
```
if (ShareIntent.hasValidKey("type", options)) {
    return new ShareFile(options.getString("url"), options.getString("type"), this.reactContext);
} else {
    return new ShareFile(options.getString("url"), this.reactContext);
 }
```

**Comment by jgcmarins** [comment]
@brunojs02 thanks for looking deeper.
Does it only happens on Android?

**Comment by brunojs02** [comment]
Yes, on iOS i dont use base64.

**Comment by brunojs02** [comment]
@jgcmarins when a new release will be available with this feature?

**Comment by jgcmarins** [comment]
is it ok on master branch?

**Comment by brunojs02** [comment]
Only work on shareSingle method.

**Comment by rrraymonde** [comment]
This issue has not been fixed, I still have the same problem as described in the first message.

**Comment by liplylie** [comment]
version `3.1.2` has a fix for this.

**Comment by MateusAndrade** [comment]
@brunojs02 can we close this?

**Comment by matheuslimatc** [comment]
3.1.1 and 3.5.0 not working for me in IOs.
