### ISSUE TITLE
IOS 12.2 Copy option with base64 img crash or stops the app

### ISSUE THREAD

**Issue by YisusMB** [react-native-community/react-native-share#618]
### Steps to reproduce
1. Make an image to share
2. Open dialog and select copy

### Expected behaviour
Only be copied and close the prompt 
### Actual behaviour
When i click in "Copy" option this breaks the app

### Here is a gif
![vid](https://user-images.githubusercontent.com/43631579/67817042-a485ee80-fa71-11e9-8f5c-5694946c81f8.gif)

### Code
Actually i use react-native-view-shot to make an base64 img for my app share
```js
  onCapture = (uri) => {
    // uri is a base64 img string
    let options = {
      url: `data:image/png;base64,${uri}`,
      message: "this is a test",
      failOnCancel: true,
      filename: "ZXZlbi1zaGFyZS5wbmc=",
    }
    console.log("do something with ", options);
    Share.open(options).then((res) => {
      console.log(res, "success")
    }).catch(e => console.log(e, "rejected share"))
  }
```

### Environment
- **React Native version**: 0.60.5
- **React Native platform + platform version**: iOS 12.2

### react-native-share
**Version**: 2.0.0"

### Link to repo (highly encouraged)
https://github.com/

**Comment by MateusAndrade** [comment]
Hi @YisusMB , thanks for sharing this with us. You can share the content logged at XCode ?

**Comment by YisusMB** [comment]
@MateusAndrade it's weird but today it fixed by itself, only restart the mac and re build the app and it works... sorry for the waste of time

**Comment by jgcmarins** [comment]
Good news!
