### ISSUE TITLE
Share video to Instagram on IOS

### ISSUE THREAD

**Issue by khylenko** [react-native-community/react-native-share#625]
I'm using "rn-fetch-blob", "react-native-fs" and "react-native-share" to share video to instagram. 
Video is downloaded from server, stored in cache, then path provided to shareOptions.

On Andrid works perfectly but on IOS post in Instagram have black preview screen.
I know that Instagram takes first frame from video to make preview and my video haven't any black frames. 
I suppose it's something wrong with "react-native-share" library, but i can't understand what is the problem

Here is the code I`m using

RNFetchBlob.config({ 
    fileCache: true, 
    appendExt: "mp4" })
    .fetch("GET", data.video)
    .then(async res => {
      const path = await res.path()
      const shareOptions = {
        url:  path,
      }
      try {
        await Share.open(shareOptions)
      ....

**Comment by khylenko** [comment]
@jgcmarins what info do you need? I will gladly supply

**Comment by jgcmarins** [comment]
Is there any error message?
or a promise rejection?

**Comment by khylenko** [comment]
@jgcmarins No. No errors, no rejections. It does transfers video to instagram app, but then it has black preview screen in instagram app and website. It happens only on IOS, android devices have no such problem.

**Comment by jgcmarins** [comment]
Got it.
Could you provide any reproducible repo?

**Comment by khylenko** [comment]
@jgcmarins I'm afraid i cant
