### ISSUE TITLE
Illegal callback invocation from native module. This callback type only permits a single invocation from native code.

### ISSUE THREAD

**Issue by NikitaNeganov** [react-native-community/react-native-share#627]
That is different from #583 

### Steps to reproduce
1. Open share dialog
2. Choose an app and cancel
3. While the dialog is still open, choose another app
4. Crash

### Expected behaviour
Choose another app and successfully share

### Actual behaviour
Trying to share through different app crashes if you previously cancelled

### Environment
- **React Native version**: 0.59.10
- **React Native platform + platform version**: iOS 13.1.3.
Does not reproduce on Android, since Android closes share dialog once you choose the app

### react-native-share
**Version**: 1.2.1

### Link to repo (highly encouraged)
https://github.com/

**Comment by jgcmarins** [comment]
Thanks for the report
might be related to https://github.com/react-native-community/react-native-share/issues/624

**Comment by NikitaNeganov** [comment]
@jgcmarins actually promise does catch when the user cancels any specific app, the problem is that there's no way (at least not in the documentation), to close the share dialog, for example. 

I.e. user chooses the app, the taps on "cancel", promise catches and then when the user tries another (or the same app) it crashes.

Bottom line - it's unlikely related

**Comment by jgcmarins** [comment]
do you know how to fix this?

**Comment by tomtargosz** [comment]
This issue was fixed by #584, we just need a new release that includes this fix. @NikitaNeganov can you test off master to see if it works for you?

**Comment by NikitaNeganov** [comment]
@tomtargosz sure, I'll post an update tomorrow, thanks

**Comment by NikitaNeganov** [comment]
@tomtargosz it appears though that master is at 2.0.0 while I'm using react-native 0.59.10 - won't that be a problem?

**Comment by NikitaNeganov** [comment]
Well, it works nevertheless so #584 does fix the problem.

On the other hand, `subject` param doesn't work anymore while sharing though ios mail or gmail, but that's whole other issue and probably due to using react-native-share@2.0.0 with react-native 0.59.10

**Comment by mikehardy** [comment]
> On the other hand, `subject` param doesn't work anymore while sharing though ios mail or gmail, but that's whole other issue and probably due to using react-native-share@2.0.0 with react-native 0.59.10

I'd be surprised if it was version interaction like that (RN59 vs RN60/61 with react-native-share v2), I'd bet that is something between react-native-share 1.x and 2.x somehow, might be possible to bisect on the commits between the two versions of react-native-share you tried, this repo doesn't have so many that it will need many bisect steps before you find the problem if that's it

**Comment by NikitaNeganov** [comment]
This fix works for ios, android doesn't build though if I use react-native-share@2.0.0 with RN 0.59.10. Looks like that `androidx` in the problem

**Comment by mikehardy** [comment]
Using anything in the react-native ecosystem right now without jetifier is about impossible.

jetifier has been added as a dependency and an included, default step in the react-native CLI for a reason

Don't avoid using the tools that make things work, set them up and use them

**Comment by Kylar13** [comment]
Hey! We've run into this issue ourselves and I wanted to ask if there's some kind of ETA for the next release that will include this?

**Comment by jgcmarins** [comment]
@Kylar13 did you tested master branch?
Is it solved for you?

**Comment by Kylar13** [comment]
@jgcmarins  Yes it did! We used the master branch, but we forced the latest commit hash, which should make it a bit safer until it's officially released

**Comment by Kylar13** [comment]
Hey! We seem to have discovered a new bug in android where the url has `\n` appended at the end. Some URL parsers are handling it fine, but some others are taking it as part of the url thus messing up our deeplinks. Also the link shows up like an array, which makes me think it's handled as an array internally and missing the final step to unwrapp it. 

Link shows like this on all major social networks when shared from android 

`["https://bla.blabla.bla/blabla\n"]`

**Comment by jgcmarins** [comment]
Thanks for you report, @Kylar13, but I think that cleaning up urls is something that should be handled on user land

**Comment by Kylar13** [comment]
I think you misunderstand. I'm passing `https://some.readable.link/foobar` as url parameter and on Android it's showing up as `["https://some.readable.link/foobar\n"]`

**Comment by jgcmarins** [comment]
Ye, sorry.
Now I get it

**Comment by Kylar13** [comment]
Update: I think the `\n` is on our end, looks like the library we use to generate deeplinks is inserting those. With plain text we're not getting that, but we are seeing the `[""]`.

So, to clarify, passing a plain string `https://some.readable.link/foobar` actually outputs `["https://some.readable.link/foobar"]`

**Comment by davidkhuu** [comment]
Forgive me since this is going a little off-topic from the original issue.

RE: @Kylar13 https://github.com/react-native-community/react-native-share/issues/627#issuecomment-553464450
I've encountered the same thing as well. On Android, I expect the `url` shared to be a string but it ends up being an array of the string. I didn't see an issue created for it in this repo so I'm not sure if it's expected behaviour or not. Have you discovered a workaround? Right now, I think I may have to pass the `url` as the `message` and leave `url` as an empty string on Android. A little hacky.. 🙈

**Comment by jgcmarins** [comment]
@davidkhuu great! Do you mind helping us with the fix? I can help you with code review.
