### ISSUE TITLE
How Can I Share Base64 File as a PDF

### ISSUE THREAD

**Issue by efecantekin** [react-native-community/react-native-share#628]
Hello,

I have a Base64 which I get from API. And I want to share it with WhatsApp and Gmail.

In ReadMe file said that I have to use RN Fetch Blob but it doesn't work with iOS 11.4.

Question 1) I've already have Base64. Do I have to use RN Fetch Blob?
Q2) Although I have Base64, why I need to save it to storage and share with storage's url?
Q3) The code on ReadMe file doesn't work for me. I wrote my code below, which part I should change?

```
const sharePDFWithIOS = () => {
    const { dirs } = RNFetchBlob.fs;

    const configOptions = {
      fileCache: true,
      path: `${dirs.DocumentDir}/${receiptTitle}.pdf`
    };

    RNFetchBlob.config(configOptions)
      .fetch('GET', documentUrl)
      .then(async (response) => {
        const filePath = response.path();
        const options = {
          type: 'application/pdf',
          url: filePath,
          subject: receiptTitle,
        };
        await Share.open(options);
        // remove the image or pdf from device's storage
        await RNFetchBlob.fs.unlink(filePath);
      });
  };

  const sharePDFWithAndroid = () => {
    Share.open({ subject: receiptTitle, filename: receiptTitle, url: `${BASE64_PREFIX}${props.receiptBase64}` });
  };
```

Thank you,

**Comment by jgcmarins** [comment]
are you seeing any error when using code described on [README](https://github.com/react-native-community/react-native-share/blob/master/README.md#share-remote-pdf-file-with-gmail--whatsapp-ios)?

**Comment by efecantekin** [comment]
Not seeing any error but never run Share.open() because RNFetchBlob.Fetch doesn't return any response.

**Comment by efecantekin** [comment]
But I have a problem with iOS also. So it's not solving my problem.

**Comment by LuizFBrisighello** [comment]
@efecantekin Did you figured it out?
