### ISSUE TITLE
SMS not showing as a share option on android

### ISSUE THREAD

**Issue by dbarner1** [react-native-community/react-native-share#631]
### Steps to reproduce
1. Set up a simple share of anything on Android
2. Run on a Moto e6 Android phone
3. Don't see the SMS sharing option.

### Expected behaviour
I should see the SMS sharing option

### Actual behaviour
I don't see the SMS sharing option

### Environment
- RN 59.4
- Android 9.0

### react-native-share
- Version 1.2.1

**Comment by jgcmarins** [comment]
does it works on other devices?
does it work on iOS?
I just want to make sure it's only related to "Moto e6"
