### ISSUE TITLE
No error thrown when saving image after camera roll permission is denied

### ISSUE THREAD

**Issue by ksesong** [react-native-community/react-native-share#635]
The bug described in issue #525 is still present in the latest version. 

There is also no error when using the *Save Image* option if the camera roll permission has manually been rejected (in the Settings app).

**Comment by jgcmarins** [comment]
@ksesong do you have a reproducible repository?
It could help to understand which behaviour it should have.

Does it only happens on iOS?

**Comment by ksesong** [comment]
I haven't tested it in iOS.

I haven't got a reproducible repository, but it is straightforward to test:
1. Share a local image (`url: ...`) with `Share.open`
2. Use the `Save image` option in the modal window.
3. Don't allow access to the permission when requested.
Instead of raising an error (so the `.catch` callback), the library behaves as if the share was successful (with the `.then` callback).
