### ISSUE TITLE
How to catch errors correclty?

### ISSUE THREAD

**Issue by NikitaNeganov** [react-native-community/react-native-share#638]
## Ask your Question

When using
```
Share.open().
  .then()
  .catch((e) => {
    //  how to handle it here?
  })
```

Say, I want to check whether catch fired because user cancelled or it is an actual error and therefore ignore calcelled events and only handle errors. How do I do that? `catch` only returns an empty object.

Is there a way to get anything out of that error and therefore handle it?

**Comment by jgcmarins** [comment]
I think that there are few scenarios where nothing is returned, specially on iOS. We're always accepting PRs to improve those workflows. I can help you with code review.

**Comment by NikitaNeganov** [comment]
Actually, I realized that for my use case it is enough to open share dialog with `failOnCancel: true` and therefore and don't have to handle `User did not share` error in the `catch` block.

**Comment by gnovo** [comment]
If you want to handle an error thrown by RNShare, you can simply check the error's message.

So, in your use case, in order to check if a user canceled, you can simply:

```
Share.open().
  .then()
  .catch((e) => {
    const userCanceled = e?.message === 'User did not share'
    
    if (userCanceled) {
      // handle error
    }
  })
```

Check: https://github.com/react-native-share/react-native-share/blob/5299d95aab25bfba6815e0f5455876897ed8ddc6/index.js#L268
