### ISSUE TITLE
How to share with both URL and message?

### ISSUE THREAD

**Issue by EnclaveAnthony** [react-native-community/react-native-share#640]
I read the document. It says : 
>NOTE: If both message and url are provided, url will be concatenated to the end of message to form the body of the message. If only one is provided it will be used

But when I try to share a video with a URL and a message. But It shows error: 

> Error: "Failure from system"

This is my code: 
``const URI64 = `data:video/mp4;base64,${URI}`;
  Share.open({message: "Paris"+ URI64,title : "Share a video"})``
URI is the base64 from local uri
Does someone can help me about that?

**Comment by jgcmarins** [comment]
Hello @EnclaveAnthony I guess that documentations are a bit misleading. Did you try to share only message or only uri?
Could you please test that for us and bring the results? Thanks.

**Comment by EnclaveAnthony** [comment]
Hi @jgcmarins.
When I try to share only message or only uri. It works perfectly.

**Comment by EnclaveAnthony** [comment]
Hi @jgcmarins.
This is my code : 
``const URI = base64.encode(this.state.uri)
        const URI64 = `data:video/mp4;base64,${URI}`
        Share.open({url : URI64, message: "Some message",title : "Title"})``
It only works well on a few apps like Mail, Imessage.
On Facebook, Instagram, and Whatsapp, It only has video and doesn't has the message.

**Comment by EnclaveAnthony** [comment]
Update : Share only message not work on facebook.

**Comment by EnclaveAnthony** [comment]
Same problem on iOS 13.

**Comment by nivas412** [comment]
> I read the document. It says :
> 
> > NOTE: If both message and url are provided, url will be concatenated to the end of message to form the body of the message. If only one is provided it will be used
> 
> But when I try to share a video with a URL and a message. But It shows error:
> 
> > Error: "Failure from system"
> 
> This is my code:
> `` const URI64 = `data:video/mp4;base64,${URI}`; Share.open({message: "Paris"+ URI64,title : "Share a video"}) ``
> URI is the base64 from local uri
> Does someone can help me about that?

Myself also having the same issue - "Failure from system" what did you done to fix this issue


here is my code :


```
   RNFS.readFile(url, 'base64')
            .then(base64 => {
                // console.warn(base64);

                let fileType = 'video/mp4'
                let base64Data = 'data:${fileType};base64,' + base64; // this works as url paramet  er
                let fileUrl = "file://" + url; // using this as url does not work

                let shareOptions = {
                    // title: 'Share',
                    message: base64Data,
                    // type: fileType,
                    // url: base64Data,

                }
                Share.open(shareOptions).then(res => {

                });

            })


```
