### ISSUE TITLE
Share cancel not rejecting promise

### ISSUE THREAD

**Issue by jehartzog** [react-native-community/react-native-share#641]
### Steps to reproduce
1. Run `Share.open(options)`, cancel dialog in iOS

### Expected behaviour
Catch an error

### Actual behaviour
No error thrown

### Environment
- RN 0.61.4
- iOS 13.2

### react-native-share
**Version**: npm version 2.0.0

### Link to repo (highly encouraged)
Will make one if desired, but this is pretty easy repro

I tried setting `failOnCancel: true` just to verify, still no effect.

**Comment by jgcmarins** [comment]
This is a known bug and already have been fix: https://github.com/react-native-community/react-native-share/issues/627
Could you please test on master branch? If you confirm it's solved, we can land a new release.
Thanks

**Comment by jehartzog** [comment]
Sorry for duplicate, I did search first but didn't read that as a dup as first.

Confirmed that master does now show the issue I listed here, thanks for quick response.

**Comment by jgcmarins** [comment]
> Sorry for duplicate, I did search first but didn't read that as a dup as first.

Don't worry.

> Confirmed that master does not have the issue I listed here, thanks for quick response.

@jehartzog that's awesome news.
I would ask if it's possible to you to keep running against master for a few days and test it.
I am quite sure it's all good and we're ready for a new release.
