### ISSUE TITLE
Video sharing via instagram will be upside down on Android.

### ISSUE THREAD

**Issue by EnclaveAnthony** [react-native-community/react-native-share#642]
### Steps to reproduce
1. Share a video via instagram

### Expected behaviour
A perfect video. 

### Actual behaviour
The video will be upside down

### Environment
- **React Native version*0.59*:
- **React Native platform + platform version**: Android 10

### react-native-share
**Version*1.2.1*: npm version or "master"

When I share a video via Instagram. It will look like that.

![Screen Shot 2019-11-27 at 15 59 33](https://user-images.githubusercontent.com/12828491/69732199-cb613e80-115d-11ea-8c67-54adc65a219c.png)

But when I click "Next" the video will be upside down. Like that : 

![Screen Shot 2019-11-27 at 15 59 52](https://user-images.githubusercontent.com/12828491/69732227-d61bd380-115d-11ea-8326-a2226337fee3.png)
How can I fix it now?

**Comment by vforvasile** [comment]
This usually happens on Emulators.

Try running on a real device.
