### ISSUE TITLE
Sigabrt when sharing to instagram

### ISSUE THREAD

**Issue by Serra19** [react-native-community/react-native-share#644]
### Steps to reproduce
Share a base64 image to instagram using singleShare on iOS.

### Expected behaviour
It should open Instagram with the image I want to share.

### Actual behaviour
It closes the app or freeze it. If I debug the app using xcode, it says "signal SIGABRT".

On Android it is working fine.

### Environment
- **React Native version**: 0.60.5
- **React Native platform + platform version**: iOS 13

### react-native-share
**Version**: 2.0.0

**Comment by acasademont** [comment]
Adding some more info, any idea of what doess that "___CRASHING_DUE_TO_PRIVACY_VIOLATION__" mean?

<img width="762" alt="Screenshot 2019-12-02 at 15 47 39" src="https://user-images.githubusercontent.com/825021/69968665-2f4b8480-151b-11ea-903d-848c1e7bb74a.png">

**Comment by acasademont** [comment]
AFAIK instagram Sharing doesn't need any special plist privacy strings

**Comment by mikehardy** [comment]
it must need at least one. bisect them by getting the full list of available ones you aren't using, add half and check, either remove half if it doesn't crash or add half the remaining if it does crash and so on. It's the only reason for that crash

**Comment by acasademont** [comment]
We're going to do that, thanks @mikehardy, we'll report back

**Comment by acasademont** [comment]
Hi all, there's actually a privacy plist that's needed for Instagram sharing after all.

```xml
<key>NSPhotoLibraryUsageDescription</key>
<string></string>
```

@jgcmarins maybe this could be added to the docs?

**Comment by jgcmarins** [comment]
> @jgcmarins maybe this could be added to the docs?

Absolutely. Do you mind sending a PR? Thank you.
