### ISSUE TITLE
IOS 13 can't share video

### ISSUE THREAD

**Issue by cherenkor** [react-native-community/react-native-share#645]
### Current Behavior

I'm trying to share locally saved video on Instagram, Twitter, Facebook, Email by using Share.shareSingle(options).
Apps open fine, but the video doesn't pass. No errors in the console.
Everything is working fine with Share.open(options)

### How to reproduce

I use:
```
Share.shareSingle({
    url: path, // /var/mobile/Containers/Data/Application/262057DF-8584-4AF8-8A56-481E0B63A143/Library/Caches/video-name.mp4
    type: 'video/mp4'
  })
```

### Environment
- **React Native version**: 0.61.3
- **React Native platform + platform version**: iOS 13.0

### react-native-share
**Version**: "master"

### Link to repo (highly encouraged)
https://github.com/cherenkor/harmix-react-native

Can you send me your account and I'll give you the access to the project?

**Comment by tai8292** [comment]
You must convert your local uri to base64 and it will work.

**Comment by EnclaveAnthony** [comment]
Yes. I have the same problem. 
I use react-native-share for Android and Share (https://facebook.github.io/react-native/docs/share) for iOS.

**Comment by jgcmarins** [comment]
@cherenkor does it works on Android?
You can add me to the repo and I can take a look.

**Comment by cherenkor** [comment]
> @cherenkor does it works on Android?
> You can add me to the repo and I can take a look.

I've added you. Could you please check it?

**Comment by cherenkor** [comment]
> Yes. I have the same problem.
> I use react-native-share for Android and Share (https://facebook.github.io/react-native/docs/share) for iOS.

How do you use it for sharing videos?

**Comment by jgcmarins** [comment]
> I've added you. Could you please check it?

Sure. I've already take a look, everything seems right.

>     url: path, // /var/mobile/Containers/Data/Application/262057DF-8584-4AF8-8A56-481E0B63A143/Library/Caches/video-name.mp4

This path seems weird.

**Comment by cherenkor** [comment]
> > I've added you. Could you please check it?
> 
> Sure. I've already take a look, everything seems right.
> 
> > ```
> > url: path, // /var/mobile/Containers/Data/Application/262057DF-8584-4AF8-8A56-481E0B63A143/Library/Caches/video-name.mp4
> > ```
> 
> This path seems weird.

Why. It's the one that the OS returns for the videos that were created within the app. We have that option. Users can record videos from the app.

**Comment by cherenkor** [comment]
> > I've added you. Could you please check it?
> 
> Sure. I've already take a look, everything seems right.
> 
> > ```
> > url: path, // /var/mobile/Containers/Data/Application/262057DF-8584-4AF8-8A56-481E0B63A143/Library/Caches/video-name.mp4
> > ```
> 
> This path seems weird.

besides, I can successfully share the video with Share.open({}) and the path is the same

**Comment by jgcmarins** [comment]
Share.open works, Share.shareSingle don't?

**Comment by cherenkor** [comment]
> Share.open works, Share.shareSingle don't That that's right

**Comment by cherenkor** [comment]
@jgcmarins any updates on that?

**Comment by chathuralakmal** [comment]
This is still not working
