### ISSUE TITLE
How can I share my file to facebook messenger?

### ISSUE THREAD

**Issue by 15110011** [react-native-community/react-native-share#647]
Hi,
I'm using this lib to share files. My problem is, I want to share a PDF file and when I hit share button, i cant find facebook messenger(installed) to share. And another problem is my social popup dont have `More` button to choose app to share. 
![Screenshot_20191213-132119](https://user-images.githubusercontent.com/37216098/70774154-fbd6e880-1dab-11ea-8a33-3fa95d81a991.png)
![Screenshot_20191213-132123](https://user-images.githubusercontent.com/37216098/70774157-fc6f7f00-1dab-11ea-8cf4-05b3c65a6d68.png)

How can i solve this or any idea? Thank you.

**Comment by jgcmarins** [comment]
Weird, all available apps should appear on this.
Maybe facebook messenger does not support pdf?
Can you try [isPackageInstalled()](https://github.com/react-native-community/react-native-share#ispackageinstalled-in-android)?

**Comment by anastely** [comment]
@jgcmarins  I'm facing the same thing and i try `isPackageInstalled()` it gives me `false`  🤷‍♂️

**Comment by jgcmarins** [comment]
Got it.
We've made a release, could you try the new version?
