### ISSUE TITLE
Share file from url

### ISSUE THREAD

**Issue by LuizFBrisighello** [react-native-community/react-native-share#648]
I'm getting a pdf file's url from my co-worker API and then display that on the screen with `react-native-pdf`. How do I go about sharing the actual pdf file?

**Comment by jgcmarins** [comment]
You can share it as a base64 or pointing to the file path

**Comment by LuizFBrisighello** [comment]
> You can share it as a base64 or pointing to the file path

Thanks for the answer!

How do I go about converting the .pdf url to a base64 string?

To point to the file path first I need to download the .pdf file right? Something like `rn-fetch-blob` should do right?

**Comment by LuizFBrisighello** [comment]
Tried to use `rn-fetch-blob` but I dont know if I'm doing it quite right.

```
  const _downloadAndShare = () => {
    const dirs = RNFetchBlob.fs.dirs

    RNFetchBlob
      .config({
        fileCache: true,
        path: dirs.DocumentDir + '/requestTicket.pdf'
      })
      .fetch('GET', ticketUrl)
      .then(async (res) => {
        const filePath = res.path()
        console.log('The file saved to ', filePath)

        const options = {
          type: 'application/pdf',
          url: `file:/${filePath}`
        }

        try {
          await Share.open(options)
          await RNFetchBlob.fs.unlink(filePath)
        } catch (error) {
          console.log('Error =>', error)
        }
      })
  }
```
The share dialog opens normally but after I choose where do I want to share he file (in my case WhatsApp), I got a pop up saying "Fail to share, try again"

**Comment by LuizFBrisighello** [comment]
Converting to base64 works ok-ish.

```
  const _shareTicketPdf = async () => {
    const options = {
      type: 'application/pdf',
      message: 'Heres the .pdf file',
      url: bill.pdfBill
    }

    try {
      await Share.open(options)
    } catch (error) {
      console.log('Error =>', error)
    }
  }
```
It shares the actual .pdf file but the message inst shared with it, and I dont know if its possible t change the file name

**Comment by LuizFBrisighello** [comment]
Oh .. #629

**Comment by LuizFBrisighello** [comment]
> Tried to use `rn-fetch-blob` but I dont know if I'm doing it quite right.
> 
> ```
>   const _downloadAndShare = () => {
>     const dirs = RNFetchBlob.fs.dirs
> 
>     RNFetchBlob
>       .config({
>         fileCache: true,
>         path: dirs.DocumentDir + '/requestTicket.pdf'
>       })
>       .fetch('GET', ticketUrl)
>       .then(async (res) => {
>         const filePath = res.path()
>         console.log('The file saved to ', filePath)
> 
>         const options = {
>           type: 'application/pdf',
>           message: 'Message here',
>           url: `file:/${filePath}`
>         }
> 
>         try {
>           await Share.open(options)
>           await RNFetchBlob.fs.unlink(filePath)
>         } catch (error) {
>           console.log('Error =>', error)
>         }
>       })
>   }
> ```
> 
> The share dialog opens normally but after I choose WhatsApp, I got a pop up saying "Fail to share, try again", other options only share the message but not the file.
> 
> Im testing on a physical android device, react-native 60.5

I guess #629

**Comment by anastely** [comment]
@LuizFBrisighello hey, are you solve it?

**Comment by LuizFBrisighello** [comment]
@anastely Not at all. Priorities changed, so I had to move to other tasks for a while

**Comment by LuizFBrisighello** [comment]
Sharing as a base64 is still an issue, even on `3.0.0`. No message with file and no filename.
