### ISSUE TITLE
add filename parameter in V1.x

### ISSUE THREAD

**Issue by badaz** [react-native-community/react-native-share#649]
Thanks for this nice lib! I need to specify a filename for my base64 file so that when I share it by email, the filename is human readable. However I'm stuck using react-native v0.59 at the moment (because of other libs very hard to migrate) so I wonder if you plan to make the filename parameter available in the v1 version of the lib?

**Comment by mikehardy** [comment]
Use the most currently libs you can, for those that moved to AndroidX (like this one), use `jetifier -r`

https://github.com/mikehardy/jetifier#to-reverse-jetify--convert-node_modules-dependencies-to-support-libraries

**Comment by badaz** [comment]
Thanks, I was about to edit my issue since I found the jetifier trick reading another issue. However I can't make the filename parameter work, event using V2.0.0 (method open and/or shareSingle). I've looked at the code and there is really no reason why this should not work, I pass the simplest string "file", yet the attachement in the email ends up having a nanotime generated name. I guess this is another issue however.

**Comment by mikehardy** [comment]
> I've looked at the code and there is really no reason why this should not work, I pass the simplest string "file", yet the attachement in the email ends up having a nanotime generated name. I guess this is another issue however.

I concur

**Comment by badaz** [comment]
ok, I think this is because I am not using master but 2.0.0 from npm, which does not include the filename thing, found a hint in https://github.com/react-native-community/react-native-share/issues/611

**Comment by jgcmarins** [comment]
@badaz master branch solved your problem?
Let us know if there is any issue going on master.
We're planning a release. Thanks.

**Comment by badaz** [comment]
@jgcmarins yes, it is working with master, but only when using shareSingle, as hinted in https://github.com/react-native-community/react-native-share/issues/611, and not when using open. If it is a quick fix it would be great to make it work with open.

**Comment by badaz** [comment]
@jgcmarins please keep me updated on this, since if you're not fixing the `filename` parameter not working in the `open` method I might consider creating a Pull Request
