### ISSUE TITLE
Share.open does not work on any file on Android 10

### ISSUE THREAD

**Issue by davidmarinangeli** [react-native-community/react-native-share#650]
### Steps to reproduce
1. Implement Share.open on Android 10 device

### Expected behaviour
It should share the document 

### Actual behaviour
It tells "unsupported attachment" in any app I try. 

### Environment
- **React Native version**: 0.59.10
- **React Native platform + platform version**: Android 10

### react-native-share
**Version**: 1.2.1

The path is local and it does work normally on Android <=9 /  iOS
```
             Share.open({
                message: localizations.formatString<string>(
                  localizations.document,
                  this.state.item!.visible_subject || ''
                ) as string,
                url: `file://${pathToFile}`,
                type: mime.lookup(pathToFile) as string,
                showAppsToview: true
              })
                .then(val => console.log(val))
                .catch(err => err.error !== 'User did not share' && this.showErrorBox(localizations.share_error))
```

**Comment by jgcmarins** [comment]
@davidmarinangeli thanks for your report.
We gonna have to deep dive into Android 10 API to understand what's going on.

**Comment by davidmarinangeli** [comment]
Thanks for your quick response. The problem seems to be related to `RNFetchBlob` that fails to download the file. It returns the download path but nothing is generated.

I will update you asap

**Comment by bansaripatel2530** [comment]
I'm facing same issue and it is working fine with Android 10 after add this line in **_AndoridManifest.xml_** in <application> tag.
`android:requestLegacyExternalStorage="true"`

**Comment by morelgarisi** [comment]
by adding android:requestLegacyExternalStorage="true" in <application> inside AndroidManifest.xml file im getting error after changing to api 29 

AILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  /Users/david/Documents/projects/hicar_v3/android/app/build/intermediates/merged_manifests/debug/arm64-v8a/AndroidManifest.xml:60: AAPT: error: attribute android:requestLegacyExternalStorage not found.
      
  error: failed processing manifest.

anyone?

**Comment by morelgarisi** [comment]
> I was facing the same issue. I have solved the issue by adding `android:requestLegacyExternalStorage="true"` in `<application>` inside `AndroidManifest.xml` file.
by adding android:requestLegacyExternalStorage="true" in inside AndroidManifest.xml file im getting error after changing to api 29

AILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:processDebugResources'.
Android resource linking failed
/Users/david/Documents/projects/hicar_v3/android/app/build/intermediates/merged_manifests/debug/arm64-v8a/AndroidManifest.xml:60: AAPT: error: attribute android:requestLegacyExternalStorage not found.

error: failed processing manifest.

anyone?

**Comment by morelgarisi** [comment]
> I was facing the same issue. I have solved the issue by adding `android:requestLegacyExternalStorage="true"` in `<application>` inside `AndroidManifest.xml` file.

by adding android:requestLegacyExternalStorage="true" in inside AndroidManifest.xml file im getting error after changing to api 29

AILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:processDebugResources'.
Android resource linking failed
/Users/david/Documents/projects/hicar_v3/android/app/build/intermediates/merged_manifests/debug/arm64-v8a/AndroidManifest.xml:60: AAPT: error: attribute android:requestLegacyExternalStorage not found.

error: failed processing manifest.

anyone?

**Comment by kotunde** [comment]
> > I was facing the same issue. I have solved the issue by adding `android:requestLegacyExternalStorage="true"` in `<application>` inside `AndroidManifest.xml` file.
> 
> by adding android:requestLegacyExternalStorage="true" in inside AndroidManifest.xml file im getting error after changing to api 29
> 
> AILURE: Build failed with an exception.
> 
> What went wrong:
> Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
> /Users/david/Documents/projects/hicar_v3/android/app/build/intermediates/merged_manifests/debug/arm64-v8a/AndroidManifest.xml:60: AAPT: error: attribute android:requestLegacyExternalStorage not found.
> 
> error: failed processing manifest.
> 
> anyone?

Add this attribute to your manifest markup : ```xmlns:tools="http://schemas.android.com/tools"```
Source: https://stackoverflow.com/questions/55334431/facing-below-error-toolsnode-associated-with-an-element-type-uses-permission

**Comment by sanimridha** [comment]
> I was facing the same issue. I have solved the issue by adding `android:requestLegacyExternalStorage="true"` in `<application>` inside `AndroidManifest.xml` file.

Thanks for your answer while mentioning ### `<application>` inside `AndroidManifest.xml` file.
