### ISSUE TITLE
Share to instagram feed

### ISSUE THREAD

**Issue by 1nfinite** [react-native-community/react-native-share#651]
How can i share to instagram feed?
I have code as below but i have only option for instagram direct in my android device share (no instagram feed in the share selection)
Am i missing some configuration and where and how should i include the product image?

What am i intend to achieve:
- Share my product image to instagram feed (with title, description and product website url)

```
  const options = {
    url: 'http://www.shop.com/product/1',
    message: 'Product 1',
    title: 'Product 1'
  }

  Share.open(options)
    .then((res) => { console.log(res) })
    .catch((err) => { err && console.log(err); });
```

**Comment by tiwus** [comment]
Have you tried Share.shareSingle(options)?

**Comment by ismaelbarry** [comment]
Hey! Just wondering if anyone was able to find a solution to this issue. If so, I'd love to know. Thanks!

**Comment by chiny20035** [comment]
I can't send multiple images to instagram!
