### ISSUE TITLE
How to pass facebook application id in react-native code.

### ISSUE THREAD

**Issue by harleenarora** [react-native-community/react-native-share#653]
HI, I am using this package, its working good but requirement are:

-> I call the my app load rest api and get the facebook application id form api response. Set the application id. On click login button get the user facebook account details and after get the user facebook details call my rest API.

So how to pass the application id on react-native code rather then android. Please tell me how to do this?

**Comment by jgcmarins** [comment]
Hi, I am afraid I couldn't understand what you mean.
Sorry.

**Comment by AmirDiafi** [comment]
You must implement Facebook SDK ( Meta SDK now ); you'll get an appid.
1- open Facebook Developer account, here => https://developers.facebook.com
2- integrate the SDK in your application following this link => https://github.com/thebergamo/react-native-fbsdk-next
