### ISSUE TITLE
Share Instagram Story

### ISSUE THREAD

**Issue by Rizaldinurm** [react-native-community/react-native-share#656]
## Ask your Question

This is my options:
`ShareData.shareSingle({
          url: 'data:image/png;base64,' + imageData,
          title: "Share via",
          type: "image/png",
          message: "Share to instagram",
          // social: ShareData.Social.INSTAGRAM
        })
`
But my device always redirect to Feed Instagram, but I want to Instagram Story.
is my options miss something?

**Comment by beardwin** [comment]
looking at #556 it sounds like IG stories were rolled back, but there is some energy to bring it back.

**Comment by beardwin** [comment]
Looks like there's an open PR for this: #600 

**Comment by MateusAndrade** [comment]
@beardwin  we are looking for some help to test this on IOS using the Release build. Could you help us with that? 😄

**Comment by beardwin** [comment]
@MateusAndrade was ahead of you on that. ;) check the PR, I posted a comment. We can move any discussion there. 

Cheers!

**Comment by MateusAndrade** [comment]
For anyone looking for this feature, we just merge #600 at `master`. Please, let us know if anyone found any breaking change at this process.
