### ISSUE TITLE
Message is not coming sharing through Facebook

### ISSUE THREAD

**Issue by NZOleg** [react-native-community/react-native-share#658]
Hi, I'm trying to share the message through facebook and using the following the following code:

```
Share.shareSingle({
  title: "Share via",
  message: "some message here",
  social: Share.Social.FACEBOOK
})
  .then(res => {
    console.log(res);
  })
  .catch(err => {
    err && console.log(err);
  });

```

### Expected behaviour
It should open "Create Post" on Facebook with "some message here" message

### Actual behaviour
It opened  "Create Post" on Facebook with no message in it. Url comes through if I include it in options
If I try to share with messager, it works just fine.

### Environment
- **React Native version**:  "react-native": "0.61.2",
- **React Native platform + platform version**:  Pixel 2, Android 9.0 (haven't tested on IOS yet)

### react-native-share
"react-native-share": "^2.0.0",

**Comment by EnclaveAnthony** [comment]
Facebook doesn't allow any prefill message. You can share it with a hashtag. You can use react-native-fbsdk to do that.

**Comment by brambang** [comment]
> Facebook doesn't allow any prefill message. You can share it with a hashtag. You can use react-native-fbsdk to do that.

is it possible to use hashtag here??

**Comment by NZOleg** [comment]
brambang, I couldn't figure it out, so I ended up sharing just a link

**Comment by felire** [comment]
But why is it working for ios and not for android? Anyone know why?

**Comment by rohit75** [comment]
So is there any way to share message or react-native-fbsdk is the only way to do that?

**Comment by LyonRH** [comment]
Is there any other solution besides react-native-fbsdk-next?
