### ISSUE TITLE
no callback found with cbID 

### ISSUE THREAD

**Issue by AlkanV** [react-native-community/react-native-share#659]
### Steps to reproduce
1. Setup Share with your app.
2.Call share.open()
3.press save to files. then cancel it. it will throw no callback found with cbID for RNSHare.Open. Most likely the callback was already invoked.
### Expected behaviour
It should close opened modal

Actual behaviour
when i try to close opened modal after cancelling save to files, it is throwing error started with 'no callback found with cbID'

Environment
React Native version:   "react-native": "0.60.0",
React Native platform + platform version: iOS13
react-native-share
"react-native-share": "^2.0.0",

**Comment by tomasvarga** [comment]
This bug is not present in the release mode meaning the app will not crash from my test. That said, it's still an issue...

Possible **workaround** leaving this here if someone would like to use it: 

Go to `RNShare.m` and **add before** 
https://github.com/react-native-community/react-native-share/blob/f706e8cae5b21079c2716998911ad86e0cd1e8ac/ios/RNShare.m#L192

**this line** 
```objective-c
...
            [controller  dismissViewControllerAnimated:true completion:nil];
            failureCallback(activityError);
...
```

This will close the Save to File modal and also sharing activity so **it will prevent callbacks to be called numerous times.**

**Comment by tailorem** [comment]
In addition to 'Save to Files', I have also seen this issue with 'Create Watch Face'. Although my app doesn't crash in release mode, this issue does seem to prevent the Share dialog from opening again.

Have not tried the workaround yet.

**Comment by kidroca** [comment]
I'm getting the same error 
Is this fatal ? 

Also if you press "Save to files" then "Cancel" then "Save to files" again you'll get the following error: 
```sh
Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
```

But then if I save the file it seems to be saved OK

**Comment by rraczae** [comment]
Still there

**Comment by majirosstefan** [comment]
so, is this a problem or not in release mode ?

**Comment by mikehardy** [comment]
@majirosstefan unsure - what did you find when you investigated? https://stackoverflow.com/help/how-to-ask / https://stackoverflow.com/help/minimal-reproducible-example

Please share the results of your investigations

**Comment by kidroca** [comment]
We didn't have any problems with this in a prod release
Haven't worked on that project for more than an year, but there were no sharing issues reported ever, and we couldn't recreate as well
