### ISSUE TITLE
_reactNative.NativeModules.RNShare.shareSingle error

### ISSUE THREAD

**Issue by crivera** [react-native-community/react-native-share#66]
Hi

i installed the library using npm and did react-native link.

when i try to do the share i get the following error: 

Possible Unhandled Promise Rejection (id: 0):
Cannot read property 'shareSingle' of undefined
TypeError: Cannot read property 'shareSingle' of undefined

It seems like it cant find the native modules even though i did react-native link

any help?

Thanks
Chris

**Comment by abeauvois** [comment]
In the source we see both methods 'open' and 'shareSingle' are Promises so we have to handle them: 
```
Share.open(shareOptions)
.catch(err => console.log(err))
```
You should mention this in the readme in addition to fixing the issue.
Thx for this useful component btw.

**Comment by agrawalo** [comment]
I am still facing this issue. Any help https://stackoverflow.com/questions/49082623/react-native-share-promise-rejection-error ??

**Comment by enieber** [comment]
try with the new version of lib
