### ISSUE TITLE
shareSingle not working on iOS

### ISSUE THREAD

**Issue by EnclaveAnthony** [react-native-community/react-native-share#660]
### Steps to reproduce
1. shareSingle video via WhatsApp.
2. Open the appstore

### Expected behaviour
Open WhatsApp

### Actual behaviour
Open WhatsApp page on the app store

### Environment
- **React Native version**: 0.61.5
- **React Native platform + platform version**: iOS 13.0,

### react-native-share
**Version**: 2.0.0
`const result = await Share.shareSingle({
                    title: "Title ",
                    message: "My message",
                    url: this.state.uri,
                    social  : "whatsapp",
                })`

**Comment by hiteshagja** [comment]
It's not working in android as well. All other sharing options working fine except whatsapp. RN = 0.61

**Comment by EnclaveAnthony** [comment]
I check the native code on iOS. It uses UIDocumentInteractionController to share. But when I checked, I saw UIDocumentInteractionController will open all of the apps which can share my content. So I think share single media via Whatsapp is impossible now.

**Comment by hiteshagja** [comment]
Ohh ok and thanks for your reply. 

any other workaround you suggest?

**Comment by EnclaveAnthony** [comment]
You can you the open(options) method.

**Comment by neemssoni** [comment]
shareSingle does not work for whats app in Android also as well as on iOS..

**Comment by MateusAndrade** [comment]
> shareSingle does not work for whats app in Android also as well as on iOS..

Did you have any Logcat that can help us debugging this?

**Comment by shamshiranees** [comment]
I am also facing same issue. SingleShare opens appstore page of the app.I tried with Instagram, facebook and whatsapp.

**Comment by loikfb** [comment]
@shamshiranees You need to add LSApplicationQueriesSchemes key in your info.plist, with value(s) in an array. For example, Instagram it's the value "instagram".

**Comment by GhayoorUlHaq** [comment]
Already added but whatsapp is not getting opened.
