### ISSUE TITLE
Android file name isn't working on release android builds

### ISSUE THREAD

**Issue by latusdenis** [react-native-community/react-native-share#662]
### Steps to reproduce
1. Share android base64
```
Share.open({
      url: `data:text/comma-separated-values;base64,${Base64.encode(file)}`,
      type: 'text/comma-separated-values',
      filename: 'test'
});
```
2. ```cd android && ./gradlew assembleRelease```
3. Timestamp is displayed instead of the filename

### Expected behavior
The android filename feature is working correctly on android release builds.

### Actual behavior
There was the pull request, which adds a feature of adding the filename for android. https://github.com/react-native-community/react-native-share/pull/565

At the master branch, it's working correctly on dev environment, if I run ```react-native run-android```, but not for the release builds.

I've tried to install the lib from the merged commit and it's working correctly:
`"react-native-share": "git+https://github.com/react-native-community/react-native-share.git#c29c10d"
`
It seems like the latest changes to master broke this feature.

Also, is it possible to create a stable release instead of pulling the master? 
### Environment
"react-native": "0.60.5"

### react-native-share
master

**Comment by appasaheb4** [comment]
store on secoundary storage and write and read.

**Comment by appasaheb4** [comment]
file:// add before read time

**Comment by latusdenis** [comment]
@appasaheb4 I didn't get you. What do you mean by ```store on secoundary storage and write and read.```?

**Comment by appasaheb4** [comment]
store file in secondary storage and write and read.

**Comment by latusdenis** [comment]
@appasaheb4 How would it solve the issue, that the file name is appearing in a wrong format? As I mentioned before, it’s working correctly out of the box in dev builds

**Comment by LuizFBrisighello** [comment]
For me on `rn 0.60.5` and `react-native-share 3.0.0` filename does not work when sharing a base64 pdf file, didnt tryied with other file types yet. heres my code:

```
  async function handleShare () {
    const fileUrl = ticketUrl
    let filePath = null
    let file_url_length = fileUrl.length
    const configOptions = { fileCache: true }
    RNFetchBlob.config(configOptions)
      .fetch('GET', fileUrl)
      .then(resp => {
        filePath = resp.path()
        return resp.readFile('base64')
      })
      .then(async data => {
        const base64Data = (await 'data:application/pdf;base64,') + data
        try {
          await Share.open({
            url: base64Data,
            title: 'title',
            subject: 'subject',
            message: 'My message'
          })
          // remove the image or pdf from device's storage
          await RNFetchBlob.fs.unlink(filePath)
        } catch (error) {
          console.log(error)
        }
      })
  }
```
