### ISSUE TITLE
shareSingle Share.Social.FACEBOOK not open FB Lite Apps

### ISSUE THREAD

**Issue by brambang** [react-native-community/react-native-share#664]
### Steps to reproduce

```
const shareOptions = {
  title: shareTitle,
  message: shareMessage,
  social: Share.Social.FACEBOOK
};
Share.shareSingle(shareOptions);
```

### Expected behaviour
Open FB apps (FB Lite installed) or play store.

### Actual behaviour
Not open FB Lite
error showing:
```
Object {
  "error": "url",
}
```

_**UPDATE:**_
1. I add URL, then it would open a browser
But, why we have to add an URL??
I want to send message only.
is it bug??
(as i check the redirect URL contain url as query get in **FacebookShare.java**)

2. I install FB apps, yes it works open the apps.
But the problem why there is no messages??
same issue when we use Share.open
is it any other way to share a message (quote)?
 
### Environment
- **React Native version**: 0.58
- **React Native platform + platform version**: Android

### react-native-share
**Version**: 1.2.1

**Comment by brambang** [comment]
UPDATE 2:
1. i have workaround to make shareSingle FB to check both of FB apps & FB Lite.

i am edit **FacebookShare.java** in _android/src/main/java/cl/json/social/_
and using getPlayStoreLink to add FB lite package name

```
private static final String PACKAGE_LITE = "com.facebook.lite";
@Override
protected String getPlayStoreLink() {
    return PACKAGE_LITE;
}
```

and open **SingleShareIntent.java** in _android/src/main/java/cl/json/social/_
and in row 34 add `else if` to check getPlayStoreLink as package

```
...
} else if (this.isPackageInstalled(getPlayStoreLink(), reactContext)) {
    System.out.println("INSTALLED");
    this.getIntent().setPackage(getPlayStoreLink());
    super.open(options);
} else {
...
```

as i check this work around works as expected and no problem in other apps singleShare.

2. BUT IM STILL CANNOT POST MESSAGE IN FB APPS.
FB Lite has different behaviour, i can post message in it.

**Comment by Ahmed-Imam** [comment]
I am still experiencing this issue with the latest version of react-native-share, it works fine on instagram, the issue happens only on facebook in my end. any updates on this ?
