### ISSUE TITLE
Implicit conversion of ‘int’ to ‘UIViewController *’ is disallowed with ARC

### ISSUE THREAD

**Issue by Pifoupif** [react-native-community/react-native-share#667]
I followed the setup steps from your github page. Tried both the yarn and npm versions of react-native-share. I'm unable to build our app on xcode after installing the library.
I always get the same error message when xcode tries to build your library:
`Implicit conversion of ‘int’ to ‘UIViewController *’ is disallowed with ARC`

I've also tried disabling ARC from xcode but the error remains.

Actual setup:
1. "react-native": "0.59.9"
2. "react-native-share": "1.2.1",
3. Build the app on xCode

Also tried with the following setup:
1. "react-native": "0.61.5"
2. "react-native-share": "2.0.0",
3. Build the app on xCode

Does anyone have any clues what the problem could be ? Happy to share the specific line where this happens.

Thanks

**Comment by XunlaY** [comment]
Had the same issue when upgrading react-native and adding Pods to our project.
Seems that we missed the React-Core pod, where that referenced ViewController came from:
`pod 'React-Core', :path => '../node_modules/react-native/'`

Adding this to our Podfile (and all other missing frameworks) solved it for us:
http://facebook.github.io/react-native/docs/integration-with-existing-apps#configuring-cocoapods-dependencies
