### ISSUE TITLE
shareSingle Share.Social.INSTAGRAM not working on iOS

### ISSUE THREAD

**Issue by SeraphimaZ** [react-native-community/react-native-share#669]
### Steps to reproduce
share png image encoded in base64 to instagram

       const shareOptions = {
        url: 'data:image/png;base64,' + base64Image,
        type: 'base64',
        social: Share.Social.INSTAGRAM,
      };

      Share.shareSingle(shareOptions)
        .then(res => {
          console.log('succeeded: ', res);
        })
        .catch(rej => {
          console.log('failed', rej);
        });

### Expected behaviour
Open Instagram app with sharing image. 

### Actual behaviour
App exits silently, Instagram doesn't open. 
On Android this code works as expected. 

### Environment
- **React Native version**: 0.61.4
- **React Native platform + platform version**: iOS 13.3

### react-native-share
**Version**: 2.0.0

### Link to repo (highly encouraged)
https://github.com/SeraphimaZ/Affirmations

**Comment by anuragipankaj** [comment]
facing same issue :(
