### ISSUE TITLE
No message when is sharing a pdf on IOS

### ISSUE THREAD

**Issue by LekZ974** [react-native-community/react-native-share#670]
### Steps to reproduce
share a pdf for IOS with a message:
`const options = {
        title: name,
        type: 'application/pdf',
        message: message,
        url: url
      };
        await Share.open(options);
        await fs.unlink(url);
      }`

It's ok on android platform
### Expected behaviour
expect to share a pdf file on IOS with a message: ex: 'Toto share this document with you <pdfFile.pdf>'

### Actual behaviour
Only share the pdf file without the message

### Environment
- **React Native version**: 0.61.5
- **React Native platform + platform version**: iOS 13.3

### react-native-share
**Version**: 2.0.0

**Comment by LuizFBrisighello** [comment]
Maybe thats fixed on `3.0.0`. It worked fine for me with `react-native` `0.60.5`

```
  async function handleShare () {
    const fileUrl = ticketUrl
    let filePath = null
    let file_url_length = fileUrl.length
    const configOptions = { fileCache: true }
    RNFetchBlob.config(configOptions)
      .fetch('GET', fileUrl)
      .then(resp => {
        filePath = resp.path()
        return resp.readFile('base64')
      })
      .then(async data => {
        const base64Data = (await 'data:application/pdf;base64,') + data
        try {
          await Share.open({
            url: base64Data,
            title: 'title',
            subject: 'subject',
            message: 'My message'
          })
          // remove the image or pdf from device's storage
          await RNFetchBlob.fs.unlink(filePath)
        } catch (error) {
          console.log(error)
        }
      })
  }
```
