### ISSUE TITLE
singleShare Messenger, SMS , SnapChat not working, 

### ISSUE THREAD

**Issue by desis123** [react-native-community/react-native-share#672]
singleShare f Messenger, SMS , SnapChat  on Android not working thowing the following error message.

Error => {"error": "key 'social' missing in options"}

**Comment by felire** [comment]
Same issue here

**Comment by felire** [comment]
If you write 'messenger' instad of using Share.Social.MESSENGER will work. I don't know why MESSENGER is not defined in constants of this library

**Comment by desis123** [comment]
That means I have to write lowercase .. like this Share.Social.messenger  or just messenger?
