### ISSUE TITLE
App Icon is missing

### ISSUE THREAD

**Issue by Sach-SPF** [react-native-community/react-native-share#676]
### Steps to reproduce
1. iOS 13
2. Add "message" property to the options
3. App icon is missing

### Expected behaviour
App Icon should appear

### Actual behaviour
App Icon is missing

### Environment
- **React Native version**: 59.9

The app icon seems to be hidden or remove or missing when I used "Message" property else its appear

ActionSheet without Message 
<img width="260" alt="Screen Shot 2020-01-16 at 7 33 28 PM" src="https://user-images.githubusercontent.com/28600651/72531356-465df000-3897-11ea-8f3e-d7ecb416a4bc.png">

ActionSheet with Message

<img width="264" alt="Screen Shot 2020-01-16 at 7 37 09 PM" src="https://user-images.githubusercontent.com/28600651/72531466-8e7d1280-3897-11ea-9f61-20cc9338e1e3.png">

<img width="358" alt="Screen Shot 2020-01-16 at 7 38 01 PM" src="https://user-images.githubusercontent.com/28600651/72531531-ac4a7780-3897-11ea-9250-3da3751a0a42.png">

Thanks
Sachin

**Comment by RavindraV07** [comment]
Iam facing same issue in iOS V13.3

**Comment by ansalspurtree** [comment]
I am also facing the same issue. any fix?

**Comment by bataevvlad** [comment]
Facing same issue

**Comment by sercanuste** [comment]
Hi,

You can use following code for App Icon.

Tested on; iOS 13.3.1,
"react": "16.8.3",
"react-native": "0.59.9",
"react-native-share": "3.1.2"

---
```javascript
const url = 'https://awesome.contents.com/';
const message = 'Please check this out.';
const logo = 'data:<data_type>/<file_extension>;base64,<base64_data>';

const options = Platform.select({
    ios: {
        activityItemSources: [
            {
                placeholderItem: {
                    type: 'url',
                    content: logo
                },
                item: {
                    default: {
                        type: 'text',
                        content: `${message} ${url}`
                    },
                },
                linkMetadata: {
                    title: message,
                    icon: logo
                }
            }
        ],
    },
    default: {
        message: `${message} ${url}`
    },
});

Share.open(options)
    .then((res) => { console.log(res) })
    .catch((err) => { console.log(err); });
```

**Comment by sumit31agarwal** [comment]
what about if we are using expo ,  I am using Share from react native and below is the screenshot what I am getting 
<img width="338" alt="Screenshot 2021-09-16 at 5 40 02 PM" src="https://user-images.githubusercontent.com/88984245/133609685-ac46651b-3319-4812-ba00-9851cca5e639.png">

**Comment by akilamist** [comment]
@sumit31agarwal any luck on above ?
