### ISSUE TITLE
Key android.intent.extra.STREAM expected ArrayList but value was a android.net.Uri$HierarchicalUri

### ISSUE THREAD

**Issue by rishabhsaxena** [react-native-community/react-native-share#677]
## Ask your Question
Unable to share a local image file to whatsapp on android. Has anyone come across a similar error?
react-native: 0.59.x
react-native-share: 1.2.1

Key android.intent.extra.STREAM expected ArrayList but value was a android.net.Uri$HierarchicalUri.  The default value <null> was returned.
01-17 23:49:41.223 19798 19798 W Bundle  : Attempt to cast generated internal exception:
01-17 23:49:41.223 19798 19798 W Bundle  : java.lang.ClassCastException: android.net.Uri$HierarchicalUri cannot be cast to java.util.ArrayList
01-17 23:49:41.223 19798 19798 W Bundle  : 	at android.os.Bundle.getParcelableArrayList(Bundle.java:1011)
01-17 23:49:41.223 19798 19798 W Bundle  : 	at com.whatsapp.ContactPickerFragment.A0q(:275573)
01-17 23:49:41.223 19798 19798 W Bundle  : 	at com.whatsapp.ContactPickerFragment.A0e(:275123)
01-17 23:49:41.223 19798 19798 W Bundle  : 	at X.1YA.A0j(:187261)
01-17 23:49:41.223 19798 19798 W Bundle  : 	at X.1YA.A0d(:186839)
01-17 23:49:41.223 19798 19798 W Bundle  : 	at X.1YA.A0U(:186617)
01-17 23:49:41.223 19798 19798 W Bundle  : 	at X.1YA.A0T(:186606)
01-17 23:49:41.223 19798 19798 W Bundle  : 	at X.2Ft.onStart(:271305)
01-17 23:49:41.223 19798 19798 W Bundle  : 	at X.2IO.onStart(:281378)
01-17 23:49:41.223 19798 19798 W Bundle  : 	at X.2Lz.onStart(:291874)
01-17 23:49:41.223 19798 19798 W Bundle  : 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
01-17 23:49:41.223 19798 19798 W Bundle  : 	at android.app.Activity.performStart(Activity.java:7848)
01-17 23:49:41.223 19798 19798 W Bundle  : 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
01-17 23:49:41.223 19798 19798 W Bundle  : 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
01-17 23:49:41.223 19798 19798 W Bundle  : 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
01-17 23:49:41.223 19798 19798 W Bundle  : 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
01-17 23:49:41.223 19798 19798 W Bundle  : 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
01-17 23:49:41.223 19798 19798 W Bundle  : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
01-17 23:49:41.223 19798 19798 W Bundle  : 	at android.os.Handler.dispatchMessage(Handler.java:107)
01-17 23:49:41.223 19798 19798 W Bundle  : 	at android.os.Looper.loop(Looper.java:214)
01-17 23:49:41.223 19798 19798 W Bundle  : 	at android.app.ActivityThread.main(ActivityThread.java:7356)
01-17 23:49:41.223 19798 19798 W Bundle  : 	at java.lang.reflect.Method.invoke(Native Method)
01-17 23:49:41.223 19798 19798 W Bundle  : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-17 23:49:41.223 19798 19798 W Bundle  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
01-17 23:49:41.224  1427  4306 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY

**Comment by KingAmo** [comment]
@rishabhsaxena have solved this issue ? i have the same problem, would you like to help please?
