### ISSUE TITLE
Support for iOS dark mode?

### ISSUE THREAD

**Issue by craftmusic** [react-native-community/react-native-share#679]
Hi, can you provide forced dark mode in iOS?

Also, I think the App Store may require that there is support for both light and dark modes; currently if I set my iPhone to dark mode, the share sheet in the app stays light.

**Comment by HrantAbrahamyan** [comment]
in your info.plist add the following line
![image](https://user-images.githubusercontent.com/36418107/82910034-2643e900-9f7b-11ea-98cf-3c62b7e1b443.png)

**Comment by MateusAndrade** [comment]
> in your info.plist add the following line
> ![image](https://user-images.githubusercontent.com/36418107/82910034-2643e900-9f7b-11ea-98cf-3c62b7e1b443.png)

Thanks! Would you mind adding this to our docs? 😄
