### ISSUE TITLE
Unable to run example

### ISSUE THREAD

**Issue by resting** [react-native-community/react-native-share#684]
Have done the followings in the example folder,

```
npm i
npm start
npx react-native run-ios --simulator "iPhone 11 Pro Max"
```

I get the following errors:

```
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening example.xcworkspace. Run CLI with --verbose flag for more details.
User defaults from command line:
    IDEDerivedDataPathOverride = [user]/react-native-share/example/ios/build/example

note: Using new build system
note: Planning build
note: Constructing build description
error: [user]/react-native-share/example/ios/Pods/Pods/Target Support Files/Pods-example/Pods-example.debug.xcconfig: unable to open file (in target "example" in project "example") (in target 'example' from project 'example')
error: [user]/react-native-share/example/ios/Pods/Pods/Target Support Files/Pods-example/Pods-example.debug.xcconfig: unable to open file (in target "example" in project "example") (in target 'example' from project 'example')
error: [user]/react-native-share/example/ios/Pods/Pods/Target Support Files/Pods-example/Pods-example.debug.xcconfig: unable to open file (in target "example" in project "example") (in target 'example' from project 'example')
error: [user]/react-native-share/example/ios/Pods/Pods/Target Support Files/Pods-example/Pods-example.debug.xcconfig: unable to open file (in target "example" in project "example") (in target 'example' from project 'example')
error: [user]/react-native-share/example/ios/Pods/Pods/Target Support Files/Pods-exampleTests/Pods-exampleTests.debug.xcconfig: unable to open file (in target "exampleTests" in project "example") (in target 'exampleTests' from project 'example')
error: [user]/react-native-share/example/ios/Pods/Pods/Target Support Files/Pods-exampleTests/Pods-exampleTests.debug.xcconfig: unable to open file (in target "exampleTests" in project "example") (in target 'exampleTests' from project 'example')
error: [user]/react-native-share/example/ios/Pods/Pods/Target Support Files/Pods-exampleTests/Pods-exampleTests.debug.xcconfig: unable to open file (in target "exampleTests" in project "example") (in target 'exampleTests' from project 'example')
error: [user]/react-native-share/example/ios/Pods/Pods/Target Support Files/Pods-exampleTests/Pods-exampleTests.debug.xcconfig: unable to open file (in target "exampleTests" in project "example") (in target 'exampleTests' from project 'example')
```

**Comment by friederbluemle** [comment]
Hi @resting - Please note the instructions in README.md of this project.
The example is using react-native 0.61.5 - which requires one additional step for iOS.

Before you try to run the app, do this:

    pushd ios && pod install && popd

[CocoaPods](https://cocoapods.org/) needs to be installed on your system. It will download required dependencies.

**Comment by resting** [comment]
@friederbluemle thanks for the info! Ran the command and tried with react-native v0.61.5 but am still getting the same errors.

Here's what I ran:
```
pushd ios && pod install && popd
npx react-native@0.61.5 run-ios --simulator "iPhone 11 Pro Max"
```

I should be running this in the `example` folder? Cause I notice the path isn't right.

`/react-native-share/example/ios/Pods/Pods/Target Support Files/`, 
**Pods/Pods** why are there 2 of `Pods/`?

**Comment by friederbluemle** [comment]
@resting - I just tried this again on the latest `master` branch and was able to successfully run the example on both Android and iOS.

1. Clone repo (if already cloned, update it and make sure it's clean: `git clean -fdX`)
1. `cd example`
1. `yarn`
1. `pushd ios && pod install && popd`
1. `yarn ios` (or `yarn android` for Android)

Please follow these steps and let us know the results.

**Comment by resting** [comment]
@friederbluemle have tried the above steps and it works. Thanks for helping!

**Comment by umitunver** [comment]
> @resting - I just tried this again on the latest `master` branch and was able to successfully run the example on both Android and iOS.
> 
> 1. Clone repo (if already cloned, update it and make sure it's clean: `git clean -fdX`)
> 2. `cd example`
> 3. `yarn`
> 4. `pushd ios && pod install && popd`
> 5. `yarn ios` (or `yarn android` for Android)
> 
> Please follow these steps and let us know the results.

it's working, thank you!
