### ISSUE TITLE
My app close when I press the screen in the moment between Pressing the button that execute Share.open and the native modal appears (ONLY ANDROID))

### ISSUE THREAD

**Issue by felire** [react-native-community/react-native-share#685]
### Steps to reproduce
1. Write a button that execute Share.open in the onPress event
2. Run the app
3. Press the button faster and many times

### Expected behaviour
The modal should appear

### Actual behaviour
The app is being closed without errors

### Environment
- **React Native version**:  0.61.5
- **React Native platform + platform version**: All android devices

### react-native-share
**Version**:  ^2.0.0

### Link to repo (highly encouraged)
https://github.com/

**Comment by felire** [comment]
It's still happening at version 3.0.0

**Comment by anastely** [comment]
Same here 😕
