### ISSUE TITLE
null is not an object (RNShare.FACEBOOK) (Android)

### ISSUE THREAD

**Issue by flo5324** [react-native-community/react-native-share#698]
I saw this error a few times through the issues but none of the solutions helped me.
I installed the library automatically, no manual linking.
iOS is working fine but Android crashes at startup with the infamous error :
![image](https://user-images.githubusercontent.com/14941833/73440004-dd737f00-4350-11ea-8faf-388f368780e5.png)

As soon as I call `Share.open()` in my code, the app crashes after reloading.
I also tried react-native clean-project-auto and reinstall everything with no success.

### Environment
System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 556.17 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.3.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.2, 25.0.0, 25.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.2
      System Images: android-17 | Google APIs Intel x86 Atom, android-19 | Google APIs ARM EABI v7a, android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs Intel x86 Atom_64, android-22 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.12.0 => 16.12.0 
    react-native: 0.61.5 => 0.61.5
### react-native-share
Version: react-native-share@3.0.0

**Comment by flo5324** [comment]
Alright, so I didn't thought this could be the problem but on Android you **have to** then/catch the promise returned but on iOS it's no problem.
Closing the issue.

**Comment by flo5324** [comment]
Simple snack example: https://snack.expo.io/ry09DvxGU

**Comment by lfalkner** [comment]
I am seeing the same

**Comment by ian** [comment]
Seeing same

**Comment by perrosnk** [comment]
I am getting the same error on iOS too

**Comment by perrosnk** [comment]
I cleaned the project by running
`
watchman watch-del-all && rm -rf $TMPDIR/react-* && rm -rf $TMPDIR/npm-* && rm -rf $TMPDIR/haste-* && rm -rf $TMPDIR/metro-* && rm -rf node_modules && npm install && rm -rf ios/Pods && cd ios && pod cache clean --all && pod repo update && pod install && cd .. &&  ./android/gradlew clean -p ./android/ && rm -rf ios/build &&  rm -rf ~/Library/Developer/Xcode/DerivedData && npm start -- --reset-cache
`
and it worked for me

**Comment by MateusAndrade** [comment]
Hey @flo5324, @perrosnk  sorry for the late answer. Are you guys trying to run that on a project without expo?

**Comment by flo5324** [comment]
Yes I was
I had to add expo on my project but didn't give it a try since 
I'll try tomorrow and see how it goes

**Comment by MateusAndrade** [comment]
> Yes I was
> I had to add expo on my project but didn't give it a try since
> I'll try tomorrow and see how it goes

I don't remember to use this library on a project using expo. But if this doesn't work for you, maybe the `Share` from `react-native` can help you?

Let me know if you find anything to help us find that. 😄

**Comment by perrosnk** [comment]
I am not using expo, but it works fine on both sim and devices after cleaning the project

**Comment by flo5324** [comment]
Well now it seems to work, don't know if it's because I added expo

But now I can't share an image
I'm downloading it with FetchBlob and convert it to base64. I can display it but when I share it via the url, the image is not transferred (save to files on iOS seems to work, but not on Android)

**Comment by padapada09** [comment]
> cd .. && ./android/gradlew clean -p ./android/ && rm -rf ios/build && rm -rf ~/Library/Developer/Xcode/DerivedData && npm start -- --reset-cache

It worked for me too.

**Comment by mikehardy** [comment]
`npx react-native-clean-project` is a critical tool that does the above and more, and should be used in CI and on personal machines when issues arise
