### ISSUE TITLE
Unable to change file name while sharing pdf in base 64(Android).

### ISSUE THREAD

**Issue by bhaskarj61** [react-native-community/react-native-share#702]
## Ask your Question
 I am sharing file by converting it to base64 string but I am unable to change filename in android.

  shareProfile = async(data) => {
    Share.open({url: `data:application/pdf;base64, ${data}`, filename: 'test'})
  }
Still some random name like timestamp is generated.

**Comment by muhammadzaheer123** [comment]
same issue here

**Comment by CDAracena** [comment]
Same, would appreciate a fix for this

**Comment by latusdenis** [comment]
@bhaskarj61 @muhammadzaheer123 @CDAracena Please try installing the library from the specific commit from the master branch:
`"react-native-share": "git+https://github.com/react-native-community/react-native-share.git#c29c10d"`

It works for me.

**Comment by frankyjuang** [comment]
@latusdenis installing from c29c10d works, thanks. But how come it's not working from latest version

**Comment by rrraymonde** [comment]
I'm still having the issue with my .txt file, even when I'm using revision c29c10d.

**Comment by CDAracena** [comment]
Has commit [c29c10d](https://github.com/react-native-community/react-native-share/commit/c29c10df5fd64d76931784c8ccb2e84606af8bc9) been merged into master yet ? Seems like it has ?

**Comment by MateusAndrade** [comment]
> Has commit [c29c10d](https://github.com/react-native-community/react-native-share/commit/c29c10df5fd64d76931784c8ccb2e84606af8bc9) been merged into master yet ? Seems like it has ?

I think this was merged on 3.1.0.

**Comment by frankyjuang** [comment]
confirm fixed in 3.1.1 thanks

**Comment by MateusAndrade** [comment]
Can we close this @bhaskarj61 ?

**Comment by Lory1990** [comment]
on ios i have the same issue, this is the code

```
await Share.open({
        type: 'application/pdf',
        filename: 'Sample',
        url: `data:application/pdf;base64,${base64data}`,
        saveToFiles: true,
        failOnCancel: false,
        isNewTask: true,
      });
```

And the name prompted is "file"

**Comment by Nisha-syngenta** [comment]
> on ios i have the same issue, this is the code
> 
> ```
> await Share.open({
>         type: 'application/pdf',
>         filename: 'Sample',
>         url: `data:application/pdf;base64,${base64data}`,
>         saveToFiles: true,
>         failOnCancel: false,
>         isNewTask: true,
>       });
> ```
> 
> And the name prompted is "file"

@Lory1990 did you get any solution for it?

**Comment by mMarcos208** [comment]
same issue, on "react-native": "0.72.10" and "react-native-share": "^10.0.2",
