### ISSUE TITLE
characters are limited to 3700 when sharing to whatsapp

### ISSUE THREAD

**Issue by pondokit** [react-native-community/react-native-share#703]
### Steps to reproduce
1. try sharing a message that exceeds 3700 characters to whatsapp

### Expected behaviour
message successfully shared with complete characters, nothing is truncated

### Actual behaviour
The message was successfully shared but with truncated characters

### Environment
- **React Native version**: 0.61.5
- **React Native platform + platform version**: Android 8.1
- **Whatsapp version**: 2.20.11

### react-native-share
**Version**:  master

### Link to repo (highly encouraged)
https://github.com/pondokit/tabik/
https://github.com/pondokit/tabik/blob/master/src/screens/Fatwa/Fatwa.js

**Comment by akshatsethi2** [comment]
@pondokit did you ever solve this?
