### ISSUE TITLE
.xls cannot sharing in iOS

### ISSUE THREAD

**Issue by 2ez4salt** [react-native-community/react-native-share#706]
### Steps to reproduce
1. In my case .xls file downloading and decoding base64, then i wanna share this '.xls' file 
 .xls sharing not working on iOS but in android works well.In iOS file cannot take extension '.xls' that's extension is '.data' then cannot share file.

### Expected behaviour
.xls file downloaded and decoded base64 must be shared.

### Actual behaviour
 .xls sharing not working on iOS but in android works well.In iOS file cannot take extension '.xls' that's extension is '.data' then cannot share file.

### Environment
System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 3.50 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.8.1 - /usr/local/bin/node
    npm: 6.13.1 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
    react-native-cli: 2.0.1
### react-native-share
**Version**:2.0.0

### Link to repo (highly encouraged)

` const base64Data = (isExcel ? 'data:application/excel;base64,' : 'data:application/pdf;base64,') + base64;` 
     `  setTimeout(() => { 
        Share.open({
          url:  Platform.OS === 'ios' ? base64Data : base64Data, 
          title: pdfData.title, 
          filename: fileName,
          type: isExcel ? "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" : "application/pdf"
        });
      }, 1000) 
`

**Comment by taylorjosephgriffin** [comment]
@2ez4salt did you ever find a solution to this?

**Comment by trungkao** [comment]
I have same problem
