### ISSUE TITLE
Background video and background video with sticker image

### ISSUE THREAD

**Issue by alejandrovasta** [react-native-community/react-native-share#707]
## Describe the Feature
Would be great to implement backgroundVideo and backgroundVideoAndStickerImage ;)

## Possible Implementations
Pretty similar to backgroundImage and backgroundImageAndStickerImage, it's just NSData. I basically used it copying and pasting the code and worked on my project.

**Comment by FraserCampbell1** [comment]
I also think backgroundVideoAndStickerImage would be a great enhancement to this library as it would allow for a richer post in the instagram story - look at sharing spotify songs for a good example of this.
