### ISSUE TITLE
URL on Android is not a link.

### ISSUE THREAD

**Issue by Adarwall** [react-native-community/react-native-share#709]
Hi, I want to share a deep-link to my app with a message.
The massage is there and the URL, but the URL is appearing as a String of array with the link in it.
IOS works fine for me.

**My Code:** 

```
    shareLink()  {
        Share.open({
            title: 'Welcome',
            message: 'get your first tickest here',
            url: 'partyz://party/ + {ticketId}
        })
        .catch((err) => console.log('user did not share or ' + err));
    }
```
**The message on Android:**
...message body...
["partyz://party/...]   **//as a String, not cliackable link**

**I'm using:** 

- react: 16.9.0
- react-native: 0.61.5
- react-native-share: ^3.0.0

Thank's! :)

**Comment by IgnacioAbadie** [comment]
I had the same issue. I resolved it by downgroading the version to the ^2.0.0

**Comment by piljac1** [comment]
Same here ! Link formatting is fine on iOS, but is enclosed with brackets on Android.

Example:

`https://www.google.com/` -> `[https://www.google.com/]`

**Comment by IgnacioAbadie** [comment]
My first solution was downgroading to 2.0.0 but I had some problems in ios, this has to be fixed faster in the 3.0.0

**Comment by lironsher** [comment]
any workaround? without downgrade

**Comment by obellce** [comment]
The urls array (single url is also turned into an array) is getting directly converted to a string rather than being concatenated.

If you use **[patch-package](https://www.npmjs.com/package/patch-package)**, you can use the following patch to fix the issue. If multiple urls are supplied, they get concatenated with spaces:

**react-native-share+3.0.0.patch**
```
diff --git a/node_modules/react-native-share/android/src/main/java/cl/json/social/ShareIntent.java b/node_modules/react-native-share/android/src/main/java/cl/json/social/ShareIntent.java
index 81ca5e7..29ecc7b 100644
--- a/node_modules/react-native-share/android/src/main/java/cl/json/social/ShareIntent.java
+++ b/node_modules/react-native-share/android/src/main/java/cl/json/social/ShareIntent.java
@@ -12,6 +12,7 @@ import android.content.pm.ResolveInfo;
 import android.content.ComponentName;
 
 import com.facebook.react.bridge.ReactApplicationContext;
+import com.facebook.react.bridge.ReadableArray;
 import com.facebook.react.bridge.ReadableMap;
 
 import java.io.UnsupportedEncodingException;
@@ -40,6 +41,22 @@ public abstract class ShareIntent {
         this.getIntent().setType("text/plain");
     }
 
+    private static String getUrlsString(ReadableMap options, String key) {
+        final ReadableArray rawUrls = options.getArray(key);
+        final StringBuilder builder = new StringBuilder();
+        final int count = rawUrls.size();
+
+        for (int i = 0; i < count; i++) {
+            if (i > 0) {
+                builder.append(' ');
+            }
+
+            builder.append(rawUrls.getString(i));
+        }
+
+        return builder.toString();
+    }
+
     public void open(ReadableMap options) throws ActivityNotFoundException {
         this.options = options;
 
@@ -86,10 +103,12 @@ public abstract class ShareIntent {
                     this.getIntent().putExtra(Intent.EXTRA_TEXT, message);
                 }
             } else {
+                String urlsString = getUrlsString(options, "urls");
+
                 if (!TextUtils.isEmpty(message)) {
-                    this.getIntent().putExtra(Intent.EXTRA_TEXT, message + " " + options.getArray("urls").toString());
+                    this.getIntent().putExtra(Intent.EXTRA_TEXT, message + " " + urlsString);
                 } else {
-                    this.getIntent().putExtra(Intent.EXTRA_TEXT, options.getArray("urls").toString());
+                    this.getIntent().putExtra(Intent.EXTRA_TEXT, urlsString);
                 }
             }
         } else if (ShareIntent.hasValidKey("url", options)) {
```

**Comment by MateusAndrade** [comment]
Recently we merged #717 . Anyone now if this helps with that problem?

**Comment by bperlman** [comment]
> Recently we merged #717 . Anyone now if this helps with that problem?

Yes this appears to fix it.

**Comment by MateusAndrade** [comment]
@Adarwall you can check our master version, to see if that works for you?

**Comment by Adarwall** [comment]
@MateusAndrade Yes, it works! thank you :)

**Comment by james-john1** [comment]
> Same here ! Link formatting is fine on iOS, but is enclosed with brackets on Android.
> 
> Example:
> 
> `https://www.google.com/` -> `[https://www.google.com/]`

change to higher version it is fixed
