### ISSUE TITLE
Share url in android. It is being shared between [ and " in version 3.0.0

### ISSUE THREAD

**Issue by felire** [react-native-community/react-native-share#710]
### Steps to reproduce
1. Install version 3.0.0 of `react-native-share`
2. Share an url using Share.open (for example 'hola')
3. enjoy the bug

### Expected behaviour
The link has to be `hola`

### Actual behaviour
The link is `["hola"]``

If I downgrade the version to the 2.0.0 it works fine

**Comment by Watersdr** [comment]
Downgrading to 2.0.0 worked for me as well

**Comment by bobber205** [comment]
I am seeing this funny error as well -- haven't had any issues with subbing the link into the end of the text message (so far)

**Comment by steppefox** [comment]
@MateusAndrade could you please make a `patch` (3.0.1) release with fix for that issue?

**Comment by felire** [comment]
I've fixed the error and upload a package called: `feli-react-native-share` . I will upload the pr when i have time.

**Comment by MateusAndrade** [comment]
@steppefox sure! I have been on a crazy week, but i'm planning to release a `3.1.0` version of this. Also, for anyone looking a fix for this issue this have been fixed with #709, and is currently working with the master version.
