### ISSUE TITLE
Instagram Stories for Android

### ISSUE THREAD

**Issue by codervss** [react-native-community/react-native-share#712]
Does the latest version 3.0.0 support Instagram Stories feature for Android?
And for ios, how do i share a video in instagram stories and also the attributionURL?

{
method: Share.InstagramStories.SHARE_BACKGROUND_IMAGE,
backgroundBottomColor: '#fefefe',
backgroundTopColor: '#906df4',
attributionURL : '',
backgroudImage : '',
social: Share.Social.INSTAGRAM_STORIES
}

The above code works fine for sharing image on instagram stories for ios.

**Comment by tadeumx1** [comment]
Hi, I think that the Instagram Stories is not implemented in Android, so it only works on IOS

**Comment by nataly-chobat** [comment]
seems yes...
team, thank you for your hard work on improving this package..when do you plan to add support for instagram stories on Android?

**Comment by lucastonon** [comment]
I just realized that too!
If we use the same code we get
`No enum constant cl.json.RNShareModule.SHARES.instagram-stories`

**Comment by jgcmarins** [comment]
We gonna accept PRs adding Instagram stories for Android

**Comment by codervss** [comment]
Instagram Story Share still does not work for Android.
Someone Please help.

**Comment by anandbatjargal** [comment]
@MateusAndrade Hey, I'm having this issue on Android.
React Native Share Version is 4.0.4

https://github.com/react-native-share/react-native-share/issues/919

**Comment by cmpdvd** [comment]
Hey, I'm still having this issue on Android.
I'm using react-native-share 7.9.0

```
 const shareOptions_IG_OpenStory = {
      backgroundImage: imagePath,
      social: Share.Social.INSTAGRAM_STORIES,
 };
 Share.shareSingle(shareOptions_IG_OpenStory).catch((error)=>{
          console.log('err: ', error);
 }); 
```
Did I miss something ? Thx!

**Comment by mikehardy** [comment]
@cmpdvd unknown - have you investigated what the current share intent should be for instagram stories and compared that with the android code here? That's the path towards discovering the issue - also, it appears you are logging an error there in your code but you don't share anything from your logs + any results of investigation
