### ISSUE TITLE
Share video to messenger (Android)

### ISSUE THREAD

**Issue by ldaubie** [react-native-community/react-native-share#714]
Hi everyone,

Currently i try to share videos to messenger with react-native-share.
At this point, it's working for IOS and i can share photos to messenger from Android.
I don't understand why but when i try to share videos from Android, messenger is not propose to the list of application, somebody could help me ?

For the time, i tried to send the full path off the video and convert it in base64 but nothing seems to work..

So if somebody have some idea i will be grateful

**Comment by chpq95** [comment]
Hi @ldaubie. have you solve this? i also have the same issue

**Comment by ldaubie** [comment]
Hello, i didn't find how do it with this module, i use 'expo-sharing' instead

**Comment by MateusAndrade** [comment]
> expo-sharing'

Hi, i gave a quick look at `expo-sharing`, and it seems that the `Share` function exposed is focused on sharing files only:

https://github.com/expo/expo/blob/132117e5cfd1f259f776b8fa5bd93e723aa58183/packages/expo-sharing/android/src/main/java/expo/modules/sharing/SharingModule.java#L61

https://docs.expo.io/versions/latest/sdk/sharing/

I never used expo, but it looks like that it's possible to use that on a `react-native` project without expo. 

Btw, please let me know if there is anything that we can help you. 😄

**Comment by ldaubie** [comment]
Hi, don't worry it's working with expo-sharing, you juste have to send your video in base64
Yes you can use expo library outside expo project !
