### ISSUE TITLE
Why doesn’t the library support SMS/iMessage sharing on iOS? 

### ISSUE THREAD

**Issue by perpetuatingcuriosity** [react-native-community/react-native-share#716]
Curious why this isn’t already supported? Where there problems implementing it, or was it a lack of time, or something else? 

Have filed a feature request: https://github.com/react-native-community/react-native-share/issues/715.

**Comment by gerryfletch** [comment]
I have just started using this library and the default `open` function with a `message` opens fine in iOS Messages on iPhone 11.

**Comment by MateusAndrade** [comment]
Thanks @gerryfletch!

**Comment by perpetuatingcuriosity** [comment]
To clarify, the request is for Share.shareSingle() – direct share to iOS Messages. #715 is still a valid issue.
