### ISSUE TITLE
Cannot share video directly in android

### ISSUE THREAD

**Issue by chpq95** [react-native-community/react-native-share#722]
### Steps to reproduce
1.    const shareOptions = {
      title: 'Share via Wimyx',
      message: 'I recorded this video by using Wimyx',
      url: `file://${filepath}`,
      type: 'video/mp4',
      showAppsToView: true,
    };
    Share.open(shareOptions).then((res) => {
      console.log(res);
    }).catch((err) => { err && console.log(err); });
  };

### Expected behaviour
Can share the video to social media

### Actual behaviour
Got 'File content not support' when try to share in telegram

### Environment
- **React Native version**: 0.61
- **React Native platform + platform version**: Android 8.0

### react-native-share
**Version**: npm version or "master"

### Link to repo (highly encouraged)
https://github.com/

**Comment by MateusAndrade** [comment]
This only happens on Telegram?

**Comment by shafiqruslan95** [comment]
On all social media.

> This only happens on Telegram?

**Comment by chpq95** [comment]
Okay i solved it, for those who having this issue. you need to call the video from cache directory. if you call it from document directory its not gonna work
