### ISSUE TITLE
Some apps is not listed when i want to share the video in android and ios

### ISSUE THREAD

**Issue by chpq95** [react-native-community/react-native-share#726]
## Ask your Question

Can i know why instagram and instagram stories is not listed when i want to share the video in android? this also happen when i want to share the video in ios, there is no twitter is shown. But if i share message only, it listing all the possible apps. How can i show all the listed apps when i want to sharing the video?

**Comment by chpq95** [comment]
This is happen when im using version 3.1.1. After i downgrade to version 2.0.0, it works perfectly.

**Comment by MateusAndrade** [comment]
possible related to #729
