### ISSUE TITLE
Problem with example with activityItemSources

### ISSUE THREAD

**Issue by m-wasilewski** [react-native-community/react-native-share#727]
Hi, I copied an [example](https://github.com/react-native-community/react-native-share#provide-data-to-share-by-using-activityitemsources-in-ios) with activityItemSources for iOS, but I've got this error message.
It seems like an app completely doesn't see activityItemSources.

![image](https://user-images.githubusercontent.com/28801475/76787253-e90fed80-67b8-11ea-89bf-ca243d291ec9.png)

```js
    const url = 'https://awesome.contents.com/';
    const title = 'Awesome Contents';
    const message = 'Please check this out.';

    const options = Platform.select({
      ios: {
        activityItemSources: [
          {
            placeholderItem: {type: 'url', content: url},
            item: {
              default: {type: 'url', content: url},
            },
            subject: {
              default: title,
            },
            linkMetadata: {originalUrl: url, url, title},
          },
          {
            placeholderItem: { type: 'text', content: message},
            item: {
              default: {type: 'text', content: message},
              message: null, // Specify no text to share via Messages app.
            },
          },
        ],
      },
      default: {
        title,
        subject: title,
        message: `${message} ${url}`,
      },
    });

    Share.open(options)
      .then(res => console.log(res))
      .catch(error => console.log(error));
```

Do I missed something? It would be weird because I'm using code from readme.
Or can someone show another example?

Thanks!

**Comment by MateusAndrade** [comment]
Hey @m-wasilewski , thanks for sharing this. Would you mind sharing a repo with your example? Also, this is currently available only on our `master` version. Wich version are you trying?

**Comment by m-wasilewski** [comment]
You have right, I used an earlier version from npm.
I'm accustomed to situation when npm has the latest version of repo 😅
Sorry for that 😓 

Could you provide an another example with activityItemSources? Because I can't display any options for sharing...

For example for that code I see that results:
```js
        activityItemSources: [
          {
            placeholderItem: { type: 'text', content: message},
            item: {
              copyToPasteBoard: {type: 'text', content: message},
              mail: {type: 'text', content: message},
              default: {type: 'text', content: message},
              message: null, // Specify no text to share via Messages app.
            },
            subject: {
              message: title,
              default: title,
            },
            linkMetadata: {originalUrl: url, url, title},
          },
        ],
```

![image](https://user-images.githubusercontent.com/28801475/76833457-a9ceb480-682b-11ea-8087-1d713083d899.png)

Is this correct behavior? Or my options are incorrect?

**Comment by klaaz0r** [comment]
I am having the exact same issue but I am on `3.0.0` ?

**Comment by MateusAndrade** [comment]
I'm planning to release https://github.com/react-native-community/react-native-share/releases/tag/v3.1.0 this week. Feedback's about stability, etc would help a lot. :)
