### ISSUE TITLE
Share sheet closes in 3.1 but Native error in debug console

### ISSUE THREAD

**Issue by imaginasean** [react-native-community/react-native-share#730]
### Steps to reproduce
1. New Version 3.1.0
2. Execute a share successfully (click Save to Files, for example)
3. Share sheet now closes (3.1.0 fix addressed this), but large Native error dump in xcode console

### Expected behaviour
No error is produced, and without the then/catch it produces yellow warning boxes.

### Actual behaviour
in xcode console window:
{ error: 
   { code: 'ENSPOSIXERRORDOMAIN22',
     message: 'The operation couldn’t be completed. Invalid argument',
     domain: 'NSPOSIXErrorDomain',
     userInfo: {},
     nativeStackIOS: 
      [ '0   VisRx                               0x00000001027cc164 RCTJSErrorFromCodeMessageAndNSError + 156',
        '1   VisRx                               0x00000001027cc088 RCTJSErrorFromNSError + 264',
        '2   VisRx                               0x000000010274c3a4 __41-[RCTModuleMethod processMethodSignature]_block_invoke_4.110 + 156',
        '3   VisRx                               0x0000000102691954 __48-[RNShare open:failureCallback:successCallback:]_block_invoke_2 + 232',
        '4   ShareSheet                          0x00000001cc6df7fc 462350DE-C8B0-3377-BDB9-62FECEA11F85 + 231420',
        '5   UIKitCore                           0x00000001c4a24fe0 D7630067-7A00-3CB7-99E1-E7F6C55D85C5 + 3178464',
        '6   UIKitCore                           0x00000001c4a2976c D7630067-7A00-3CB7-99E1-E7F6C55D85C5 + 3196780',
        '7   UIKitCore                           0x00000001c4b2d5a8 D7630067-7A00-3CB7-99E1-E7F6C55D85C5 + 4261288',
        '8   UIKitCore                           0x00000001c5573fe0 D7630067-7A00-3CB7-99E1-E7F6C55D85C5 + 15036384',
        '9   UIKitCore                           0x00000001c5573c8c D7630067-7A00-3CB7-99E1-E7F6C55D85C5 + 15035532',
        '10  UIKitCore                           0x00000001c55a9d90 D7630067-7A00-3CB7-99E1-E7F6C55D85C5 + 15256976',
        '11  UIKitCore                           0x00000001c557dc70 D7630067-7A00-3CB7-99E1-E7F6C55D85C5 + 15076464',
        '12  UIKitCore                           0x00000001c557e178 D7630067-7A00-3CB7-99E1-E7F6C55D85C5 + 15077752',
        '13  UIKitCore                           0x00000001c557e2c8 D7630067-7A00-3CB7-99E1-E7F6C55D85C5 + 15078088',
        '14  QuartzCore                          0x00000001c7b2fdac 3EE40592-F011-38CC-8472-776B3C912A42 + 1453484',
        '15  libdispatch.dylib                   0x00000001040aabd8 _dispatch_client_callout + 16',
        '16  libdispatch.dylib                   0x00000001040b8c34 _dispatch_main_queue_callback_4CF + 1316',
        '17  CoreFoundation                      0x00000001c10185e4 7519E999-1053-3367-B9D5-8844F6D3BDC6 + 693732',
        '18  CoreFoundation                      0x00000001c10135d8 7519E999-1053-3367-B9D5-8844F6D3BDC6 + 673240',
        '19  CoreFoundation                      0x00000001c1012adc CFRunLoopRunSpecific + 464',
        '20  GraphicsServices                    0x00000001cafb3328 GSEventRunModal + 104',
        '21  UIKitCore                           0x00000001c512063c UIApplicationMain + 1936',
        '22  VisRx                               0x0000000102531bbc main + 124',
        '23  libdyld.dylib                       0x00000001c0e9c360 7B531A15-3E73-3185-90E2-B88D9476DA5E + 4960' ] } }

### Environment
- **React Native version**: 0.61
- **React Native platform + platform version**: iOS 12.0

### react-native-share
**Version**: npm version or "master" 3.1.0

**Comment by imaginasean** [comment]
Found the issue, it was mine with a non-existent file path reference.  Closing as working as expected.

**Comment by hasanalfath** [comment]
hi, I have the same problem, did you solve it?
