### ISSUE TITLE
'LinkPresentation/LinkPresentation.h' file not found

### ISSUE THREAD

**Issue by fedu44** [react-native-community/react-native-share#736]
### Steps to reproduce
1. Add to package.json "react-native-share": "git+https://git@github.com/react-native-community/react-native-share.git" or "react-native-share": "^3.1.1", or "react-native-share": "^3.1.0"
2. Build project on xCode Version 10.2.1

### Expected behaviour
Application building correctly

### Actual behaviour
Build failed with error 'linkpresentation/linkpresentation.h' file not found react-native'

### Environment
- **React Native version**: "^0.61.5"
- **React Native platform + platform version**: iOS 11.3, physical device

### react-native-share
**Version**: "git+https://git@github.com/react-native-community/react-native-share.git" or "react-native-share": "^3.1.1", or "react-native-share": "^3.1.0"

### Link to repo (highly encouraged)
https://github.com/---

**Comment by MateusAndrade** [comment]
This works with 3.0.0? Also, you are trying to build on `debug` or `release` mode?

**Comment by fedu44** [comment]
> This works with 3.0.0? Also, you are trying to build on `debug` or `release` mode?

With 3.0.0 it's working perfect, and I am building on debug mode.

**Comment by luancurti** [comment]
Same here I'm getting this error on my build in the CI 

`/node_modules/react-native-share/ios/RNShareActivityItemSource.m:2:9: 'LinkPresentation/LinkPresentation.h' file not found`

## Environment

React Native version: `0.61.5`
React Native platform + platform version: `iOS 12.1`

## react-native-share

Version: `3.1.0`

**Comment by luancurti** [comment]
> Also, you are trying to build on `debug` or `release` mode?

In `debug` I can build ok, my error is only on the `release`

**Comment by luancurti** [comment]
I'm investigating this case. @MateusAndrade I'll assign myself as responsible for this issue ok?

**Comment by fedu44** [comment]
> I'm investigating this case. @MateusAndrade I'll assign myself as responsible for this issue ok?

If need more info or want me to try a possible solution I'll be glad to help you guys.

**Comment by MateusAndrade** [comment]
> I'm investigating this case. @MateusAndrade I'll assign myself as responsible for this issue ok?

Sure, thanks! Please let me known if there is anything i can help.

**Comment by MateusAndrade** [comment]
Maybe this can be related to: https://github.com/react-native-community/react-native-share/commit/ad7cce872a5244986f18e6d3d80338b767befb53. I don't have tested a revert on that, but this is importing it here: https://github.com/react-native-community/react-native-share/blob/ad7cce872a5244986f18e6d3d80338b767befb53/ios/RNShareActivityItemSource.m

**Comment by luancurti** [comment]
> Maybe this can be related to: [ad7cce8](https://github.com/react-native-community/react-native-share/commit/ad7cce872a5244986f18e6d3d80338b767befb53). I don't have tested a revert on that, but this is importing it here: https://github.com/react-native-community/react-native-share/blob/ad7cce872a5244986f18e6d3d80338b767befb53/ios/RNShareActivityItemSource.m
> 
> @fedu44 would you mind this before merging #693?

It's the `LinkPresentation` framework is only available on `iOS 13` I'm testing some alternatives to try to fix this

**Comment by MateusAndrade** [comment]
> > Maybe this can be related to: [ad7cce8](https://github.com/react-native-community/react-native-share/commit/ad7cce872a5244986f18e6d3d80338b767befb53). I don't have tested a revert on that, but this is importing it here: https://github.com/react-native-community/react-native-share/blob/ad7cce872a5244986f18e6d3d80338b767befb53/ios/RNShareActivityItemSource.m
> > @fedu44 would you mind this before merging #693?
> 
> It's the `LinkPresentation` framework is only available on `iOS 13` I'm testing some alternatives to try to fix this
> 
> The problem only works in my CI because it uses the `iOS 12.1 SDK` and `LinkPresentation` is not available

Maybe we can import that dynamically?

**Comment by luancurti** [comment]
> > > Maybe this can be related to: [ad7cce8](https://github.com/react-native-community/react-native-share/commit/ad7cce872a5244986f18e6d3d80338b767befb53). I don't have tested a revert on that, but this is importing it here: https://github.com/react-native-community/react-native-share/blob/ad7cce872a5244986f18e6d3d80338b767befb53/ios/RNShareActivityItemSource.m
> > > @fedu44 would you mind this before merging #693?
> > 
> > 
> > It's the `LinkPresentation` framework is only available on `iOS 13` I'm testing some alternatives to try to fix this
> > The problem only works in my CI because it uses the `iOS 12.1 SDK` and `LinkPresentation` is not available
> 
> Maybe we can import that dynamically?

I tried to do this

`#if __has_include(<LinkPresentation/LinkPresentation.h>)
#import <LinkPresentation/LinkPresentation.h>
#endif`

but `LPLinkMetadata` depends of `LinkPresentation` in compilation this throws an exception `unknow type LPLinkMetadata`

**Comment by MateusAndrade** [comment]
> > > > Maybe this can be related to: [ad7cce8](https://github.com/react-native-community/react-native-share/commit/ad7cce872a5244986f18e6d3d80338b767befb53). I don't have tested a revert on that, but this is importing it here: https://github.com/react-native-community/react-native-share/blob/ad7cce872a5244986f18e6d3d80338b767befb53/ios/RNShareActivityItemSource.m
> > > > @fedu44 would you mind this before merging #693?
> > > 
> > > 
> > > It's the `LinkPresentation` framework is only available on `iOS 13` I'm testing some alternatives to try to fix this
> > > The problem only works in my CI because it uses the `iOS 12.1 SDK` and `LinkPresentation` is not available
> > 
> > 
> > Maybe we can import that dynamically?
> 
> I tried to do this
> 
> `#if __has_include(<LinkPresentation/LinkPresentation.h>) #import <LinkPresentation/LinkPresentation.h> #endif`
> 
> but `LPLinkMetadata` depends of `LinkPresentation` in compilation this throws an exception `unknow type LPLinkMetadata`

Strange. 🤔 Maybe we can @miyabi to help us out. Btw, we can still reverting this.

**Comment by miyabi** [comment]
I will check it during weekend.

**Comment by luancurti** [comment]
The solution is compile the app with `iOS SDK 13` or higher. I've compiled the app and installed in one iPhone with iOS 12.1 and the app works successfully. Thanks for the time @miyabi @MateusAndrade. I will close this issue if any another problem related of this issue is happening feel free to reopen.

**Comment by MateusAndrade** [comment]
@luancurti thanks for letting us know. I think we need to update our docs regarding this issue. Would you mind helping us with that? :smile:

**Comment by luancurti** [comment]
> @luancurti thanks for letting us know. I think we need to update our docs regarding this issue. Would you mind helping us with that? 😄

Of course! I'll make an pull request updating the readme with this information

**Comment by miyabi** [comment]
Thank you for adding requirements and troubleshooting to readme. If you need to use Xcode 10 or earlier, I can fix it.

**Comment by luancurti** [comment]
> Thank you for adding requirements and troubleshooting to readme. If you need to use Xcode 10 or earlier, I can fix it.

@miyabi feel free to make the PR fixing it!

**Comment by demedos** [comment]
> Thank you for adding requirements and troubleshooting to readme. If you need to use Xcode 10 or earlier, I can fix it.

+1, I am stuck on Xcode 10.2.1 and would love to get the latest updates

**Comment by miyabi** [comment]
@MateusAndrade Thank you for quick release!
