### ISSUE TITLE
is there a way to share image as well as url from this library 

### ISSUE THREAD

**Issue by manjeet-dobble** [react-native-community/react-native-share#74]
Hi, I am looking to share image as well as url at the same time, but it seems that this library only support one url at a time, is there a way to achieve this thing.

**Comment by adamkdean** [comment]
This would be nice...

**Comment by andyscraven** [comment]
Any update on this?  As there has been no reply

**Comment by ju5td0m7m1nd** [comment]
I came up with this workaround.
First parse the library url into assets url 

```
const parseUri = (uri) => {
  const id = uri.split('photos://')[1].split('/L0/001')[0];
  return `assets-library://asset/asset.JPG?id=${id}&ext=JPG`
}
```

And then use RNFetchBlob from [react-native-fetch-blob](https://github.com/wkh237/react-native-fetch-blob) to read from assets url and convert as base64 string

As we got the base64 string we can share it : >
```
RNFetchBlob.fs
      .readFile(
        parseUri(libraryUrl),
        "base64"
      )
      .then(base64data => {
        let base64Image = `data:image/jpeg;base64,${base64data}`;
        Share.open(
          {
            url: base64Image
          }
        )
          .then(() => console.log("He shared!!"))
          .catch(() => console.log("He didn't share :("));
      });
```

**Comment by idoor88** [comment]
This approach still only shares  only image of the url, not both the image and the url string, any way to share both?

**Comment by jgcmarins** [comment]
We did a new release, can you try it? v1.2.0.
Thank you.

**Comment by ospfranco** [comment]
I'm having the same problem on 1.2.1, cannot migrate to 2.0.0, guess no solution available?

**Comment by jgcmarins** [comment]
which problem?

**Comment by ospfranco** [comment]
Cannot share both image and link, when url field has image url and the message field also contains a link, the image is not displayed and only the link in the message field is recognized

**Comment by MateusAndrade** [comment]
> Cannot share both image and link, when url field has image url and the message field also contains a link, the image is not displayed and only the link in the message field is recognized

You can provide us a example code showing this?

**Comment by ospfranco** [comment]
Hey, thanks for the support after more testing I found the problem only happens on iOS, on android you are able to (more or less) easily share and image and a message, but on iOS you cannot place both of them, here is the final code I ended up:

```
try {
const sharingMessage = 'Lassen Sie uns unsere Kommunikation vereinfachen'
      if (Platform.OS === 'ios') {
        url = url.slice(7);
      }

      // https://github.com/EstebanFuentealba/react-native-share/issues/125
      // base64 fallback for Android
      let data = '';
      RNFetchBlob.fs.readStream(url, 'base64', 4095).then(ifstream => {
        ifstream.open();
        ifstream.onData(chunk => {
          data += chunk;
        });
        ifstream.onError(err => {
          console.warn('oops', err);
        });
        ifstream.onEnd(() => {
          url = 'data:image/jpeg;base64,' + data;

          Share.open({
            message: Platform.OS === 'android' ? sharingMessage : undefined, // if this field is set on iOS, sharing the image does not work
            url: url,
            mime: 'image/jpeg',
            subject: sharingMessage,
          }).catch((err: any) => null);
        });
      });
    } catch (e) {
      console.warn('error', e);
    }
```

**Comment by ospfranco** [comment]
Not stale

**Comment by jgcmarins** [comment]
@ospfranco should we reopen?

**Comment by ospfranco** [comment]
Yes, this is still valid

**Comment by jgcmarins** [comment]
@ospfranco do you have any reproducible repository?
Or just fork and use our [example](https://github.com/react-native-community/react-native-share/tree/master/example)

**Comment by ospfranco** [comment]
I put the comment snippet a few comments up there ^, did not produce a repository, it should be a matter of copying and pasting

**Comment by MateusAndrade** [comment]
@ospfranco would you mind helping us setting this example at the docs/example app? 😄

**Comment by promit01** [comment]
Still cannot share image and message both at the same time. Did anybody manage to fix it ?
