### ISSUE TITLE
How to share only one file per time?

### ISSUE THREAD

**Issue by reallijie** [react-native-community/react-native-share#740]
## How to share only one file per time?
I cannot use react-native-share share file to QQ or wechat, because QQ or wechat only receive one file per time.

when I remove below codes in node_modules\react-native-share\index.js,It works.
  static open(options: Options | MultipleOptions): Promise<OpenReturn> {
    return new Promise((resolve, reject) => {
      requireAndAskPermissions(options)
        .then(() => {
          // if (options.url && !options.urls) {
          //   // Backward compatibility with { Share } from react-native
          //   const url = options.url;
          //   delete options.url;
          //
          //   options.urls = [url];
          //
          //   if (options.filename && !options.filenames) {
          //     options.filenames = [options.filename];
          //     delete options.filename;
          //   }
          // }

## Possible Implementations
Hope react-native-share provide an option or a new method to do so, QQ/wechat is the most popular social application in china, many people need this feature.

**Comment by MateusAndrade** [comment]
Hi @reallijie , your problem is that whenever you try to share a file to QQ/Wechat you are unable because of the following [snippet](https://github.com/react-native-community/react-native-share/blob/master/index.js#L226&L237)?

Would you mind sharing which version are you using? 😃

**Comment by reallijie** [comment]
step1: npx react-native init testShare
step2: cd testShare
step3: npm install react-native-share
step4: npx react-active run-android

## App.js

import React, {Component} from 'react';
import {Button} from 'react-native';
import Share from 'react-native-share';

export default class App extends Component {
  render() {
    return (
      <Button
        title="test share"
        onPress={() => {
          this.shareFile();
        }}
      />
    );
  }

  async shareFile() {
    try {
      const options = {
        url: 'file:///storage/emulated/0/Download/table.pdf',
        type: 'application/pdf',
      };
      await Share.open(options);
    } catch (e) {
      console.log(e);
    }
  }
}


## package.json
{
  "name": "testShare",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.11.0",
    "react-native": "0.62.0",
    "react-native-share": "^3.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "react-test-renderer": "16.11.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by reallijie** [comment]
remove below codes in node_modules\react-native-share\index.js or not.
static open(options: Options | MultipleOptions): Promise {
return new Promise((resolve, reject) => {
requireAndAskPermissions(options)
.then(() => {
// if (options.url && !options.urls) {
// // Backward compatibility with { Share } from react-native
// const url = options.url;
// delete options.url;
//
// options.urls = [url];
//
// if (options.filename && !options.filenames) {
// options.filenames = [options.filename];
// delete options.filename;
// }
// }


[
![Screenshot_2020-03-29-21-45-20](https://user-images.githubusercontent.com/39477602/77876296-1f536f80-7285-11ea-8762-8fc2890359ca.png)
![Screenshot_2020-03-29-21-45-43](https://user-images.githubusercontent.com/39477602/77876303-211d3300-7285-11ea-884a-9c5a5031c32a.png)

](url)

**Comment by reallijie** [comment]
Backward compatibility with { Share } from react-native. transform options.url to options.urls is the reason. wechat/qq dont receive file array.

**Comment by MateusAndrade** [comment]
> Backward compatibility with { Share } from react-native. transform options.url to options.urls is the reason. wechat/qq dont receive file array.

Do you know any way we can handle these `url` or `urls` to these applications? Maybe sharing the Share scheme from both would help us to find a solution. 

Also, you meant that calling the `Share` from `react-native` works for you?

**Comment by reallijie** [comment]
Share from react-native dose not work in another way. 

Provide an option like 'transfromUrlToUrls'/'transformToArray'/'forceToAarry' maybe a solution, user dicide how to use it.

**Comment by MateusAndrade** [comment]
> Share from react-native dose not work in another way.
> 
> Provide an option like 'transfromUrlToUrls'/'transformToArray'/'forceToAarry' maybe a solution, user dicide how to use it.

What do you think about using `Promise.all` or `Promise.settled`? This should be a bit complex, but I remember to use a similar workaround on a project.

**Comment by reallijie** [comment]
I think it is best to be loyal to the user's intention. When user pass a single file, share a single file, when user passes multiple files, share multiple files. In order to be compatible with share, provide a compatibility option, and in order to consider current users, the compatibility option is enabled by default.
As for using promise.all, applications that accept multiple files may face some unpredictable problems.

**Comment by reallijie** [comment]
Is there any progress on this requirement?@MateusAndrade
