### ISSUE TITLE
While sharing image it shares BIN file

### ISSUE THREAD

**Issue by engineer2u4u** [react-native-community/react-native-share#743]
## Ask your Question
When I am trying to share an image, it shares a BIN file.
![error1](https://user-images.githubusercontent.com/48150735/77644492-12820380-6f87-11ea-94c8-2b71d8f080c0.jpg)

Code:
![image](https://user-images.githubusercontent.com/48150735/77644571-36dde000-6f87-11ea-8c90-82ef28da4b95.png)

Please Help!!!!

**Comment by MateusAndrade** [comment]
You tried passing a `mime` to the `open` option with your image type? 

https://github.com/react-native-community/react-native-share#openoptions

Also, i can give a try here with your image, just share the base64 or the repo that you are working on that(if this is possible). 😄

**Comment by engineer2u4u** [comment]
You can try with any base64. None of the base64 value seem to work for me.
I even tried using type:"image/jpeg". Still nothing
--

**Comment by MateusAndrade** [comment]
I will give a look at the example test to see if i can reproduce that. Btw, i should reopen this issue @engineer2u4u ?

**Comment by engineer2u4u** [comment]
Still facing this issue. Please help

**Comment by MateusAndrade** [comment]
> Still facing this issue. Please help

Can you share your repo?

**Comment by engineer2u4u** [comment]
Hi, the issue is fixed. Thank you

**Comment by BlkHrt225** [comment]
@engineer2u4u  what was the solution can u pls explain

**Comment by MummadIbrahim** [comment]
> Hi, the issue is fixed. Thank you

What was the solution ? Can you please share ?

**Comment by MummadIbrahim** [comment]
> > Still facing this issue. Please help
> 
> Can you share your repo?

What was the solution ? Can you explain please ?

**Comment by aksh-22** [comment]
I am facing the same issue

**Comment by vishaldhanotiyadev** [comment]
I am also facing the same issue.
