### ISSUE TITLE
console.error: JSON value '<null>' of type NSNull cannot be converted to NSString

### ISSUE THREAD

**Issue by jacargentina** [react-native-community/react-native-share#744]
### Steps to reproduce
Having a JSON file on `listPath` which has this content:
```plain
{
 "1": "G",
 "2": null,
 "3": null,
 "type": "palabra",
 "version": 1,
 "ambiental": "Test",
 "entrada": null,
 "1-monicion": "F",
 "1-salmo": null,
 "2-monicion": null,
 "2-salmo": null,
 "3-monicion": null,
 "3-salmo": null,
 "evangelio-monicion": null,
 "evangelio": null,
 "salida": null,
 "nota": null
}
```
Running this code:

```javascript
      Share.open({
        title: I18n.t('ui.share'),
        message: null,
        subject: `iResucitó - ${listName}`,
        url: `file://${listPath}`,
        failOnCancel: false
      })
        .then(res => {
          console.log(res);
        })
        .catch(err => {
          err && console.log(err);
        });
```

### Expected behaviour
Should just work

### Actual behaviour
`console.error: JSON value '<null>' of type NSNull cannot be converted to NSString`

![Simulator Screen Shot - iPhone 11 Pro - 2020-03-28 at 21 07 32](https://user-images.githubusercontent.com/517228/77836860-ae9f3c80-7138-11ea-9600-80657fcc11d3.png)

### Environment
- **React Native version**: 0.62.0
- **React Native platform + platform version**: iOS 13.0

### react-native-share
**Version**: 3.1.2

### Link to repo (highly encouraged)
https://github.com/

**Comment by miyabi** [comment]
@jacargentina It seems that `message: null` in your option causes that error. If you don't want to pass message, you can leave it blank.

**Comment by jacargentina** [comment]
@miyabi That works! I should note BTW, that worked just fine previously (RN 0.60.5 + react-native-share 3.0.0
