### ISSUE TITLE
Crash on Android with url: file://

### ISSUE THREAD

**Issue by tspiva** [react-native-community/react-native-share#746]
I'm trying to share a file using the following options:

```js
const options = {
 title: "My title",
 subject: "My Subject"
 message: "My Message"
 url: "file:///data/user/0/com.example/files/38d252c8-bdef-49c3-809e-3360e006de5b"
}

Share.open(options)
  .then(res => {
    console.log('Shared: ', res);
  })
  .catch(err => {
    err && console.log('Share failed: ', err);
  });
```
When the Share.open is called the app crashes crashes and looking at logcat the following error is logged:

    : Key android.intent.extra.TEXT expected ArrayList<CharSequence> but value was a java.lang.String.  The default value <null> was returned.
    : Attempt to cast generated internal exception:
    : java.lang.ClassCastException: java.lang.String cannot be cast to java.util.ArrayList
    : 	at android.os.BaseBundle.getCharSequenceArrayList(BaseBundle.java:1307)
    : 	at android.os.Bundle.getCharSequenceArrayList(Bundle.java:1095)
    : 	at android.content.Intent.getCharSequenceArrayListExtra(Intent.java:8016)
    : 	at android.content.Intent.migrateExtraStreamToClipData(Intent.java:10962)
    : 	at android.content.Intent.migrateExtraStreamToClipData(Intent.java:10925)
    : 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1702)
    : 	at android.app.Activity.startActivityForResult(Activity.java:5192)
    : 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
    : 	at android.app.Activity.startActivityForResult(Activity.java:5150)
    : 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
    : 	at cl.json.social.ShareIntent.openIntentChooser(ShareIntent.java:258)
    : 	at cl.json.social.GenericShare.open(GenericShare.java:20)
    : 	at cl.json.RNShareModule.open(RNShareModule.java:134)
    : 	at java.lang.reflect.Method.invoke(Native Method)
    : 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
    : 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
    : 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
    : 	at android.os.Handler.handleCallback(Handler.java:883)
    : 	at android.os.Handler.dispatchMessage(Handler.java:100)
    : 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
    : 	at android.os.Looper.loop(Looper.java:214)
    : 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
    : 	at java.lang.Thread.run(Thread.java:919)

### Expected behaviour
Share with the file

### Actual behaviour
Application Crashed

### Environment
- **React Native version**: 0.61.5

### react-native-share
**Version**: npm version 3.1.2

**Comment by MateusAndrade** [comment]
Hey, probably you need to access the file using the System FIle on the device. You can try sharing an url as base64 to ensure this works? To access the system files, you will need something like [RNFS](https://github.com/itinance/react-native-fs).

Please, let me know if this helps you. 😄

**Comment by tspiva** [comment]
I changed it to:
```js
const contents = await RNFS.readFile(item.photo, 'base64');
options.url = `data:${item.mimeType};base64,${contents}`;
```
And it no longer crashes on Android.  Is using the url pointed to the file not supposed to work? The docs says it is an option.
