### ISSUE TITLE
"Package manager has died" when using shareSingle()

### ISSUE THREAD

**Issue by matheuscuba** [react-native-community/react-native-share#751]
I'm not being able to share on Facebook using `Share.shareSingle()`, with `Share.open()` is everything work as expected. But when I try using `Share.shareSingle()` it returns:

```
{
  "error": "Package manager has died"
} 
```

### Steps to reproduce
```
const shareOptions = {
    url: 'https://www.google.com.br',
    title: 'Facebook Test',
    message: 'This is a test',
    social: Share.Social.FACEBOOK,
};

Share.shareSingle(shareOptions)
    .catch((e) => console.log('Share error', e));
```

### Expected behaviour
Sharing to Facebook

### Actual behaviour
Returns error and nothing happens

### Environment
- **React Native version**: 0.61.5
- **Platform version**: Android 6.0

### react-native-share
**Version**: npm version 3.0.0

**Comment by MateusAndrade** [comment]
Okay, this a really different than the usual issues hahaha. Did you test this on release mode?

**Comment by matheuscuba** [comment]
> Okay, this strange than the usual issues hahaha. Did you test this on release mode?
Yes, and nothing happens, no crashes, no app crashings. Any idea why?

**Comment by MateusAndrade** [comment]
Strange, I tested our example app using the following snippet:

```js
    const shareOptions = {
      url: 'https://www.google.com.br',
      title: 'Facebook Test',
      message: 'This is a test',
      social: Share.Social.FACEBOOK,
    };

    try {
      const ShareResponse = await Share.shareSingle(shareOptions);
      setResult(JSON.stringify(ShareResponse, null, 2));
    } catch (error) {
      console.log('Error =>', error);
      setResult('error: '.concat(getErrorString(error)));
    }
```

And I wasn't able to reproduce that, tested on Android 9.0 and iOS 13. There is any repo that you can share to help with that?

**Comment by matheuscuba** [comment]
> Strange, I tested our example app using the following snippet:
> 
> ```js
>     const shareOptions = {
>       url: 'https://www.google.com.br',
>       title: 'Facebook Test',
>       message: 'This is a test',
>       social: Share.Social.FACEBOOK,
>     };
> 
>     try {
>       const ShareResponse = await Share.shareSingle(shareOptions);
>       setResult(JSON.stringify(ShareResponse, null, 2));
>     } catch (error) {
>       console.log('Error =>', error);
>       setResult('error: '.concat(getErrorString(error)));
>     }
> ```
> 
> And I wasn't able to reproduce that, tested on Android 9.0 and iOS 13. There is any repo that you can share to help with that?

Unfortunately not, its a private repository from my company. 
I think the problem is related to the version of Android that I'm testing, (6.0). I will try to make more tests in other Android versions

**Comment by MateusAndrade** [comment]
I can test with this version if this helps you. Btw, the min version is Android Pie 9. I will test the example with version 6.0 here.

**Comment by SalmanCorleone** [comment]
Facing the same issue on Android 6.0. 
With`Share.open()`, all the options work just fine. 
Any workaround for this issue?
