### ISSUE TITLE
App crashed when calling the Share.open()

### ISSUE THREAD

**Issue by chamikarar** [react-native-community/react-native-share#757]
### Steps to reproduce
`const url = `data:image/png;base64,${base64FileString}`;

    const shareOptions = {
      title: 'Test Title',
      message: 'Test message',
      url: url,
      failOnCancel: false,
    };

    try {
      Share.open(shareOptions);
    } catch (err) {
      console.log(err);
    }`

### Expected behaviour
Open share action sheet on iPhone

### Actual behaviour
App crashed before open the share action sheet. Only on iOS, works perfectly on android.
Edit: Log message from Xcode

> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSURLResponse allHeaderFields]: unrecognized selector sent to instance 0x2818c8e80'

### Environment
- **React Native version**: 0.62.0
- **React Native platform + platform version**: iOS 13.4

### react-native-share
**Version**: 3.1.2

**Comment by MateusAndrade** [comment]
Did you test this on the `example` app? I tested with our `example` app and this works as expected. Maybe this an error with the `base64?`?

**Comment by chamikarar** [comment]
Yes. I tried the example app and it worked. I replaced the base64 string with example app's strings and still the issue is there. This only happens on debug scheme. Seems like the issue is not related to react native share.

**Comment by artmerlop** [comment]
I'm having this issue too! @chamikarar how did you fixed it?
