### ISSUE TITLE
Is it possible to verify that the user really shared the link

### ISSUE THREAD

**Issue by component6** [react-native-community/react-native-share#759]
Is it possible to verify that the user really shared the link, and not just opened a dialog box with a specific application

**Comment by MateusAndrade** [comment]
> Is it possible to verify that the user really shared the link, and not just opened a dialog box with a specific application

Currently, I think the Promise is resolved whenever the Native dialogue os called. Btw, you can check the Native Implementation, so see how this properly works under the hood.

https://github.com/react-native-community/react-native-share/blob/master/android/src/main/java/cl/json/social/TargetChosenReceiver.java

Also, I recommend using something like [Dynamic Links](https://firebase.google.com/docs/dynamic-links) to properly handle this behavior. 🐰

**Comment by jgcmarins** [comment]
Can we close this one?
