### ISSUE TITLE
Provide contact number in share single

### ISSUE THREAD

**Issue by akshaystreak** [react-native-community/react-native-share#762]
How can I add contact number (array or single) while using shareSingle() feature ?

**Comment by vinikatyal** [comment]
Which platform are you sharing it to @akshaystreak ?

**Comment by akshaystreak** [comment]
Android

**Comment by vinikatyal** [comment]
I meant where are you trying to share to which platform?

**Comment by akshaystreak** [comment]
Mobile default SMS

>
