### ISSUE TITLE
Instagram feed not coming up as a share option

### ISSUE THREAD

**Issue by pramacha** [react-native-community/react-native-share#764]
Hello,

I am using Share.open, here is my code:

 var base64Data = `data:image/png;base64,` + base64Data;
  await Share.open({ url: base64Data });

This works great, except I do not get "Instagram feed" and "Instagram direct" as options for sharing. I only see "Instagram Stories" as an option.

Would anyone happen to know how I can fix this? (I am testing this on Andriod 10)

**Comment by stoica94** [comment]
I have the same issue

**Comment by allindeveloper** [comment]
Hello, I also get an issue similar to this one,
But mine is i don't see Twitter Tweet or Direct message whenever i add the url, but when i remove the url, the Twitter option now shows...
 const shareOptions = {
        title: 'Share The Sound!!',
        type:"url",
        // url:base64Data,
        subject:"God is the Almighty",
        message: "",
        failOnCancel: false,
        method:Share.InstagramStories.SHARE_BACKGROUND_IMAGE,
        backgroundImage:Share.Social.INSTAGRAM_STORIES,
        social: Share.Social.TWITTER,
        social:Share.Social.INSTAGRAM_STORIES,
      //  social:"facebook"
      };
try {
        const ShareResponse = await Share.open(shareOptions);
        console.log("response after share",JSON.stringify(ShareResponse, null, 2));
      } catch (error) {
        console.log('Error =>', error);
      }
Any help please

**Comment by RafaelChianca** [comment]
> Hello,
> 
> I am using Share.open, here is my code:
> 
> var base64Data = `data:image/png;base64,` + base64Data;
> await Share.open({ url: base64Data });
> 
> This works great, except I do not get "Instagram feed" and "Instagram direct" as options for sharing. I only see "Instagram Stories" as an option.
> 
> Would anyone happen to know how I can fix this? (I am testing this on Andriod 10)

Could you show me part of your code where you implement sharing? I'm having a lot of trouble trying to share anything to my instagram stories, though the sharing via instagram direct has always appeared to me.
