### ISSUE TITLE
Title does not appear

### ISSUE THREAD

**Issue by MuhammadMattiullah** [react-native-community/react-native-share#767]
### Steps to reproduce
1. Add the title key in share object
2. Share the content
3. Title does not appear instead it shows the url

### Expected behaviour
It should appear the title

### Actual behaviour
Its showing the passing url

### Environment
"react": "16.9.0",
 "react-native": "0.61.5",

### react-native-share
**Version**: 3.0"

Title still not working. I am adding a title key in the share options object but it's not appearing as a title in IOS and Android.

const shareUrl = ${config.shareUrl}/conversations/${conversation.id};
const title = conversation.subject || conversation.body.slice(0, 60);
const shareOptions = {
title: title,
url: shareUrl,
};
Share.open(shareOptions);
But when i pass message and url it concatenate the message and url as a title.
But i want to show only the title.
How can i do this?

**Comment by MateusAndrade** [comment]
Hi @MuhammadMattiullah, let me see if I understand: you want to share this payload:

```js
const shareOptions = {
  title: title,
  url: shareUrl,
};
```

And then when calling `Share.open` with want that only this Title should appear on iOS/Android without being appended to the message?

**Comment by MuhammadMattiullah** [comment]
Hi @MateusAndrade i really appreciate your response!
Just wanted to give u an update its working fine on Android 9 version.
Its working differently on versions greater than 9 and title is not displaying anything so to have a title i was using message.
But in Ios its not showing the title at all.
It only accepting message key to work as a title

**Comment by MateusAndrade** [comment]
This is strange, did you try using https://github.com/react-native-community/react-native-share#provide-data-to-share-by-using-activityitemsources-in-ios

**Comment by MuhammadMattiullah** [comment]
yes, I tried this too @MateusAndrade but unfortunately, it didn't work for me.

**Comment by hungdev** [comment]
@MateusAndrade it only works when you are not attach image. If you attach image, it does not show content in post, instead of show content in post, it show message in title header modal share.

**Comment by MateusAndrade** [comment]
@hungdev thanks for your feedback. Probably this is due to url or something that end's replacing the params. Would you mind, checking if passing just the url, or the message/title works? I faced that on WhatsApp iOS and choose to pass only the file url. 😢

**Comment by MuhammadMattiullah** [comment]
@MateusAndrade if we pass only the message URL then it shows the title. But in this case, the content of the message and title will be the same which is not the required use case.
Mostly the title is different from the share content.
But if we use url and message at the same time then it concatenates both.

**Comment by MateusAndrade** [comment]
Strange, are you still trying this implementation here?

```
const shareUrl = ${config.shareUrl}/conversations/${conversation.id};
const title = conversation.subject || conversation.body.slice(0, 60);
const shareOptions = {
title: title,
url: shareUrl,
};
Share.open(shareOptions);
```

I will give a proper look at this on the weekend, would you mind sharing the applications that you are facing this issue with their respective platforms?

**Comment by JoaoMartins1930** [comment]
Hi guys!!

I am facing this problem too. The title is not being shown when I share something either on IOS or on Android.

I am using the Share component from react-native.

Just like you said, on Android, the problem seems to be the version (10) but do you know why this happens too on IOS?

**Comment by MateusAndrade** [comment]
> Hi guys!!
> 
> I am facing this problem too. The title is not being shown when I share something either on IOS or on Android, even if I use the keys "title" and "message".
> 
> I am using the Share component from react-native.
> 
> Just like you said, on Android, the problem seems to be the version (10) but do you know why this happens too on IOS?

I don't understand. You are facing this problem with `react-native-share` or with the `Share` exported from `react-native` with Android 10?

**Comment by JoaoMartins1930** [comment]
> 
> 
> > Hi guys!!
> > I am facing this problem too. The title is not being shown when I share something either on IOS or on Android, even if I use the keys "title" and "message".
> > I am using the Share component from react-native.
> > Just like you said, on Android, the problem seems to be the version (10) but do you know why this happens too on IOS?
> 
> I don't understand. You are facing this problem with `react-native-share` or with the `Share` exported from `react-native` with Android 10?

With the Share exported from react-native

**Comment by MateusAndrade** [comment]
> With the Share exported from react-native

You can test using `react-native-share`. You can follow our step by step to add the library in tour project: https://react-native-community.github.io/react-native-share/docs/

**Comment by hewseph** [comment]
I have an issue where the subject line disappears when I open mail app with the share sheet, delete draft, then re-open mail app. iOS 14 never closes the share sheet during this process.

**Comment by Monkey911** [comment]
Still having the problem where the title works only with Android versions < 10 while trying to share files from the phone. The title has no effect with Android 10 or Android 11 

```
const options = {
  title: 'My title',
  url: 'file://path_to_file/my_file.pdf',
};

Share.open(options).
  then((res) => {})
  .catch((err) => {});
```

With this code the title of the share sheet with Android 9 is `My title`, but with Android 10 it is `my_file.pdf`

Used versions:
react: 16.13.1
react-native: 0.63.1
react-native-share": 5.1.4

**Comment by Enetty102** [comment]
Same issue

**Comment by arlovip** [comment]
Any updates about this?

**Comment by adity1729** [comment]
> Any updates about this?

++

**Comment by mikehardy** [comment]
Why would there be updates on an issue closed in 2020? Perhaps a new issue with details and reproducible example using current versions of this module and react-native is the best path forward
