### ISSUE TITLE
showAppsToView not working? (Android 9)

### ISSUE THREAD

**Issue by marqroldan** [react-native-community/react-native-share#768]
### Steps to reproduce
`Share.open({"showAppsToView": true, "type": "application/pdf", "url": "file:///storage/emulated/0/Download/8e447932-1411-444a-bfa4-aa6845f6a507.pdf"})`

### Expected behaviour
It should show at least one of the following:
![image](https://user-images.githubusercontent.com/11716376/79937139-b332e880-848b-11ea-82e6-520a5db5243f.png)

### Actual behaviour
Share shows up but it doesn't show any pdf related
![image](https://user-images.githubusercontent.com/11716376/79937993-f2623900-848d-11ea-803e-12b3ea171f72.png)
![image](https://user-images.githubusercontent.com/11716376/79938007-f8581a00-848d-11ea-90d2-bd09ca9dbd68.png)
![image](https://user-images.githubusercontent.com/11716376/79938013-fc843780-848d-11ea-9fa8-1ea3227f222a.png)

### Environment
- **React Native version**: 0.61.5
- **React Native platform + platform version**: Android 9, Emui 9.1.0 

### react-native-share
**Version**: " 3.2.0

I haven't tested this with an emulator yet and I can confirm that the file exists, not corrupted, and that the app has permissions needed

**Comment by marqroldan** [comment]
I installed Adobe PDF and "Combine to Adobe PDF" shows.

Is this an intended behavior or am I doing something wrong? Could it possible be a problem with the other apps?

**Comment by marqroldan** [comment]
I ended up using another package called `react-native-file-viewer`. I checked its code and wondered if I should just copy paste stuff from there to here but I don't really know much native coding ;D

I think this was the last commit for the functionality https://github.com/react-native-community/react-native-share/pull/215/commits/3c76ef2b8e64f8480bd52d57bffbd76439474fee

This is the implementation in `react-native-file-viewer` 
https://github.com/vinzscam/react-native-file-viewer/blob/master/android/src/main/java/com/vinzscam/reactnativefileviewer/RNFileViewerModule.java

I skimmed it and they look similar

**Comment by i1skn** [comment]
@marqroldan I had a similar problems, try to apply this change https://github.com/react-native-community/react-native-share/pull/770 inside your `node_modules` to check would it work for you as well or not.
