### ISSUE TITLE
Sharing Text and Image Not Working

### ISSUE THREAD

**Issue by jihadkahil** [react-native-community/react-native-share#769]
Share.open(options) is not working with the FaceBook New feed it allows only show urls! 
 return Share.open({
        title: "ABC",
        message: "ABC",
        subject: "ABC",
        urls: ["file:" + res.path()]
      })

**Comment by Utkarshkr1710** [comment]
it is working for whatsapp but it will not work for facebook and all

**Comment by FrederickEngelhardt** [comment]
It also does not work with Messages. Email does work.
