### ISSUE TITLE
Why this library don't support with Expo

### ISSUE THREAD

**Issue by seven7hell** [react-native-community/react-native-share#771]
Please do let me know why this library isn't supporting react native app 0.60 which is created by **expo**?

If it can then let me know how? I'm trying to find a solution.

**Comment by mikehardy** [comment]
Expo problems should go to expo repo
If you use the bare workflow it might work
Otherwise you must learn immediately that using Expo managed workflow you may not use non-expo native modules, to the best of my knowledge.

**Comment by seven7hell** [comment]
Thank you @mikehardy for providing valuable information. I'm a beginner in react native app development please accept my apologies.

**Comment by mikehardy** [comment]
No problem - and welcome to react-native :-)
Expo's a great place to start but does have that limitation, getting very familiar with their documentation will help ensure success on your project
