### ISSUE TITLE
Facebook Share Android

### ISSUE THREAD

**Issue by martinop** [react-native-community/react-native-share#775]
I'm using react native@0.61.5 and react native share@3.3.1,
I'm using share single for facebook share and it opens the app but without the message :/ 

I tried with title, message and subject and none works

**Comment by MateusAndrade** [comment]
Hi @martinop you can confirm is this works when using the `Share.open` passing it directly to Facebook? Also which Platform are you testing this?

**Comment by KaioGomesx** [comment]
same issue
```
 Share.open({
        url: '',
        message: 'just test',
        social: Share.Social.FACEBOOK,
      });
```

**Comment by martinop** [comment]
We need help here :(

**Comment by vincemillora** [comment]
This also happens on IOS. There is no message when sharing to Facebook. 😢

**Comment by vinikatyal** [comment]
Same here doesnt work

**Comment by thilinawarnakula** [comment]
@MateusAndrade please help

**Comment by martinop** [comment]
I found that this is not a bug, the problem is the privacy policy: https://developers.facebook.com/policy/#socialplugins

So.. we can't fill the message, what we can do is use the "quote".

**Comment by thilinawarnakula** [comment]
@martinop yes its facebook privacy policy:
