### ISSUE TITLE
if link includes # - link is cutting 

### ISSUE THREAD

**Issue by Vitalik7** [react-native-community/react-native-share#778]
### Steps to reproduce
1. https://prnt.sc/sd337a
2.https://prnt.sc/sd33g1

### Description
When I share link to facebook or twitter, my link is cutting off after number sign(#) symbol, please help anyone!

### Environment
"react-native": "0.61.5",
ios 13.2.2

### react-native-share
"react-native-share": "^3.3.2",

### Link to repo (highly encouraged)
https://github.com/Vitalik7

**Comment by MateusAndrade** [comment]
Hi @Vitalik7, this is happening only on Twitter and Facebook? Also, are you using the `Share.open` or `Share.single`?

**Comment by Vitalik7** [comment]
Hi @MateusAndrade this specific case, when app installed for example twitter and we share link with number sign symbol then is open modal window and link is ok, but if app not installed we redirect to browser and then link is cutting.
I am using ```Share.single```

**Comment by jgcmarins** [comment]
does it only happens on iOS?

**Comment by Vitalik7** [comment]
@jgcmarins I don't know what with android, because we supported only ios
