### ISSUE TITLE
Instagram Stories - Android - Update in progress...

### ISSUE THREAD

**Issue by scgough** [react-native-community/react-native-share#780]
**Update** - strangely a new day, new test and this seems to work. I'll update back here when I know for sure. 
I've added a further question in the comments below: https://github.com/react-native-community/react-native-share/issues/780#issuecomment-629623438

---

Hi
I've been working on this library a bit as I want to extend it's functionality in various areas on both iOS and Android.
 
The main one I'm looking at right now is Instagram Stories for Android. The goal: get IG to open straight away with the media on stories (no Android selector for Direct, Feed, Stories).

I've managed to make some changes which I believe _should_ work but the share seemingly tries to open IG (I see a white screen appear) then almost instantly closes and returns to my app. 

Note, I am currently only dealing with a background image but once that works I will get videos and stickers working. 

The main thing I am doing is making the intent that is fired be an `com.instagram.share.ADD_TO_STORY` intent. The rest of the code in `singleShareIntent.java` fires as normal:

```
...
this.getIntent().setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
this.reactContext.startActivity(this.getIntent());
TargetChosenReceiver.sendCallback(true, true, this.getIntent().getPackage());
...
```

I've used FB's docs as a reference: https://developers.facebook.com/docs/instagram/sharing-to-stories/

Can anyone see anything obvious I might be missing? I'm quite stuck at the moment! 

### File Changes

`shareIntent.java` (new "instagram_stories" else if...)

```
public void open(ReadableMap options) throws ActivityNotFoundException {
        this.options = options;

        ...

        String socialType  = "";
        if (ShareIntent.hasValidKey("social", options)) {
            socialType = options.getString("social");
        }
        if (socialType.equals("whatsapp")) {
            String whatsAppNumber = options.getString("whatsAppNumber");
            if (!whatsAppNumber.isEmpty()) {
                String chatAddress = whatsAppNumber + "@s.whatsapp.net";
                this.getIntent().putExtra("jid", chatAddress);
            }
        }
        else if(socialType.equals("instagram_stories")) {
            //ig stories keys
            this.setIntent(new Intent("com.instagram.share.ADD_TO_STORY"));
            this.getIntent().setPackage("com.instagram.android");

            ShareFile fileShare = getFileShare(options);
            if(fileShare.isFile()) {
                intent.setDataAndType(fileShare.getURI(), "image/*");

//                if (options.hasKey("stickerImage") && !options.getString("stickerImage").isEmpty()) {
//                    Uri stickerAssetUri = Uri.parse(options.getString("stickerImage"));
//                    this.getIntent().putExtra("interactive_asset_uri", stickerAssetUri);
//                    this.reactContext.getCurrentActivity().grantUriPermission(
//                            "com.instagram.android", stickerAssetUri, Intent.FLAG_GRANT_READ_URI_PERMISSION);
//                }

                this.getIntent().addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);

                if (options.hasKey("backgroundBottomColor") && !options.getString("backgroundBottomColor").isEmpty()) {
                    this.getIntent().putExtra("bottom_background_color", options.getString("backgroundBottomColor"));
                }

                if (options.hasKey("backgroundTopColor") && !options.getString("backgroundTopColor").isEmpty()) {
                    this.getIntent().putExtra("top_background_color", options.getString("backgroundTopColor"));
                }

                if (options.hasKey("attributionLink") && !options.getString("attributionLink").isEmpty()) {
                    this.getIntent().putExtra("content_url", options.getString("attributionLink"));
                }
            }
        }

        ...

        } else if (!TextUtils.isEmpty(message)) {
            this.getIntent().putExtra(Intent.EXTRA_TEXT, message);
        }
    }
```

`RNShareModule.java`
 - added `instagram_stories` to `SHARES`

`index.js` (fix `-` issue for android, it passes using an underscore)

`INSTAGRAM_STORIES: NativeModules.RNShare.INSTAGRAM_STORIES || (Platform.OS === 'android' ? 'instagram_stories' : 'instagram-stories'),`

**Comment by mikehardy** [comment]
Are you watching unfiltered logcat at the same time? Usually there is a good reason thrown into there in the form of a stack trace or similar

**Comment by scgough** [comment]
> Are you watching unfiltered logcat at the same time? Usually there is a good reason thrown into there in the form of a stack trace or similar

Yea I did think that but nothing. It seems to hand over then it’s just thrown back with no reason :/

**Comment by scgough** [comment]
OK - this seems to be working now...false alarm. I must have had some caching going on somewhere along the line..

**Question 2:**

The sticker URL needs to be a local file. 
Do you think that if (for example) and external http(s) URL is provided for this sticker it should be (a) downloaded and processed within this component on the android side OR (b) dealt with in the source app's JS code which passes (for example) a Base64 string as the URL to the component.

I've started working on "(a)" but it got me wondering if this is the wrong direction.
