### ISSUE TITLE
How to Share to Instagram DM on IOS?

### ISSUE THREAD

**Issue by ramosquito5** [react-native-community/react-native-share#781]
## How to Share to Instagram DM on IOS?
I have been trying to Share to Instagram DM some text, but the option does not appear.
I have added the corresponding tags to info.plist for Instagram as well as other social networks which work perfectly.

The interesting part is that it does work on Android but not in IOs so I don't know what i am doing wrong.

This is my code on the app
```
import Share from 'react-native-share';
          const shareOptions = {
            title: "title",
            message: "message",
          };
          Share.open(shareOptions);
```
info.plist
```
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>twitter</string>
		<string>whatsapp</string>
		<string>instagram</string>
		<string>instagram-stories</string>
	</array>
```

Software 

```
react-native@0.62.2
react-native-share@3.3.2
```

Any help will be deeply appreciated.

**Comment by Bang9** [comment]
`Share.shareSingle({ social:"instagram, ... })`

**Comment by ramosquito5** [comment]
True, but why doesn't it work with the method open and only with shareSingle? on android open method works just fine.

**Comment by ezos86** [comment]
Side note - my binary is invalid when I have instagram-stories, is that working for everyone else?

**Comment by MateusAndrade** [comment]
> Side note - my binary is invalid when I have instagram-stories, is that working for everyone else?

Do you mean sharing to instagram stories? Could you share the error log? Or this is being refused at Itunes?

**Comment by ezos86** [comment]
> > Side note - my binary is invalid when I have instagram-stories, is that working for everyone else?
> 
> Do you mean sharing to instagram stories? Could you share the error log? Or this is being refused at Itunes?

I end up getting it to work, It was just Xcode issue, needed computer restart and update.

**Comment by DevJoaoLopes** [comment]
someone with a problem to share text via direct on instagram?

**Comment by MateusAndrade** [comment]
> someone with a problem to share text via direct on instagram? is possible ?

Calling `Share.open` doesn't work for you? I think this will show the share from Instagram with the DM option. Would you mind sharing your payload?

**Comment by blindibrasil** [comment]
Any updates on how to send a DM on Instagram with text and image?
I am currently using the following code and the only thing I can send is the image.

```
const shareOptions = {
  title: 'Compartilhar oferta via',
  message: 'Oferta do dia: \n Cimento Tocantins - R$ 24,99',
  social: Share.Social.INSTAGRAM,
  url:
    'data:image/jpeg;base64_CODE_OF_IMAGE,'
};
const shareButton = async () => {
    await Share.shareSingle(shareOptions);
  };
```

**Comment by MateusAndrade** [comment]
> Any updates on how to send a DM on Instagram with text and image?
> I am currently using the following code and the only thing I can send is the image.
> 
> ```
> const shareOptions = {
>   title: 'Compartilhar oferta via',
>   message: 'Oferta do dia: \n Cimento Tocantins - R$ 24,99',
>   social: Share.Social.INSTAGRAM,
>   url:
>     'data:image/jpeg;base64_CODE_OF_IMAGE,'
> };
> const shareButton = async () => {
>     await Share.shareSingle(shareOptions);
>   };
> ```

Which version you are using? Recently we added some changes to Instagram Stories. 🤔

**Comment by blindibrasil** [comment]
The version is: "react-native-share": "^3.7.0".
And with it I'm only able to send images via Direct Messages from Instagram.

**Comment by MateusAndrade** [comment]
> @MateusAndrade the version is: "react-native-share": "^3.7.0".
> And with it I'm only able to send images via Direct Messages from Instagram.

When you pass the payload that you sent, it sends only the message to the `Stories`?

**Comment by blindibrasil** [comment]
@MateusAndrade 
It gives me the following options:
Send via:
Direct;
Feed;
Stories;

Except that when trying to send via Direct to a user it is only possible to send an image and not an image and text as is what I want.

**Comment by TereshchenkoVlad** [comment]
I can't share my link to instagram.
`const shareOptions = {
        title: 'Invitation link',
        message: 'Invitation link',
        url: link.current,
        social: Share.Social.INSTAGRAM,
      };
await Share.shareSingle(shareOptions);
`
This code open the Instagram, but i don't have any opportunities to share my code inside Instagram.

**Comment by hrishi-neo** [comment]
any solution for this? I want to dm in instagram.

**Comment by hrishi-neo** [comment]
> ## How to Share to Instagram DM on IOS?
> I have been trying to Share to Instagram DM some text, but the option does not appear. I have added the corresponding tags to info.plist for Instagram as well as other social networks which work perfectly.
> 
> The interesting part is that it does work on Android but not in IOs so I don't know what i am doing wrong.
> 
> This is my code on the app
> 
> ```
> import Share from 'react-native-share';
>           const shareOptions = {
>             title: "title",
>             message: "message",
>           };
>           Share.open(shareOptions);
> ```
> 
> info.plist
> 
> ```
> 	<key>LSApplicationQueriesSchemes</key>
> 	<array>
> 		<string>twitter</string>
> 		<string>whatsapp</string>
> 		<string>instagram</string>
> 		<string>instagram-stories</string>
> 	</array>
> ```
> 
> Software
> 
> ```
> react-native@0.62.2
> react-native-share@3.3.2
> ```
> 
> Any help will be deeply appreciated.

Hey did you find any solution for this? I'm also not able to send dm on ios. Works absolutely fine on android.

**Comment by dprajapati1179** [comment]
Any solution , I am unable to see Instagram in list of option in iOS only

**Comment by yasirwahid** [comment]
if anyone is still looking to DM on instagram with a builtin message here the code.

```
// enoceURI did the trick
 RNShare.shareSingle({
        message: encodeURI(
          'Checkout the great search engine: https://google.com',
        ),
        social: RNShare.Social.INSTAGRAM,
      })
```

**Comment by Romulo-Almeida** [comment]
> if anyone is still looking to DM on instagram with a builtin message here the code.
> 
> ```
> // enoceURI did the trick
>  RNShare.shareSingle({
>         message: encodeURI(
>           'Checkout the great search engine: https://google.com',
>         ),
>         social: RNShare.Social.INSTAGRAM,
>       })
> ```

Thank you!

It worked just fine!
