### ISSUE TITLE
Not working share in iPhone 11 Pro Max native app mail ?

### ISSUE THREAD

**Issue by sunilprajapatisa** [react-native-community/react-native-share#783]
Not working share in iPhone 11 Pro Max native app mail. When click on mail app, opening app and close immediately without any error.

**Comment by sunilprajapati714** [comment]
@EstebanFuentealba , Any updates?

**Comment by MateusAndrade** [comment]
@sunilprajapati714 would you mind sharing which version of rn-share are you using? Also with the react-native and an example?
