### ISSUE TITLE
how to share base64 pdf file with message?

### ISSUE THREAD

**Issue by isot1990** [react-native-community/react-native-share#785]
## Ask your Question

I try to share base64 pdf file with a message but it does not send the message with it? Do you have solution for that?

**Comment by MateusAndrade** [comment]
Hi, @isot1990, would you mind sharing how you are trying to call `Share.open`? Also which platform you are experiencing this issue. 😄

**Comment by anwarDigitalDividend** [comment]
Facing the issue on Android

    let shareOptionsUrl = {
      title: 'My Application',
      message: 'Use my application',
      subject: 'Share information from your application',
      url :`data:image/jpeg;base64,${res}`;
    };
Share.open(shareOptionsUrl);

**Comment by SanjanaTailor** [comment]
Hello,
```
ShareMessage = async () => {
    try {
      await Share.share({
       title: 'Share',
       message: 'About.pdf',
       subject: 'Share information from your application',
       url: 'file://../../../../assets/Pdfs/Aboutpdf',
      });
    } catch (error) {
      console.log(error.message);
    }
  };
```
how to share base64 URL and pdf currently in assets folder .
Any suggestions please help me on this.

**Comment by isot1990** [comment]
> Hi, @isot1990, would you mind sharing how you are trying to call `Share.open`? Also which platform you are experiencing this issue. 😄

Hello Mateus,

I am using Share.open and the platform is react native.

Share.open({
      title: 'title',
      message: 'message',
      url: 'data:application/pdf;base64,' + res,
    });

thank you for your interest.

**Comment by MateusAndrade** [comment]
@SanjanaTailor you can try following our [guide](https://react-native-community.github.io/react-native-share/docs/share-remote-file), passing the file as base64  will probably solve your problem.

@isot1990 sorry for the long wait. Are you facing this on both Android/ios? Also, would you mind testing our example app to reproduce that?

**Comment by SanjanaTailor** [comment]
@MateusAndrade : Hi Thank you for the guide. Currently Pdf is inside assets folders 
```
static sharePDFWithAndroid(fileUrl, type) {
  let filePath = null;
  let file_url_length = fileUrl.length;
  const configOptions = { fileCache: true };
  RNFetchBlob.config(configOptions)
    .fetch('GET', fileUrl)
    .then(resp => {
      filePath = resp.path();
      return resp.readFile('base64');
    })
    .then(async base64Data => {
      base64Data = `data:${type};base64,` + base64Data;
      await Share.open({ url: base64Data });
      // remove the image or pdf from device's storage
      await RNFS.unlink(filePath);
    });
}
```
so how to modify above code on click of share button ?
Please give me code snippet to use it. Thank you

**Comment by MateusAndrade** [comment]
> Please give me code snippet to use it. Thank you

By `assets` you mean the assets folder inside the app on Android? 🤔

**Comment by SanjanaTailor** [comment]
yes, assets is react native architecure where inside src -> assets -> share.pdf is there so how to refactor above code using assets folder path @MateusAndrade ?

**Comment by MateusAndrade** [comment]
> yes, assets folder inside react native file structure inside src -> assets -> share.pdf. so how to refactor above code using assets folder path @MateusAndrade ?

If you are sharing a file from the `src/assests/sharePdf` which is inside your react-native project, maybe a require passing this to RNFetchBlob could work. Did you try using the [file-system)](https://github.com/joltup/rn-fetch-blob#file-system) API from RNFetchBlob to find your files?

Also, maybe you will need to apply [this](https://react-native-community.github.io/react-native-share/docs/install#adding-your-implementation-of-fileprovider) config on the native side.

**Comment by SanjanaTailor** [comment]
okay Thank you @MateusAndrade ,
on which line shall I pass path  inside fetch can you help me to correct below code ? and what are changes I need to do 
as fileURL, type what shall I pass and also using File-system ?

static sharePDFWithAndroid(fileUrl, type) {
  let filePath = null;
  let file_url_length = fileUrl.length;
  const configOptions = { fileCache: true };
  RNFetchBlob.config(configOptions)
    .fetch('GET', 'src/assets/sharePDF')
    .then(resp => {
      filePath = resp.path();
      return resp.readFile('base64');
    })
    .then(async base64Data => {
      base64Data = `data:${type};base64,` + base64Data;
      await Share.open({ url: base64Data });
      // remove the image or pdf from device's storage
      await RNFS.unlink(filePath);
    });
}

**Comment by MateusAndrade** [comment]
@SanjanaTailor  maybe something likes this:

```js
static sharePDFWithAndroid(fileUrl, type) {
let filePath = null;
let file_url_length = fileUrl.length;
const configOptions = { fileCache: true };
RNFetchBlob.config(configOptions)
.fetch('GET', `${RNFetchBlob.dirs. CacheDirsharePDF}/yourFile.pdf`)
.then(resp => {
filePath = resp.path();
return resp.readFile('base64');
})
.then(async base64Data => {
base64Data = data:${type};base64, + base64Data;
await Share.open({ url: base64Data });
// remove the image or pdf from device's storage
await RNFS.unlink(filePath);
});
```

I recommend you give a look at the dirs [documentation](https://github.com/joltup/rn-fetch-blob/wiki/File-System-Access-API#dirs)

**Comment by elifcakirr** [comment]
still have this problem, anyone have a solution?

**Comment by yuriigeivakh** [comment]
I have the same issue with android, issue hasn't resolved(
