### ISSUE TITLE
Email to specific person not working! ;(

### ISSUE THREAD

**Issue by jeremyfrancis** [react-native-community/react-native-share#786]
I want a user to click a button and then it opens up with an email ready to be sent to a specific email. So I filled in "email" with that email it should be sent to! It opens the iOS mail app with the correct subject and message, but the "To" field is completely empty. Not really sure there's anything I can do. Can this be fixed please!?

Share.shareSingle({
            subject: 'Support',
            message: "",
            social: Share.Social.EMAIL,
            email: "support@mysite.com"
})

**Comment by mikehardy** [comment]
Why not use a "mailto:" link? A lot easier.
