### ISSUE TITLE
How to share the quote/text message on Facebook?

### ISSUE THREAD

**Issue by ajaykumar97** [react-native-community/react-native-share#788]
## Ask your Question

Hi! firstly, thanks a lot for this great module.
I am trying to share the playstore link of my application and some text along with the url. I am able to share the url but I am not able to share the text. I tried to share the text in `quote` key but it is not working for the Facebook share. My code for the Facebook share is: 

```
Share.shareSingle({
                    title: 'shareVia',
                    message: 'I am message',
                    caption: 'I am a caption',
                    url: 'https://www.google.com',
                    social: Share.Social.FACEBOOK,
                    contentDescription: 'Facebook sharing is easy!',
                    quote: 'I am quote',
                    type: 'url',
});
```

Can anyone please help me in this and guide me how to share the text and the url on Facebook?

**Comment by MateusAndrade** [comment]
Hi @ajaykumar97, thanks for your feedback 🙉 ! Which platform are you facing this?

**Comment by ajaykumar97** [comment]
@MateusAndrade I am facing this issue on both, android and iOS platforms. My dependencies versions are:

```
"react": "16.11.0",
"react-native": "0.62.2",
"react-native-share": "^3.3.2",
```

**Comment by brmk** [comment]
Experiencing the same behavior. Facebook message is empty when using Share.shareSingle (tested without Facebook app installed)

**Comment by MateusAndrade** [comment]
> Experiencing the same behavior. Facebook message is empty when using Share.shareSingle (tested without Facebook app installed)

This happens when you are using `Share.open` instead?

**Comment by artemkhalygov** [comment]
@MateusAndrade I have same issue with Share.open

**Comment by johnlim5847** [comment]
I'm facing the same issue, it works fine on Twiter, Messenger, Whatsapp, Telegram and etc but not on Facebook. Do you guys have any workaround for Facebook?

**Comment by ajaykumar97** [comment]
For now, I have used the Facebook SDK for sharing the text on Facebook. I am sharing the text as a `quote`:

```
import {ShareDialog} from 'react-native-fbsdk';

const shareLinkContent = {
      contentType: 'link',
      contentUrl: 'https://www.google.com',
      quote: 'I am a message',
};
ShareDialog.show(shareLinkContent);
```

**Comment by nadercojo** [comment]
Guys it is in their Conditions and Terms you cannot share any text till the user types it on FB fields :-) stupid I know

**Comment by yqlim** [comment]
> Guys it is in their Conditions and Terms you cannot share any text till the user types it on FB fields :-) stupid I know

@nadercojo do you have the URL linking to this terms and conditions?

**Comment by shantanuIngle** [comment]
@yqlim a little late but here you go 
https://developers.facebook.com/docs/apps/review/prefill/
