### ISSUE TITLE
Example app crashes in iOS with react-native0.62.2

### ISSUE THREAD

**Issue by Kta-M** [react-native-community/react-native-share#789]
### Steps to reproduce
1. `npx react-native init example`
2. `cd example`
3. `npx pod-install`
4. copy `App.js` `images/*`, `components/*` from `react-native-share/example/`
5. run app in ios simulator
6. all buttons crashes the app

### Expected behaviour
share menu comes in.

### Actual behaviour
the app crashes without any messages.

### Environment
- **React Native version**:0.62.2
- **React Native platform + platform version**: iPhone11, iOS 13.4.1

### react-native-share
**Version**: 3.3.2

### Link to repo (highly encouraged)
https://github.com/Kta-M/react-native-share-example-app

**Comment by Kta-M** [comment]
- It works when [this line](https://github.com/Kta-M/react-native-share-example-app/blob/master/ios/example/AppDelegate.m#L21) is commented out, so I think it is affected by FlipperKitNetworkPlugin.
- #783 might be a question about this bug.

**Comment by MateusAndrade** [comment]
Thanks @Kta-M  did you tested this on a fresh project with rn 0.62.2? I think we might need to look at the update in the example app to fix this.

**Comment by mikehardy** [comment]
Updating examples should never ever take maintainer time :-) 
https://github.com/react-native-community/react-native-device-info/blob/master/refresh-example.sh

**Comment by MateusAndrade** [comment]
> Updating examples should never ever take maintainer time :-)
> https://github.com/react-native-community/react-native-device-info/blob/master/refresh-example.sh

Thanks, Mike! I will look forward to implementing this. 🙉

**Comment by Kta-M** [comment]
Thanks @MateusAndrade, yes, I tested  this on a fresh project (https://github.com/Kta-M/react-native-share-example-app).

**Comment by MateusAndrade** [comment]
> Thanks @MateusAndrade, yes, I tested this on a fresh project (https://github.com/Kta-M/react-native-share-example-app).

Strange, I tested this here with a fresh project with the following version and it works fine. Also, I checked your project and your dependencies are matching with the ones that I tested here.

```
  "dependencies": {
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-share": "^3.3.2"
  }
```

I checked here, it looks that the example app is using a version `3.0.0` of `react-native-share`. Probably because it's using the master version, then the hash should be saved at the `.lock`. I will try to look at that, but I would appreciate it if you help me with this. 😄

**Comment by Kta-M** [comment]
> I checked here, it looks that the example app is using a version 3.0.0 of react-native-share.

"the example app" is referring to my `Kta-M/react-native-share-example-app` or this repository's   `react-native-community/react-native-share/example`?

My example app has a committed `package-lock.json` file and [uses react-native-share `3.3.2`](https://github.com/Kta-M/react-native-share-example-app/blob/master/package-lock.json#L7984). This does not work in my environment.
The example app in this repository will work. When I tried it, the hash was 10c72e4, the latest commit, not `3.0.0`.

In addition, thinking that it might be a problem of the environment of the iOS simulator, I executed `Device` > `Erase All Erase All Content and Settings`, but after all my example app does not work😢

**Comment by Kta-M** [comment]
@MateusAndrade, I've solved it!

It was a problem on the react-native side.
https://github.com/facebook/react-native/issues/28589

Upgrading Flipper in the Podfile from `0.33.1` to `0.37.0` solved the problem.

In react-native, the following pull requests have already been merged and it looks like they are going to include `0.63.0`😄
https://github.com/facebook/react-native/pull/28597
https://github.com/facebook/react-native/pull/28545
