### ISSUE TITLE
Share.open not working on Alert options

### ISSUE THREAD

**Issue by kelvinaliyanto** [react-native-community/react-native-share#79]
Hi, I am trying to ask the user whether they want to share or not using Alert. But for some reason, the Share.open is not executed. Is it not supported? Because when I tried to share using a button (Touchable), the Share.open does work correctly. Any suggestion is appreciated.

**Comment by manjeet-dobble** [comment]
please add some code, may be you need to call share.open() in callback of your yes/no pressed

**Comment by kelvinaliyanto** [comment]
Hi @manjeet-dobble , here is the code:

`componentWillMount() {
		this.retrieveBookingDetail();
	},
	shareBooking() {
		var shareOptions;
		var message;
		if (booking_detail) {
			message = "Hi";
			shareOptions = {
				title: "Hello",
				message: message
			};
		} else {
			shareOptions = {
				title: "Hello",
				message: ""
			};
		}
		Share.open(shareOptions);
	},
	async retrieveBookingDetail() {
		try {
			var obj = {  
				method: 'POST',
				headers: {
					'Accept': 'application/json',
					'Content-Type': 'application/json'
				},
				body: JSON.stringify({
					'booking_code': this.props.booking_code
				})
			};
			let response = await fetch(http://example.com, obj);
			let resjson = await response.json();
			resjson = resjson.data_array;
			this.setState({
				booking_detail: resjson
			});
			if (this.props.ask_share) {
				Alert.alert(
					'Share now', 
					'Do you want to share now?',
					[
						{text: 'Yes', onPress: () => this.shareBooking()},
						{text: 'Later', style: 'cancel'}
					]
				);
			}
		} catch(error) {
			Alert.alert('No Internet Connection', 'Please connect to a network',
			[
				{text: 'Retry', onPress: () => this.retrieveBookingDetail()},
			]
			);
		}
		this.setState({loading: false});
	},`

**Comment by EstebanFuentealba** [comment]
pass url in shareOptions 

```javascript
shareOptions = {
title: "Hello",
message: "",
url: "http://a.cl"
};
Share.open(shareOptions);
```

**Comment by kelvinaliyanto** [comment]
Hi @EstebanFuentealba, passing url however does not fix the issue. Is it because it cannot be used together with Alert function? I managed to get this log from xcode: 

`2016-11-08 10:31:21.979 golf[67663:1822231] Warning: Attempt to present <UIActivityViewController: 0x7f8022cce710> on <UIAlertController: 0x7f8022cab900> whose view is not in the window hierarchy!`

Not sure what it is because I am not proficient in Obj-C, but I will try my best to debug on my part. Thanks.

**Comment by fencex** [comment]
`     setTimeout(() => {
                    Share.open(shareOptions);
                  }, 600);`

**Comment by fencex** [comment]
`setTimeout(() => {`
                  `  Share.open(shareOptions);`
                  `}, 600);`

**Comment by fencex** [comment]
The problem is solved by using  `setTimeout `:

` setTimeout(() => {Share.open(shareOptions);}, 600);`

Remember to set a big `timeout`;

**Comment by enieber** [comment]
@kelvinaliyanto can you try the new version of the master branch?
