### ISSUE TITLE
Documentation.. Whaaa??

### ISSUE THREAD

**Issue by ezos86** [react-native-community/react-native-share#791]
## Can we get some clean examples of actual use cases?

The documentation for this is the worse I have seen for any react-native-community, it has a lot there, thank you. But just overall clean use cases to test, impossible to know the correct structure of JSON, without hours of trial and error.

**Comment by mikehardy** [comment]
I believe the example is the documentation https://github.com/react-native-community/react-native-share/blob/master/example/App.js

Is it missing something? PRs are merged here frequently, feel free to propose something

**Comment by ezos86** [comment]
> I believe the example is the documentation https://github.com/react-native-community/react-native-share/blob/master/example/App.js
> 
> Is it missing something? PRs are merged here frequently, feel free to propose something

This is great, I think it would be great to add documentation or common use cases links, that have walk throughs. I might do this for some as I work on them for my own app. 
ie: Share a sticker on instagram
ie: Share a post with image on Facebook

And they have little tutorials in there on how to do that. So I guess more walkthroughs then documentation. Thanks for the link though, this does help.

**Comment by MateusAndrade** [comment]
@ezos86 please check out: https://react-native-community.github.io/react-native-share. 😄

**Comment by mikehardy** [comment]
Those are pretty @MateusAndrade !

**Comment by MateusAndrade** [comment]
> Those are pretty @MateusAndrade !

Thanks a lot. 🙈 🙈 🙈

**Comment by friederbluemle** [comment]
Nice @MateusAndrade 👍

**Comment by infinitbility** [comment]
React Native Share Tutorial with examples.

https://infinitbility.com/react-native-share

Hope it helpful for you
