### ISSUE TITLE
can i get more information after complete share ??

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [react-native-community/react-native-share#80]
Hi,

can i get more information after completely shared??

i want information about on which app user share this links,

and more another information.

**Comment by matart15** [comment]
@nilaybrahmbhatt did you manage to get any info about completion?

**Comment by matart15** [comment]
I am not good with obj-c but completion:Nil on this line seems we can't get completion callback with current version. Is it right? https://github.com/EstebanFuentealba/react-native-share/blob/master/ios/GenericShare.m#L48

**Comment by ahmdsdk** [comment]
```
Share.open(options).then((obj) => {
    // gives you a string "app" in which it says where did the user share //
    console.log("shared", obj);
}).catch(err => console.log(err));
```

**Comment by jgcmarins** [comment]
great!

**Comment by mikehardy** [comment]
master has a change for android where the promise waits for the share to be returned - it was spotted and fixed recently

**Comment by mikehardy** [comment]
https://github.com/react-native-community/react-native-share/pull/482
