### ISSUE TITLE
Custom Icon not showing (shows App Icon instead)

### ISSUE THREAD

**Issue by thedivac** [react-native-community/react-native-share#804]
### Steps to reproduce

Opening Share Sheet with following options:

```javascript
let options=Platform.select({
        ios:{
          activityItemSources: [
            {
              placeholderItem: {
                type: 'url',
                content: 'data:image/png;base64,' + base64Data,
              },
              item: {
                default: {
                  type: 'url',
                  content: 'data:image/png;base64,' + base64Data,
                },
              },
              subject: {
                default: shoe.shoe_name + " - " + style.name
              },
              linkMetadata: {
                title: shoe.shoe_name + " - " + style.name,
                icon: 'data:image/png;base64,' + base64Data,
              }
            }
        ]
      },
      default:{
        title: shoe.shoe_name + " - " + style.name,
        url:'data:image/png;base64,' + base64Data,
        message:shoe.shoe_name + " - " + style.name,
      }
      });
```

### Expected behaviour

Share Sheet should show my custom icon on iOS

### Actual behaviour

Share Sheet shows app icon

### Environment
- **React Native version**: 0.62.2
- **React Native platform + platform version**: iOS 13

### react-native-share
npm 3.3.3

I played around with the options for a day but couldn't get it to work...

**Comment by MateusAndrade** [comment]
Hi @thedivac, would you mind testing this with our example app?

**Comment by thedivac** [comment]
I tested it with the example app:

```
  const shareSingleImage = async () => {
    const shareOptions = {
      activityItemSources: [
            {
              placeholderItem: {
                type: 'url',
                content: images.image1,
              },
              item: {
                default: {
                  type: 'url',
                  content: images.image1,
                },
              },
              subject: {
                default: "test"
              },
              linkMetadata: {
                title: "Test linkMetadata",
                icon: images.image1,
              }
            }
        ]

    };

```
Same issue, it's showing the example app icon instead of the custom icon:

![](https://user-images.githubusercontent.com/26794143/84955359-14271780-b0ef-11ea-96e3-9b072ddfc1f9.png)

**Comment by PidfihurnyiOrest** [comment]
The same issue, need to provide an example how to use custom icon in documentation

**Comment by thedivac** [comment]
Has anybody gotten this to work? I still can't figure out if this is a bug or if my config is wrong...

**Comment by aborile** [comment]
Same here 😢
I created new issue #848 and described [how it doesn't work in detail](https://github.com/react-native-community/react-native-share/issues/848#issuecomment-692418559)

**Comment by jiyuan12354** [comment]
same issue
