### ISSUE TITLE
Multiple File Share not working in iOS

### ISSUE THREAD

**Issue by nabilnalakath** [react-native-community/react-native-share#806]
### Steps to reproduce
1. Share two files separately - works fine
2. Share same files together - does not work

### Expected behaviour
Pop up to select application should appear and stay for user to select the app to share.
### Actual behaviour
Pop up to select application disappears as soon as it comes ( see gif below)

### Environment
- **React Native version**: 0.62.2
- **React Native platform + platform version**: iOS 13.5.0

### react-native-share
**Version**: 3.4.0"

**Share Config-** 

`{"email": "", "failOnCancel": false, "social": "email", "subject": "Multiple files have been uploaded and shared", "title": "Share file", "urls": ["/Users/nabil.nalakath/Library/Developer/CoreSimulator/Devices/F7886290-52D9-4ACC-805A-DAC2CC8A823D/data/Containers/Data/Application/9CAA5A4D-C026-4F76-9852-D1BF1A61A307/Documents/sample1.pdf", "/Users/nabil.nalakath/Library/Developer/CoreSimulator/Devices/F7886290-52D9-4ACC-805A-DAC2CC8A823D/data/Containers/Data/Application/9CAA5A4D-C026-4F76-9852-D1BF1A61A307/Documents/sample2.pdf"]}`

![fileshare](https://user-images.githubusercontent.com/32065631/84945716-37f55800-b105-11ea-94b0-18976d7704cb.gif)

**Comment by MateusAndrade** [comment]
Hi @nabilnalakath , this is happening only on IOS? Also, did you try sharing the `urls` with a base64?

**Comment by nabilnalakath** [comment]
@MateusAndrade Yes. Only in iOS, these same files work fine in Android. And no, I haven't tried sharing base64 URLs.

**Comment by MateusAndrade** [comment]
Can you try sharing with base64 only? Also, could you share the options that you are sending to `Share.open`?

**Comment by nabilnalakath** [comment]
@MateusAndrade It works with base64. So does this mean I cannot use local paths for multiple file sharing at all?

**Comment by nabilnalakath** [comment]
@MateusAndrade It also causes my app to crash when I am trying to pass an array of base64 URLs created from multiple PDF files as soon as I call the share.open function. I cannot get logs anything in the then() or catch() block as well.

**Comment by MateusAndrade** [comment]
Hi, @nabilnalakath sorry for the wait. I think this crash on iOS might be related to #797. Would you mind testing if these changes solve your problem?
