### ISSUE TITLE
How to share custom text file types (IGC)?

### ISSUE THREAD

**Issue by enesozturk** [react-native-community/react-native-share#807]
Hi! Thanks for provide such a good library. I am using this lib to share my local or remote files. I can share files both Android and iOS. But in Android, I need to convert my files to base64. So far so good. But when I try to share my base64 coded file, lib adds different file extension to my file. Here is info about my files;

My files are **flight record file that has to be .IGC extension (just string inside)**. I create my record like file_name.IGC. When I try to share it in Android;

### Example 1
**File Name:** '2020-06-20-11-51-28-FNMN.IGC'
**Converting to base 64 (data:text/plain)**
```
await RNFS.readFile(fileURLToShare, 'base64').then(res => {
     fileURLToShare = `data:text/plain;base64,${res}`;
});
```
**Share Options**
```
Share.open({
        url: fileURLToShare,
        email: user.email,
        filename: fileName,
        showAppsToView: true,
        type: 'other',
        title: fileName,
})
```

**Result:**
<img width="415" alt="Screen Shot 2020-06-20 at 11 53 02" src="https://user-images.githubusercontent.com/19428358/85197877-9fb9c780-b2ec-11ea-9a7c-fecd33aa5ef3.png">

### Example 2
**Converting to base 64 (data:text/igc)**
```
await RNFS.readFile(fileURLToShare, 'base64').then(res => {
     fileURLToShare = `data:text/igc;base64,${res}`;
});
```
**Result:** Same above

### Example 3
**file_name:** '2020-06-20-11-51-28-FNMN' (I created record file without any extension to try)
**Converting to base 64 (data:text/plain)**
```
await RNFS.readFile(fileURLToShare, 'base64').then(res => {
     fileURLToShare = `data:text/igc;base64,${res}`;
});
```
**Result:**
<img width="397" alt="Screen Shot 2020-06-20 at 12 01 45" src="https://user-images.githubusercontent.com/19428358/85198009-d512e500-b2ed-11ea-966e-5ddf572fa75b.png">

What should I do to share my record file with .igc extension?
Thanks in advance

"react-native-share": "3.3.2",
"react-native": "0.61.4",

**Comment by MateusAndrade** [comment]
Hi @enesozturk, sorry for the wait. Do you found any solution to that? Also, did you try sharing the file directly instead of converting this?

**Comment by enesozturk** [comment]
Hi @MateusAndrade, that not problem, thanks for responding me. Unfortunately I could not found any solution for Android. Yes I tried. I don't remember what was the problem by sharing without base64 but it was not working. After converting to base64, it worked. But this time I have this problem. I will retry sharing without base64.

**Comment by enesozturk** [comment]
When I try to share without base64, it shares string like below;

![Screen Shot 2020-06-29 at 11 36 59](https://user-images.githubusercontent.com/19428358/85992641-d767f400-b9fd-11ea-889d-99651fecca4a.png)

And if I put 'file://' beggining of the string I see;

![Screen Shot 2020-06-29 at 11 41 42](https://user-images.githubusercontent.com/19428358/85992464-9a036680-b9fd-11ea-8fbc-dd1b9d898b97.png)

**Comment by enesozturk** [comment]
Hi @MateusAndrade , do you have any idea about sharing specific file (like .igc extension). How can I share it in Android? Do you have any suggestion for that? Thanks in advance.

**Comment by perfecten** [comment]
@enesozturk I have the same problem, just share a text string. How can I share a file ? Would you like to give me some advices? Thanks

**Comment by enesozturk** [comment]
Following settings solved my problem on Android;

```
Share.open({
   ...
   url: 'file://' + fileURLToShare,
   type: 'plain/text',
   ...
})
```

**Comment by perfecten** [comment]
@enesozturk Thank you very much.
