### ISSUE TITLE
Unable to share an Gif (base64) on IOS

### ISSUE THREAD

**Issue by Mavenic** [react-native-community/react-native-share#809]
### Steps to reproduce
1. Download a gif from URL as a base 64.
2. Share using `shareSingle(...)` (Tried for Facebook, Instagram & Mail)
3. It loses all it's animation when shared.

### Expected behaviour
It should be able to share the animated gif on the above-mentioned platforms.

### Actual behaviour
It shares a static image on Facebook (only in IOS) and Instagram (Android and IOS). When shared on email (Only In IOS) it shares the actual base 64 string in the mail. Double checked if base64 code correct, yes it is. The screenshot for mail is attached.

![85055127-bb24b580-b1ba-11ea-9453-e7d1fbf75241](https://user-images.githubusercontent.com/1584324/85359446-e77e6000-b533-11ea-9f2b-67c4bb86f824.jpg)

### Environment
- **61.5**
- **ios 13**

### react-native-share
**3.5.0**

### Link to repo (highly encouraged)
https://github.com/

**Comment by MateusAndrade** [comment]
Hi @Mavenic did you try passing the path file or something like instead of a base64? Also, there is an application that handles this correctly?

**Comment by Mavenic** [comment]
@MateusAndrade Yes, I tried with the local file instead of base64 and it's the same result. On Android, it works as expected except for Instagram, on IOS it doesn't, neither for Facebook nor Instagram. I'm trying some workaround, let's see if that works.

**Comment by MateusAndrade** [comment]
@Mavenic  let me know if there is anything that I can help you.
