### ISSUE TITLE
Instagram on iOS: the Instagram share option doesn't appear in the standard iOS menu 

### ISSUE THREAD

**Issue by MrUmarArshad** [react-native-community/react-native-share#810]
### Steps to reproduce
1. just install react-native-share or use Share from React
2. click share button 

### Expected behavior
After open Share Action Instagram app there 

### Actual behavior
After the open Share Action sheet, all apps are there. but Instagram is not present in list
### Environment
- **React Native version**:  0.61.5
- **React Native platform + platform version**: iOS 13.0, Android 5.0, etc

### react-native-share
**Version**: npm version or "master"

**Comment by vforvasile** [comment]
As far as I know, you need to install and open Instagram a few times until Android system detects the app and adds it to the share sheet. For stories, you have to open Create Story and allow all permissions, maybe create a dummy story as a test.

**Comment by MateusAndrade** [comment]
@vforvasile maybe this can be related to how iOS handle deep linking or something similar. Also, @MrUmarArshad did you set your URL schemes?

https://react-native-community.github.io/react-native-share/docs/share-open#lsapplicationqueriesschemes-ios-only
