### ISSUE TITLE
Add recipients for SMS sharing on Android

### ISSUE THREAD

**Issue by Ackuq** [react-native-community/react-native-share#812]
## Describe the Feature
Be able to specify recipients when sending SMS on Android. 

## Possible Implementations
When using SMS, have a field in the options object that specifies the recipients as an array of phone numbers, for example  `{ ... social: 'sms', recipients: Array<string> ...}`.

## Related Issues
#762

**Comment by mikehardy** [comment]
PRs happily accepted
