### ISSUE TITLE
TypeError: Cannot read property 'FACEBOOK' of null

### ISSUE THREAD

**Issue by xxczaki** [react-native-community/react-native-share#817]
### Steps to reproduce
1. Import `react-native-share@3.6.0`

### Expected behaviour
I should be able to actually use the library.

### Actual behaviour
I get the following error:

```
TypeError: Cannot read property 'FACEBOOK' of null, js engine: hermes
```

### Environment
- **React Native version**: `0.63.0-rc.1`
- **React Native platform + platform version**: Android 9.0

### react-native-share
**Version**: `3.6.0`

### Additional information:

Related to #360

**Comment by mikehardy** [comment]
I don't believe you have integrated the module correctly in your project, that's almost always the cause.
If you can reproduce this in the example app, there is a problem, otherwise it's a project integration issue

**Comment by mikehardy** [comment]
Or just by doing react-native-init SampleApp, an add of this module, and attempting to use it trivially

**Comment by xxczaki** [comment]
@mikehardy You were right, I did not set up everything correctly :laughing:

**Comment by brunoosella** [comment]
@xxczaki i have the same problem, what's was wrong with your set up?

**Comment by mikehardy** [comment]
@brunoosella usually this means "I have added the module and tried to use it in javascript, but have not actually built it (with auto-linking working correctly) in to my native code that's installed and running on my test device"

**Comment by gshoanganh** [comment]
> @xxczaki i have the same problem, what's was wrong with your set up?

please run full:
step 01: `yarn add react-native-share` or `npm install react-native-share`
step 02: `npx pod-install` or `cd ios && pod install`.  (You can skip this step, if you are using this on Android).

**Comment by Tukutlas** [comment]
Please has anyone solved this issue, I am currently facing it

**Comment by Tukutlas** [comment]
this helped me out `<a href="https://reactnative.dev/docs/share" target="_blanc">https://reactnative.dev/docs/share</a>`

**Comment by priyanshi-zepto** [comment]
@xxczaki how did you fixed the issue?

**Comment by wannarun526** [comment]
I face the same issue. Does anyone address the problem? 
packages version: 

"react-native": "0.72.3"
"react-native-share": "8.2.2"

**Comment by belsalm** [comment]
What worked for me was to import only what you need to avoid loading social modules automatically.

In your file:

Change the import:
import Share from 'react-native-share';

to:
import { open } from 'react-native-share';

and change your code from:
Share.open(shareOptions)

to:
open(shareOptions)
