### ISSUE TITLE
Open login dialog on facebook, twitter and instgram?

### ISSUE THREAD

**Issue by hunghkit** [react-native-community/react-native-share#820]
First at all, thank you so much on your great package.

I'm working with this package, I just have a question should we open a dialog for login on social instead of just show a message and ask user back to app and login on there?

**Comment by MateusAndrade** [comment]
Hi @hunghkit, let me see if I understood: you want to open the login screen on these applications? Currently, we don't support that and also I think you should ask for your users to log in on the desired application before sharing(I don't know if these application can redirect the user to the sharing after login in).

**Comment by hunghkit** [comment]
got it, thanks @MateusAndrade ;)
