### ISSUE TITLE
Crashed on iOS 14 with EXC_BAD_ACCESS error

### ISSUE THREAD

**Issue by lkwjohn** [react-native-community/react-native-share#823]
### Steps to reproduce
1. Run the app on iOS 14
2. Open Share function that call Share.open
3. Crashed

### Expected behaviour
Should behave the same for as compared to iOS 13 and below

### Actual behaviour
Once the Share.open was being called, it crashed
Retrieved error on  the line indirect_symbol_bindings[i] = cur->rebindings[j].replacement

```
static void perform_rebinding_with_section(struct rebindings_entry *rebindings,
                                           section_t *section,
                                           intptr_t slide,
                                           nlist_t *symtab,
                                           char *strtab,
                                           uint32_t *indirect_symtab) {
  uint32_t *indirect_symbol_indices = indirect_symtab + section->reserved1;
  void **indirect_symbol_bindings = (void **)((uintptr_t)slide + section->addr);
  for (uint i = 0; i < section->size / sizeof(void *); i++) {
    uint32_t symtab_index = indirect_symbol_indices[i];
    if (symtab_index == INDIRECT_SYMBOL_ABS || symtab_index == INDIRECT_SYMBOL_LOCAL ||
        symtab_index == (INDIRECT_SYMBOL_LOCAL   | INDIRECT_SYMBOL_ABS)) {
      continue;
    }
    uint32_t strtab_offset = symtab[symtab_index].n_un.n_strx;
    char *symbol_name = strtab + strtab_offset;
    if (strnlen(symbol_name, 2) < 2) {
      continue;
    }
    struct rebindings_entry *cur = rebindings;
    while (cur) {
      for (uint j = 0; j < cur->rebindings_nel; j++) {
        if (strcmp(&symbol_name[1], cur->rebindings[j].name) == 0) {
          if (cur->rebindings[j].replaced != NULL &&
              indirect_symbol_bindings[i] != cur->rebindings[j].replacement) {
            *(cur->rebindings[j].replaced) = indirect_symbol_bindings[i];
          }
           
          indirect_symbol_bindings[i] = cur->rebindings[j].replacement; #EXC_BAD_ACCESS
          goto symbol_loop;
        }
      }
      cur = cur->next;
    }
  symbol_loop:;
  }
}
```

### Environment
- **React Native version**: 0.60.4
- **React Native platform + platform version**: iOS 14
- **Xcode**: 11.5

### react-native-share
**Version**: 3.7

### Link to repo (highly encouraged)
```
#url is a photo stored on a tmp folder 
# /var/mobile/Containers/Data/Application/A56D9C0C-B407-4250-9A6F-50D4210E9EA8/Documents/temp/share/<file-name>.jpeg"

 const url = Platform.select({
                ios: path,
                android: 'file://' + path
            });

Share.open({
                url: url,
                failOnCancel: false
            });
```

**Comment by lkwjohn** [comment]
did a change to use React Native Share module, seems to be having the same issue, the root cause might be react native itself on iOS 14

**Comment by lkwjohn** [comment]
Went to dig deeper, the problem lies in the fishhook code where 0.60.4 still integrate with fishhook. upgraded RN to 0.60.6 and it works fine now. Closing this issue.

**Comment by menna-magdy-182** [comment]
issue still exists, using react-native 0.63.2

**Comment by mikehardy** [comment]
react-native 0.63 is old enough it's out of support.
As a general rule the process to follow when you have a problem is:

1) check your versions
2) if you have versions that are not current stable, don't talk about it anywhere, perform your deferred maintenance and update your software to stable versions
3) attempt to reproduce
4) if you still reproduce on current stable versions, post a comment or new issue with information required to help https://stackoverflow.com/help/minimal-reproducible-example / https://stackoverflow.com/help/how-to-ask

You've missed item 2
