### ISSUE TITLE
Sharing to Instagram does not work

### ISSUE THREAD

**Issue by NishidaRyu416** [react-native-community/react-native-share#824]
### Steps to reproduce

```
  RNFetchBlob.config({
          fileCache: true,
          appendExt: 'mp4',
        })
          .fetch('GET', 'MP4 VIDEO URL', {})
          .then(res => {
            shareOptions = {
              social: Share.Social.INSTAGRAM,
              url: res.path(),
              type: 'video/mp4',
            };
              res.flush();
            });
          });

```

### Expected behaviour
We should be able to share videos to Instagram.

### Actual behaviour
It seems that the very last file of image gallery on the device is selected for sharing instead of the specified video file.
### Environment
- **React Native version**:  0.61

### react-native-share
**Version**: npm version or "master"
The latest version, 3.7.0
### Link to repo (highly encouraged)
https://github.com/

**Comment by gavrilin-remote** [comment]
Hi, try to save your video gallery
`const savedVideo = await CameraRoll.saveToCameraRoll(uri, 'video')
    return savedVideo`

**Comment by NishidaRyu416** [comment]
Yes! I realised that later on.
The doc is not obviously providing enough info.
So, for people who might be facing this in the future, these steps below are needed to share videos to Instagram.

1. with `react-native-fetch-blob`, save a video to the cache directory.
2. with `react-native-camera-roll`, save the cached video to the device's camera roll.
3. specify the path to the camera roll for sharing to Instagram.

That's it!
Thx @gavrilin-remote anyway

**Comment by MateusAndrade** [comment]
> Yes! I realised that later on.
> The doc is not obviously providing enough info.
> So, for people who might be facing this in the future, these steps below are needed to share videos to Instagram.
> 
> 1. with `react-native-fetch-blob`, save a video to the cache directory.
> 2. with `react-native-camera-roll`, save the cached video to the device's camera roll.
> 3. specify the path to the camera roll for sharing to Instagram.
> 
> That's it!
> Thx anyway @gavrilin-remote

We can add a "recipe" to our docs explaining that. What do you think?

**Comment by NishidaRyu416** [comment]
> > Yes! I realised that later on.
> > The doc is not obviously providing enough info.
> > So, for people who might be facing this in the future, these steps below are needed to share videos to Instagram.
> > 
> > 1. with `react-native-fetch-blob`, save a video to the cache directory.
> > 2. with `react-native-camera-roll`, save the cached video to the device's camera roll.
> > 3. specify the path to the camera roll for sharing to Instagram.
> > 
> > That's it!
> > Thx anyway @gavrilin-remote
> 
> We can add a "recipe" to our docs explaining that. What do you think?

That will be definitely helpful. I feel like this module is not well documented:(

**Comment by mikehardy** [comment]
@NishidaRyu416 

> I feel like this module is not well documents:(

Well hit that little pencil button next to any of the docs and fix it :-)

**Comment by pvinis** [comment]
>     3. specify the path to the video in the camera roll for sharing to Instagram.

This step is not even needed. It only works because Instagram picks the latest image/video on camera roll.

It's one way to make it work, but it's definitely not the best, because deleting the photo after requires user interaction.
