### ISSUE TITLE
Share through Instagram added first photo from the gallery

### ISSUE THREAD

**Issue by ktarasenkowow** [react-native-community/react-native-share#830]
### Steps to reproduce
1. Call the method shareSingle from react-native-share

import RNShare from 'react-native-share';
...
RNShare.shareSingle({
        title: TITLE,
        method: RNShare.InstagramStories.SHARE_BACKGROUND_IMAGE,
        url,
        backgroundImage: 'https://sun9-68.userapi.com/ea7IDXOtU3Vd3Xa1tjhJuFZ1QVhyOMrIVDlX1A/kqkicjKOB7g.jpg',
        social: RNShare.Social.INSTAGRAM,
      })

### Expected behaviour
Adding **backgroundImage** to preview in instagram.

### Actual behaviour
Adding first image from gallery to preview in instagram.

### Environment
- **React Native version**: "react-native": "0.62.0",
- **Platform**: Only ios

### react-native-share
**Version**: "react-native-share": "^3.7.0",

**Comment by tmjordan** [comment]
@ktarasenkowow Hi, i have the same problem. Please how did you fix it?
Thanks for your help

**Comment by ktarasenkowow** [comment]
> @ktarasenkowow Hi, i have the same problem. Please how did you fix it?
> Thanks for your help

Try to use the last version

**Comment by davidwinograd1** [comment]
any updates? also facing this
