### ISSUE TITLE
Modal does disappear if we click on save image option on iOS

### ISSUE THREAD

**Issue by Hamawis** [react-native-community/react-native-share#832]
### Steps to reproduce
1.Wrap your component inside react native modal
2. Press share button then choose save image
3. Modal will get disappear

### Expected behaviour
Modal should not get disappear

### Environment
- **React Native version**: 0.61.5
- **iOS version**:  13

**Comment by ameena-arahman** [comment]
> ### Steps to reproduce
> 1.Wrap your component inside react native modal 2. Press share button then choose save image 3. Modal will get disappear
> 
> ### Expected behaviour
> Modal should not get disappear
> 
> ### Environment
> * **React Native version**: 0.61.5
> * **iOS version**:  13

Were you able to fix it ?
