### ISSUE TITLE
Is it possible to share multiple images at once?

### ISSUE THREAD

**Issue by eomine** [react-native-community/react-native-share#85]
I've been using this module to share images, one at a time. I'm using `RNFS.readFile` to get base64 data of the image, and setting the appropriate MIME type manually. It's working fine.

But, I would like to share multiple images with a single `Share.open` call. Is this possible?

Thanks!

**Comment by sibelius** [comment]
I think this code

https://github.com/tjvantoll/nativescript-social-share

can help

**Comment by fxfactorial** [comment]
you can watch progress here: https://github.com/EstebanFuentealba/react-native-share/issues/85

**Comment by Kampeone** [comment]
@eomine how exactly you managed to share the image from an url? I struggle to make this one work in my project

**Comment by eomine** [comment]
@Kampeone I had to use RNFS (`react-native-fs`) and:
1- Download the image file to the device;
2- Read the downloaded file;
3- Pass the file contents as a base64 string to `react-native-share`.

```
import RNFS from 'react-native-fs';
import Share from 'react-native-share';

share(file, fileName) {
  const localFile = `${RNFS.DocumentDirectoryPath}/${fileName}`;
  const options = {
    fromUrl: file,
    toFile: localFile,
  };
  RNFS.downloadFile(options).promise
    .then(() => this.share1(localFile))
    .catch(this.onError);
}
share1(localFile) {
  RNFS.readFile(localFile, 'base64')
    .then(base64 => {
      const mimeType = Utils.getMimeType(localFile);
      Share.open({
        type: mimeType,
        url: `data:${mimeType};base64,${base64}`,
      });
    });
}
```

Images could be JPG or PNG, so I had a `Utils.getMimeType` method to get the correct MIME type. It just read the file extension and returned the proper MIME type string (`image/jpeg` or `image/png`) accordingly.

**Comment by Kampeone** [comment]
@eomine Thanks, it worked!
