### ISSUE TITLE
Android Share Base64 Image Fail, RN 0.62 

### ISSUE THREAD

**Issue by HimiGame** [react-native-community/react-native-share#863]
Version:
"react-native-share": "^3.8.0",
"react-native": "0.62.2",

Des:
IOS is running normally
When Android shares, either the image cannot be displayed normally, or it prompts: failed to obtain resources

![image](https://user-images.githubusercontent.com/4198936/93300534-88c23d00-f829-11ea-9947-4b043bed7feb.png)

Code:
var shareOptions = {
                            message:"Test",
                            title:"Test",
                            type:"image/png",
                            url: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFwAAABWCAYAAABCdPE+AAAMXWlDQ1BJQ0MgUHJvZmlsZQAASImVVwdYU8kWnltSIbQAAlJCb6JIDSAlhBapUgVRCUkgoYSYEFTs6KKCaxcRsKGrIoquBZC1InYXxd4XCyqKLhZsqLwJCejqK9873zd3/pw585+SmXtnANBs50okOagWALnifGlsaCBjbHIKg/QIEAEB6AIHwOTyZBJWTEwEgDLQ/1PeXQOIor/spOD6efy/ig5fIOMBgKRCnM6X8XIhPgoAXsSTSPMBIAZBveXkfIkCCyHWlcIAIZ6uwJlKvFSB05V4c79NfCwb4kYAyOpcrjQTAI0WqGcU8DIhj8YjiJ3FfJEYAE1diP14Qi4f4niIh+Xm5inwbIjtoL0E4m0QM9O/48z8B3/6ID+XmzmIlXn1CzlIJJPkcKf+n6X535KbIx/wYQObulAaFqvIH9bwRnZeuAKrQ9wlTo+KVtQa4g8ivrLuAKBUoTwsQWmPGvNkbFg/oA+xM58bFA6xMcQh4pyoCJU+PUMUwoEYrhZ0iiifE6+au0AgC45TcVZJ82KjB3CGlM1Sza3jSvv9Kuxb5NkJLBX/DaGAM8D/tlAYnwQxFQCMWiBKjIJYA2JdWXZcuNIGsygUsqMGbKTyWEX8VhAzBeLQQCU/lpohDYlV2UtyZQP5YsVCESdKhcvzhfFhyvpg23nc/vgNIK4XiFkJAzwC2diIgVz4gqBgZe5Yq0CcoMoXuyfJD4xVze2W5MSo7HGyICdUobeA2EhWEKeai4/Kh4tTyY9HSPJj4pVx4mlZ3NExynjwAhAB2CAIMIActnSQB7KAqLWroQv+Uo6EAC6QgkwgAE4qzcCMpP4RMXzGgULwAiIBkA3OC+wfFYACqP8yqFU+nUBG/2hB/4xs8BjiXBAOcuBvef8s8aC3RPAIakQ/eefBWHNgU4z9rGNBTYRKIx/gZWgOWBKDiUHEMGII0R43wv1wHzwCPgNgc8GZuNdAtN/sCY8JbYQHhKuEdsLNiaIi6Q+xRIJ2yB+iyjj9+4xxG8jpjgfivpAdMuP6uBFwwt2gHxbuDz27Qy1bFbcid8a/yXMwg+9qrrKjOFNQyhBKAMXux5kaDhrugyyKin5fH2Ws6YNVZQ+O/Oif/V2d+bAP/9ESW4DtxU5hx7Az2EGsATCwI1gjdh47pMCDa+hR/xoa8BbbH0825BH95I+r8qmopMy51rnT+bNqDOQLpuQrNhg7TzJVKsoU5jNY8CsgYHDEvOHDGC7OLs4AKL4pytdU94X+bwViqP1NNycPgFFVfX19B77pIu8CsO8F3Oa3vulsS+DroACA0xU8ubRAqcMVDwJ8G2jCHWUITIElsIMZuQAP4AMCQDAYDaJBPEgGE2CdhXA9S8FkMB3MAcWgFCwFq0AFWA82gW1gJ9gDGsBBcAycBOfARXAV3IbrpwM8B93gHehFEISE0BA6YoiYIdaII+KCMBE/JBiJQGKRZCQNyUTEiByZjsxFSpHlSAWyEalBfkcOIMeQM0gbchO5j3Qir5FPKIaqo7qoCWqDjkCZKAsNR+PR8WgmOgktROehi9FytBrdgdajx9Bz6FW0HX2O9mAAU8P0MXPMCWNibCwaS8EyMCk2EyvByrBqrA5rgv/0Zawd68I+4kScjjNwJ7iGw/AEnIdPwmfii/AKfBtej7fgl/H7eDf+lUAjGBMcCd4EDmEsIZMwmVBMKCNsIewnnIC7qYPwjkgk6hNtiZ5wNyYTs4jTiIuIa4m7iEeJbcSHxB4SiWRIciT5kqJJXFI+qZi0hrSDdIR0idRB+kBWI5uRXcgh5BSymFxELiNvJx8mXyI/IfdStCjWFG9KNIVPmUpZQtlMaaJcoHRQeqnaVFuqLzWemkWdQy2n1lFPUO9Q36ipqVmoeamNUROpzVYrV9utdlrtvtpHdR11B3W2eqq6XH2x+lb1o+o31d/QaDQbWgAthZZPW0yroR2n3aN90KBrDNfgaPA1ZmlUatRrXNJ4qUnRtNZkaU7QLNQs09yreUGzS4uiZaPF1uJqzdSq1DqgdV2rR5uuPVI7WjtXe5H2du0z2k91SDo2OsE6fJ15Opt0jus8pGN0SzqbzqPPpW+mn6B36BJ1bXU5ulm6pbo7dVt1u/V09Nz0EvWm6FXqHdJr18f0bfQ5+jn6S/T36F/T/zTEZAhriGDIwiF1Qy4NeW8w1CDAQGBQYrDL4KrBJ0OGYbBhtuEywwbDu0a4kYPRGKPJRuuMThh1DdUd6jOUN7Rk6J6ht4xRYwfjWONpxpuMzxv3mJiahJpITNaYHDfpMtU3DTDNMl1peti004xu5mcmMltpdsTsGUOPwWLkMMoZLYxuc2PzMHO5+UbzVvNeC1uLBIsii10Wdy2plkzLDMuVls2W3VZmVpFW061qrW5ZU6yZ1kLr1danrN/b2Nok2cy3abB5amtgy7EttK21vWNHs/O3m2RXbXfFnmjPtM+2X2t/0QF1cHcQOlQ6XHBEHT0cRY5rHduGEYZ5DRMPqx523UndieVU4FTrdH+4/vCI4UXDG4a/HGE1ImXEshGnRnx1dnfOcd7sfHukzsjRI4tGNo187eLgwnOpdLniSnMNcZ3l2uj6ys3RTeC2zu2GO9090n2+e7P7Fw9PD6lHnUenp5VnmmeV53WmLjOGuYh52ovgFeg1y+ug10dvD+987z3ef/s4+WT7bPd5Osp2lGDU5lEPfS18ub4bfdv9GH5pfhv82v3N/bn+1f4PAiwD+AFbAp6w7FlZrB2sl4HOgdLA/YHv2d7sGeyjQVhQaFBJUGuwTnBCcEXwvRCLkMyQ2pDuUPfQaaFHwwhh4WHLwq5zTDg8Tg2ne7Tn6BmjW8LVw+PCK8IfRDhESCOaItHI0ZErIu9EWUeJoxqiQTQnekX03RjbmEkxf4whjokZUznmcezI2Omxp+LocRPjtse9iw+MXxJ/O8EuQZ7QnKiZmJpYk/g+KShpeVL72BFjZ4w9l2yULEpuTCGlJKZsSekZFzxu1biOVPfU4tRr423HTxl/ZoLRhJwJhyZqTuRO3JtGSEtK2572mRvNreb2pHPSq9K7eWzeat5zfgB/Jb9T4CtYLniS4ZuxPONppm/misxOob+wTNglYosqRK+ywrLWZ73Pjs7emt2Xk5SzK5ecm5Z7QKwjzha35JnmTclrkzhKiiXtk7wnrZrULQ2XbpEhsvGyxnxdeHg/L7eT/yK/X+BXUFnwYXLi5L1TtKeIp5yf6jB14dQnhSGFv03Dp/GmNU83nz5n+v0ZrBkbZyIz02c2z7KcNW9Wx+zQ2dvmUOdkz/mzyLloedHbuUlzm+aZzJs97+Evob/UFmsUS4uvz/eZv34BvkC0oHWh68I1C7+W8EvOljqXlpV+XsRbdPbXkb+W/9q3OGNx6xKPJeuWEpeKl15b5r9s23Lt5YXLH66IXFG/krGyZOXbVRNXnSlzK1u/mrpavrq9PKK8cY3VmqVrPlcIK65WBlbuqjKuWlj1fi1/7aV1Aevq1pusL13/aYNow42NoRvrq22qyzYRNxVserw5cfOp35i/1Wwx2lK65ctW8db2bbHbWmo8a2q2G29fUovWyms7d6TuuLgzaGdjnVPdxl36u0p3g93y3c9+T/v92p7wPc17mXvr9lnvq9pP319Sj9RPre9uEDa0NyY3th0YfaC5yadp/x/D/9h60Pxg5SG9Q0sOUw/PO9x3pPBIz1HJ0a5jmcceNk9svn187PErLWNaWk+Enzh9MuTk8VOsU0dO+54+eMb7zIGzzLMN5zzO1Z93P7//T/c/97d6tNZf8LzQeNHrYlPbqLbDl/wvHbscdPnkFc6Vc1ejrrZdS7h243rq9fYb/BtPb+bcfHWr4Fbv7dl3CHdK7mrdLbtnfK/6L/u/drV7tB+6H3T//IO4B7cf8h4+fyR79Llj3mPa47InZk9qnro8PdgZ0nnx2bhnHc8lz3u7il9ov6h6afdy398Bf5/vHtvd8Ur6qu/1ojeGb7a+dXvb3BPTc+9d7rve9yUfDD9s+8j8eOpT0qcnvZM/kz6Xf7H/0vQ1/Oudvty+PglXyu0/CmCwoRkZALzeCgAtGQD6RXh+GKe88/ULoryn9iPwn7DyXtgvHgDUwU5xXGcfBWA3bDYBkHs2ANGwjw8AqKvrYFOJLMPVRcmlUQsAybyv7zU831Bg+xza19cb09f3pQoGewWAw0+Vd02FEOHdYIOzAl0y2wt+FOU99Lscf+yBIgI38GP/L5eMiU/Rbf0CAAAAbGVYSWZNTQAqAAAACAAEARoABQAAAAEAAAA+ARsABQAAAAEAAABGASgAAwAAAAEAAgAAh2kABAAAAAEAAABOAAAAAAAAAJAAAAABAAAAkAAAAAEAAqACAAQAAAABAAAAXKADAAQAAAABAAAAVgAAAABBkji4AAAACXBIWXMAABYlAAAWJQFJUiTwAAAVYUlEQVR4Ae1da3Mbx5W9eD9IgKREySIly7YcK0psl9a7Se1mq3b/xH7aVD7ll/jn+HP+QCqvSiW1a8eOLUeRbOtl06JIggTxGDwn59yeBgaDmcGABCjHZJeGGMz09Jw+ffv2vd23odT2v/7Klbjkxt3mvbj7s29LbPlBYHjXjNcFn4j9nkqJ4EgVS5LeWJdMaUUklxXpdGRQq8mw1RS31xMZDrWYFPNmUpLJpCWbTSv0brcvw765H/su72Y6SabvTh4QtMjExiaZg764TleGva6k+B3EupmMSBoHG2WU2OAu/uGTl/23RnniT9CcLzlphViRl4fDHQxEnLYMIbnpXE5JTmUzhnQf4QqRUE+B9Tsi4ScQlUW2D6TahXRTlbj9vmGU0p3NSirto8gjm3yflHRfaYuswT9ZWWQPRFNfU60MKfEkmmrFJ+FaK+b1s837wTwx1X/5KiUG3JndsiRSl3cg6VTOIDwFwt0YMpVr5kZ2Sn0StXgh4STKS9TlbtsxpFNwocdnSa+Szry2kBmfF4T7CaKFQl3exUGpt9IdxiZFWrOQbWYIy+Qv3JxfEO7nBCS7/Z4eMgD5qqs9Qv18gujB0JUBSUeifZ6Qb7nQ4YYz89evyynllkgOoGwAT0nTDndBuElsCXvuXYr5uJDwEHJUlzuOmokU3VQGcmnVi5dfnR/yrB3AL/4hBfouXUi4j4zRKXU5JFy9TZVyyGWAcOaFnMOYMTJLtcLvs9IF4WEMebpc3X44P6rL/VzinBIO2VcJD2uMsGJ57YLwMGasLue9gVUXQcZxj/mYmMVm0wvRf+C7ejntw9F5z98dcgJnSJOPH0u971Jibi4kPI4qZdSj17Js8+O7vZRQuPXJ5RNu0Vh0FvA/y2cYbo9sVk2HTK0j/vAzLL+vrhdmoY+M+U7HzJJno5mV+dhiLgiPpSfmJvm2StzjWUmfwfkF4TGcJr1FHzQJ2SxvNuEsyfSXpO8/V/mMh2840jXPGfbhKQdN23/G+kxbEZez6ZTkcmkp5NOS54HzHK5p+0U0CSeEuliQ7fdc6fXNudMZ6HnEI7GX6QSOcWQURwE4slgIJvIoOSIOvr8HLIqjN5RQHKi2NWSUbBTopngxGtYpCWfB06SzkqViWjaqObmyWZDLGwXZWM/LSjHDVStBfUOT0xnK0XFP6sd9OW72Zb/Wk50XDirt2cKhT0VfVBzlDHDk5cpl4sgDR0FWSsCBqW4sYYYmknsEDHVgOW4OZP+gG42DjOOfJTy0QN/FBRDOyIK0rILg8kpGKuWcVFazsg6yL1/Ky1VUdPNSQdZJOCoPAdPVKx+G0WmnO5TDI0N4HRXd3evIk6dN+eZ5W57jvNGOJ569iGSWS1ngwAEM62v5BeBwgKMl33zbmsBhZw1JNuUupT04fk5lIYSvopKvXy/J6zfLcuv1itzcLsvVKyVZq+SlWDAqheqFXdmb6xmR7D/R+X90X3bjPo7Do64822nKx58eyq//8FwaT+MJJ9mv3ygDxypwrMrN6ysLxlGTX/9+EoeSDinXxeaInuuv46kIL0NFsJu+tlWSH71VkdtvsqIVub5VhlQVVdL8L5v3vNHoQQXk0K178uePoqESxybU1s3rZeCoyu0fVJaH48P96WqoSsFlEj6D9OhaTBc7dYVk/+e/XZK772zInVsV2bpWgtrISQmSVshDSZ4ysadS1+bZM2xFdKQzetMWT7J/9tNNg+PN6pJxWCB4O2FAunlwOHB9tyy24OeJCGfXpV5+53ZVfvreZbn743W5sb0i1QqCaBaYyG0aTI/IHpXNmrnQ11m5Ahxv/3DN4Hh7Y/k4fKTq/DdIV+bjTJMR7hNOz5Ls//73TfnJv1ySd1DZ7WtllWpfuWdySrL/62dXDY476y8FhxopSnqyKs8l4bQCqrA0bmFgeg9q5O7b67J1tSSrK+GS3YcdSxPLcXDQnsaAOKSt3XWlBYujC3ubKZ9Lqb7P4ZOJg2sBg20f64gN6O8O8hkHQ28LbekKcLzx6oq89y5wAMuJcbSIg74iccDSgnUTjcPgNyjw1yOaHyQ+SZqLcJJ9+42yvHunIm+9saqVLBaidTVJ3tmFSQez7tvdltTrXZA9lD3Y14+fteWwjshUJJqQr90oycaaabgyVNbVzbw2AgNxGrDJabXYRJPv9q0VeffHVeDA2IFGPzEOmJ0TONCI0TgGEzgUT1DEqQd5RLTAXITTvr79ZkXeubMmW69ES3ZHHYee2q1//+JYHj1tyHMQfgQzj9J0cNiTRyC8BseCaQO6f+c5zUgDZwWEXoENX8H1bC4DO9yRY0iiTRXkMzjQw5Lg2GnJ37+sy6MnHg42PHrNQa0LHC2peQ1PR23neUvW8MlEv4Fqa4TjW0caPhwWj/+TfVT55sWxjIyyzEV4dTUvd26v41hTEKNSAif0Fj+7fwj7uSYf/rUmT79uIU5yoGSrSkFlm23E73mpCfXCiueyRqUw/rqI6QB+p1PRgge6X+vY7FKFCvvRvDg+PvBwQIVA1ek6MRp/EsfAw2Fc0AxUG/2IHPDQqWlDNe75cIwA4URVnifcJJxkh/CdbE2TOrUEM28TUvcqnJprV8vQsdOqhDq6CZ37BBL90V8P5P8/rsm9B3XZPQBZYW/3EHehLrqelPkrETxnA1B1bMJ7vQGnJhGOT4jjQO7dPzI4goX6vrP3WX3uuzz7lOTiUKL5R0/42HSlE0l4Ca28BZ26fa0IfZtXstn6wUSyHz2uyyefHcj/fXQgn0Od1OG8JEpxYuEVQLK3rhRlG45WIhyfAgcclc8f1pPjSAQ2JJPqcsMJe2XUJFZCwjOy/UpRXt0qwiLJ6naLkFdKE/rtyyfH8vmDI/nqWXOmRE2X4fXF6Rt6pQTCDQ6OH8lwPHrWOAGOCAARl+2cCm9zHjIuPiVivmyy5FIpDVVShFNBd31aldjctCYePmrJF49bUC3jQc7eP+1nGRNkc+F40oKFMx4rTvv+uOdJumoQ1SjTvd8+m0zCob+vbhblFRxhupsDYR+RjRwsn+048gxWRRsD3aJTcS4cbXkGq6KNwfqsEiV7ViRWIgnnTN8lzCNzLpnOQTCRbDootcMuplQdfNJZWTzhOVguyXB0ZHcXOGBRLANHsP6UbJVw3qBwjwbNqZzJrBTOd1dWc7IKs5Db5YKJHiUJPzruqpPSWpJUJcYBi4fqrQUz7mySp048Z0f5jtAqiVRKmvZoMYsjg20v0yXRC2w0sEqDg3PZy0qcyEqEA2RzeeysktZYpdwfpxL+9kSEZ1DRQgGE42Clg4lzHs1WT4+BxlEHcyzmOxu7wIafhQO9bbDEhp+qjRXwqRvTF6b1w3Qe7A+F5wfp5oAZJuFDkOy0e3osk3AOSLTFXzaOEIqM5+OpFL1PvTItm8l0OJ+1253DXqZWSp8TO9iU5J/WC8t8imtz4fBX/hTvPMmj5Nkc0zZ5Igk/yUvP9TNgWwUc7PLTny4I97OxsHMz6WbYnmT8gvCFkWwKokZV+wiibcMn/K9IZKX4H7g4j2FATUPPZInIdkF4BDEnuayTWNy8iX8cNVXCAwUlIpyWR69nFhBMMM+kXsrAXCvks4jdo52+PC3FCiXCAdMxzF8I1H3hX7lIkcXURxZ+Ag+y3oXX3e/0ZdDFDyfAGUtEuHqScCbovnPBOB9wfviSCqKsqjh4vqyUHEdhqTii6pfBtEcRHJTXS1K+VNb9nQ5mK1tHjjT36tJtOskIZzQpV947Tl8Y5aQBgr630hkqoyFKCAJiD1hWUhyQmFk4uPKeZaTmnFCC2akZ/Cl4f3TPGyDz8ILLa1gzuLIipQ0QjsjVzOpQUhDCIX6LBY5KMsKpUgboDpyk4igcTCScHmAJjcF5l9gUd1t1nz8D90KOE1VKEhzEkvHWQ8dPR5z5XqCn9ntIPSfu2+KQj3GFlO5CGdJ92ZCdLmEhGo3OkA7XzeP3swq6h3+8bdAW4Ps0L0BMCFZcW3DdW5gvWV8r+HKYU3qhJUasQspXIV3sBVwb1GkVfwXo/dnvU6XgAu9NVJSm1TgjPVpimImDM5vAwsUSRuSyZ4QlU7bvBchk38cnJu+ElTDOlMaDaUQY5Io5yYHsIVUrVC8bPoeFkxyw5CAIWSp6k+znuOAUCOLtPgivHXb02NwsjzN4Z1QjrCBjwLlQcQmfjPXgIoQdqXW+OLzek+VNwxjd50zkwVESHAWNSycehj9HTdNackcv8J3Ye5SRycRYQv8VA5gTeDN/3Q1Z4wdN7609hDXUEFNyiHgOrswHEy0CDqRc2L2JqKxvENtByVr0qg/ffYhFjmQ4VjSuvOM0QHj4ct8kccFaed9B7gS/E194z1xwEck5oCXXcFSS3WJedx64ENZeA3EwWO/tg5Osba5AOaO3cwq/jdA0SiylJYxwm5kBOncQtszGef6iqxFW+F06c5svSFRD5rMlTn52uoP5cKBXMupr7yCiwMniI7/NfBqCSdkc4jcM28/r+EWhvqSrFXGh192OI506rJT9FqyUnmSq2z9/f/QmEsLSAwfDhRn/V4VufO3GqqoOvsCqC/s8H+fcOZfcuNzWbsEGhVTqYgDLTJJ8jUKTPod30+CgJGVxQeMbYXolwTEADkZXtRF0RJPypIsjYxyc/QMWWxePA05fcxyj+nVBeh+C0e/DBgfB3aOWOEdtcbAa1sP1TGXrf98f8TAqaXRFT3TNEqs5dG7eQqgb9TTVSNC5oIXC7R5sHLxbAzfZM2aFh02+bfyNZDPWnGuqQ5DHgKFGY6Cx58lwMGKKOER3U5wKB8LeFAcw2DUWjn9KNiSZhLMdSCqdHQeDe6cBoqFiujjvQ91w3WCswyPIZvVpceyhoB0szH79TUujr7ilJLi+yTXHXCWtMdp33x6oTU6JfIpnOhhAaVaq14oXO9BnJCLLUZwSAmLYO1gJmpl8jmRXEc/IDVaMUdxDr+lAXe0gKuDrnba8et3RLSWROBCddRf+A23yPLApDpU+9BdYLj3iAK4h6s482pu0R4XgQJyj4ngIHBi42bst2RQ849ajN4MrWlMp/7ouWkKNBnA5JpzMzkhcmH3wVUMtADoXDLoMSzQP38JOBMaR//AHVV3J39vvaPRTv8e1z5682MdAAmlhGTzKRWPLM3iTuyg2sBmKG6LovT748lg+aDxWwvk+SuqDr45PiMPxcAzkGGEdLxCGx8DOFWDWDVkw4bi6NY0jBxwN+eD4kezDeLBkq2SjwawEsyEp6pR2VbtoDE0YDEl6OGMmy9TfOgi/D0njTofNy0Ulik5GUMK4L/NyvoBo2JxGt9ahv1ixBkZrdjlOEezu4RyE24ZbKWG9EnEnORxlEG7JprlJaWKklU0Mn7uP8DXFgb1EbLCzwJGGfqrCElOyIRjsjWriQ91RXVDtjZNSPhrnNPQNN8e1GOeMPGNF7z041i6/zf08IEED4dFdwxJVA9cfNzIFJZGDJyWAqoUqhmCZhw3GvTzsmqyEdm+oFLvzLVg290/eu19XFaQ4oHbOAsdIZ4PsLAATP3ssf8nT9YyxEVbD9+grpZ1pLsKpdx1I6sPHTQ1D5iDJ1XG75YQ63J8omdTRJLRY9N853bmDAcg5GMgXjzLy4Sc1bajBnbPBkUZdKOFMtLGNZINtEhxMuEbrSk0Ij/G5CLfl7YH03/5pT00uO0hwUxUHzKUn3+BONfW7P+7KAT7PAoeVcLrxPZh/nNch6aFkgwh1iij5nnTzAz3D2M3zEMUg9iaC7Dkar2L3Ma0YDkDXsBuBZqENqWDZlHKvcRO/QqMAoA9JIo86dD/VUDAxkL/5Nbo0cUCtLB2H2tKYm4G+Jtn6o8Bhku0HCgFhFrVkwHzm2q1fvG83N/nzJTmnM7EPx+IFzEXuGqaOJ0FsUqtKOEiT9HkSB1MTq9jB3qC2DpB/+exQdmHphCWODQfYD7+LffmKA4PyMnD8DZsLuNGA+5biJDuIkSqFM4qqYjeqWd1hhkZTuziYOe47J4VasIe5Y7jZQoX322ofb2EbIffYMx6RvyZB64NbNzhAxiV6hrSLGWdOy4bkcZqAJiAjc6MScTzBPh7uWGYE2O6+sdO5/+cqrCnu0TkJDu60o+3NuRtueXnwRR37kzpmksqn2qJw6XWKt6/aqf/55W9cWh4th45ATP+IfIGre3FWYbuW4Y2VMQnPeXFaJySZG5PWsTuNDcCp27hE+5pSXEOvqcOzpUuuagKVZoV11i8Sh9n2Z3/cYIQDDU4VR4tqHdvI58HBX5Ro4xdRubenBaE6rHfwyxLAgYaYJ6laVfUKHX4H+9KbmPN4grjuQ7xgvsQGMnMUtQamcAHKnzgH4/8ZjxU0RnQyG61ekHBO7ZJsqJZ5EhuHh92VZp/Nw1IqoeHtz3iwUaISyWmC4D2oqDp4wdioM58cJHX6NabBo8rUURVVob2S/Y+fXIHIp7Etby+c8BO9wLy6j8Gs7cClH+AnOTAHMmv5Te1zEEb9y2cXlRSHTqTB24VQReLwxpshSB9guhWRe2YRGGaoS517Qi70MQ5tMOKy9AqpYzNzDmxJyCBnXaipLhwD//a80GdPWJnQsgIXabl1AaYLBiNxkGyM8Iw6yMCpob3NBZiRy35KfGqPg4/svb8dycOv6pDwSXUQwPz9/qqSTdPNhDhQrahDgwbi8mLi1ao4lthh8Z7spyD8CXYFt6Azz2siwfQeeegAB2kekmyoETsZtRBuKOF/+fxYZ98WvRw2AsiW/S4nkJ0C0VnM9VOlcGCkQ2PJPqUmmag51Up2B78lpWmRJU+85rv7hQST7Az+NxN1TCjZkOplkG1ZGK1p2gvn5lMHScxIqmRjtQa62rjrRo0sRf6oUs4Nwb6KqmTTGqHO5twDujpVyUCnWdHxl6gGzx/hVrIRbEmyXZitVCFKNs7tUpivfRZ6egbzqQvFe6rCJqwRSDinWc+SbII/VxLOFfwcl5agSlws0XC2U+3sM5BsKynng3BVI8aL5H9ACsH2zWl7jo1lZMmf54Jw6mp11yHZTOMFhLMlm+/+fhNuJRtEc26Eok2yjXMz1Egp7rDm2ixX3HmPix9cQQpLuiiOxW2u3jCWhQvHHGS1QVkGvjMcj/P6Uel7TfhIsjkRRYsERFqySRTJvsyfJMEEHn+Bro35eC6mdBBLGZYY672BXwFlfv3ZbTQOG4khyYyl4crZPn5NI26+/PtJOCUb0szJKEo2Y130B8vA4xDkcKBk4vorY1vyWCjJO8YuZy/IQ0o1kXc0DAWePYALGYyPKWI+neRyOplWDoPxS7jeR0MxzI0N4E+MbLCS/w8vxmnBbgpUbAAAAABJRU5ErkJggg==",
                        };
Share.open(shareOptions)
                            .then((res) => { console.log(res) })
                            .catch((err) => { err && console.log(err); });

**Comment by liwei3927** [comment]
https://github.com/react-native-community/react-native-share/issues/808

**Comment by liwei3927** [comment]
Maybe it helps to understand the problem(

I use a workaround with a local file and it works on Android without asking Storage permissions.
https://github.com/react-native-community/react-native-share/issues/808

**Comment by HimiGame** [comment]
> Maybe it helps to understand the problem(
> 
> I use a workaround with a local file and it works on Android without asking Storage permissions.
> #808

thx to reply,
I'll take a look now

**Comment by HimiGame** [comment]
The problem remains

**Comment by kkCode** [comment]
I also encountered this problem in version 0.63

**Comment by IrfanKhan01** [comment]
Try version **3.7.0**, it's working for me

**Comment by HimiGame** [comment]
> Try version **3.7.0**, it's working for me

thx for your reply ,   try  now

**Comment by HimiGame** [comment]
change version to  3.7.0 , fix

**Comment by MateusAndrade** [comment]
Hi, @HimiGame this is happening with our latest version: 3.8.0? Maybe it's related to update with the react-native version. 😢

**Comment by HimiGame** [comment]
> flipper

my project package.json config

{
  "name": "xxxxx",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.11.0",
    "@react-native-community/cameraroll": "^4.0.0",
    "@react-native-community/clipboard": "^1.2.3",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/viewpager": "^4.0.1",
    "@react-navigation/bottom-tabs": "^5.5.2",
    "@react-navigation/compat": "^5.1.26",
    "@react-navigation/native": "^5.5.1",
    "@react-navigation/stack": "^5.5.1",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-code-push": "^6.2.1",
    "react-native-fs": "^2.16.6",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-head-tab-view": "^1.1.4",
    "react-native-image-crop-picker": "^0.32.2",
    "react-native-popup-menu": "^0.15.9",
    "react-native-reanimated": "^1.9.0",
    "react-native-root-toast": "^3.2.1",
    "react-native-safe-area-context": "^1.0.0",
    "react-native-screens": "^2.9.0",
    "react-native-share": "^3.7.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-swiper": "^1.6.0flipper",
    "react-native-video": "^4.4.5",
    "react-native-view-shot": "^3.1.2",
    "react-native-webview": "^10.3.1",
    "rn-fetch-blob": "^0.12.0",
    "yaqrcode": "^0.2.1"
  },
  "devDependencies": {
    "@babel/core": "^7.10.3",
    "@babel/runtime": "^7.10.3",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "react-test-renderer": "16.11.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by HimiGame** [comment]
> Hi, @HimiGame this is happening with our latest version: 3.8.0? Maybe it's related to update with the react-native version. Can you check your flipper version? 😢

my project package.json config:

{
  "name": "xxxxxx",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.11.0",
    "@react-native-community/cameraroll": "^4.0.0",
    "@react-native-community/clipboard": "^1.2.3",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/viewpager": "^4.0.1",
    "@react-navigation/bottom-tabs": "^5.5.2",
    "@react-navigation/compat": "^5.1.26",
    "@react-navigation/native": "^5.5.1",
    "@react-navigation/stack": "^5.5.1",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-code-push": "^6.2.1",
    "react-native-fs": "^2.16.6",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-head-tab-view": "^1.1.4",
    "react-native-image-crop-picker": "^0.32.2",
    "react-native-popup-menu": "^0.15.9",
    "react-native-reanimated": "^1.9.0",
    "react-native-root-toast": "^3.2.1",
    "react-native-safe-area-context": "^1.0.0",
    "react-native-screens": "^2.9.0",
    "react-native-share": "^3.7.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-swiper": "^1.6.0flipper",
    "react-native-video": "^4.4.5",
    "react-native-view-shot": "^3.1.2",
    "react-native-webview": "^10.3.1",
    "rn-fetch-blob": "^0.12.0",
    "yaqrcode": "^0.2.1"
  },
  "devDependencies": {
    "@babel/core": "^7.10.3",
    "@babel/runtime": "^7.10.3",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.58.0",
    "react-test-renderer": "16.11.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
