### ISSUE TITLE
iOS Instagram share, video is not appearing in share dialog

### ISSUE THREAD

**Issue by mikeschoneveld** [react-native-community/react-native-share#874]
### Steps to reproduce
1. Follow the steps in this PR: https://github.com/react-native-community/react-native-share/pull/826/files

### Expected behaviour
If I upload share a video through Instagram the video will appear in my share dialog from Instagram.

### Actual behaviour
The video only appears on Android devices, if I only change `social: Share.Social.INSTAGRAM` to social: `Share.Social.FACEBOOK` it works on both iOS and Android. 

### Environment
- **React Native version**: 0.62.2

### react-native-share
**Version**: "v3.8.3"

This is what I see in the share dialog:
![instagram_share](https://user-images.githubusercontent.com/36042966/93853918-0fa56880-fcb5-11ea-84a1-991cd6fd4068.png)

**Comment by chathuralakmal** [comment]
I have the same issue

**Comment by ferbeab** [comment]
I am facing the same issue

**Comment by chathuralakmal** [comment]
I have found quick solution for this.

Go to Development Pods > RNShare > InstagramShare.m
In here. 
```
   if (videoDurationSeconds <= 60.0f) {
        NSString * urlString = [NSString stringWithFormat:@"instagram://library?AssetPath=%@", options[@"url"]];
        shareURL = [NSURL URLWithString:urlString];
    } else {
        shareURL = [NSURL URLWithString:@"instagram://camera"];
    }
```
 Change above Like Below.

 ```
if (videoDurationSeconds <= 60.0f) {
        NSString *phIdentifier= options[@"url"];
        [phIdentifier stringByReplacingOccurrencesOfString:@"ph:" withString:@""];
         NSString * urlString = [NSString stringWithFormat:@"instagram://library?LocalIdentifier=%@", phIdentifier];
        shareURL = [NSURL URLWithString:urlString];
    } else {
        shareURL = [NSURL URLWithString:@"instagram://camera"];
}
```

Simply need to  remove the "ph:" part from the URL. it's the local identifier. it worked for me.

**Comment by ferbeab** [comment]
It fixed the issue for me too!! Million thanks!

**Comment by mikeschoneveld** [comment]
@chathuralakmal Many thanks for the solution!
