### ISSUE TITLE
Sharing with Google’s Inbox fills the subject incorrectly

### ISSUE THREAD

**Issue by benjaminreid** [react-native-community/react-native-share#89]
Hello 👋,

On iOS, using Google’s Inbox app to share via email, the subject line gets filled with the message body instead of the specified subject

To recreate, use the simplest test case.

```js
Share.open({
  title: "Email Title",
  subject: "Email subject",
  message: "Email message",
});
```

This opens Inbox with the title filled correctly, but both the subject and message body equalling "Email message". The subject seems to be ignored completely.

I know this is an edge case, as the majority of people won't be using Inbox but it'd be nice to know if a fix was possible or how to go about avoiding it if possible if it's not the responsibility of `react-native-share`.

Thanks!

**Comment by enieber** [comment]
this issue is in version very old, try with the new version
